repos:
  - repo: local
    hooks:
      - id: pytest-full
        name: pytest rac_size_matters
        entry: python -m pytest
        args: [worlds/rac_size_matters]
        language: system
        pass_filenames: false
        stages: [pre-commit]
