"""User-curated skill point difficulty and additional operative requirements."""
from enum import IntEnum

from .operatives import SACOperatives
from .skillpoints import SACSkillPointLocations as SP, SKILL_POINT_FLAGS


class SkillPointDifficulty(IntEnum):
    EASY = 1
    NORMAL = 2
    HARD = 3


EASY_SKILL_POINTS = frozenset({
    SP.GONDOLA_ASCENT_STEEL_RAIN,
    SP.SUCK_AND_JIVE_DRESS_FOR_SUCCESS,
    SP.VENANTONIO_LABS_RAMMING_SPEED,
    SP.VENANTONIO_CANALS_EVASIVE_MANEUVERS,
    SP.INSIDE_THE_A_EYE_DIA_DE_LOS_MUERTOS,
    SP.SAINT_QWARK_PUNCHY,
    SP.SAINT_QWARK_SOUR_VICTORY,
    SP.PRISON_BREAKOUT_WHIP_IT_GOOD,
    SP.DAMS_EDGE_HYDRANO_YEEE_HAAAAAW,
    SP.A_FICTION_FULL_OF_DOLLARS_CLEANS_POOLS_TOO,
    SP.UNDERWATER_BUNKER_LEET_HAXXOR,
    SP.UNDERWATER_BUNKER_RUST_PROOF,
})
NORMAL_SKILL_POINTS = frozenset({
    SP.BOLTAIRE_MUSEUM_FURIOUS_FISTS,
    SP.BOLTAIRE_MUSEUM_SILENT_NIGHT,
    SP.BOLTAIRE_GEM_WING_PYRRHIC_VICTORY,
    SP.ROOFTOP_DEATHTRAP_SPEED_DEMON,
    SP.ASYANICA_ROOFTOPS_ROBOT_FINDS_NINJA,
    SP.ASYANICA_ROOFTOPS_BLACK_TIE_AFFAIR,
    SP.LARGER_THAN_LIFE_INVERSE_NINJA_LAW,
    SP.LARGER_THAN_LIFE_BLASTER_OVERLOAD,
    SP.GLACIARA_SKI_SLOPES_BLACK_DIAMOND,
    SP.GLACIARA_SKI_SLOPES_SMOOTH_MOVES,
    SP.GLACIARA_SKI_SLOPES_RINGLEADER,
    SP.THE_MESS_HALL_ANTAEUS,
    SP.AZCOTAL_ALLEY_TRASH_TALK,
    SP.AZCOTAL_ALLEY_DEADLY_HANDS,
    SP.SUCK_AND_JIVE_CARD_PICKUP,
    SP.THE_EXERCISE_YARD_INDIAN_BURN,
    SP.VENANTONIO_LABS_ALL_SLIME_MUST_BURN,
    SP.VENANTONIO_CANALS_DEEP_SIX,
    SP.VENANTONIO_CANALS_WAKE_OF_DESTRUCTION,
    SP.VENANTONIO_CANALS_RINGMASTER,
    SP.MADAM_BUTTERQWARK_TWINKLE_TOES,
    SP.GALACTIC_BOLT_RESERVE_WITH_INTEREST,
    SP.GALACTIC_BOLT_RESERVE_ANDROIDS_IN_DISGUISE,
    SP.GALACTIC_BOLT_RESERVE_VAULT_VAULT,
    SP.THE_SHOWERS_MODESTY,
    SP.SPACESHIP_GRAVEYARD_DELICACY_SOMEWHERE,
    SP.PRISON_BREAKOUT_HANGING_JUDGE,
    SP.DAMS_EDGE_HYDRANO_OFFENSIVE_DRIVER,
    SP.DAMS_EDGE_HYDRANO_SLIPPERY_SLOPE,
    SP.DAMS_EDGE_HYDRANO_RING_AROUND_THE_ROSIE,
    SP.BULKHEAD_LOCK_CEREAL_DECODER_RING,
    SP.UNDERWATER_BUNKER_IM_NOT_THERE,
    SP.KLUNKS_LAIR_TURN_THE_TABLES,
})
# Everything not explicitly listed in Easy or Normal belongs to Hard.
HARD_SKILL_POINTS = frozenset(SKILL_POINT_FLAGS) - EASY_SKILL_POINTS - NORMAL_SKILL_POINTS

SKILL_POINT_DIFFICULTY = {
    **dict.fromkeys(EASY_SKILL_POINTS, SkillPointDifficulty.EASY),
    **dict.fromkeys(NORMAL_SKILL_POINTS, SkillPointDifficulty.NORMAL),
    **dict.fromkeys(HARD_SKILL_POINTS, SkillPointDifficulty.HARD),
}

# Operatives a skill point needs besides its own case's. The casino rhythm
# mission embeds Gadgetbot combat sections.
EXTRA_SKILL_POINT_OPERATIVES: dict[str, frozenset[str]] = {
    SP.HIGH_STAKES_ROOM_GADGEBOT_STANDS_ALONE: frozenset({SACOperatives.GADGETBOTS}),
}
