from ..model import Kind, LBPLocationData

LEVEL = 'g89121'

LOCATIONS = (
    LBPLocationData('A Navy Frigate - Score Bubble 1', LEVEL, Kind.SCORE, uid=9070),
    LBPLocationData('A Navy Frigate - Score Bubble 2', LEVEL, Kind.SCORE, uid=9076),
    LBPLocationData('A Navy Frigate - Score Bubble 3', LEVEL, Kind.SCORE, uid=9080),
    LBPLocationData('A Navy Frigate - Score Bubble 4', LEVEL, Kind.SCORE, uid=9082),
    LBPLocationData('A Navy Frigate - Score Bubble 5', LEVEL, Kind.SCORE, uid=9084),
    LBPLocationData('A Navy Frigate - Score Bubble 6', LEVEL, Kind.SCORE, uid=2357005),
    LBPLocationData('A Navy Frigate - Score Bubble 7', LEVEL, Kind.SCORE, uid=2357007),
    LBPLocationData('A Navy Frigate - Score Bubble 8', LEVEL, Kind.SCORE, uid=2385736),
    LBPLocationData('A Navy Frigate - Score Bubble 9', LEVEL, Kind.SCORE, uid=2386149),
    LBPLocationData('A Navy Frigate - Score Bubble 10', LEVEL, Kind.SCORE, uid=2483670),
    LBPLocationData('A Navy Frigate - Score Bubble 11', LEVEL, Kind.SCORE, uid=2483672),
    LBPLocationData('A Navy Frigate - Score Bubble 12', LEVEL, Kind.SCORE, uid=2483674),
    LBPLocationData('A Navy Frigate - Score Bubble 13', LEVEL, Kind.SCORE, uid=2483680),
    LBPLocationData('A Navy Frigate - Score Bubble 14', LEVEL, Kind.SCORE, uid=2483682),
    LBPLocationData('A Navy Frigate - Score Bubble 15', LEVEL, Kind.SCORE, uid=2483684),
    LBPLocationData('A Navy Frigate - Score Bubble 16', LEVEL, Kind.SCORE, uid=2494657),
    LBPLocationData('A Navy Frigate - Score Bubble 17', LEVEL, Kind.SCORE, uid=2494659),
    LBPLocationData('A Navy Frigate - Score Bubble 18', LEVEL, Kind.SCORE, uid=2502662),
    LBPLocationData('A Navy Frigate - Score Bubble 19', LEVEL, Kind.SCORE, uid=2502666),
    LBPLocationData('A Navy Frigate - Score Bubble 20', LEVEL, Kind.SCORE, uid=2502692),
    LBPLocationData('A Navy Frigate - Score Bubble 21', LEVEL, Kind.SCORE, uid=2502694),
    LBPLocationData('A Navy Frigate - Score Bubble 22', LEVEL, Kind.SCORE, uid=2502696),
    LBPLocationData('A Navy Frigate - Score Bubble 23', LEVEL, Kind.SCORE, uid=2502698),
    LBPLocationData('A Navy Frigate - Score Bubble 24', LEVEL, Kind.SCORE, uid=2502700),
    LBPLocationData('A Navy Frigate - Score Bubble 25', LEVEL, Kind.SCORE, uid=2503521),
    LBPLocationData('A Navy Frigate - Score Bubble 26', LEVEL, Kind.SCORE, uid=2503527),
    LBPLocationData('A Navy Frigate - Score Bubble 27', LEVEL, Kind.SCORE, uid=2503590),
    LBPLocationData('A Navy Frigate - Score Bubble 28', LEVEL, Kind.SCORE, uid=2503592),
    LBPLocationData('A Navy Frigate - Score Bubble 29', LEVEL, Kind.SCORE, uid=2505666),
    LBPLocationData('A Navy Frigate - Score Bubble 30', LEVEL, Kind.SCORE, uid=2505667),
    LBPLocationData('A Navy Frigate - Score Bubble 31', LEVEL, Kind.SCORE, uid=2505668),
    LBPLocationData('A Navy Frigate - Score Bubble 32', LEVEL, Kind.SCORE, uid=2506077),
    LBPLocationData('A Navy Frigate - Score Bubble 33', LEVEL, Kind.SCORE, uid=2506079),
    LBPLocationData('A Navy Frigate - Score Bubble 34', LEVEL, Kind.SCORE, uid=2506476),
    LBPLocationData('A Navy Frigate - Score Bubble 35', LEVEL, Kind.SCORE, uid=2507262),
    LBPLocationData('A Navy Frigate - Score Bubble 36', LEVEL, Kind.SCORE, uid=2507264),
    LBPLocationData('A Navy Frigate - Score Bubble 37', LEVEL, Kind.SCORE, uid=2793092),
    LBPLocationData('A Navy Frigate - Score Bubble 38', LEVEL, Kind.SCORE, uid=2793094),
    LBPLocationData('A Navy Frigate - Score Bubble 39', LEVEL, Kind.SCORE, uid=2793096),
    LBPLocationData('A Navy Frigate - Score Bubble 40', LEVEL, Kind.SCORE, uid=3002333),
    LBPLocationData('A Navy Frigate - Score Bubble 41', LEVEL, Kind.SCORE, uid=3002335),
    LBPLocationData('A Navy Frigate - Score Bubble 42', LEVEL, Kind.SCORE, uid=3002337),
    LBPLocationData('A Navy Frigate - Score Bubble 43', LEVEL, Kind.SCORE, uid=3002339),
    LBPLocationData('A Navy Frigate - Score Bubble 44', LEVEL, Kind.SCORE, uid=3002341),
    LBPLocationData('A Navy Frigate - Prize Bubble 1 - Blue Balcony', LEVEL, Kind.PRIZE, uid=663059, plan='g85403'),
    LBPLocationData('A Navy Frigate - Prize Bubble 2 - Dark Wall', LEVEL, Kind.PRIZE, uid=817144, plan='g85420'),
    LBPLocationData('A Navy Frigate - Prize Bubble 3 - Grate', LEVEL, Kind.PRIZE, uid=817162, plan='g85424'),
    LBPLocationData("A Navy Frigate - Prize Bubble 4 - Dead Man's Chest Top", LEVEL, Kind.PRIZE, uid=2090136, plan='g82189'),
    LBPLocationData("A Navy Frigate - Prize Bubble 5 - Dead Man's Chest Bottom", LEVEL, Kind.PRIZE, uid=2090146, plan='g82187'),
    LBPLocationData('A Navy Frigate - Prize Bubble 6 - Door Decoration', LEVEL, Kind.PRIZE, uid=2115873, plan='g85484'),
    LBPLocationData('A Navy Frigate - Prize Bubble 7 - Low Wood Wall', LEVEL, Kind.PRIZE, uid=2116552, plan='g85432'),
    LBPLocationData('A Navy Frigate - Prize Bubble 8 - Weathervane', LEVEL, Kind.PRIZE, uid=2254192, plan='g85537'),
    LBPLocationData('A Navy Frigate - Prize Bubble 9 - Cutlass', LEVEL, Kind.PRIZE, uid=2254928, plan='g85536'),
    LBPLocationData('A Navy Frigate - Prize Bubble 10 - Lantern Torch', LEVEL, Kind.PRIZE, uid=2356094, plan='g81978'),
    LBPLocationData('A Navy Frigate - Prize Bubble 11 - Blue Roof Pitch', LEVEL, Kind.PRIZE, uid=2940897, plan='g85409'),
    LBPLocationData('A Navy Frigate - Prize Bubble 12 - Compass', LEVEL, Kind.PRIZE, uid=2940918, plan='g82023'),
    LBPLocationData('A Navy Frigate - Prize Bubble 13 - Blue Door', LEVEL, Kind.PRIZE, uid=2941327, plan='g85405'),
    LBPLocationData('A Navy Frigate - Prize Bubble 14 - Blue Beamed Wall', LEVEL, Kind.PRIZE, uid=2941329, plan='g85404'),
    LBPLocationData('A Navy Frigate - Prize Bubble 15 - Blue Gable', LEVEL, Kind.PRIZE, uid=2941338, plan='g85406'),
    LBPLocationData('A Navy Frigate - Prize Bubble 16 - Wooden Gable Wall', LEVEL, Kind.PRIZE, uid=2941356, plan='g85449'),
    LBPLocationData('A Navy Frigate - Prize Bubble 17 - Weathered Wood with Iron Bands', LEVEL, Kind.PRIZE, uid=2941371, plan='g80186'),
    LBPLocationData('A Navy Frigate - Prize Bubble 18 - Stone Archway', LEVEL, Kind.PRIZE, uid=2964576, plan='g85443'),
    LBPLocationData('A Navy Frigate - Prize Bubble 19 - Low Stone Wall', LEVEL, Kind.PRIZE, uid=2964578, plan='g85431'),
    LBPLocationData('A Navy Frigate - Prize Bubble 20 - Stone Pillar', LEVEL, Kind.PRIZE, uid=2989456, plan='g85444'),
    LBPLocationData('A Navy Frigate - Prize Bubble 21 - Wax Seal', LEVEL, Kind.PRIZE, uid=2989458, plan='g80184'),
    LBPLocationData('A Navy Frigate - Prize Bubble 22 - Wood Balcony', LEVEL, Kind.PRIZE, uid=3009680, plan='g85448'),
    LBPLocationData("A Navy Frigate - Prize Bubble 23 - 'Deep Blue Quay'", LEVEL, Kind.PRIZE, uid=3080891, plan='g86862'),
    LBPLocationData('A Navy Frigate - Prize Bubble 24 - Blue Leaded Window', LEVEL, Kind.PRIZE, uid=3091782, plan='g85407'),
    LBPLocationData('A Navy Frigate - Prize Bubble 25 - Skull Cupboard', LEVEL, Kind.PRIZE, uid=3099163, plan='g91948'),
    LBPLocationData('A Navy Frigate - Prize Bubble 26 - The Frigate', LEVEL, Kind.PRIZE, uid=3099173, plan='g91951'),
    LBPLocationData('A Navy Frigate - Prize Bubble 27 - Armed Red Coat', LEVEL, Kind.PRIZE, uid=3099187, plan='g91953'),
    LBPLocationData('A Navy Frigate - Prize Bubble 28 - Blue Tiles End', LEVEL, Kind.PRIZE, uid=3155530, plan='g85410'),
    LBPLocationData('A Navy Frigate - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('A Navy Frigate - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('A Navy Frigate - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('A Navy Frigate - Completion Reward 1 - Green Float', LEVEL, Kind.REWARD, plan='g85520', condition=Kind.COMPLETE),
    LBPLocationData('A Navy Frigate - Completion Reward 2 - Torch', LEVEL, Kind.REWARD, plan='g82180', condition=Kind.COMPLETE),
    LBPLocationData('A Navy Frigate - Completion Reward 3 - Blue Window Illuminated', LEVEL, Kind.REWARD, plan='g85412', condition=Kind.COMPLETE),
    LBPLocationData('A Navy Frigate - All Prizes Reward 1 - Door 3', LEVEL, Kind.REWARD, plan='g85423', condition=Kind.ALL_PRIZES),
    LBPLocationData('A Navy Frigate - All Prizes Reward 2 - Wooden Roof Pitch', LEVEL, Kind.REWARD, plan='g85450', condition=Kind.ALL_PRIZES),
    LBPLocationData('A Navy Frigate - All Prizes Reward 3 - Bunting', LEVEL, Kind.REWARD, plan='g85509', condition=Kind.ALL_PRIZES),
    LBPLocationData('A Navy Frigate - Ace Reward 1 - Blue Window', LEVEL, Kind.REWARD, plan='g85413', condition=Kind.ACE),
    LBPLocationData('A Navy Frigate - Ace Reward 2 - Blue Tiles', LEVEL, Kind.REWARD, plan='g85411', condition=Kind.ACE),
    LBPLocationData('A Navy Frigate - Ace Reward 3 - Blue Low Wall', LEVEL, Kind.REWARD, plan='g85408', condition=Kind.ACE),
    LBPLocationData('A Navy Frigate - Sticker Switch 1 - Barbossa', LEVEL, Kind.STICKER_SWITCH, uid=2256074, plan='g89071'),
    LBPLocationData('A Navy Frigate - Sticker Switch 2 - Skull Flag', LEVEL, Kind.STICKER_SWITCH, uid=2489985, plan='g85535'),
)
