from ..model import Kind, LBPLocationData

LEVEL = 'g101098'

LOCATIONS = (
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 1', LEVEL, Kind.SCORE, uid=1526349),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 2', LEVEL, Kind.SCORE, uid=1526350),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 3', LEVEL, Kind.SCORE, uid=1526351),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 4', LEVEL, Kind.SCORE, uid=1526352),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 5', LEVEL, Kind.SCORE, uid=1566438),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 6', LEVEL, Kind.SCORE, uid=1566440),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 7', LEVEL, Kind.SCORE, uid=1566441),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 8', LEVEL, Kind.SCORE, uid=1566442),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 9', LEVEL, Kind.SCORE, uid=1566448),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 10', LEVEL, Kind.SCORE, uid=1566450),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 11', LEVEL, Kind.SCORE, uid=1566451),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 12', LEVEL, Kind.SCORE, uid=1566452),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 13', LEVEL, Kind.SCORE, uid=1566458),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 14', LEVEL, Kind.SCORE, uid=1566460),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 15', LEVEL, Kind.SCORE, uid=1566461),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 16', LEVEL, Kind.SCORE, uid=1566462),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 17', LEVEL, Kind.SCORE, uid=1566497),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 18', LEVEL, Kind.SCORE, uid=1566499),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 19', LEVEL, Kind.SCORE, uid=1566500),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 20', LEVEL, Kind.SCORE, uid=1566501),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 21', LEVEL, Kind.SCORE, uid=1567154),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 22', LEVEL, Kind.SCORE, uid=1567156),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 23', LEVEL, Kind.SCORE, uid=1567157),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 24', LEVEL, Kind.SCORE, uid=1567158),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 25', LEVEL, Kind.SCORE, uid=1569328),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 26', LEVEL, Kind.SCORE, uid=1569330),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 27', LEVEL, Kind.SCORE, uid=1569331),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 28', LEVEL, Kind.SCORE, uid=1569332),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 29', LEVEL, Kind.SCORE, uid=1569802),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 30', LEVEL, Kind.SCORE, uid=1569804),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 31', LEVEL, Kind.SCORE, uid=1569805),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 32', LEVEL, Kind.SCORE, uid=1569806),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 33', LEVEL, Kind.SCORE, uid=1569878),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 34', LEVEL, Kind.SCORE, uid=1569880),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 35', LEVEL, Kind.SCORE, uid=1569882),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 36', LEVEL, Kind.SCORE, uid=1569884),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 37', LEVEL, Kind.SCORE, uid=1569886),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 38', LEVEL, Kind.SCORE, uid=1583744),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 39', LEVEL, Kind.SCORE, uid=1583746),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 40', LEVEL, Kind.SCORE, uid=1583756),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 41', LEVEL, Kind.SCORE, uid=1583757),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 42', LEVEL, Kind.SCORE, uid=2512722),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 43', LEVEL, Kind.SCORE, uid=2512723),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 44', LEVEL, Kind.SCORE, uid=2512724),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 45', LEVEL, Kind.SCORE, uid=2512756),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 46', LEVEL, Kind.SCORE, uid=2512757),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 47', LEVEL, Kind.SCORE, uid=2512758),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 48', LEVEL, Kind.SCORE, uid=2616102),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 49', LEVEL, Kind.SCORE, uid=2616104),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 50', LEVEL, Kind.SCORE, uid=2616106),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 51', LEVEL, Kind.SCORE, uid=2616108),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 52', LEVEL, Kind.SCORE, uid=2616110),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 53', LEVEL, Kind.SCORE, uid=4185644),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 54', LEVEL, Kind.SCORE, uid=4185646),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 55', LEVEL, Kind.SCORE, uid=5387123),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 56', LEVEL, Kind.SCORE, uid=5387163),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 57', LEVEL, Kind.SCORE, uid=5387165),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 58', LEVEL, Kind.SCORE, uid=5387167),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 59', LEVEL, Kind.SCORE, uid=5387169),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 60', LEVEL, Kind.SCORE, uid=5387171),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 61', LEVEL, Kind.SCORE, uid=5387173),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 62', LEVEL, Kind.SCORE, uid=5387175),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 63', LEVEL, Kind.SCORE, uid=5387177),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 64', LEVEL, Kind.SCORE, uid=5418190),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 65', LEVEL, Kind.SCORE, uid=5418192),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 66', LEVEL, Kind.SCORE, uid=5418194),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 67', LEVEL, Kind.SCORE, uid=5418247),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 68', LEVEL, Kind.SCORE, uid=5418249),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 69', LEVEL, Kind.SCORE, uid=5418251),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 70', LEVEL, Kind.SCORE, uid=5418253),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 71', LEVEL, Kind.SCORE, uid=5418255),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 72', LEVEL, Kind.SCORE, uid=5418257),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 73', LEVEL, Kind.SCORE, uid=5419515),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 74', LEVEL, Kind.SCORE, uid=5419516),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 75', LEVEL, Kind.SCORE, uid=5419628),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 76', LEVEL, Kind.SCORE, uid=5422765),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 77', LEVEL, Kind.SCORE, uid=5422766),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 78', LEVEL, Kind.SCORE, uid=5422767),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 79', LEVEL, Kind.SCORE, uid=5422768),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 80', LEVEL, Kind.SCORE, uid=5422779),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 81', LEVEL, Kind.SCORE, uid=5422792),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 82', LEVEL, Kind.SCORE, uid=5422793),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 83', LEVEL, Kind.SCORE, uid=5422794),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 84', LEVEL, Kind.SCORE, uid=5422899),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 85', LEVEL, Kind.SCORE, uid=5422900),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Score Bubble 86', LEVEL, Kind.SCORE, uid=5422901),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 1 - Storm Head', LEVEL, Kind.PRIZE, uid=2466224, plan='g93287'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 2 - Storm Arm Left', LEVEL, Kind.PRIZE, uid=2616132, plan='g93237'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 3 - Storm Arm Right', LEVEL, Kind.PRIZE, uid=2616134, plan='g93238'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 4 - Storm Cloak', LEVEL, Kind.PRIZE, uid=4181120, plan='g93180'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 5 - Wolverine Head', LEVEL, Kind.PRIZE, uid=4182469, plan='g93293'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 6 - Storm Torso', LEVEL, Kind.PRIZE, uid=4184628, plan='g93242'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 7 - Storm Hair', LEVEL, Kind.PRIZE, uid=4186084, plan='g93239'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 8 - Storm Leg Right', LEVEL, Kind.PRIZE, uid=4186086, plan='g93241'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 9 - Storm Leg Left', LEVEL, Kind.PRIZE, uid=4186088, plan='g93240'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 10 - Thor Wing', LEVEL, Kind.PRIZE, uid=4960312, plan='g92063'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 11 - Iron Man Light', LEVEL, Kind.PRIZE, uid=4960528, plan='g89785'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 12 - Iron Man Mask', LEVEL, Kind.PRIZE, uid=4960606, plan='g89786'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 13 - Shlingg!', LEVEL, Kind.PRIZE, uid=5042101, plan='g100651'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 14 - Nooo!', LEVEL, Kind.PRIZE, uid=5042176, plan='g100653'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 15 - Krack!', LEVEL, Kind.PRIZE, uid=5042178, plan='g100654'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 16 - Bamf!', LEVEL, Kind.PRIZE, uid=5042180, plan='g100647'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 17 - Blam', LEVEL, Kind.PRIZE, uid=5042182, plan='g100641'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 18 - Wolverine Torso', LEVEL, Kind.PRIZE, uid=5345829, plan='g93257'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 19 - Human Torch Arm', LEVEL, Kind.PRIZE, uid=5387203, plan='g93213'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 20 - Human Torch Leg', LEVEL, Kind.PRIZE, uid=5387204, plan='g93214'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 21 - Human Torch Torso', LEVEL, Kind.PRIZE, uid=5387207, plan='g93215'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 22 - Human Torch Head', LEVEL, Kind.PRIZE, uid=5387208, plan='g93278'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 23 - Magneto', LEVEL, Kind.PRIZE, uid=5418119, plan='g93281'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 24 - Captain America', LEVEL, Kind.PRIZE, uid=5419512, plan='g93185'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 25 - Captain America Leg', LEVEL, Kind.PRIZE, uid=5419547, plan='g93184'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 26 - Captain America Arm', LEVEL, Kind.PRIZE, uid=5419550, plan='g93183'),
    LBPLocationData("Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 27 - 'Showdown'", LEVEL, Kind.PRIZE, uid=5419641, plan='g97017'),
    LBPLocationData("Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 28 - Captain America's Shield", LEVEL, Kind.PRIZE, uid=5422778, plan='g92056'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 29 - Captain America Torso', LEVEL, Kind.PRIZE, uid=5422797, plan='g93186'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Prize Bubble 30 - Captain America Head', LEVEL, Kind.PRIZE, uid=5422798, plan='g93267'),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData("Marvel™ Issue 2 - Freeway Frenzy - Completion Reward 1 - 'Abomination Alley'", LEVEL, Kind.REWARD, plan='g97016', condition=Kind.COMPLETE),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Completion Reward 2 - Wolverine Leg', LEVEL, Kind.REWARD, plan='g93256', condition=Kind.COMPLETE),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Completion Reward 3 - Wolverine Arm', LEVEL, Kind.REWARD, plan='g93255', condition=Kind.COMPLETE),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - All Prizes Reward 1 - Punisher', LEVEL, Kind.REWARD, plan='g93284', condition=Kind.ALL_PRIZES),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - All Prizes Reward 2 - Punisher Torso', LEVEL, Kind.REWARD, plan='g93230', condition=Kind.ALL_PRIZES),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - All Prizes Reward 3 - Punisher Arm', LEVEL, Kind.REWARD, plan='g93228', condition=Kind.ALL_PRIZES),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Ace Reward 1 - Human Torch Flames', LEVEL, Kind.REWARD, plan='g93303', condition=Kind.ACE),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Ace Reward 2 - Ghost Rider Leg', LEVEL, Kind.REWARD, plan='g93202', condition=Kind.ACE),
    LBPLocationData('Marvel™ Issue 2 - Freeway Frenzy - Ace Reward 3 - Punisher Leg', LEVEL, Kind.REWARD, plan='g93229', condition=Kind.ACE),
)
