from ..model import Kind, LBPLocationData

LEVEL = 'g100338'

LOCATIONS = (
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 1', LEVEL, Kind.SCORE, uid=5716),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 2', LEVEL, Kind.SCORE, uid=5717),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 3', LEVEL, Kind.SCORE, uid=5718),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 4', LEVEL, Kind.SCORE, uid=5719),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 5', LEVEL, Kind.SCORE, uid=5720),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 6', LEVEL, Kind.SCORE, uid=5729),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 7', LEVEL, Kind.SCORE, uid=5730),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 8', LEVEL, Kind.SCORE, uid=5731),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 9', LEVEL, Kind.SCORE, uid=5732),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 10', LEVEL, Kind.SCORE, uid=5733),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 11', LEVEL, Kind.SCORE, uid=5792),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 12', LEVEL, Kind.SCORE, uid=5793),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 13', LEVEL, Kind.SCORE, uid=5794),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 14', LEVEL, Kind.SCORE, uid=5795),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 15', LEVEL, Kind.SCORE, uid=5796),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 16', LEVEL, Kind.SCORE, uid=5828),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 17', LEVEL, Kind.SCORE, uid=5829),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 18', LEVEL, Kind.SCORE, uid=5830),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 19', LEVEL, Kind.SCORE, uid=5831),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 20', LEVEL, Kind.SCORE, uid=5832),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 21', LEVEL, Kind.SCORE, uid=5900),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 22', LEVEL, Kind.SCORE, uid=5901),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 23', LEVEL, Kind.SCORE, uid=5902),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 24', LEVEL, Kind.SCORE, uid=5903),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 25', LEVEL, Kind.SCORE, uid=5904),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 26', LEVEL, Kind.SCORE, uid=5907),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 27', LEVEL, Kind.SCORE, uid=5908),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 28', LEVEL, Kind.SCORE, uid=5909),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 29', LEVEL, Kind.SCORE, uid=5910),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 30', LEVEL, Kind.SCORE, uid=5911),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 31', LEVEL, Kind.SCORE, uid=6390),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 32', LEVEL, Kind.SCORE, uid=6392),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 33', LEVEL, Kind.SCORE, uid=6394),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 34', LEVEL, Kind.SCORE, uid=6396),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 35', LEVEL, Kind.SCORE, uid=6398),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 36', LEVEL, Kind.SCORE, uid=6414),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 37', LEVEL, Kind.SCORE, uid=6416),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 38', LEVEL, Kind.SCORE, uid=6418),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 39', LEVEL, Kind.SCORE, uid=6420),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 40', LEVEL, Kind.SCORE, uid=6422),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 41', LEVEL, Kind.SCORE, uid=7199),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 42', LEVEL, Kind.SCORE, uid=7200),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 43', LEVEL, Kind.SCORE, uid=7201),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 44', LEVEL, Kind.SCORE, uid=7207),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 45', LEVEL, Kind.SCORE, uid=7208),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 46', LEVEL, Kind.SCORE, uid=7212),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 47', LEVEL, Kind.SCORE, uid=7213),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 48', LEVEL, Kind.SCORE, uid=7217),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 49', LEVEL, Kind.SCORE, uid=7218),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 50', LEVEL, Kind.SCORE, uid=7884),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 51', LEVEL, Kind.SCORE, uid=7885),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 52', LEVEL, Kind.SCORE, uid=7886),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 53', LEVEL, Kind.SCORE, uid=7887),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 54', LEVEL, Kind.SCORE, uid=7888),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 55', LEVEL, Kind.SCORE, uid=7890),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 56', LEVEL, Kind.SCORE, uid=7891),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 57', LEVEL, Kind.SCORE, uid=7892),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 58', LEVEL, Kind.SCORE, uid=7893),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 59', LEVEL, Kind.SCORE, uid=7894),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 60', LEVEL, Kind.SCORE, uid=7896),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 61', LEVEL, Kind.SCORE, uid=7897),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 62', LEVEL, Kind.SCORE, uid=7898),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 63', LEVEL, Kind.SCORE, uid=7899),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 64', LEVEL, Kind.SCORE, uid=7900),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 65', LEVEL, Kind.SCORE, uid=7956),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 66', LEVEL, Kind.SCORE, uid=7957),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 67', LEVEL, Kind.SCORE, uid=7958),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 68', LEVEL, Kind.SCORE, uid=7959),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 69', LEVEL, Kind.SCORE, uid=7960),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 70', LEVEL, Kind.SCORE, uid=7961),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 71', LEVEL, Kind.SCORE, uid=7962),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 72', LEVEL, Kind.SCORE, uid=7963),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 73', LEVEL, Kind.SCORE, uid=7964),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 74', LEVEL, Kind.SCORE, uid=7965),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 75', LEVEL, Kind.SCORE, uid=7974),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 76', LEVEL, Kind.SCORE, uid=7975),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 77', LEVEL, Kind.SCORE, uid=7976),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 78', LEVEL, Kind.SCORE, uid=7977),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 79', LEVEL, Kind.SCORE, uid=7978),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 80', LEVEL, Kind.SCORE, uid=7979),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 81', LEVEL, Kind.SCORE, uid=7980),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 82', LEVEL, Kind.SCORE, uid=7981),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 83', LEVEL, Kind.SCORE, uid=7982),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 84', LEVEL, Kind.SCORE, uid=7983),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 85', LEVEL, Kind.SCORE, uid=8284),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 86', LEVEL, Kind.SCORE, uid=378831),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 87', LEVEL, Kind.SCORE, uid=378846),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 88', LEVEL, Kind.SCORE, uid=378848),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 89', LEVEL, Kind.SCORE, uid=378865),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 90', LEVEL, Kind.SCORE, uid=378921),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 91', LEVEL, Kind.SCORE, uid=378923),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 92', LEVEL, Kind.SCORE, uid=378924),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 93', LEVEL, Kind.SCORE, uid=378926),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 94', LEVEL, Kind.SCORE, uid=378949),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 95', LEVEL, Kind.SCORE, uid=378950),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 96', LEVEL, Kind.SCORE, uid=378952),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 97', LEVEL, Kind.SCORE, uid=378954),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 98', LEVEL, Kind.SCORE, uid=378961),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 99', LEVEL, Kind.SCORE, uid=378963),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 100', LEVEL, Kind.SCORE, uid=378964),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 101', LEVEL, Kind.SCORE, uid=378966),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 102', LEVEL, Kind.SCORE, uid=507336),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 103', LEVEL, Kind.SCORE, uid=507337),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 104', LEVEL, Kind.SCORE, uid=507338),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 105', LEVEL, Kind.SCORE, uid=507351),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 106', LEVEL, Kind.SCORE, uid=507352),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 107', LEVEL, Kind.SCORE, uid=507353),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 108', LEVEL, Kind.SCORE, uid=507357),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 109', LEVEL, Kind.SCORE, uid=507358),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 110', LEVEL, Kind.SCORE, uid=507359),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 111', LEVEL, Kind.SCORE, uid=507363),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 112', LEVEL, Kind.SCORE, uid=507364),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 113', LEVEL, Kind.SCORE, uid=507365),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 114', LEVEL, Kind.SCORE, uid=507874),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 115', LEVEL, Kind.SCORE, uid=507876),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 116', LEVEL, Kind.SCORE, uid=507878),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 117', LEVEL, Kind.SCORE, uid=507880),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 118', LEVEL, Kind.SCORE, uid=507882),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 119', LEVEL, Kind.SCORE, uid=507884),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 120', LEVEL, Kind.SCORE, uid=508346),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 121', LEVEL, Kind.SCORE, uid=508348),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 122', LEVEL, Kind.SCORE, uid=508350),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 123', LEVEL, Kind.SCORE, uid=508352),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 124', LEVEL, Kind.SCORE, uid=508354),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 125', LEVEL, Kind.SCORE, uid=508574),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 126', LEVEL, Kind.SCORE, uid=508576),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 127', LEVEL, Kind.SCORE, uid=508578),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 128', LEVEL, Kind.SCORE, uid=508580),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 129', LEVEL, Kind.SCORE, uid=508582),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 130', LEVEL, Kind.SCORE, uid=526534),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 131', LEVEL, Kind.SCORE, uid=526536),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 132', LEVEL, Kind.SCORE, uid=526538),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 133', LEVEL, Kind.SCORE, uid=526540),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 134', LEVEL, Kind.SCORE, uid=526542),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 135', LEVEL, Kind.SCORE, uid=526544),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 136', LEVEL, Kind.SCORE, uid=526546),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 137', LEVEL, Kind.SCORE, uid=526548),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 138', LEVEL, Kind.SCORE, uid=526550),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 139', LEVEL, Kind.SCORE, uid=526552),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 140', LEVEL, Kind.SCORE, uid=526554),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 141', LEVEL, Kind.SCORE, uid=526556),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 142', LEVEL, Kind.SCORE, uid=526558),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 143', LEVEL, Kind.SCORE, uid=526560),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 144', LEVEL, Kind.SCORE, uid=526562),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 145', LEVEL, Kind.SCORE, uid=526564),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 146', LEVEL, Kind.SCORE, uid=526579),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 147', LEVEL, Kind.SCORE, uid=526581),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 148', LEVEL, Kind.SCORE, uid=526583),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 149', LEVEL, Kind.SCORE, uid=526585),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 150', LEVEL, Kind.SCORE, uid=526587),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 151', LEVEL, Kind.SCORE, uid=526589),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 152', LEVEL, Kind.SCORE, uid=526603),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 153', LEVEL, Kind.SCORE, uid=526605),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 154', LEVEL, Kind.SCORE, uid=526607),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 155', LEVEL, Kind.SCORE, uid=526609),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Score Bubble 156', LEVEL, Kind.SCORE, uid=526611),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 1 - Straight Web', LEVEL, Kind.PRIZE, uid=5773, plan='g93296'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 2 - Story Box', LEVEL, Kind.PRIZE, uid=5786, plan='g93264'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 3 - Fireball', LEVEL, Kind.PRIZE, uid=5787, plan='g93301'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 4 - Hulk Arm', LEVEL, Kind.PRIZE, uid=200671, plan='g93206'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 5 - Hulk Leg', LEVEL, Kind.PRIZE, uid=200676, plan='g93207'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 6 - Hulk Torso', LEVEL, Kind.PRIZE, uid=200711, plan='g93208'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 7 - Hulk Head', LEVEL, Kind.PRIZE, uid=200713, plan='g93276'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 8 - Red Splat', LEVEL, Kind.PRIZE, uid=200748, plan='g93260'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 9 - Thing Torso', LEVEL, Kind.PRIZE, uid=251024, plan='g93246'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 10 - Thing Head', LEVEL, Kind.PRIZE, uid=251026, plan='g93288'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 11 - Thing Legs', LEVEL, Kind.PRIZE, uid=251028, plan='g93245'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 12 - Narrow Story Box', LEVEL, Kind.PRIZE, uid=298649, plan='g93263'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 13 - Spider-Man Torso', LEVEL, Kind.PRIZE, uid=441668, plan='g93233'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 14 - Spider-Man Arm', LEVEL, Kind.PRIZE, uid=441670, plan='g93231'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 15 - Spider-Man Leg', LEVEL, Kind.PRIZE, uid=441672, plan='g93232'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 16 - Exhaust Vent', LEVEL, Kind.PRIZE, uid=441685, plan='g92058'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 17 - Window Big', LEVEL, Kind.PRIZE, uid=441687, plan='g92064'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 18 - Thor Torso', LEVEL, Kind.PRIZE, uid=443087, plan='g93251'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 19 - Thor Hair', LEVEL, Kind.PRIZE, uid=443119, plan='g93249'),
    LBPLocationData("Marvel™ Issue 1 - Downtown Doom - Prize Bubble 20 - Thor's Hammer", LEVEL, Kind.PRIZE, uid=443417, plan='g89787'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 21 - Pencilled Windows', LEVEL, Kind.PRIZE, uid=443424, plan='g89781'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 22 - Thing Mask', LEVEL, Kind.PRIZE, uid=443450, plan='g89789'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 23 - Black Ink Spatter', LEVEL, Kind.PRIZE, uid=443452, plan='g93258'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 24 - Skylight', LEVEL, Kind.PRIZE, uid=443454, plan='g92061'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 25 - Thing Arm Left', LEVEL, Kind.PRIZE, uid=443465, plan='g93243'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 26 - Galactus Leg', LEVEL, Kind.PRIZE, uid=443480, plan='g93197'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 27 - Galactus Kilt', LEVEL, Kind.PRIZE, uid=443490, plan='g93196'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 28 - Galactus Torso', LEVEL, Kind.PRIZE, uid=443497, plan='g93198'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 29 - Galactus Arm Left', LEVEL, Kind.PRIZE, uid=443504, plan='g93195'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 30 - Galactus Head', LEVEL, Kind.PRIZE, uid=443506, plan='g93271'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 31 - Wriggly Web', LEVEL, Kind.PRIZE, uid=443531, plan='g93295'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 32 - Attached Web', LEVEL, Kind.PRIZE, uid=443533, plan='g93294'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 33 - Green Goblin Torso', LEVEL, Kind.PRIZE, uid=443541, plan='g93201'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 34 - Green Goblin Arm', LEVEL, Kind.PRIZE, uid=443543, plan='g93199'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 35 - Green Goblin Leg', LEVEL, Kind.PRIZE, uid=443545, plan='g93200'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 36 - Spider-Man Eye', LEVEL, Kind.PRIZE, uid=443567, plan='g92062'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 37 - Thor Leg', LEVEL, Kind.PRIZE, uid=444620, plan='g93250'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 38 - Thor Arm Right', LEVEL, Kind.PRIZE, uid=444622, plan='g93247'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 39 - Thor Arm Left', LEVEL, Kind.PRIZE, uid=444624, plan='g93248'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 40 - Window Small', LEVEL, Kind.PRIZE, uid=445337, plan='g92065'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 41 - Pencilled Cityscape', LEVEL, Kind.PRIZE, uid=445375, plan='g89780'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 42 - Gargoyle', LEVEL, Kind.PRIZE, uid=445383, plan='g92059'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 43 - Thor Cloak', LEVEL, Kind.PRIZE, uid=499875, plan='g93181'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 44 - Thor Wing', LEVEL, Kind.PRIZE, uid=598788, plan='g93182'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 45 - Galactus Arm Right', LEVEL, Kind.PRIZE, uid=600180, plan='g93194'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 46 - Thing Arm Right', LEVEL, Kind.PRIZE, uid=664752, plan='g93244'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 47 - Spider-Man Head', LEVEL, Kind.PRIZE, uid=665234, plan='g93285'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 48 - Thor Head', LEVEL, Kind.PRIZE, uid=665812, plan='g93289'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 49 - Green Goblin Head', LEVEL, Kind.PRIZE, uid=665836, plan='g93272'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 50 - Pa-Zam!', LEVEL, Kind.PRIZE, uid=703157, plan='g100652'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 51 - Klonk!', LEVEL, Kind.PRIZE, uid=703159, plan='g100640'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 52 - Kra-koom!', LEVEL, Kind.PRIZE, uid=703161, plan='g100638'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 53 - Thwap!', LEVEL, Kind.PRIZE, uid=703163, plan='g100646'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Prize Bubble 54 - Thoomp!', LEVEL, Kind.PRIZE, uid=703206, plan='g100648'),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Completion Reward 1 - Marvel™ Level Kit Background', LEVEL, Kind.REWARD, plan='g92664', condition=Kind.COMPLETE),
    LBPLocationData("Marvel™ Issue 1 - Downtown Doom - Completion Reward 2 - 'Frantic Pursuit'", LEVEL, Kind.REWARD, plan='g97015', condition=Kind.COMPLETE),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Completion Reward 3 - Retro Marvel™ Panels', LEVEL, Kind.REWARD, plan='g89782', condition=Kind.COMPLETE),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - All Prizes Reward 1 - Fantastic Four Logo', LEVEL, Kind.REWARD, plan='g93312', condition=Kind.ALL_PRIZES),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - All Prizes Reward 2 - Hanging Spider-Man', LEVEL, Kind.REWARD, plan='g100598', condition=Kind.ALL_PRIZES),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - All Prizes Reward 3 - Punisher Chopper', LEVEL, Kind.REWARD, plan='g101186', condition=Kind.ALL_PRIZES),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Ace Reward 1 - Narrow Speech Bubble', LEVEL, Kind.REWARD, plan='g93309', condition=Kind.ACE),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Ace Reward 2 - Speech Bubble', LEVEL, Kind.REWARD, plan='g93310', condition=Kind.ACE),
    LBPLocationData('Marvel™ Issue 1 - Downtown Doom - Ace Reward 3 - Tension Bubble', LEVEL, Kind.REWARD, plan='g93311', condition=Kind.ACE),
    LBPLocationData('Marvelâ„¢ Issue 1 - Downtown Doom - Sticker Switch 1 - Doctor Octopus Caricature', LEVEL, Kind.STICKER_SWITCH, uid=479495, plan='g93283'),
)
