from ..model import Kind, LBPLocationData

LEVEL = 'g67166'

LOCATIONS = (
    LBPLocationData('METAL GEAR SOLID® Act 1: Introduction - Prize Bubble 1 - METAL GEAR SOLID®', LEVEL, Kind.PRIZE, uid=440693902, plan='g66379'),
    LBPLocationData('METAL GEAR SOLID® Act 1: Introduction - Prize Bubble 2 - METAL GEAR SOLID®', LEVEL, Kind.PRIZE, uid=440693907, plan='g66082'),
    LBPLocationData('METAL GEAR SOLID® Act 1: Introduction - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('METAL GEAR SOLID® Act 1: Introduction - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('METAL GEAR SOLID® Act 1: Introduction - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('METAL GEAR SOLID® Act 1: Introduction - Completion Reward 1 - Gurlukovich Soldier Helmet and Mask', LEVEL, Kind.REWARD, plan='g66959', condition=Kind.COMPLETE),
    LBPLocationData('METAL GEAR SOLID® Act 1: Introduction - Completion Reward 2 - Gurlukovich Soldier Vest', LEVEL, Kind.REWARD, plan='g66960', condition=Kind.COMPLETE),
    LBPLocationData('METAL GEAR SOLID® Act 1: Introduction - Completion Reward 3 - Gurlukovich Soldier Uniform', LEVEL, Kind.REWARD, plan='g66961', condition=Kind.COMPLETE),
    LBPLocationData('METAL GEAR SOLID® Act 1: Introduction - Ace Reward 1 - Metal', LEVEL, Kind.REWARD, plan='g65692', condition=Kind.ACE),
    LBPLocationData('METAL GEAR SOLID® Act 1: Introduction - Ace Reward 2 - Gear', LEVEL, Kind.REWARD, plan='g65691', condition=Kind.ACE),
    LBPLocationData('METAL GEAR SOLID® Act 1: Introduction - Ace Reward 3 - Solid', LEVEL, Kind.REWARD, plan='g65693', condition=Kind.ACE),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 1 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=374603717, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 2 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=376702305, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 3 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=377751249, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 4 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=379849106, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 5 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=385093853, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 6 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=385093857, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 7 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=385093859, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 11 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=395583880, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 12 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=395583891, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 13 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=395583893, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 14 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=396632866, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 15 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=396632868, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 16 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=396632870, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 17 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=396632872, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 18 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=396632874, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 19 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=401877831, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 20 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=405024705, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 21 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=405024760, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 22 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=405024784, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 23 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=407122644, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 24 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=407122655, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 25 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=407122666, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 26 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=407122677, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 27 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=407122688, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 28 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=407122699, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 29 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=419711038, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 30 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=419711055, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 31 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=419711064, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 32 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=419711073, plan='g66622'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 1: Introduction - Sticker Switch 33 - Big Bullet Hole', LEVEL, Kind.STICKER_SWITCH, uid=419711100, plan='g66622'),
)
