from ..model import Kind, LBPLocationData

LEVEL = 'g67647'

LOCATIONS = (
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 1', LEVEL, Kind.SCORE, uid=1069500),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 2', LEVEL, Kind.SCORE, uid=1069501),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 3', LEVEL, Kind.SCORE, uid=1069502),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 4', LEVEL, Kind.SCORE, uid=2147339),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 5', LEVEL, Kind.SCORE, uid=2147340),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 6', LEVEL, Kind.SCORE, uid=2147341),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 7', LEVEL, Kind.SCORE, uid=2147342),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 8', LEVEL, Kind.SCORE, uid=2147343),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 9', LEVEL, Kind.SCORE, uid=2147344),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 10', LEVEL, Kind.SCORE, uid=2147345),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 11', LEVEL, Kind.SCORE, uid=2147346),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 12', LEVEL, Kind.SCORE, uid=2147347),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 13', LEVEL, Kind.SCORE, uid=2157940),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 14', LEVEL, Kind.SCORE, uid=2157941),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 15', LEVEL, Kind.SCORE, uid=2157942),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 16', LEVEL, Kind.SCORE, uid=2165981),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 17', LEVEL, Kind.SCORE, uid=2165982),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 18', LEVEL, Kind.SCORE, uid=2165983),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 19', LEVEL, Kind.SCORE, uid=2166374),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 20', LEVEL, Kind.SCORE, uid=2166375),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 21', LEVEL, Kind.SCORE, uid=2166376),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 22', LEVEL, Kind.SCORE, uid=2166377),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 23', LEVEL, Kind.SCORE, uid=2166378),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 24', LEVEL, Kind.SCORE, uid=2166379),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 25', LEVEL, Kind.SCORE, uid=2166380),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 26', LEVEL, Kind.SCORE, uid=2166381),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 27', LEVEL, Kind.SCORE, uid=2166382),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 28', LEVEL, Kind.SCORE, uid=2166383),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 29', LEVEL, Kind.SCORE, uid=2166384),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 30', LEVEL, Kind.SCORE, uid=2166385),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 31', LEVEL, Kind.SCORE, uid=2166758),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 32', LEVEL, Kind.SCORE, uid=2166759),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 33', LEVEL, Kind.SCORE, uid=2166760),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 34', LEVEL, Kind.SCORE, uid=2167094),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 35', LEVEL, Kind.SCORE, uid=2167095),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 36', LEVEL, Kind.SCORE, uid=2167096),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 37', LEVEL, Kind.SCORE, uid=3222951),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 38', LEVEL, Kind.SCORE, uid=3222952),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 39', LEVEL, Kind.SCORE, uid=3222953),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 40', LEVEL, Kind.SCORE, uid=3222954),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 41', LEVEL, Kind.SCORE, uid=3222961),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 42', LEVEL, Kind.SCORE, uid=3222962),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 43', LEVEL, Kind.SCORE, uid=3222963),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 44', LEVEL, Kind.SCORE, uid=3222964),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 45', LEVEL, Kind.SCORE, uid=3224104),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 46', LEVEL, Kind.SCORE, uid=3224105),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 47', LEVEL, Kind.SCORE, uid=3224106),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 48', LEVEL, Kind.SCORE, uid=3224107),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 49', LEVEL, Kind.SCORE, uid=3224114),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 50', LEVEL, Kind.SCORE, uid=3224115),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 51', LEVEL, Kind.SCORE, uid=3224116),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 52', LEVEL, Kind.SCORE, uid=3224117),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 53', LEVEL, Kind.SCORE, uid=3224124),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 54', LEVEL, Kind.SCORE, uid=3224125),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 55', LEVEL, Kind.SCORE, uid=3224126),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 56', LEVEL, Kind.SCORE, uid=3224127),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 57', LEVEL, Kind.SCORE, uid=3224134),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 58', LEVEL, Kind.SCORE, uid=3224135),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 59', LEVEL, Kind.SCORE, uid=3224136),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 60', LEVEL, Kind.SCORE, uid=3224137),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 61', LEVEL, Kind.SCORE, uid=31080406),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 62', LEVEL, Kind.SCORE, uid=31080407),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 63', LEVEL, Kind.SCORE, uid=31080408),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 64', LEVEL, Kind.SCORE, uid=31080409),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 65', LEVEL, Kind.SCORE, uid=31080416),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 66', LEVEL, Kind.SCORE, uid=31080417),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 67', LEVEL, Kind.SCORE, uid=31080418),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 68', LEVEL, Kind.SCORE, uid=31080419),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 69', LEVEL, Kind.SCORE, uid=31080426),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 70', LEVEL, Kind.SCORE, uid=31080427),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 71', LEVEL, Kind.SCORE, uid=31080428),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Score Bubble 72', LEVEL, Kind.SCORE, uid=31080429),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 1 - Gekko Leg', LEVEL, Kind.PRIZE, uid=3223369, plan='g65695'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 2 - Old Snake Arm 1', LEVEL, Kind.PRIZE, uid=3223371, plan='g65708'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 3 - Old Snake Arm 2', LEVEL, Kind.PRIZE, uid=3223372, plan='g65709'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 4 - Boss', LEVEL, Kind.PRIZE, uid=3223374, plan='g65768'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 5 - Black Spider', LEVEL, Kind.PRIZE, uid=3223375, plan='g65780'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 6 - Camouflage 2', LEVEL, Kind.PRIZE, uid=3223379, plan='g66617'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 7 - Camouflage 1', LEVEL, Kind.PRIZE, uid=3223380, plan='g66618'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 8 - Eye Have You Logo', LEVEL, Kind.PRIZE, uid=3223382, plan='g65697'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 9 - Big', LEVEL, Kind.PRIZE, uid=3223383, plan='g65769'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 10 - Screaming Mantis Helmet', LEVEL, Kind.PRIZE, uid=3223386, plan='g65772'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 11 - Red Eagle', LEVEL, Kind.PRIZE, uid=3223389, plan='g65785'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 12 - Old Snake Leg', LEVEL, Kind.PRIZE, uid=3223390, plan='g65786'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 13 - Old Snake Body', LEVEL, Kind.PRIZE, uid=3223391, plan='g65787'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 14 - Decal 4', LEVEL, Kind.PRIZE, uid=3223396, plan='g66609'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 15 - Decal 3', LEVEL, Kind.PRIZE, uid=3223397, plan='g66610'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 16 - Decal 2', LEVEL, Kind.PRIZE, uid=3223398, plan='g66611'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 17 - Decal 1', LEVEL, Kind.PRIZE, uid=3223399, plan='g66612'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 18 - Single Bullet Hole', LEVEL, Kind.PRIZE, uid=3223401, plan='g66621'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 19 - Grenade Silo', LEVEL, Kind.PRIZE, uid=3223406, plan='g66215'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 20 - Utility Pack', LEVEL, Kind.PRIZE, uid=3223407, plan='g66150'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 21 - Circular Armour Plate', LEVEL, Kind.PRIZE, uid=3223408, plan='g66309'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 22 - Long Armour Plate', LEVEL, Kind.PRIZE, uid=3223409, plan='g66310'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 23 - Bubble Vendor', LEVEL, Kind.PRIZE, uid=3223415, plan='g67556'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 24 - Stryker Rex', LEVEL, Kind.PRIZE, uid=3223418, plan='g67562'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 25 - Target Platform', LEVEL, Kind.PRIZE, uid=3223419, plan='g67605'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 26 - Super Sentry Turret', LEVEL, Kind.PRIZE, uid=3223420, plan='g67607'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 27 - Pop-up Sentry Turret', LEVEL, Kind.PRIZE, uid=3223421, plan='g67606'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 28 - Pop-down Sentry Turret', LEVEL, Kind.PRIZE, uid=3223424, plan='g67584'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 29 - Teabag', LEVEL, Kind.PRIZE, uid=3223425, plan='g66655'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 30 - Tin Bunker', LEVEL, Kind.PRIZE, uid=3223426, plan='g66975'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 31 - Tin Bunker Front', LEVEL, Kind.PRIZE, uid=3223428, plan='g67175'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 32 - MGS2 \'Yell "Dead Cell" (VR remix)\'', LEVEL, Kind.PRIZE, uid=31093096, plan='g67000'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 33 - Bubbles Container', LEVEL, Kind.PRIZE, uid=31094101, plan='g67557'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 34 - Gekko Skin Edge', LEVEL, Kind.PRIZE, uid=31101090, plan='g65720'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 35 - Orange Gecko', LEVEL, Kind.PRIZE, uid=31101091, plan='g65783'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Prize Bubble 36 - Missile', LEVEL, Kind.PRIZE, uid=31101092, plan='g67084'),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Completion Reward 1 - Gekko Amour Plating', LEVEL, Kind.REWARD, plan='g65979', condition=Kind.COMPLETE),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Completion Reward 2 - Gekko Skin', LEVEL, Kind.REWARD, plan='g66058', condition=Kind.COMPLETE),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Completion Reward 3 - Middle Eastern Stone Relief', LEVEL, Kind.REWARD, plan='g65722', condition=Kind.COMPLETE),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - All Prizes Reward 1 - Metal Gear Rex', LEVEL, Kind.REWARD, plan='g66596', condition=Kind.ALL_PRIZES),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - All Prizes Reward 2 - METAL GEAR Mk.II', LEVEL, Kind.REWARD, plan='g67257', condition=Kind.ALL_PRIZES),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Ace Reward 1 - Snake', LEVEL, Kind.REWARD, plan='g65770', condition=Kind.ACE),
    LBPLocationData('METAL GEAR SOLID® Act 4: The Level Factory - Ace Reward 2 - Old Snake Moustache', LEVEL, Kind.REWARD, plan='g65696', condition=Kind.ACE),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 4: The Level Factory - Sticker Switch 1 - Gekko Crouching 1', LEVEL, Kind.STICKER_SWITCH, uid=3224157, plan='g66606'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 4: The Level Factory - Sticker Switch 2 - Otacon Face', LEVEL, Kind.STICKER_SWITCH, uid=3224826, plan='g65788'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 4: The Level Factory - Sticker Switch 3 - Black Spider', LEVEL, Kind.STICKER_SWITCH, uid=3224828, plan='g65780'),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 4: The Level Factory - Key 1', LEVEL, Kind.KEY, uid=2152254, target_slot='SlotID{DLC_LEVEL, 66977}'),
)
