from ..model import Kind, LBPLocationData

LEVEL = 'g67167'

LOCATIONS = (
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 1', LEVEL, Kind.SCORE, uid=1066779),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 2', LEVEL, Kind.SCORE, uid=1066780),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 3', LEVEL, Kind.SCORE, uid=1066782),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 4', LEVEL, Kind.SCORE, uid=1066783),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 5', LEVEL, Kind.SCORE, uid=1066787),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 6', LEVEL, Kind.SCORE, uid=1066788),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 7', LEVEL, Kind.SCORE, uid=1066789),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 8', LEVEL, Kind.SCORE, uid=1066790),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 9', LEVEL, Kind.SCORE, uid=1066791),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 10', LEVEL, Kind.SCORE, uid=1066792),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 11', LEVEL, Kind.SCORE, uid=1066793),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 12', LEVEL, Kind.SCORE, uid=1066794),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 13', LEVEL, Kind.SCORE, uid=1066795),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 14', LEVEL, Kind.SCORE, uid=1066796),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 15', LEVEL, Kind.SCORE, uid=1066797),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 16', LEVEL, Kind.SCORE, uid=1066798),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 17', LEVEL, Kind.SCORE, uid=2157876),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 18', LEVEL, Kind.SCORE, uid=2157877),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 19', LEVEL, Kind.SCORE, uid=2157878),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 20', LEVEL, Kind.SCORE, uid=2157879),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 21', LEVEL, Kind.SCORE, uid=2157880),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 22', LEVEL, Kind.SCORE, uid=2157881),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 23', LEVEL, Kind.SCORE, uid=2157882),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 24', LEVEL, Kind.SCORE, uid=2157884),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 25', LEVEL, Kind.SCORE, uid=2157885),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 26', LEVEL, Kind.SCORE, uid=2157949),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 27', LEVEL, Kind.SCORE, uid=2157950),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 28', LEVEL, Kind.SCORE, uid=2157951),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 29', LEVEL, Kind.SCORE, uid=2157953),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 30', LEVEL, Kind.SCORE, uid=2157955),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 31', LEVEL, Kind.SCORE, uid=2157957),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 32', LEVEL, Kind.SCORE, uid=2157969),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 33', LEVEL, Kind.SCORE, uid=2157970),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 34', LEVEL, Kind.SCORE, uid=2157971),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 35', LEVEL, Kind.SCORE, uid=2160994),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 36', LEVEL, Kind.SCORE, uid=2160995),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 37', LEVEL, Kind.SCORE, uid=2160996),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 38', LEVEL, Kind.SCORE, uid=2160997),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 39', LEVEL, Kind.SCORE, uid=2160998),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 40', LEVEL, Kind.SCORE, uid=2160999),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 41', LEVEL, Kind.SCORE, uid=2168518),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 42', LEVEL, Kind.SCORE, uid=2168519),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 43', LEVEL, Kind.SCORE, uid=2168520),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 44', LEVEL, Kind.SCORE, uid=2168521),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 45', LEVEL, Kind.SCORE, uid=2168528),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 46', LEVEL, Kind.SCORE, uid=2168529),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 47', LEVEL, Kind.SCORE, uid=2168530),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 48', LEVEL, Kind.SCORE, uid=2168531),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 49', LEVEL, Kind.SCORE, uid=2168538),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 50', LEVEL, Kind.SCORE, uid=2168539),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 51', LEVEL, Kind.SCORE, uid=2168540),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 52', LEVEL, Kind.SCORE, uid=2168541),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 53', LEVEL, Kind.SCORE, uid=2168548),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 54', LEVEL, Kind.SCORE, uid=2168549),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 55', LEVEL, Kind.SCORE, uid=2168550),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 56', LEVEL, Kind.SCORE, uid=2168551),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 57', LEVEL, Kind.SCORE, uid=2168562),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 58', LEVEL, Kind.SCORE, uid=2168563),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 59', LEVEL, Kind.SCORE, uid=2168564),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 60', LEVEL, Kind.SCORE, uid=2168565),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 61', LEVEL, Kind.SCORE, uid=2168573),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 62', LEVEL, Kind.SCORE, uid=2168574),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 63', LEVEL, Kind.SCORE, uid=2168575),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 64', LEVEL, Kind.SCORE, uid=2168576),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Score Bubble 65', LEVEL, Kind.SCORE, uid=3223764),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 1 - Blue Wolf', LEVEL, Kind.PRIZE, uid=3223376, plan='g65781'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 2 - Camouflage 3', LEVEL, Kind.PRIZE, uid=3223378, plan='g66616'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 3 - Damage Crack 2', LEVEL, Kind.PRIZE, uid=3223381, plan='g66619'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 4 - Young Snake Leg', LEVEL, Kind.PRIZE, uid=3223387, plan='g65776'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 5 - Green Frog', LEVEL, Kind.PRIZE, uid=3223388, plan='g65784'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 6 - Explosion', LEVEL, Kind.PRIZE, uid=3223395, plan='g66608'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 7 - Bullet Holes', LEVEL, Kind.PRIZE, uid=3223402, plan='g66623'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 8 - Practice Target', LEVEL, Kind.PRIZE, uid=3223403, plan='g66624'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 9 - Wall Damage', LEVEL, Kind.PRIZE, uid=3223405, plan='g67258'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 10 - Short Armour Plate', LEVEL, Kind.PRIZE, uid=3223410, plan='g66311'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 11 - Interlocking Armour Plate', LEVEL, Kind.PRIZE, uid=3223411, plan='g66312'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 12 - Stryker', LEVEL, Kind.PRIZE, uid=3223417, plan='g67572'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 13 - Sentry Turret', LEVEL, Kind.PRIZE, uid=3223422, plan='g67604'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 14 - Static Sentry Turret', LEVEL, Kind.PRIZE, uid=3223423, plan='g67603'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 15 - Searchlight', LEVEL, Kind.PRIZE, uid=3223427, plan='g67859'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 16 - Damage Crack 1', LEVEL, Kind.PRIZE, uid=3223429, plan='g66620'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 17 - Middle Eastern Tiles', LEVEL, Kind.PRIZE, uid=31082818, plan='g65721'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 18 - Embossed Cardboard', LEVEL, Kind.PRIZE, uid=31082820, plan='g65934'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 19 - Middle Eastern Render', LEVEL, Kind.PRIZE, uid=31082822, plan='g65982'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 20 - Middle Eastern Lattice', LEVEL, Kind.PRIZE, uid=31082824, plan='g67472'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 21 - Sack Cannon', LEVEL, Kind.PRIZE, uid=31091327, plan='g67552'),
    LBPLocationData("METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 22 - MGS4 'The Hunter'", LEVEL, Kind.PRIZE, uid=31093402, plan='g66380'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Prize Bubble 23 - Laser Sight', LEVEL, Kind.PRIZE, uid=31096747, plan='g66991'),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Completion Reward 1 - Old Snake Head', LEVEL, Kind.REWARD, plan='g65710', condition=Kind.COMPLETE),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Completion Reward 2 - Circular Vent', LEVEL, Kind.REWARD, plan='g66442', condition=Kind.COMPLETE),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Completion Reward 3 - Solid Eye', LEVEL, Kind.REWARD, plan='g65701', condition=Kind.COMPLETE),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - All Prizes Reward 1 - Foxhound Patch', LEVEL, Kind.REWARD, plan='g65777', condition=Kind.ALL_PRIZES),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - All Prizes Reward 2 - Pixel Crate', LEVEL, Kind.REWARD, plan='g66607', condition=Kind.ALL_PRIZES),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - All Prizes Reward 3 - Black Wolf', LEVEL, Kind.REWARD, plan='g65694', condition=Kind.ALL_PRIZES),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Ace Reward 1 - Metal Gear Rex Head', LEVEL, Kind.REWARD, plan='g65771', condition=Kind.ACE),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Ace Reward 2 - Sensor Pod', LEVEL, Kind.REWARD, plan='g66469', condition=Kind.ACE),
    LBPLocationData('METAL GEAR SOLID® Act 3: The Mission - Ace Reward 3 - Metal Gear Ray', LEVEL, Kind.REWARD, plan='g66597', condition=Kind.ACE),
    LBPLocationData('METAL GEAR SOLIDÂ® Act 3: The Mission - Sticker Switch 1 - Solid Eye', LEVEL, Kind.STICKER_SWITCH, uid=2164169, plan='g65701'),
)
