from ..model import Kind, LBPLocationData

LEVEL = 'g89120'

LOCATIONS = (
    LBPLocationData('Pirate Town - Score Bubble 1', LEVEL, Kind.SCORE, uid=7803),
    LBPLocationData('Pirate Town - Score Bubble 2', LEVEL, Kind.SCORE, uid=9063),
    LBPLocationData('Pirate Town - Score Bubble 3', LEVEL, Kind.SCORE, uid=9065),
    LBPLocationData('Pirate Town - Score Bubble 4', LEVEL, Kind.SCORE, uid=9067),
    LBPLocationData('Pirate Town - Score Bubble 5', LEVEL, Kind.SCORE, uid=9189),
    LBPLocationData('Pirate Town - Score Bubble 6', LEVEL, Kind.SCORE, uid=499177),
    LBPLocationData('Pirate Town - Score Bubble 7', LEVEL, Kind.SCORE, uid=1539557),
    LBPLocationData('Pirate Town - Score Bubble 8', LEVEL, Kind.SCORE, uid=2072538),
    LBPLocationData('Pirate Town - Score Bubble 9', LEVEL, Kind.SCORE, uid=2162929),
    LBPLocationData('Pirate Town - Score Bubble 10', LEVEL, Kind.SCORE, uid=2162943),
    LBPLocationData('Pirate Town - Score Bubble 11', LEVEL, Kind.SCORE, uid=2162961),
    LBPLocationData('Pirate Town - Score Bubble 12', LEVEL, Kind.SCORE, uid=2162975),
    LBPLocationData('Pirate Town - Score Bubble 13', LEVEL, Kind.SCORE, uid=2163840),
    LBPLocationData('Pirate Town - Score Bubble 14', LEVEL, Kind.SCORE, uid=2166530),
    LBPLocationData('Pirate Town - Score Bubble 15', LEVEL, Kind.SCORE, uid=2477603),
    LBPLocationData('Pirate Town - Score Bubble 16', LEVEL, Kind.SCORE, uid=2477605),
    LBPLocationData('Pirate Town - Score Bubble 17', LEVEL, Kind.SCORE, uid=2477607),
    LBPLocationData('Pirate Town - Score Bubble 18', LEVEL, Kind.SCORE, uid=2477609),
    LBPLocationData('Pirate Town - Score Bubble 19', LEVEL, Kind.SCORE, uid=2477611),
    LBPLocationData('Pirate Town - Score Bubble 20', LEVEL, Kind.SCORE, uid=2581707),
    LBPLocationData('Pirate Town - Score Bubble 21', LEVEL, Kind.SCORE, uid=2581714),
    LBPLocationData('Pirate Town - Score Bubble 22', LEVEL, Kind.SCORE, uid=2581731),
    LBPLocationData('Pirate Town - Score Bubble 23', LEVEL, Kind.SCORE, uid=2581758),
    LBPLocationData('Pirate Town - Score Bubble 24', LEVEL, Kind.SCORE, uid=2718663),
    LBPLocationData('Pirate Town - Score Bubble 25', LEVEL, Kind.SCORE, uid=2898265),
    LBPLocationData('Pirate Town - Score Bubble 26', LEVEL, Kind.SCORE, uid=2898272),
    LBPLocationData('Pirate Town - Score Bubble 27', LEVEL, Kind.SCORE, uid=2898274),
    LBPLocationData('Pirate Town - Score Bubble 28', LEVEL, Kind.SCORE, uid=2916352),
    LBPLocationData('Pirate Town - Score Bubble 29', LEVEL, Kind.SCORE, uid=2916355),
    LBPLocationData('Pirate Town - Score Bubble 30', LEVEL, Kind.SCORE, uid=2916358),
    LBPLocationData('Pirate Town - Score Bubble 31', LEVEL, Kind.SCORE, uid=2916754),
    LBPLocationData('Pirate Town - Score Bubble 32', LEVEL, Kind.SCORE, uid=2916756),
    LBPLocationData('Pirate Town - Score Bubble 33', LEVEL, Kind.SCORE, uid=2916760),
    LBPLocationData('Pirate Town - Score Bubble 34', LEVEL, Kind.SCORE, uid=2924691),
    LBPLocationData('Pirate Town - Score Bubble 35', LEVEL, Kind.SCORE, uid=2924709),
    LBPLocationData('Pirate Town - Score Bubble 36', LEVEL, Kind.SCORE, uid=2924711),
    LBPLocationData('Pirate Town - Score Bubble 37', LEVEL, Kind.SCORE, uid=2938223),
    LBPLocationData('Pirate Town - Score Bubble 38', LEVEL, Kind.SCORE, uid=2939301),
    LBPLocationData('Pirate Town - Score Bubble 39', LEVEL, Kind.SCORE, uid=2939303),
    LBPLocationData('Pirate Town - Score Bubble 40', LEVEL, Kind.SCORE, uid=2939305),
    LBPLocationData('Pirate Town - Score Bubble 41', LEVEL, Kind.SCORE, uid=2939307),
    LBPLocationData('Pirate Town - Score Bubble 42', LEVEL, Kind.SCORE, uid=2970647),
    LBPLocationData('Pirate Town - Score Bubble 43', LEVEL, Kind.SCORE, uid=2970649),
    LBPLocationData('Pirate Town - Score Bubble 44', LEVEL, Kind.SCORE, uid=2970651),
    LBPLocationData('Pirate Town - Score Bubble 45', LEVEL, Kind.SCORE, uid=2970653),
    LBPLocationData('Pirate Town - Score Bubble 46', LEVEL, Kind.SCORE, uid=2983433),
    LBPLocationData('Pirate Town - Score Bubble 47', LEVEL, Kind.SCORE, uid=2984229),
    LBPLocationData('Pirate Town - Score Bubble 48', LEVEL, Kind.SCORE, uid=2984231),
    LBPLocationData('Pirate Town - Score Bubble 49', LEVEL, Kind.SCORE, uid=2984233),
    LBPLocationData('Pirate Town - Score Bubble 50', LEVEL, Kind.SCORE, uid=2984235),
    LBPLocationData('Pirate Town - Score Bubble 51', LEVEL, Kind.SCORE, uid=2984237),
    LBPLocationData('Pirate Town - Score Bubble 52', LEVEL, Kind.SCORE, uid=2984239),
    LBPLocationData('Pirate Town - Score Bubble 53', LEVEL, Kind.SCORE, uid=2984241),
    LBPLocationData('Pirate Town - Score Bubble 54', LEVEL, Kind.SCORE, uid=2984243),
    LBPLocationData('Pirate Town - Score Bubble 55', LEVEL, Kind.SCORE, uid=2984245),
    LBPLocationData('Pirate Town - Score Bubble 56', LEVEL, Kind.SCORE, uid=2984247),
    LBPLocationData('Pirate Town - Score Bubble 57', LEVEL, Kind.SCORE, uid=2984258),
    LBPLocationData('Pirate Town - Score Bubble 58', LEVEL, Kind.SCORE, uid=2984260),
    LBPLocationData('Pirate Town - Score Bubble 59', LEVEL, Kind.SCORE, uid=3018720),
    LBPLocationData('Pirate Town - Prize Bubble 1 - Column', LEVEL, Kind.PRIZE, uid=7804, plan='g85418'),
    LBPLocationData('Pirate Town - Prize Bubble 2 - Cloudy Peaks', LEVEL, Kind.PRIZE, uid=1539647, plan='g85543'),
    LBPLocationData('Pirate Town - Prize Bubble 3 - Octopus', LEVEL, Kind.PRIZE, uid=1733611, plan='g85398'),
    LBPLocationData('Pirate Town - Prize Bubble 4 - Seahorse', LEVEL, Kind.PRIZE, uid=1733653, plan='g85399'),
    LBPLocationData('Pirate Town - Prize Bubble 5 - Shuttered Window Illuminated', LEVEL, Kind.PRIZE, uid=1745667, plan='g85439'),
    LBPLocationData('Pirate Town - Prize Bubble 6 - Brown Tiles End', LEVEL, Kind.PRIZE, uid=2009027, plan='g85415'),
    LBPLocationData('Pirate Town - Prize Bubble 7 - Brown Tiles Cone', LEVEL, Kind.PRIZE, uid=2009035, plan='g85414'),
    LBPLocationData('Pirate Town - Prize Bubble 8 - Volcano', LEVEL, Kind.PRIZE, uid=2428369, plan='g85546'),
    LBPLocationData('Pirate Town - Prize Bubble 9 - Square Window Illuminated', LEVEL, Kind.PRIZE, uid=2598080, plan='g85442'),
    LBPLocationData('Pirate Town - Prize Bubble 10 - Tower Wall', LEVEL, Kind.PRIZE, uid=2750312, plan='g85447'),
    LBPLocationData('Pirate Town - Prize Bubble 11 - Tile Canopy', LEVEL, Kind.PRIZE, uid=2911132, plan='g85446'),
    LBPLocationData('Pirate Town - Prize Bubble 12 - Cloth Canopy', LEVEL, Kind.PRIZE, uid=2911134, plan='g85417'),
    LBPLocationData('Pirate Town - Prize Bubble 13 - Brown Tiles', LEVEL, Kind.PRIZE, uid=2918855, plan='g85416'),
    LBPLocationData('Pirate Town - Prize Bubble 14 - Beamed Gable End', LEVEL, Kind.PRIZE, uid=2918857, plan='g85402'),
    LBPLocationData('Pirate Town - Prize Bubble 15 - Shop Sign', LEVEL, Kind.PRIZE, uid=2918979, plan='g85438'),
    LBPLocationData('Pirate Town - Prize Bubble 16 - Picket Fence', LEVEL, Kind.PRIZE, uid=2918993, plan='g85435'),
    LBPLocationData('Pirate Town - Prize Bubble 17 - Arch Window', LEVEL, Kind.PRIZE, uid=2919112, plan='g85401'),
    LBPLocationData('Pirate Town - Prize Bubble 18 - Stone Wall', LEVEL, Kind.PRIZE, uid=2919120, plan='g85445'),
    LBPLocationData('Pirate Town - Prize Bubble 19 - Compass', LEVEL, Kind.PRIZE, uid=2922559, plan='g85513'),
    LBPLocationData('Pirate Town - Prize Bubble 20 - Black Sail', LEVEL, Kind.PRIZE, uid=2939296, plan='g85504'),
    LBPLocationData("Pirate Town - Prize Bubble 21 - 'The End is Nigh'", LEVEL, Kind.PRIZE, uid=3018732, plan='g86857'),
    LBPLocationData('Pirate Town - Prize Bubble 22 - Ruined Fort', LEVEL, Kind.PRIZE, uid=3079984, plan='g91952'),
    LBPLocationData('Pirate Town - Prize Bubble 23 - Knitted Boat', LEVEL, Kind.PRIZE, uid=3080779, plan='g91949'),
    LBPLocationData('Pirate Town - Prize Bubble 24 - Skull Pirate', LEVEL, Kind.PRIZE, uid=3080792, plan='g91950'),
    LBPLocationData("Pirate Town - Prize Bubble 25 - Ship's Wheel", LEVEL, Kind.PRIZE, uid=3242977, plan='g88567'),
    LBPLocationData('Pirate Town - Prize Bubble 26 - Carved Wood', LEVEL, Kind.PRIZE, uid=3242986, plan='g80392'),
    LBPLocationData('Pirate Town - Prize Bubble 27 - Will Turner', LEVEL, Kind.PRIZE, uid=3244173, plan='g89070'),
    LBPLocationData('Pirate Town - Prize Bubble 28 - Sack Sparrow', LEVEL, Kind.PRIZE, uid=3245761, plan='g89067'),
    LBPLocationData('Pirate Town - Prize Bubble 29 - Old Glass', LEVEL, Kind.PRIZE, uid=3245789, plan='g80702'),
    LBPLocationData('Pirate Town - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Pirate Town - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('Pirate Town - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('Pirate Town - Completion Reward 1 - Knotted Rope', LEVEL, Kind.REWARD, plan='g82026', condition=Kind.COMPLETE),
    LBPLocationData('Pirate Town - Completion Reward 2 - Door 1', LEVEL, Kind.REWARD, plan='g85421', condition=Kind.COMPLETE),
    LBPLocationData('Pirate Town - Completion Reward 3 - Red Float', LEVEL, Kind.REWARD, plan='g85526', condition=Kind.COMPLETE),
    LBPLocationData('Pirate Town - All Prizes Reward 1 - Thick Cloud', LEVEL, Kind.REWARD, plan='g85540', condition=Kind.ALL_PRIZES),
    LBPLocationData('Pirate Town - All Prizes Reward 2 - Curly Cloud', LEVEL, Kind.REWARD, plan='g85541', condition=Kind.ALL_PRIZES),
    LBPLocationData('Pirate Town - All Prizes Reward 3 - Thin Cloud', LEVEL, Kind.REWARD, plan='g85542', condition=Kind.ALL_PRIZES),
    LBPLocationData('Pirate Town - Ace Reward 1 - Fat Fish', LEVEL, Kind.REWARD, plan='g85395', condition=Kind.ACE),
    LBPLocationData('Pirate Town - Ace Reward 2 - Long Fish', LEVEL, Kind.REWARD, plan='g85394', condition=Kind.ACE),
    LBPLocationData('Pirate Town - Ace Reward 3 - Cannon', LEVEL, Kind.REWARD, plan='g85510', condition=Kind.ACE),
    LBPLocationData('Pirate Town - Sticker Switch 1 - Blue Float', LEVEL, Kind.STICKER_SWITCH, uid=2986380, plan='g85505'),
    LBPLocationData('Pirate Town - Sticker Switch 2 - Green Float', LEVEL, Kind.STICKER_SWITCH, uid=2986382, plan='g85520'),
    LBPLocationData('Pirate Town - Sticker Switch 3 - Red Float', LEVEL, Kind.STICKER_SWITCH, uid=2986384, plan='g85526'),
)
