from ..model import Kind, LBPLocationData

LEVEL = 'g73765'

LOCATIONS = (
    LBPLocationData('Step Through Time - Prize Bubble 1 - Large Roman Panel', LEVEL, Kind.PRIZE, uid=7399, plan='g73627'),
    LBPLocationData('Step Through Time - Prize Bubble 2 - Large Roman Arch', LEVEL, Kind.PRIZE, uid=7400, plan='g73626'),
    LBPLocationData('Step Through Time - Prize Bubble 3 - Roman Stairs', LEVEL, Kind.PRIZE, uid=7441, plan='g73635'),
    LBPLocationData('Step Through Time - Prize Bubble 4 - Roman Panel', LEVEL, Kind.PRIZE, uid=7442, plan='g73634'),
    LBPLocationData('Step Through Time - Prize Bubble 5 - Roman Tiled Roof', LEVEL, Kind.PRIZE, uid=7445, plan='g73636'),
    LBPLocationData('Step Through Time - Prize Bubble 6 - Roman Sacktue', LEVEL, Kind.PRIZE, uid=7446, plan='g73631'),
    LBPLocationData('Step Through Time - Prize Bubble 7 - Small Roman Arch', LEVEL, Kind.PRIZE, uid=7447, plan='g73632'),
    LBPLocationData('Step Through Time - Prize Bubble 8 - Small Roman Panel', LEVEL, Kind.PRIZE, uid=7448, plan='g73633'),
    LBPLocationData('Step Through Time - Prize Bubble 9 - Large Roman Panel', LEVEL, Kind.PRIZE, uid=7449, plan='g73628'),
    LBPLocationData('Step Through Time - Prize Bubble 10 - Roman Relief', LEVEL, Kind.PRIZE, uid=7450, plan='g73629'),
    LBPLocationData('Step Through Time - Prize Bubble 11 - Egyptian Capital', LEVEL, Kind.PRIZE, uid=8087, plan='g73561'),
    LBPLocationData('Step Through Time - Prize Bubble 12 - Egyptian Hieroglyphs', LEVEL, Kind.PRIZE, uid=8088, plan='g73559'),
    LBPLocationData('Step Through Time - Prize Bubble 13 - Roman Roof', LEVEL, Kind.PRIZE, uid=56114, plan='g73630'),
    LBPLocationData('Step Through Time - Prize Bubble 14 - Roman Relief', LEVEL, Kind.PRIZE, uid=56115, plan='g73625'),
    LBPLocationData('Step Through Time - Prize Bubble 15 - Roman Column', LEVEL, Kind.PRIZE, uid=56116, plan='g73622'),
    LBPLocationData('Step Through Time - Prize Bubble 16 - Roman Relief', LEVEL, Kind.PRIZE, uid=56117, plan='g73623'),
    LBPLocationData('Step Through Time - Prize Bubble 17 - Roman Half Arch', LEVEL, Kind.PRIZE, uid=56118, plan='g73624'),
    LBPLocationData('Step Through Time - Prize Bubble 18 - Roman Dado Relief', LEVEL, Kind.PRIZE, uid=56119, plan='g73619'),
    LBPLocationData('Step Through Time - Prize Bubble 19 - Roman Column', LEVEL, Kind.PRIZE, uid=56120, plan='g73620'),
    LBPLocationData('Step Through Time - Prize Bubble 20 - Roman Column', LEVEL, Kind.PRIZE, uid=56121, plan='g73621'),
    LBPLocationData('Step Through Time - Prize Bubble 21 - Roman Bust', LEVEL, Kind.PRIZE, uid=56122, plan='g73617'),
    LBPLocationData('Step Through Time - Prize Bubble 22 - Roman Coin', LEVEL, Kind.PRIZE, uid=56123, plan='g73618'),
    LBPLocationData('Step Through Time - Prize Bubble 23 - Egyptian Capital', LEVEL, Kind.PRIZE, uid=56957, plan='g73558'),
    LBPLocationData('Step Through Time - Prize Bubble 24 - Egyptian Capital', LEVEL, Kind.PRIZE, uid=56958, plan='g73557'),
    LBPLocationData('Step Through Time - Prize Bubble 25 - Egyptian Column', LEVEL, Kind.PRIZE, uid=56965, plan='g73568'),
    LBPLocationData('Step Through Time - Prize Bubble 26 - Egyptian Column Base', LEVEL, Kind.PRIZE, uid=56966, plan='g73565'),
    LBPLocationData('Step Through Time - Prize Bubble 27 - Egyptian Column', LEVEL, Kind.PRIZE, uid=56967, plan='g73563'),
    LBPLocationData('Step Through Time - Prize Bubble 28 - Egyptian Column', LEVEL, Kind.PRIZE, uid=56968, plan='g73564'),
    LBPLocationData('Step Through Time - Prize Bubble 29 - Arabian Window', LEVEL, Kind.PRIZE, uid=59350, plan='g73599'),
    LBPLocationData('Step Through Time - Prize Bubble 30 - Arabian Arch', LEVEL, Kind.PRIZE, uid=59351, plan='g73598'),
    LBPLocationData('Step Through Time - Prize Bubble 31 - Arabian Window', LEVEL, Kind.PRIZE, uid=59354, plan='g73600'),
    LBPLocationData('Step Through Time - Prize Bubble 32 - Low Arabian Dome', LEVEL, Kind.PRIZE, uid=59355, plan='g73595'),
    LBPLocationData('Step Through Time - Prize Bubble 33 - Arabian Minaret', LEVEL, Kind.PRIZE, uid=59356, plan='g73596'),
    LBPLocationData('Step Through Time - Prize Bubble 34 - Arabian Pinnacle', LEVEL, Kind.PRIZE, uid=59357, plan='g73597'),
    LBPLocationData('Step Through Time - Prize Bubble 35 - Arabian Arch', LEVEL, Kind.PRIZE, uid=59358, plan='g73585'),
    LBPLocationData('Step Through Time - Prize Bubble 36 - Arabian Dome', LEVEL, Kind.PRIZE, uid=59359, plan='g73588'),
    LBPLocationData('Step Through Time - Prize Bubble 37 - Arabian Arch', LEVEL, Kind.PRIZE, uid=59360, plan='g73586'),
    LBPLocationData('Step Through Time - Prize Bubble 38 - Arabian Capital', LEVEL, Kind.PRIZE, uid=59361, plan='g73587'),
    LBPLocationData('Step Through Time - Prize Bubble 39 - Arabian Column', LEVEL, Kind.PRIZE, uid=59362, plan='g73590'),
    LBPLocationData('Step Through Time - Prize Bubble 40 - Arabian Panel', LEVEL, Kind.PRIZE, uid=59363, plan='g73591'),
    LBPLocationData('Step Through Time - Prize Bubble 41 - Arabian Column', LEVEL, Kind.PRIZE, uid=59370, plan='g73589'),
    LBPLocationData('Step Through Time - Prize Bubble 42 - Gold Arabian Dome', LEVEL, Kind.PRIZE, uid=59371, plan='g73594'),
    LBPLocationData('Step Through Time - Prize Bubble 43 - Arabian Window', LEVEL, Kind.PRIZE, uid=59372, plan='g73593'),
    LBPLocationData('Step Through Time - Prize Bubble 44 - Arabian Window', LEVEL, Kind.PRIZE, uid=59373, plan='g73592'),
    LBPLocationData('Step Through Time - Prize Bubble 45 - Chinese Stone Roof', LEVEL, Kind.PRIZE, uid=59389, plan='g73547'),
    LBPLocationData('Step Through Time - Prize Bubble 46 - Japanese Warrior Head', LEVEL, Kind.PRIZE, uid=59391, plan='g73541'),
    LBPLocationData('Step Through Time - Prize Bubble 47 - Chinese Roof', LEVEL, Kind.PRIZE, uid=59393, plan='g73530'),
    LBPLocationData('Step Through Time - Prize Bubble 48 - Chinese Pillar', LEVEL, Kind.PRIZE, uid=59394, plan='g73529'),
    LBPLocationData('Step Through Time - Prize Bubble 49 - Chinese Window', LEVEL, Kind.PRIZE, uid=59395, plan='g73536'),
    LBPLocationData('Step Through Time - Prize Bubble 50 - Chinese Window', LEVEL, Kind.PRIZE, uid=59396, plan='g73540'),
    LBPLocationData('Step Through Time - Prize Bubble 51 - Chinese Rock', LEVEL, Kind.PRIZE, uid=59397, plan='g73539'),
    LBPLocationData('Step Through Time - Prize Bubble 52 - Japanese Warrior Leg', LEVEL, Kind.PRIZE, uid=59398, plan='g73543'),
    LBPLocationData('Step Through Time - Prize Bubble 53 - Chinese Wall', LEVEL, Kind.PRIZE, uid=59401, plan='g73538'),
    LBPLocationData('Step Through Time - Prize Bubble 54 - Chinese Roof', LEVEL, Kind.PRIZE, uid=59402, plan='g73534'),
    LBPLocationData('Step Through Time - Prize Bubble 55 - Chinese Panel', LEVEL, Kind.PRIZE, uid=59403, plan='g73537'),
    LBPLocationData('Step Through Time - Prize Bubble 56 - Chinese Roof', LEVEL, Kind.PRIZE, uid=59404, plan='g73535'),
    LBPLocationData('Step Through Time - Prize Bubble 57 - Celtic Gate', LEVEL, Kind.PRIZE, uid=59408, plan='g73516'),
    LBPLocationData('Step Through Time - Prize Bubble 58 - Celtic Stone Wall', LEVEL, Kind.PRIZE, uid=59409, plan='g73525'),
    LBPLocationData('Step Through Time - Prize Bubble 59 - Celtic Roof', LEVEL, Kind.PRIZE, uid=59410, plan='g73527'),
    LBPLocationData('Step Through Time - Prize Bubble 60 - Celtic Hut', LEVEL, Kind.PRIZE, uid=59411, plan='g73517'),
    LBPLocationData('Step Through Time - Prize Bubble 61 - Celtic Brooch', LEVEL, Kind.PRIZE, uid=59412, plan='g72953'),
    LBPLocationData('Step Through Time - Prize Bubble 62 - Chinese Blue Panel', LEVEL, Kind.PRIZE, uid=59413, plan='g73528'),
    LBPLocationData('Step Through Time - Prize Bubble 63 - Standing Stone', LEVEL, Kind.PRIZE, uid=59417, plan='g73524'),
    LBPLocationData('Step Through Time - Prize Bubble 64 - Standing Stone', LEVEL, Kind.PRIZE, uid=59418, plan='g73521'),
    LBPLocationData('Step Through Time - Prize Bubble 65 - Persian Brooch', LEVEL, Kind.PRIZE, uid=59419, plan='g73647'),
    LBPLocationData('Step Through Time - Prize Bubble 66 - Celtic Capstone', LEVEL, Kind.PRIZE, uid=59422, plan='g73513'),
    LBPLocationData('Step Through Time - Prize Bubble 67 - Native American Totem Pole', LEVEL, Kind.PRIZE, uid=59423, plan='g73601'),
    LBPLocationData('Step Through Time - Prize Bubble 68 - Native American Totem Pole', LEVEL, Kind.PRIZE, uid=59424, plan='g73602'),
    LBPLocationData('Step Through Time - Prize Bubble 69 - Native American Feather', LEVEL, Kind.PRIZE, uid=59425, plan='g73605'),
    LBPLocationData('Step Through Time - Prize Bubble 70 - Native American Tepee', LEVEL, Kind.PRIZE, uid=59426, plan='g73611'),
    LBPLocationData('Step Through Time - Prize Bubble 71 - Native American Totem Pole', LEVEL, Kind.PRIZE, uid=59427, plan='g73607'),
    LBPLocationData('Step Through Time - Prize Bubble 72 - Native American Totem Pole', LEVEL, Kind.PRIZE, uid=59428, plan='g73608'),
    LBPLocationData('Step Through Time - Prize Bubble 73 - Native American Totem Pole', LEVEL, Kind.PRIZE, uid=59429, plan='g73603'),
    LBPLocationData('Step Through Time - Prize Bubble 74 - Native American Totem Pole', LEVEL, Kind.PRIZE, uid=59430, plan='g73604'),
    LBPLocationData('Step Through Time - Prize Bubble 75 - Native American Totem Pole', LEVEL, Kind.PRIZE, uid=59431, plan='g73609'),
    LBPLocationData('Step Through Time - Prize Bubble 76 - Native American Totem Pole', LEVEL, Kind.PRIZE, uid=59432, plan='g73606'),
    LBPLocationData('Step Through Time - Prize Bubble 77 - Celtic Wheel', LEVEL, Kind.PRIZE, uid=59433, plan='g73514'),
    LBPLocationData('Step Through Time - Prize Bubble 78 - Gothic Tympanum', LEVEL, Kind.PRIZE, uid=60217, plan='g73584'),
    LBPLocationData('Step Through Time - Prize Bubble 79 - Gothic Columns', LEVEL, Kind.PRIZE, uid=60218, plan='g73583'),
    LBPLocationData('Step Through Time - Prize Bubble 80 - Gothic Pinnacle', LEVEL, Kind.PRIZE, uid=60221, plan='g73580'),
    LBPLocationData('Step Through Time - Prize Bubble 81 - Gothic Arch', LEVEL, Kind.PRIZE, uid=60222, plan='g73581'),
    LBPLocationData('Step Through Time - Prize Bubble 82 - Gothic Window', LEVEL, Kind.PRIZE, uid=60224, plan='g73582'),
    LBPLocationData('Step Through Time - Prize Bubble 83 - Gothic Arch', LEVEL, Kind.PRIZE, uid=60225, plan='g73577'),
    LBPLocationData('Step Through Time - Prize Bubble 84 - Gothic Window', LEVEL, Kind.PRIZE, uid=60227, plan='g73578'),
    LBPLocationData('Step Through Time - Prize Bubble 85 - Gothic Column', LEVEL, Kind.PRIZE, uid=60228, plan='g73579'),
    LBPLocationData('Step Through Time - Prize Bubble 86 - Gothic Pinnacle', LEVEL, Kind.PRIZE, uid=68115, plan='g73574'),
    LBPLocationData('Step Through Time - Prize Bubble 87 - Gothic Pattern', LEVEL, Kind.PRIZE, uid=68116, plan='g73575'),
    LBPLocationData('Step Through Time - Prize Bubble 88 - Egyptian Column', LEVEL, Kind.PRIZE, uid=68124, plan='g73562'),
    LBPLocationData('Step Through Time - Prize Bubble 89 - Egyptian Column', LEVEL, Kind.PRIZE, uid=68125, plan='g73567'),
    LBPLocationData('Step Through Time - Prize Bubble 90 - Egyptian Wall', LEVEL, Kind.PRIZE, uid=68127, plan='g73569'),
    LBPLocationData('Step Through Time - Prize Bubble 91 - Egyptian Column', LEVEL, Kind.PRIZE, uid=68128, plan='g73566'),
    LBPLocationData('Step Through Time - Prize Bubble 92 - Egyptian Capital', LEVEL, Kind.PRIZE, uid=68130, plan='g73560'),
    LBPLocationData('Step Through Time - Prize Bubble 93 - Egyptian Arch', LEVEL, Kind.PRIZE, uid=68131, plan='g73556'),
    LBPLocationData('Step Through Time - Prize Bubble 94 - Egyptian Stele', LEVEL, Kind.PRIZE, uid=68133, plan='g73644'),
    LBPLocationData('Step Through Time - Prize Bubble 95 - Egyptian Scarab', LEVEL, Kind.PRIZE, uid=68134, plan='g73649'),
    LBPLocationData('Step Through Time - Prize Bubble 96 - Chinese Stone Tower', LEVEL, Kind.PRIZE, uid=68137, plan='g73548'),
    LBPLocationData('Step Through Time - Prize Bubble 97 - Japanese Warrior Sword', LEVEL, Kind.PRIZE, uid=68138, plan='g73545'),
    LBPLocationData('Step Through Time - Prize Bubble 98 - Chinese Stone Wall', LEVEL, Kind.PRIZE, uid=68139, plan='g73549'),
    LBPLocationData('Step Through Time - Prize Bubble 99 - Japanese Warrior Torso', LEVEL, Kind.PRIZE, uid=68140, plan='g73546'),
    LBPLocationData('Step Through Time - Prize Bubble 100 - Japanese Warrior Right Arm', LEVEL, Kind.PRIZE, uid=68141, plan='g73544'),
    LBPLocationData('Step Through Time - Prize Bubble 101 - Japanese Warrior Left Arm', LEVEL, Kind.PRIZE, uid=68142, plan='g73542'),
    LBPLocationData('Step Through Time - Prize Bubble 102 - Chinese Tree Trunk', LEVEL, Kind.PRIZE, uid=68143, plan='g73554'),
    LBPLocationData('Step Through Time - Prize Bubble 103 - Chinese Window', LEVEL, Kind.PRIZE, uid=68144, plan='g73555'),
    LBPLocationData('Step Through Time - Prize Bubble 104 - Chinese Branch', LEVEL, Kind.PRIZE, uid=68145, plan='g73553'),
    LBPLocationData('Step Through Time - Prize Bubble 105 - Chinese Tree', LEVEL, Kind.PRIZE, uid=68147, plan='g73550'),
    LBPLocationData('Step Through Time - Prize Bubble 106 - Chinese Tree', LEVEL, Kind.PRIZE, uid=68148, plan='g73551'),
    LBPLocationData('Step Through Time - Prize Bubble 107 - Chinese Tree', LEVEL, Kind.PRIZE, uid=68149, plan='g73552'),
    LBPLocationData('Step Through Time - Prize Bubble 108 - Celtic Roof', LEVEL, Kind.PRIZE, uid=68924, plan='g73526'),
    LBPLocationData('Step Through Time - Prize Bubble 109 - Celtic Knot', LEVEL, Kind.PRIZE, uid=68925, plan='g73518'),
    LBPLocationData('Step Through Time - Prize Bubble 110 - Celtic Roof', LEVEL, Kind.PRIZE, uid=68926, plan='g73520'),
    LBPLocationData('Step Through Time - Prize Bubble 111 - Celtic Roof', LEVEL, Kind.PRIZE, uid=68927, plan='g73519'),
    LBPLocationData('Step Through Time - Prize Bubble 112 - Native American Red Wing', LEVEL, Kind.PRIZE, uid=68928, plan='g73613'),
    LBPLocationData('Step Through Time - Prize Bubble 113 - Native American Totem Pole', LEVEL, Kind.PRIZE, uid=68929, plan='g73610'),
    LBPLocationData('Step Through Time - Prize Bubble 114 - Native American Totem Pole', LEVEL, Kind.PRIZE, uid=68930, plan='g73615'),
    LBPLocationData('Step Through Time - Prize Bubble 115 - Native American Grey Wing', LEVEL, Kind.PRIZE, uid=68931, plan='g73612'),
    LBPLocationData('Step Through Time - Prize Bubble 116 - Native American Totem Pole', LEVEL, Kind.PRIZE, uid=68932, plan='g73650'),
    LBPLocationData('Step Through Time - Prize Bubble 117 - Native American Tree', LEVEL, Kind.PRIZE, uid=68933, plan='g73614'),
    LBPLocationData('Step Through Time - Prize Bubble 118 - Native American Totem Pole', LEVEL, Kind.PRIZE, uid=68934, plan='g73616'),
    LBPLocationData('Step Through Time - Prize Bubble 119 - Arabian Tiles', LEVEL, Kind.PRIZE, uid=68937, plan='g73696'),
    LBPLocationData('Step Through Time - Prize Bubble 120 - Cleopatra', LEVEL, Kind.PRIZE, uid=70493, plan='g73851'),
    LBPLocationData('Step Through Time - Prize Bubble 121 - Egyptian Hieroglyphs', LEVEL, Kind.PRIZE, uid=70494, plan='g73695'),
    LBPLocationData('Step Through Time - Prize Bubble 122 - Gothic Pillar', LEVEL, Kind.PRIZE, uid=74418, plan='g73576'),
    LBPLocationData('Step Through Time - Prize Bubble 123 - Gothic Arch', LEVEL, Kind.PRIZE, uid=74419, plan='g73571'),
    LBPLocationData('Step Through Time - Prize Bubble 124 - Gothic Arches', LEVEL, Kind.PRIZE, uid=74420, plan='g73570'),
    LBPLocationData('Step Through Time - Prize Bubble 125 - Gothic Grotesque', LEVEL, Kind.PRIZE, uid=74421, plan='g73573'),
    LBPLocationData('Step Through Time - Prize Bubble 126 - Gothic Window', LEVEL, Kind.PRIZE, uid=74422, plan='g73572'),
    LBPLocationData('Step Through Time - Prize Bubble 127 - Gothic Support', LEVEL, Kind.PRIZE, uid=77541, plan='g73651'),
    LBPLocationData('Step Through Time - Prize Bubble 128 - Ancient Greek Plate', LEVEL, Kind.PRIZE, uid=81464, plan='g73645'),
    LBPLocationData('Step Through Time - Prize Bubble 129 - Ancient Greek Vase', LEVEL, Kind.PRIZE, uid=83013, plan='g73261'),
    LBPLocationData('Step Through Time - Prize Bubble 130 - George Washington Body', LEVEL, Kind.PRIZE, uid=83016, plan='g73863'),
    LBPLocationData('Step Through Time - Prize Bubble 131 - George Washington Head', LEVEL, Kind.PRIZE, uid=83017, plan='g73861'),
    LBPLocationData('Step Through Time - Prize Bubble 132 - George Washington Legs', LEVEL, Kind.PRIZE, uid=83018, plan='g73865'),
    LBPLocationData('Step Through Time - Prize Bubble 133 - William Shakespeare', LEVEL, Kind.PRIZE, uid=83021, plan='g73858'),
    LBPLocationData('Step Through Time - Prize Bubble 134 - Napoleon Bonaparte', LEVEL, Kind.PRIZE, uid=83022, plan='g73864'),
    LBPLocationData("Step Through Time - Prize Bubble 135 - Napoleon's Hat", LEVEL, Kind.PRIZE, uid=83023, plan='g73856'),
    LBPLocationData('Step Through Time - Prize Bubble 136 - Pablo Picasso', LEVEL, Kind.PRIZE, uid=83024, plan='g73855'),
    LBPLocationData('Step Through Time - Prize Bubble 137 - Abraham Lincoln', LEVEL, Kind.PRIZE, uid=83025, plan='g73849'),
    LBPLocationData('Step Through Time - Prize Bubble 138 - Galileo', LEVEL, Kind.PRIZE, uid=83026, plan='g73852'),
    LBPLocationData('Step Through Time - Prize Bubble 139 - Ludwig Van', LEVEL, Kind.PRIZE, uid=83027, plan='g73850'),
    LBPLocationData('Step Through Time - Prize Bubble 140 - Edgar Allen Poe', LEVEL, Kind.PRIZE, uid=83028, plan='g73854'),
    LBPLocationData('Step Through Time - Prize Bubble 141 - Standing Stone', LEVEL, Kind.PRIZE, uid=83030, plan='g73522'),
    LBPLocationData('Step Through Time - Prize Bubble 142 - Persian Griffon Pedestal', LEVEL, Kind.PRIZE, uid=83032, plan='g73646'),
    LBPLocationData('Step Through Time - Prize Bubble 143 - Chinese Mask', LEVEL, Kind.PRIZE, uid=83033, plan='g73643'),
    LBPLocationData('Step Through Time - Prize Bubble 144 - Pantheon Background', LEVEL, Kind.PRIZE, uid=90125, plan='g74443'),
    LBPLocationData("Step Through Time - Prize Bubble 145 - 'The Chrysalis of Eternity'", LEVEL, Kind.PRIZE, uid=90126, plan='g75905'),
    LBPLocationData('Step Through Time - Prize Bubble 146 - History Pack', LEVEL, Kind.PRIZE, uid=90127, plan='g75312'),
    LBPLocationData('Step Through Time - Prize Bubble 147 - Laurel Wreath', LEVEL, Kind.PRIZE, uid=91465, plan='g73640'),
    LBPLocationData('Step Through Time - Prize Bubble 148 - Standing Stone', LEVEL, Kind.PRIZE, uid=91466, plan='g73515'),
    LBPLocationData('Step Through Time - Prize Bubble 149 - Chinese Roof', LEVEL, Kind.PRIZE, uid=91840, plan='g73533'),
    LBPLocationData('Step Through Time - Prize Bubble 150 - Chinese Wall', LEVEL, Kind.PRIZE, uid=91841, plan='g73531'),
    LBPLocationData('Step Through Time - Prize Bubble 151 - Chinese Grass', LEVEL, Kind.PRIZE, uid=91844, plan='g73532'),
    LBPLocationData('Step Through Time - Prize Bubble 152 - Boudica', LEVEL, Kind.PRIZE, uid=91845, plan='g73853'),
    LBPLocationData('Step Through Time - Prize Bubble 153 - Queen Victoria I', LEVEL, Kind.PRIZE, uid=91847, plan='g73860'),
    LBPLocationData('Step Through Time - Prize Bubble 154 - Tutankhamun', LEVEL, Kind.PRIZE, uid=91848, plan='g73862'),
    LBPLocationData('Step Through Time - Prize Bubble 155 - Queen Elizabeth I', LEVEL, Kind.PRIZE, uid=93196, plan='g73859'),
    LBPLocationData('Step Through Time - Prize Bubble 156 - Celtic Stake', LEVEL, Kind.PRIZE, uid=93573, plan='g73523'),
    LBPLocationData('Step Through Time - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Step Through Time - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('Step Through Time - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('Step Through Time - Completion Reward 1 - Tapestry', LEVEL, Kind.REWARD, plan='g73935', condition=Kind.COMPLETE),
    LBPLocationData('Step Through Time - Completion Reward 2 - Antique Maps', LEVEL, Kind.REWARD, plan='g73697', condition=Kind.COMPLETE),
    LBPLocationData('Step Through Time - Completion Reward 3 - Cave Painting', LEVEL, Kind.REWARD, plan='g72971', condition=Kind.COMPLETE),
    LBPLocationData('Step Through Time - All Prizes Reward 1 - Aztec Mask', LEVEL, Kind.REWARD, plan='g73642', condition=Kind.ALL_PRIZES),
    LBPLocationData('Step Through Time - All Prizes Reward 2 - Mayan Mask', LEVEL, Kind.REWARD, plan='g73641', condition=Kind.ALL_PRIZES),
    LBPLocationData('Step Through Time - All Prizes Reward 3 - Roman Plaque', LEVEL, Kind.REWARD, plan='g73648', condition=Kind.ALL_PRIZES),
    LBPLocationData('Step Through Time - Ace Reward 1 - Chinese Bell', LEVEL, Kind.REWARD, plan='g73258', condition=Kind.ACE),
    LBPLocationData('Step Through Time - Ace Reward 2 - Gothic Gargoyle', LEVEL, Kind.REWARD, plan='g73260', condition=Kind.ACE),
    LBPLocationData('Step Through Time - Ace Reward 3 - Egyptian Mask', LEVEL, Kind.REWARD, plan='g73259', condition=Kind.ACE),
)
