from ..model import Kind, LBPLocationData

LEVEL = 'g74459'

LOCATIONS = (
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 1", LEVEL, Kind.SCORE, uid=7286),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 2", LEVEL, Kind.SCORE, uid=7290),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 3", LEVEL, Kind.SCORE, uid=7291),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 4", LEVEL, Kind.SCORE, uid=7292),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 5", LEVEL, Kind.SCORE, uid=7293),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 6", LEVEL, Kind.SCORE, uid=7294),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 7", LEVEL, Kind.SCORE, uid=7295),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 8", LEVEL, Kind.SCORE, uid=7296),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 9", LEVEL, Kind.SCORE, uid=7297),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 10", LEVEL, Kind.SCORE, uid=7298),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 11", LEVEL, Kind.SCORE, uid=7299),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 12", LEVEL, Kind.SCORE, uid=7300),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 13", LEVEL, Kind.SCORE, uid=7301),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 14", LEVEL, Kind.SCORE, uid=7302),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 15", LEVEL, Kind.SCORE, uid=7303),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 16", LEVEL, Kind.SCORE, uid=7304),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 17", LEVEL, Kind.SCORE, uid=7305),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 18", LEVEL, Kind.SCORE, uid=7306),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 19", LEVEL, Kind.SCORE, uid=7307),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 20", LEVEL, Kind.SCORE, uid=7308),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 21", LEVEL, Kind.SCORE, uid=7309),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 22", LEVEL, Kind.SCORE, uid=7310),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 23", LEVEL, Kind.SCORE, uid=7311),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 24", LEVEL, Kind.SCORE, uid=7312),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 25", LEVEL, Kind.SCORE, uid=7313),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 26", LEVEL, Kind.SCORE, uid=7317),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 27", LEVEL, Kind.SCORE, uid=7318),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 28", LEVEL, Kind.SCORE, uid=7319),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 29", LEVEL, Kind.SCORE, uid=7535),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 30", LEVEL, Kind.SCORE, uid=7536),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 31", LEVEL, Kind.SCORE, uid=7602),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 32", LEVEL, Kind.SCORE, uid=7637),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 33", LEVEL, Kind.SCORE, uid=7638),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 34", LEVEL, Kind.SCORE, uid=8661),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 35", LEVEL, Kind.SCORE, uid=8663),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 36", LEVEL, Kind.SCORE, uid=8664),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 37", LEVEL, Kind.SCORE, uid=8665),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 38", LEVEL, Kind.SCORE, uid=8666),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 39", LEVEL, Kind.SCORE, uid=8667),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 40", LEVEL, Kind.SCORE, uid=8668),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 41", LEVEL, Kind.SCORE, uid=8669),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 42", LEVEL, Kind.SCORE, uid=8670),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 43", LEVEL, Kind.SCORE, uid=8671),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 44", LEVEL, Kind.SCORE, uid=8672),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 45", LEVEL, Kind.SCORE, uid=8673),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 46", LEVEL, Kind.SCORE, uid=8674),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 47", LEVEL, Kind.SCORE, uid=8675),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 48", LEVEL, Kind.SCORE, uid=8676),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 49", LEVEL, Kind.SCORE, uid=8677),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 50", LEVEL, Kind.SCORE, uid=8678),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 51", LEVEL, Kind.SCORE, uid=8692),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 52", LEVEL, Kind.SCORE, uid=8693),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 53", LEVEL, Kind.SCORE, uid=8694),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 54", LEVEL, Kind.SCORE, uid=8695),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 55", LEVEL, Kind.SCORE, uid=8696),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 56", LEVEL, Kind.SCORE, uid=8697),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 57", LEVEL, Kind.SCORE, uid=8698),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 58", LEVEL, Kind.SCORE, uid=8699),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 59", LEVEL, Kind.SCORE, uid=8700),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 60", LEVEL, Kind.SCORE, uid=8701),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 61", LEVEL, Kind.SCORE, uid=8702),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 62", LEVEL, Kind.SCORE, uid=8703),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 63", LEVEL, Kind.SCORE, uid=8704),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 64", LEVEL, Kind.SCORE, uid=8705),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 65", LEVEL, Kind.SCORE, uid=8706),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 66", LEVEL, Kind.SCORE, uid=8708),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 67", LEVEL, Kind.SCORE, uid=8709),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 68", LEVEL, Kind.SCORE, uid=8710),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 69", LEVEL, Kind.SCORE, uid=8711),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 70", LEVEL, Kind.SCORE, uid=8712),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 71", LEVEL, Kind.SCORE, uid=8713),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 72", LEVEL, Kind.SCORE, uid=8714),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 73", LEVEL, Kind.SCORE, uid=8715),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 74", LEVEL, Kind.SCORE, uid=9467),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 75", LEVEL, Kind.SCORE, uid=9468),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 76", LEVEL, Kind.SCORE, uid=9469),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 77", LEVEL, Kind.SCORE, uid=9470),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 78", LEVEL, Kind.SCORE, uid=9471),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 79", LEVEL, Kind.SCORE, uid=9472),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 80", LEVEL, Kind.SCORE, uid=9505),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 81", LEVEL, Kind.SCORE, uid=9506),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 82", LEVEL, Kind.SCORE, uid=9507),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 83", LEVEL, Kind.SCORE, uid=9508),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 84", LEVEL, Kind.SCORE, uid=10202),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 85", LEVEL, Kind.SCORE, uid=10203),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 86", LEVEL, Kind.SCORE, uid=10204),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 87", LEVEL, Kind.SCORE, uid=10205),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 88", LEVEL, Kind.SCORE, uid=10206),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 89", LEVEL, Kind.SCORE, uid=10207),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 90", LEVEL, Kind.SCORE, uid=10208),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 91", LEVEL, Kind.SCORE, uid=10209),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 92", LEVEL, Kind.SCORE, uid=10212),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 93", LEVEL, Kind.SCORE, uid=10213),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 94", LEVEL, Kind.SCORE, uid=10214),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 95", LEVEL, Kind.SCORE, uid=10215),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 96", LEVEL, Kind.SCORE, uid=10216),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 97", LEVEL, Kind.SCORE, uid=10217),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 98", LEVEL, Kind.SCORE, uid=10580),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 99", LEVEL, Kind.SCORE, uid=10592),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 100", LEVEL, Kind.SCORE, uid=10593),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 101", LEVEL, Kind.SCORE, uid=10594),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 102", LEVEL, Kind.SCORE, uid=10595),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 103", LEVEL, Kind.SCORE, uid=10596),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 104", LEVEL, Kind.SCORE, uid=10604),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 105", LEVEL, Kind.SCORE, uid=10930),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 106", LEVEL, Kind.SCORE, uid=10934),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 107", LEVEL, Kind.SCORE, uid=11820),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 108", LEVEL, Kind.SCORE, uid=11914),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 109", LEVEL, Kind.SCORE, uid=11915),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 110", LEVEL, Kind.SCORE, uid=11916),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 111", LEVEL, Kind.SCORE, uid=11917),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 112", LEVEL, Kind.SCORE, uid=11918),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 113", LEVEL, Kind.SCORE, uid=11919),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 114", LEVEL, Kind.SCORE, uid=11930),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 115", LEVEL, Kind.SCORE, uid=11931),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 116", LEVEL, Kind.SCORE, uid=11963),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 117", LEVEL, Kind.SCORE, uid=11967),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 118", LEVEL, Kind.SCORE, uid=11968),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 119", LEVEL, Kind.SCORE, uid=11969),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 120", LEVEL, Kind.SCORE, uid=11970),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 121", LEVEL, Kind.SCORE, uid=11971),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 122", LEVEL, Kind.SCORE, uid=11972),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 123", LEVEL, Kind.SCORE, uid=11980),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 124", LEVEL, Kind.SCORE, uid=11981),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 125", LEVEL, Kind.SCORE, uid=11982),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 126", LEVEL, Kind.SCORE, uid=11983),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 127", LEVEL, Kind.SCORE, uid=11984),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 128", LEVEL, Kind.SCORE, uid=11990),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 129", LEVEL, Kind.SCORE, uid=11991),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 130", LEVEL, Kind.SCORE, uid=11992),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 131", LEVEL, Kind.SCORE, uid=11993),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 132", LEVEL, Kind.SCORE, uid=11994),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 133", LEVEL, Kind.SCORE, uid=11995),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 134", LEVEL, Kind.SCORE, uid=12026),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 135", LEVEL, Kind.SCORE, uid=12027),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 136", LEVEL, Kind.SCORE, uid=12737),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 137", LEVEL, Kind.SCORE, uid=12741),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 138", LEVEL, Kind.SCORE, uid=12742),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 139", LEVEL, Kind.SCORE, uid=12864),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 140", LEVEL, Kind.SCORE, uid=12866),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 141", LEVEL, Kind.SCORE, uid=12894),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 142", LEVEL, Kind.SCORE, uid=12895),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 143", LEVEL, Kind.SCORE, uid=12897),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 144", LEVEL, Kind.SCORE, uid=12898),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 145", LEVEL, Kind.SCORE, uid=13351),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 146", LEVEL, Kind.SCORE, uid=13450),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 147", LEVEL, Kind.SCORE, uid=13452),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 148", LEVEL, Kind.SCORE, uid=13454),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 149", LEVEL, Kind.SCORE, uid=13526),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 150", LEVEL, Kind.SCORE, uid=13528),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 151", LEVEL, Kind.SCORE, uid=13530),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 152", LEVEL, Kind.SCORE, uid=36125),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 153", LEVEL, Kind.SCORE, uid=36127),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 154", LEVEL, Kind.SCORE, uid=36128),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 155", LEVEL, Kind.SCORE, uid=49873),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 156", LEVEL, Kind.SCORE, uid=49875),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 157", LEVEL, Kind.SCORE, uid=49876),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 158", LEVEL, Kind.SCORE, uid=59549),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 159", LEVEL, Kind.SCORE, uid=59551),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 160", LEVEL, Kind.SCORE, uid=59552),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 161", LEVEL, Kind.SCORE, uid=59557),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 162", LEVEL, Kind.SCORE, uid=59559),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 163", LEVEL, Kind.SCORE, uid=59560),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 164", LEVEL, Kind.SCORE, uid=59573),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 165", LEVEL, Kind.SCORE, uid=59575),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 166", LEVEL, Kind.SCORE, uid=59576),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 167", LEVEL, Kind.SCORE, uid=75773),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 168", LEVEL, Kind.SCORE, uid=75778),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 169", LEVEL, Kind.SCORE, uid=139436),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 170", LEVEL, Kind.SCORE, uid=139438),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 171", LEVEL, Kind.SCORE, uid=139439),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 172", LEVEL, Kind.SCORE, uid=269029),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 173", LEVEL, Kind.SCORE, uid=269031),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 174", LEVEL, Kind.SCORE, uid=269032),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 175", LEVEL, Kind.SCORE, uid=348930),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 176", LEVEL, Kind.SCORE, uid=348932),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 177", LEVEL, Kind.SCORE, uid=390711),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 178", LEVEL, Kind.SCORE, uid=390713),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 179", LEVEL, Kind.SCORE, uid=624245),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 180", LEVEL, Kind.SCORE, uid=624247),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 181", LEVEL, Kind.SCORE, uid=624248),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 182", LEVEL, Kind.SCORE, uid=665692),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 183", LEVEL, Kind.SCORE, uid=665694),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 184", LEVEL, Kind.SCORE, uid=665696),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 185", LEVEL, Kind.SCORE, uid=665708),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 186", LEVEL, Kind.SCORE, uid=665709),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 187", LEVEL, Kind.SCORE, uid=665710),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 188", LEVEL, Kind.SCORE, uid=665714),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 189", LEVEL, Kind.SCORE, uid=665715),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 190", LEVEL, Kind.SCORE, uid=665716),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 191", LEVEL, Kind.SCORE, uid=665720),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 192", LEVEL, Kind.SCORE, uid=665721),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 193", LEVEL, Kind.SCORE, uid=665722),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 194", LEVEL, Kind.SCORE, uid=665726),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 195", LEVEL, Kind.SCORE, uid=665727),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 196", LEVEL, Kind.SCORE, uid=665728),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 197", LEVEL, Kind.SCORE, uid=766692),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 198", LEVEL, Kind.SCORE, uid=766694),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 199", LEVEL, Kind.SCORE, uid=766695),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 200", LEVEL, Kind.SCORE, uid=766700),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 201", LEVEL, Kind.SCORE, uid=766702),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 202", LEVEL, Kind.SCORE, uid=766703),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 203", LEVEL, Kind.SCORE, uid=782679),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 204", LEVEL, Kind.SCORE, uid=782681),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 205", LEVEL, Kind.SCORE, uid=782683),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 206", LEVEL, Kind.SCORE, uid=782685),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 207", LEVEL, Kind.SCORE, uid=863404),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 208", LEVEL, Kind.SCORE, uid=863406),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 209", LEVEL, Kind.SCORE, uid=863408),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 210", LEVEL, Kind.SCORE, uid=863410),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 211", LEVEL, Kind.SCORE, uid=863412),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 212", LEVEL, Kind.SCORE, uid=863414),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 213", LEVEL, Kind.SCORE, uid=863426),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 214", LEVEL, Kind.SCORE, uid=863428),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 215", LEVEL, Kind.SCORE, uid=863430),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 216", LEVEL, Kind.SCORE, uid=863438),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 217", LEVEL, Kind.SCORE, uid=864992),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 218", LEVEL, Kind.SCORE, uid=864994),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 219", LEVEL, Kind.SCORE, uid=865786),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 220", LEVEL, Kind.SCORE, uid=865788),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 221", LEVEL, Kind.SCORE, uid=865789),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 222", LEVEL, Kind.SCORE, uid=873681),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 223", LEVEL, Kind.SCORE, uid=873683),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 224", LEVEL, Kind.SCORE, uid=873684),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 225", LEVEL, Kind.SCORE, uid=956175),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 226", LEVEL, Kind.SCORE, uid=956177),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 227", LEVEL, Kind.SCORE, uid=1140184),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 228", LEVEL, Kind.SCORE, uid=1140186),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 229", LEVEL, Kind.SCORE, uid=1140187),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 230", LEVEL, Kind.SCORE, uid=1140204),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 231", LEVEL, Kind.SCORE, uid=1140206),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 232", LEVEL, Kind.SCORE, uid=1140207),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 233", LEVEL, Kind.SCORE, uid=1272172),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 234", LEVEL, Kind.SCORE, uid=1272174),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 235", LEVEL, Kind.SCORE, uid=1272175),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 236", LEVEL, Kind.SCORE, uid=1272180),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 237", LEVEL, Kind.SCORE, uid=1272182),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 238", LEVEL, Kind.SCORE, uid=1272183),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 239", LEVEL, Kind.SCORE, uid=1462971),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 240", LEVEL, Kind.SCORE, uid=1462973),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 241", LEVEL, Kind.SCORE, uid=1462974),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 242", LEVEL, Kind.SCORE, uid=1462979),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 243", LEVEL, Kind.SCORE, uid=1462981),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 244", LEVEL, Kind.SCORE, uid=1462982),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 245", LEVEL, Kind.SCORE, uid=1473540),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 246", LEVEL, Kind.SCORE, uid=1473542),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 247", LEVEL, Kind.SCORE, uid=1473543),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 248", LEVEL, Kind.SCORE, uid=1473548),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 249", LEVEL, Kind.SCORE, uid=1473550),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Score Bubble 250", LEVEL, Kind.SCORE, uid=1473551),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 1 - Unresolved prize g76905", LEVEL, Kind.PRIZE, uid=7320, plan='g76905'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 2 - Unresolved prize g76907", LEVEL, Kind.PRIZE, uid=8662, plan='g76907'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 3 - Unresolved prize g76909", LEVEL, Kind.PRIZE, uid=8679, plan='g76909'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 4 - Unresolved prize g76911", LEVEL, Kind.PRIZE, uid=8912, plan='g76911'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 5 - Unresolved prize g76912", LEVEL, Kind.PRIZE, uid=9464, plan='g76912'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 6 - Unresolved prize g76914", LEVEL, Kind.PRIZE, uid=9466, plan='g76914'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 7 - Unresolved prize g76917", LEVEL, Kind.PRIZE, uid=10210, plan='g76917'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 8 - Unresolved prize g76918", LEVEL, Kind.PRIZE, uid=10211, plan='g76918'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 9 - Unresolved prize g76920", LEVEL, Kind.PRIZE, uid=10591, plan='g76920'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 10 - Unresolved prize g76922", LEVEL, Kind.PRIZE, uid=10935, plan='g76922'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 11 - Unresolved prize g76923", LEVEL, Kind.PRIZE, uid=10936, plan='g76923'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 12 - Unresolved prize g76925", LEVEL, Kind.PRIZE, uid=11314, plan='g76925'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 13 - Unresolved prize g76926", LEVEL, Kind.PRIZE, uid=11379, plan='g76926'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 14 - Unresolved prize g76927", LEVEL, Kind.PRIZE, uid=11381, plan='g76927'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 15 - Unresolved prize g76929", LEVEL, Kind.PRIZE, uid=11912, plan='g76929'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 16 - Unresolved prize g76930", LEVEL, Kind.PRIZE, uid=11913, plan='g76930'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 17 - Unresolved prize g76932", LEVEL, Kind.PRIZE, uid=11973, plan='g76932'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 18 - Unresolved prize g76934", LEVEL, Kind.PRIZE, uid=11985, plan='g76934'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 19 - Unresolved prize g76935", LEVEL, Kind.PRIZE, uid=11996, plan='g76935'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 20 - Unresolved prize g76937", LEVEL, Kind.PRIZE, uid=12354, plan='g76937'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 21 - Unresolved prize g76939", LEVEL, Kind.PRIZE, uid=12371, plan='g76939'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 22 - Unresolved prize g76941", LEVEL, Kind.PRIZE, uid=12738, plan='g76941'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 23 - Unresolved prize g76943", LEVEL, Kind.PRIZE, uid=12879, plan='g76943'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 24 - Unresolved prize g76945", LEVEL, Kind.PRIZE, uid=12881, plan='g76945'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 25 - Unresolved prize g76947", LEVEL, Kind.PRIZE, uid=13522, plan='g76947'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 26 - Unresolved prize g76949", LEVEL, Kind.PRIZE, uid=13524, plan='g76949'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 27 - Unresolved prize g76951", LEVEL, Kind.PRIZE, uid=14129, plan='g76951'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 28 - Unresolved prize g76952", LEVEL, Kind.PRIZE, uid=14197, plan='g76952'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 29 - Unresolved prize g76954", LEVEL, Kind.PRIZE, uid=188558, plan='g76954'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 30 - Unresolved prize g76956", LEVEL, Kind.PRIZE, uid=1140252, plan='g76956'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 31 - Unresolved prize g76958", LEVEL, Kind.PRIZE, uid=1140254, plan='g76958'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 32 - Unresolved prize g76960", LEVEL, Kind.PRIZE, uid=1355144, plan='g76960'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 33 - Unresolved prize g76962", LEVEL, Kind.PRIZE, uid=1355145, plan='g76962'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Prize Bubble 34 - Unresolved prize g76964", LEVEL, Kind.PRIZE, uid=1355146, plan='g76964'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Level Complete", LEVEL, Kind.COMPLETE),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - All Prize Bubbles", LEVEL, Kind.ALL_PRIZES),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Ace (No Deaths)", LEVEL, Kind.ACE),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Sticker Switch 1 - White Square", LEVEL, Kind.STICKER_SWITCH, uid=12030, plan='g59230'),
    LBPLocationData("TAKLAMAKAN 'Go and never come back' - Sticker Switch 2 - Yellow Circle", LEVEL, Kind.STICKER_SWITCH, uid=12033, plan='g59222'),
)
