from ..model import Kind, LBPLocationData

LEVEL = 'g75108'

LOCATIONS = (
    LBPLocationData('Until The Cows Come Home - Score Bubble 1', LEVEL, Kind.SCORE, uid=3159809),
    LBPLocationData('Until The Cows Come Home - Score Bubble 2', LEVEL, Kind.SCORE, uid=3159811),
    LBPLocationData('Until The Cows Come Home - Score Bubble 3', LEVEL, Kind.SCORE, uid=3159813),
    LBPLocationData('Until The Cows Come Home - Score Bubble 4', LEVEL, Kind.SCORE, uid=3159815),
    LBPLocationData('Until The Cows Come Home - Score Bubble 5', LEVEL, Kind.SCORE, uid=3159817),
    LBPLocationData('Until The Cows Come Home - Score Bubble 6', LEVEL, Kind.SCORE, uid=3159819),
    LBPLocationData('Until The Cows Come Home - Score Bubble 7', LEVEL, Kind.SCORE, uid=5361716),
    LBPLocationData('Until The Cows Come Home - Score Bubble 8', LEVEL, Kind.SCORE, uid=5361718),
    LBPLocationData('Until The Cows Come Home - Score Bubble 9', LEVEL, Kind.SCORE, uid=5361720),
    LBPLocationData('Until The Cows Come Home - Score Bubble 10', LEVEL, Kind.SCORE, uid=5361722),
    LBPLocationData('Until The Cows Come Home - Score Bubble 11', LEVEL, Kind.SCORE, uid=5361724),
    LBPLocationData('Until The Cows Come Home - Score Bubble 12', LEVEL, Kind.SCORE, uid=5361726),
    LBPLocationData('Until The Cows Come Home - Score Bubble 13', LEVEL, Kind.SCORE, uid=6455296),
    LBPLocationData('Until The Cows Come Home - Score Bubble 14', LEVEL, Kind.SCORE, uid=6455297),
    LBPLocationData('Until The Cows Come Home - Score Bubble 15', LEVEL, Kind.SCORE, uid=6455298),
    LBPLocationData('Until The Cows Come Home - Score Bubble 16', LEVEL, Kind.SCORE, uid=6455299),
    LBPLocationData('Until The Cows Come Home - Score Bubble 17', LEVEL, Kind.SCORE, uid=6455862),
    LBPLocationData('Until The Cows Come Home - Score Bubble 18', LEVEL, Kind.SCORE, uid=6455863),
    LBPLocationData('Until The Cows Come Home - Score Bubble 19', LEVEL, Kind.SCORE, uid=6455864),
    LBPLocationData('Until The Cows Come Home - Score Bubble 20', LEVEL, Kind.SCORE, uid=6455865),
    LBPLocationData('Until The Cows Come Home - Score Bubble 21', LEVEL, Kind.SCORE, uid=6458589),
    LBPLocationData('Until The Cows Come Home - Score Bubble 22', LEVEL, Kind.SCORE, uid=6458590),
    LBPLocationData('Until The Cows Come Home - Score Bubble 23', LEVEL, Kind.SCORE, uid=6458591),
    LBPLocationData('Until The Cows Come Home - Score Bubble 24', LEVEL, Kind.SCORE, uid=6458592),
    LBPLocationData('Until The Cows Come Home - Score Bubble 25', LEVEL, Kind.SCORE, uid=6458607),
    LBPLocationData('Until The Cows Come Home - Score Bubble 26', LEVEL, Kind.SCORE, uid=6458608),
    LBPLocationData('Until The Cows Come Home - Score Bubble 27', LEVEL, Kind.SCORE, uid=6458609),
    LBPLocationData('Until The Cows Come Home - Score Bubble 28', LEVEL, Kind.SCORE, uid=6458610),
    LBPLocationData('Until The Cows Come Home - Score Bubble 29', LEVEL, Kind.SCORE, uid=6469666),
    LBPLocationData('Until The Cows Come Home - Score Bubble 30', LEVEL, Kind.SCORE, uid=6469667),
    LBPLocationData('Until The Cows Come Home - Score Bubble 31', LEVEL, Kind.SCORE, uid=6469668),
    LBPLocationData('Until The Cows Come Home - Score Bubble 32', LEVEL, Kind.SCORE, uid=6469669),
    LBPLocationData('Until The Cows Come Home - Score Bubble 33', LEVEL, Kind.SCORE, uid=6469684),
    LBPLocationData('Until The Cows Come Home - Score Bubble 34', LEVEL, Kind.SCORE, uid=6469685),
    LBPLocationData('Until The Cows Come Home - Score Bubble 35', LEVEL, Kind.SCORE, uid=6469686),
    LBPLocationData('Until The Cows Come Home - Score Bubble 36', LEVEL, Kind.SCORE, uid=6469687),
    LBPLocationData('Until The Cows Come Home - Score Bubble 37', LEVEL, Kind.SCORE, uid=6469702),
    LBPLocationData('Until The Cows Come Home - Score Bubble 38', LEVEL, Kind.SCORE, uid=6469703),
    LBPLocationData('Until The Cows Come Home - Score Bubble 39', LEVEL, Kind.SCORE, uid=6469704),
    LBPLocationData('Until The Cows Come Home - Score Bubble 40', LEVEL, Kind.SCORE, uid=6469705),
    LBPLocationData('Until The Cows Come Home - Score Bubble 41', LEVEL, Kind.SCORE, uid=6469720),
    LBPLocationData('Until The Cows Come Home - Score Bubble 42', LEVEL, Kind.SCORE, uid=6469721),
    LBPLocationData('Until The Cows Come Home - Score Bubble 43', LEVEL, Kind.SCORE, uid=6469722),
    LBPLocationData('Until The Cows Come Home - Score Bubble 44', LEVEL, Kind.SCORE, uid=6469723),
    LBPLocationData('Until The Cows Come Home - Score Bubble 45', LEVEL, Kind.SCORE, uid=7561959),
    LBPLocationData('Until The Cows Come Home - Score Bubble 46', LEVEL, Kind.SCORE, uid=7561961),
    LBPLocationData('Until The Cows Come Home - Score Bubble 47', LEVEL, Kind.SCORE, uid=7561969),
    LBPLocationData('Until The Cows Come Home - Score Bubble 48', LEVEL, Kind.SCORE, uid=7561970),
    LBPLocationData('Until The Cows Come Home - Score Bubble 49', LEVEL, Kind.SCORE, uid=7561973),
    LBPLocationData('Until The Cows Come Home - Score Bubble 50', LEVEL, Kind.SCORE, uid=7561974),
    LBPLocationData('Until The Cows Come Home - Score Bubble 51', LEVEL, Kind.SCORE, uid=7561977),
    LBPLocationData('Until The Cows Come Home - Score Bubble 52', LEVEL, Kind.SCORE, uid=7561978),
    LBPLocationData('Until The Cows Come Home - Score Bubble 53', LEVEL, Kind.SCORE, uid=8624282),
    LBPLocationData('Until The Cows Come Home - Score Bubble 54', LEVEL, Kind.SCORE, uid=8624284),
    LBPLocationData('Until The Cows Come Home - Score Bubble 55', LEVEL, Kind.SCORE, uid=8624286),
    LBPLocationData('Until The Cows Come Home - Score Bubble 56', LEVEL, Kind.SCORE, uid=8624288),
    LBPLocationData('Until The Cows Come Home - Score Bubble 57', LEVEL, Kind.SCORE, uid=8624290),
    LBPLocationData('Until The Cows Come Home - Score Bubble 58', LEVEL, Kind.SCORE, uid=8624292),
    LBPLocationData('Until The Cows Come Home - Score Bubble 59', LEVEL, Kind.SCORE, uid=9674057),
    LBPLocationData('Until The Cows Come Home - Score Bubble 60', LEVEL, Kind.SCORE, uid=9674066),
    LBPLocationData('Until The Cows Come Home - Score Bubble 61', LEVEL, Kind.SCORE, uid=9674070),
    LBPLocationData('Until The Cows Come Home - Score Bubble 62', LEVEL, Kind.SCORE, uid=9674074),
    LBPLocationData('Until The Cows Come Home - Score Bubble 63', LEVEL, Kind.SCORE, uid=9674078),
    LBPLocationData('Until The Cows Come Home - Score Bubble 64', LEVEL, Kind.SCORE, uid=9674082),
    LBPLocationData('Until The Cows Come Home - Score Bubble 65', LEVEL, Kind.SCORE, uid=10726702),
    LBPLocationData('Until The Cows Come Home - Score Bubble 66', LEVEL, Kind.SCORE, uid=10726703),
    LBPLocationData('Until The Cows Come Home - Score Bubble 67', LEVEL, Kind.SCORE, uid=10726704),
    LBPLocationData('Until The Cows Come Home - Score Bubble 68', LEVEL, Kind.SCORE, uid=10726705),
    LBPLocationData('Until The Cows Come Home - Score Bubble 69', LEVEL, Kind.SCORE, uid=10726720),
    LBPLocationData('Until The Cows Come Home - Score Bubble 70', LEVEL, Kind.SCORE, uid=10726721),
    LBPLocationData('Until The Cows Come Home - Score Bubble 71', LEVEL, Kind.SCORE, uid=10726722),
    LBPLocationData('Until The Cows Come Home - Score Bubble 72', LEVEL, Kind.SCORE, uid=10726723),
    LBPLocationData('Until The Cows Come Home - Score Bubble 73', LEVEL, Kind.SCORE, uid=11775893),
    LBPLocationData('Until The Cows Come Home - Score Bubble 74', LEVEL, Kind.SCORE, uid=11775894),
    LBPLocationData('Until The Cows Come Home - Score Bubble 75', LEVEL, Kind.SCORE, uid=11775895),
    LBPLocationData('Until The Cows Come Home - Score Bubble 76', LEVEL, Kind.SCORE, uid=11775896),
    LBPLocationData('Until The Cows Come Home - Score Bubble 77', LEVEL, Kind.SCORE, uid=11775911),
    LBPLocationData('Until The Cows Come Home - Score Bubble 78', LEVEL, Kind.SCORE, uid=11775912),
    LBPLocationData('Until The Cows Come Home - Score Bubble 79', LEVEL, Kind.SCORE, uid=11775913),
    LBPLocationData('Until The Cows Come Home - Score Bubble 80', LEVEL, Kind.SCORE, uid=11775914),
    LBPLocationData('Until The Cows Come Home - Score Bubble 81', LEVEL, Kind.SCORE, uid=11775929),
    LBPLocationData('Until The Cows Come Home - Score Bubble 82', LEVEL, Kind.SCORE, uid=11775930),
    LBPLocationData('Until The Cows Come Home - Score Bubble 83', LEVEL, Kind.SCORE, uid=11775931),
    LBPLocationData('Until The Cows Come Home - Score Bubble 84', LEVEL, Kind.SCORE, uid=11775932),
    LBPLocationData('Until The Cows Come Home - Score Bubble 85', LEVEL, Kind.SCORE, uid=11775947),
    LBPLocationData('Until The Cows Come Home - Score Bubble 86', LEVEL, Kind.SCORE, uid=11775948),
    LBPLocationData('Until The Cows Come Home - Score Bubble 87', LEVEL, Kind.SCORE, uid=11775949),
    LBPLocationData('Until The Cows Come Home - Score Bubble 88', LEVEL, Kind.SCORE, uid=11775950),
    LBPLocationData('Until The Cows Come Home - Score Bubble 89', LEVEL, Kind.SCORE, uid=11775965),
    LBPLocationData('Until The Cows Come Home - Score Bubble 90', LEVEL, Kind.SCORE, uid=11775966),
    LBPLocationData('Until The Cows Come Home - Score Bubble 91', LEVEL, Kind.SCORE, uid=11775967),
    LBPLocationData('Until The Cows Come Home - Score Bubble 92', LEVEL, Kind.SCORE, uid=11775968),
    LBPLocationData('Until The Cows Come Home - Score Bubble 93', LEVEL, Kind.SCORE, uid=11775983),
    LBPLocationData('Until The Cows Come Home - Score Bubble 94', LEVEL, Kind.SCORE, uid=11775984),
    LBPLocationData('Until The Cows Come Home - Score Bubble 95', LEVEL, Kind.SCORE, uid=11775985),
    LBPLocationData('Until The Cows Come Home - Score Bubble 96', LEVEL, Kind.SCORE, uid=11775986),
    LBPLocationData('Until The Cows Come Home - Score Bubble 97', LEVEL, Kind.SCORE, uid=12833172),
    LBPLocationData('Until The Cows Come Home - Score Bubble 98', LEVEL, Kind.SCORE, uid=12833174),
    LBPLocationData('Until The Cows Come Home - Score Bubble 99', LEVEL, Kind.SCORE, uid=15999353),
    LBPLocationData('Until The Cows Come Home - Score Bubble 100', LEVEL, Kind.SCORE, uid=15999354),
    LBPLocationData('Until The Cows Come Home - Score Bubble 101', LEVEL, Kind.SCORE, uid=15999355),
    LBPLocationData('Until The Cows Come Home - Score Bubble 102', LEVEL, Kind.SCORE, uid=15999356),
    LBPLocationData('Until The Cows Come Home - Score Bubble 103', LEVEL, Kind.SCORE, uid=15999371),
    LBPLocationData('Until The Cows Come Home - Score Bubble 104', LEVEL, Kind.SCORE, uid=15999372),
    LBPLocationData('Until The Cows Come Home - Score Bubble 105', LEVEL, Kind.SCORE, uid=15999373),
    LBPLocationData('Until The Cows Come Home - Score Bubble 106', LEVEL, Kind.SCORE, uid=15999374),
    LBPLocationData('Until The Cows Come Home - Score Bubble 107', LEVEL, Kind.SCORE, uid=15999389),
    LBPLocationData('Until The Cows Come Home - Score Bubble 108', LEVEL, Kind.SCORE, uid=15999390),
    LBPLocationData('Until The Cows Come Home - Score Bubble 109', LEVEL, Kind.SCORE, uid=15999391),
    LBPLocationData('Until The Cows Come Home - Score Bubble 110', LEVEL, Kind.SCORE, uid=15999392),
    LBPLocationData('Until The Cows Come Home - Score Bubble 111', LEVEL, Kind.SCORE, uid=15999407),
    LBPLocationData('Until The Cows Come Home - Score Bubble 112', LEVEL, Kind.SCORE, uid=15999408),
    LBPLocationData('Until The Cows Come Home - Score Bubble 113', LEVEL, Kind.SCORE, uid=15999409),
    LBPLocationData('Until The Cows Come Home - Score Bubble 114', LEVEL, Kind.SCORE, uid=15999410),
    LBPLocationData('Until The Cows Come Home - Score Bubble 115', LEVEL, Kind.SCORE, uid=24440727),
    LBPLocationData('Until The Cows Come Home - Score Bubble 116', LEVEL, Kind.SCORE, uid=24440728),
    LBPLocationData('Until The Cows Come Home - Score Bubble 117', LEVEL, Kind.SCORE, uid=24440729),
    LBPLocationData('Until The Cows Come Home - Score Bubble 118', LEVEL, Kind.SCORE, uid=24440730),
    LBPLocationData('Until The Cows Come Home - Score Bubble 119', LEVEL, Kind.SCORE, uid=24440745),
    LBPLocationData('Until The Cows Come Home - Score Bubble 120', LEVEL, Kind.SCORE, uid=24440746),
    LBPLocationData('Until The Cows Come Home - Score Bubble 121', LEVEL, Kind.SCORE, uid=24440747),
    LBPLocationData('Until The Cows Come Home - Score Bubble 122', LEVEL, Kind.SCORE, uid=24440748),
    LBPLocationData('Until The Cows Come Home - Score Bubble 123', LEVEL, Kind.SCORE, uid=24440763),
    LBPLocationData('Until The Cows Come Home - Score Bubble 124', LEVEL, Kind.SCORE, uid=24440764),
    LBPLocationData('Until The Cows Come Home - Score Bubble 125', LEVEL, Kind.SCORE, uid=24440765),
    LBPLocationData('Until The Cows Come Home - Score Bubble 126', LEVEL, Kind.SCORE, uid=24440766),
    LBPLocationData('Until The Cows Come Home - Score Bubble 127', LEVEL, Kind.SCORE, uid=39230078),
    LBPLocationData('Until The Cows Come Home - Score Bubble 128', LEVEL, Kind.SCORE, uid=39230079),
    LBPLocationData('Until The Cows Come Home - Score Bubble 129', LEVEL, Kind.SCORE, uid=39230080),
    LBPLocationData('Until The Cows Come Home - Score Bubble 130', LEVEL, Kind.SCORE, uid=39230081),
    LBPLocationData('Until The Cows Come Home - Score Bubble 131', LEVEL, Kind.SCORE, uid=39230096),
    LBPLocationData('Until The Cows Come Home - Score Bubble 132', LEVEL, Kind.SCORE, uid=39230097),
    LBPLocationData('Until The Cows Come Home - Score Bubble 133', LEVEL, Kind.SCORE, uid=39230098),
    LBPLocationData('Until The Cows Come Home - Score Bubble 134', LEVEL, Kind.SCORE, uid=39230099),
    LBPLocationData('Until The Cows Come Home - Score Bubble 135', LEVEL, Kind.SCORE, uid=58421912),
    LBPLocationData('Until The Cows Come Home - Score Bubble 136', LEVEL, Kind.SCORE, uid=58421947),
    LBPLocationData('Until The Cows Come Home - Score Bubble 137', LEVEL, Kind.SCORE, uid=58421973),
    LBPLocationData('Until The Cows Come Home - Score Bubble 138', LEVEL, Kind.SCORE, uid=58422020),
    LBPLocationData('Until The Cows Come Home - Score Bubble 139', LEVEL, Kind.SCORE, uid=58422076),
    LBPLocationData('Until The Cows Come Home - Score Bubble 140', LEVEL, Kind.SCORE, uid=58422132),
    LBPLocationData('Until The Cows Come Home - Score Bubble 141', LEVEL, Kind.SCORE, uid=58422179),
    LBPLocationData('Until The Cows Come Home - Score Bubble 142', LEVEL, Kind.SCORE, uid=58423263),
    LBPLocationData('Until The Cows Come Home - Score Bubble 143', LEVEL, Kind.SCORE, uid=58423313),
    LBPLocationData('Until The Cows Come Home - Score Bubble 144', LEVEL, Kind.SCORE, uid=58423345),
    LBPLocationData('Until The Cows Come Home - Score Bubble 145', LEVEL, Kind.SCORE, uid=58423374),
    LBPLocationData('Until The Cows Come Home - Score Bubble 146', LEVEL, Kind.SCORE, uid=58423427),
    LBPLocationData('Until The Cows Come Home - Score Bubble 147', LEVEL, Kind.SCORE, uid=58630640),
    LBPLocationData('Until The Cows Come Home - Score Bubble 148', LEVEL, Kind.SCORE, uid=58630711),
    LBPLocationData('Until The Cows Come Home - Score Bubble 149', LEVEL, Kind.SCORE, uid=58630800),
    LBPLocationData('Until The Cows Come Home - Score Bubble 150', LEVEL, Kind.SCORE, uid=58630850),
    LBPLocationData('Until The Cows Come Home - Score Bubble 151', LEVEL, Kind.SCORE, uid=58630918),
    LBPLocationData('Until The Cows Come Home - Score Bubble 152', LEVEL, Kind.SCORE, uid=58633453),
    LBPLocationData('Until The Cows Come Home - Score Bubble 153', LEVEL, Kind.SCORE, uid=58633503),
    LBPLocationData('Until The Cows Come Home - Score Bubble 154', LEVEL, Kind.SCORE, uid=58633529),
    LBPLocationData('Until The Cows Come Home - Score Bubble 155', LEVEL, Kind.SCORE, uid=58641365),
    LBPLocationData('Until The Cows Come Home - Score Bubble 156', LEVEL, Kind.SCORE, uid=58641400),
    LBPLocationData('Until The Cows Come Home - Score Bubble 157', LEVEL, Kind.SCORE, uid=58641918),
    LBPLocationData('Until The Cows Come Home - Score Bubble 158', LEVEL, Kind.SCORE, uid=58643207),
    LBPLocationData('Until The Cows Come Home - Score Bubble 159', LEVEL, Kind.SCORE, uid=58643278),
    LBPLocationData('Until The Cows Come Home - Score Bubble 160', LEVEL, Kind.SCORE, uid=58643820),
    LBPLocationData('Until The Cows Come Home - Score Bubble 161', LEVEL, Kind.SCORE, uid=58643879),
    LBPLocationData('Until The Cows Come Home - Score Bubble 162', LEVEL, Kind.SCORE, uid=58643926),
    LBPLocationData('Until The Cows Come Home - Score Bubble 163', LEVEL, Kind.SCORE, uid=58643952),
    LBPLocationData('Until The Cows Come Home - Score Bubble 164', LEVEL, Kind.SCORE, uid=58674377),
    LBPLocationData('Until The Cows Come Home - Score Bubble 165', LEVEL, Kind.SCORE, uid=58674379),
    LBPLocationData('Until The Cows Come Home - Score Bubble 166', LEVEL, Kind.SCORE, uid=58674381),
    LBPLocationData('Until The Cows Come Home - Score Bubble 167', LEVEL, Kind.SCORE, uid=58674659),
    LBPLocationData('Until The Cows Come Home - Score Bubble 168', LEVEL, Kind.SCORE, uid=58674712),
    LBPLocationData('Until The Cows Come Home - Score Bubble 169', LEVEL, Kind.SCORE, uid=58674762),
    LBPLocationData('Until The Cows Come Home - Score Bubble 170', LEVEL, Kind.SCORE, uid=58782059),
    LBPLocationData('Until The Cows Come Home - Prize Bubble 1 - Small door ', LEVEL, Kind.PRIZE, uid=6465800, plan='g75361'),
    LBPLocationData('Until The Cows Come Home - Prize Bubble 2 - Hanging Platform', LEVEL, Kind.PRIZE, uid=8624303, plan='g75407'),
    LBPLocationData('Until The Cows Come Home - Prize Bubble 3 - Large door ', LEVEL, Kind.PRIZE, uid=24442459, plan='g75410'),
    LBPLocationData('Until The Cows Come Home - Prize Bubble 4 - Spinning Platform', LEVEL, Kind.PRIZE, uid=39230699, plan='g75414'),
    LBPLocationData('Until The Cows Come Home - Prize Bubble 5 - Farm Sign', LEVEL, Kind.PRIZE, uid=45538886, plan='g75369'),
    LBPLocationData('Until The Cows Come Home - Prize Bubble 6 - Stars', LEVEL, Kind.PRIZE, uid=58337531, plan='g75415'),
    LBPLocationData('Until The Cows Come Home - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Until The Cows Come Home - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('Until The Cows Come Home - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('Until The Cows Come Home - Completion Reward 1 - Time Trial', LEVEL, Kind.REWARD, plan='g76903', condition=Kind.COMPLETE),
    LBPLocationData('Until The Cows Come Home - All Prizes Reward 1 - Large Spinning Platform', LEVEL, Kind.REWARD, plan='g75417', condition=Kind.ALL_PRIZES),
    LBPLocationData('Until The Cows Come Home - All Prizes Reward 2 - Point box ', LEVEL, Kind.REWARD, plan='g75413', condition=Kind.ALL_PRIZES),
    LBPLocationData('Until The Cows Come Home - Ace Reward 1 - Tank with cup ', LEVEL, Kind.REWARD, plan='g75418', condition=Kind.ACE),
    LBPLocationData('Until The Cows Come Home - Ace Reward 2 - Tank with fish ', LEVEL, Kind.REWARD, plan='g75419', condition=Kind.ACE),
    LBPLocationData('Until The Cows Come Home - Ace Reward 3 - Tank with banana', LEVEL, Kind.REWARD, plan='g75420', condition=Kind.ACE),
    LBPLocationData('Until The Cows Come Home - Sticker Switch 1 - Time Trial', LEVEL, Kind.STICKER_SWITCH, uid=17074188, plan='g76903'),
)
