from rule_builder.options import OptionFilter
from rule_builder.rules import Has, HasAll, True_

from .. import constants as C
from ..constants import Rac5Gadgets
from ..items import GLITCHES_ITEM_NAME
from ..options import (
    AllCutscenes,
    AllMissions,
    ChallengeMode,
    EnableSkyboardChallengeSkillPoints,
    ShrinkRayOptions,
    SkillPoints,
    SkyboardChallenges,
)
from ..rules._helpers import HasChallengeMode, HasShrinkRayDoorAccess
from .model import Completion, LocationOptions, Rac5Locations

LOCATIONS = (
    Rac5Locations(
        C.Rac5TBolts.KALIDON_SHIP,
        C.Rac5Planets.KALIDON,
        lambda world: True_(),
        Completion("bolt_bits", None, 256),
        categories=frozenset(("titanium_bolt",)),
        native_planets=(3,),
        definition_order=4,
    ),
    Rac5Locations(
        C.Rac5TBolts.KALIDON_FACTORY,
        C.Rac5Planets.KALIDON,
        lambda world: Has(Rac5Gadgets.HYPERSHOT) | HasAll(GLITCHES_ITEM_NAME, Rac5Gadgets.SHRINK_RAY),
        Completion("bolt_bits", None, 1024),
        categories=frozenset(("titanium_bolt",)),
        native_planets=(3,),
        definition_order=5,
    ),
    Rac5Locations(
        C.Rac5TBolts.KALIDON_RAMP,
        C.Rac5Planets.KALIDON,
        lambda world: Has(Rac5Gadgets.HYPERSHOT) & HasShrinkRayDoorAccess(world),
        Completion("bolt_bits", None, 512),
        categories=frozenset(("titanium_bolt",)),
        native_planets=(3,),
        definition_order=6,
    ),
    Rac5Locations(
        C.Rac5Locations.KALIDON_CHESTPLATE,
        C.Rac5Planets.KALIDON,
        lambda world: Has(Rac5Gadgets.HYPERSHOT) & HasShrinkRayDoorAccess(world),
        Completion("armour", "sludge", 1),
        categories=frozenset(("armour_pickup",)),
        definition_order=24,
    ),
    Rac5Locations(
        C.Rac5Locations.KALIDON_BOOTS,
        C.Rac5Planets.KALIDON,
        lambda world: (
            Has(Rac5Gadgets.HYPERSHOT) & HasShrinkRayDoorAccess(world)
            | HasShrinkRayDoorAccess(world) & Has(GLITCHES_ITEM_NAME)
        ),
        Completion("armour", "wildfire", 16),
        categories=frozenset(("armour_pickup",)),
        definition_order=25,
    ),
    Rac5Locations(
        C.Rac5Locations.KALIDON_CHAMELEON_CHESTPLATE,
        C.Rac5Planets.KALIDON,
        lambda world: Has(Rac5Gadgets.HYPERSHOT) & HasShrinkRayDoorAccess(world) & HasChallengeMode(world, 2),
        Completion("armour", "chameleon", 1),
        options=LocationOptions(requirements=(OptionFilter(ChallengeMode, (2,), "in"),)),
        categories=frozenset(("armour_pickup", "challenge_mode_2_armour")),
        definition_order=38,
    ),
    Rac5Locations(
        C.Rac5Locations.KALIDON_SHRINK,
        C.Rac5Planets.KALIDON,
        lambda world: True_(),
        Completion("events", C.Rac5Locations.KALIDON_SHRINK),
        categories=frozenset(("gadget_pickup",)),
        definition_order=43,
    ),
    Rac5Locations(
        C.Rac5SkillPoints.KALIDON_EXPLOSIVE,
        C.Rac5Planets.KALIDON,
        lambda world: Has(Rac5Gadgets.HYPERSHOT) & HasShrinkRayDoorAccess(world),
        Completion("skill_bits", None, 256),
        options=LocationOptions(requirements=(OptionFilter(SkillPoints, (1, 2), "in"),)),
        categories=frozenset(("skill_point", "easy_skill_point")),
        native_planets=(3,),
        definition_order=50,
    ),
    Rac5Locations(
        C.Rac5SkillPoints.KALIDON_SUPER_LOMBAX,
        C.Rac5Planets.KALIDON,
        lambda world: Has(Rac5Gadgets.HYPERSHOT) & HasShrinkRayDoorAccess(world),
        Completion("skill_bits", None, 512),
        options=LocationOptions(requirements=(OptionFilter(SkillPoints, (2,), "in"),)),
        categories=frozenset(("skill_point", "hard_skill_point")),
        native_planets=(3,),
        definition_order=51,
    ),
    Rac5Locations(
        C.Rac5SkillPoints.KALIDON_SKYBOARDER,
        C.Rac5Planets.KALIDON,
        lambda world: True_(),
        Completion("skill_bits", None, 1024),
        options=LocationOptions(requirements=(OptionFilter(EnableSkyboardChallengeSkillPoints, (1,), "in"),)),
        categories=frozenset(("skill_point", "skyboard_challenge_skill_point")),
        native_planets=(3,),
        definition_order=52,
    ),
    Rac5Locations(
        C.Rac5CutsceneLocations.KALIDON_WIN,
        C.Rac5Planets.KALIDON,
        lambda world: True_(),
        Completion("missions", 0x088c1388, 16, 3),
        options=LocationOptions(requirements=(OptionFilter(AllMissions, (1,), "in"),)),
        categories=frozenset(("story_mission", "mission")),
        check_order=6,
        definition_order=71,
    ),
    Rac5Locations(
        C.Rac5CutsceneLocations.KALIDON_SEARCH,
        C.Rac5Planets.KALIDON,
        lambda world: Has(Rac5Gadgets.HYPERSHOT) & HasShrinkRayDoorAccess(world),
        Completion("missions", 0x088c1388, 4, 3),
        options=LocationOptions(requirements=(OptionFilter(AllMissions, (1,), "in"),)),
        categories=frozenset(("story_mission", "mission")),
        reload_planet=3,
        check_order=1,
        definition_order=84,
    ),
    Rac5Locations(
        C.Rac5CutsceneLocations.KALIDON_EXPLORE,
        C.Rac5Planets.KALIDON,
        lambda world: Has(Rac5Gadgets.HYPERSHOT) & HasShrinkRayDoorAccess(world),
        Completion("missions", 0x088c1388, 8, 3),
        options=LocationOptions(requirements=(OptionFilter(AllCutscenes, (1,), "in"),)),
        categories=frozenset(("cutscene", "mission")),
        grants_location=C.Rac5Locations.KALIDON_SHRINK,
        check_order=27,
        definition_order=87,
    ),
    Rac5Locations(
        C.Rac5CutsceneLocations.KALIDON_ENTER,
        C.Rac5Planets.KALIDON,
        lambda world: True_(),
        Completion("missions", 0x088c1388, 1, 3),
        options=LocationOptions(requirements=(OptionFilter(AllCutscenes, (1,), "in"),)),
        categories=frozenset(("cutscene", "mission")),
        check_order=19,
        definition_order=96,
    ),
    Rac5Locations(
        C.Rac5VendorLocations.KALIDON_SCORCHER,
        C.Rac5Planets.KALIDON,
        lambda world: True_(),
        Completion("events", C.Rac5VendorLocations.KALIDON_SCORCHER),
        options=LocationOptions(weapon=C.Rac5Weapons.SCORCHER),
        categories=frozenset(("weapon_vendor",)),
        weapon="scorcher",
        definition_order=108,
    ),
    Rac5Locations(
        C.Rac5ModVendorLocations.KALIDON_LACERATOR_LOCK,
        C.Rac5Planets.KALIDON,
        lambda world: True_(),
        Completion("events", C.Rac5ModVendorLocations.KALIDON_LACERATOR_LOCK),
        options=LocationOptions(weapon=C.Rac5Weapons.LACERATOR),
        categories=frozenset(("weapon_mod_vendor",)),
        weapon="lacerator",
        mod_slot="mod_slot_two",
        definition_order=121,
    ),
    Rac5Locations(
        C.Rac5ModVendorLocations.KALIDON_CONCUSSION_SPLIT,
        C.Rac5Planets.KALIDON,
        lambda world: True_(),
        Completion("events", C.Rac5ModVendorLocations.KALIDON_CONCUSSION_SPLIT),
        options=LocationOptions(weapon=C.Rac5Weapons.CONCUSSION_GUN),
        categories=frozenset(("weapon_mod_vendor",)),
        weapon="concussion_gun",
        mod_slot="mod_slot_one",
        definition_order=122,
    ),
    Rac5Locations(
        C.Rac5ModVendorLocations.KALIDON_AGENTS_EXPLOSIVE,
        C.Rac5Planets.KALIDON,
        lambda world: HasChallengeMode(world, 1),
        Completion("events", C.Rac5ModVendorLocations.KALIDON_AGENTS_EXPLOSIVE),
        options=LocationOptions(
            requirements=(OptionFilter(ChallengeMode, (1, 2), "in"),), weapon=C.Rac5Weapons.AGENTS_OF_DOOM
        ),
        categories=frozenset(("weapon_mod_vendor", "challenge_mode_mod")),
        weapon="agents_of_doom",
        mod_slot="mod_slot_one",
        definition_order=134,
    ),
    Rac5Locations(
        C.Rac5ModVendorLocations.KALIDON_SCORCHER_SUNFLARE,
        C.Rac5Planets.KALIDON,
        lambda world: HasChallengeMode(world, 1),
        Completion("events", C.Rac5ModVendorLocations.KALIDON_SCORCHER_SUNFLARE),
        options=LocationOptions(
            requirements=(OptionFilter(ChallengeMode, (1, 2), "in"),), weapon=C.Rac5Weapons.SCORCHER
        ),
        categories=frozenset(("weapon_mod_vendor", "challenge_mode_mod")),
        weapon="scorcher",
        mod_slot="mod_slot_one",
        definition_order=135,
    ),
    Rac5Locations(
        C.Rac5ModVendorLocations.KALIDON_SUCK_CANNON_BOUNCE,
        C.Rac5Planets.KALIDON,
        lambda world: HasChallengeMode(world, 1),
        Completion("events", C.Rac5ModVendorLocations.KALIDON_SUCK_CANNON_BOUNCE),
        options=LocationOptions(
            requirements=(OptionFilter(ChallengeMode, (1, 2), "in"),), weapon=C.Rac5Weapons.SUCK_CANNON
        ),
        categories=frozenset(("weapon_mod_vendor", "challenge_mode_mod")),
        weapon="suck_cannon",
        mod_slot="mod_slot_one",
        definition_order=136,
    ),
    Rac5Locations(
        C.Rac5ModVendorLocations.KALIDON_BEE_HIVE_BOMB,
        C.Rac5Planets.KALIDON,
        lambda world: HasChallengeMode(world, 1),
        Completion("events", C.Rac5ModVendorLocations.KALIDON_BEE_HIVE_BOMB),
        options=LocationOptions(
            requirements=(OptionFilter(ChallengeMode, (1, 2), "in"),), weapon=C.Rac5Weapons.BEE_MINE_GLOVE
        ),
        categories=frozenset(("weapon_mod_vendor", "challenge_mode_mod")),
        weapon="bee_mine_glove",
        mod_slot="mod_slot_two",
        definition_order=137,
    ),
    Rac5Locations(
        C.Rac5ModVendorLocations.KALIDON_STATIC_REFLECTION,
        C.Rac5Planets.KALIDON,
        lambda world: HasChallengeMode(world, 1),
        Completion("events", C.Rac5ModVendorLocations.KALIDON_STATIC_REFLECTION),
        options=LocationOptions(
            requirements=(OptionFilter(ChallengeMode, (1, 2), "in"),), weapon=C.Rac5Weapons.STATIC_BARRIER
        ),
        categories=frozenset(("weapon_mod_vendor", "challenge_mode_mod")),
        weapon="static_barrier",
        mod_slot="mod_slot_one",
        definition_order=140,
    ),
    Rac5Locations(
        C.Rac5TitanVendorLocations.KALIDON_SCORCHER_TITAN,
        C.Rac5Planets.KALIDON,
        lambda world: HasChallengeMode(world, 1),
        Completion("events", C.Rac5TitanVendorLocations.KALIDON_SCORCHER_TITAN),
        options=LocationOptions(
            requirements=(OptionFilter(ChallengeMode, (1, 2), "in"),), weapon=C.Rac5Weapons.SCORCHER
        ),
        categories=frozenset(("weapon_titan_vendor",)),
        weapon="scorcher",
        definition_order=148,
    ),
    Rac5Locations(
        C.Rac5SkyboardChallenges.KALIDON_LEARNER,
        C.Rac5Planets.KALIDON,
        lambda world: True_(),
        Completion("skyboard", 0x088c13c8, 1),
        options=LocationOptions(requirements=(OptionFilter(SkyboardChallenges, (1,), "in"),)),
        categories=frozenset(("skyboard_item",)),
        check_order=0,
        definition_order=356,
    ),
    Rac5Locations(
        C.Rac5SkyboardChallenges.KALIDON_MASTER,
        C.Rac5Planets.KALIDON,
        lambda world: True_(),
        Completion("skyboard", 0x088c13c8, 64),
        options=LocationOptions(requirements=(OptionFilter(SkyboardChallenges, (1,), "in"),)),
        categories=frozenset(("skyboard_item",)),
        check_order=3,
        definition_order=357,
    ),
    Rac5Locations(
        C.Rac5SkyboardChallenges.KALIDON_TICKET,
        C.Rac5Planets.KALIDON,
        lambda world: True_(),
        Completion("skyboard", 0x088c13c8, 4),
        options=LocationOptions(requirements=(OptionFilter(SkyboardChallenges, (1,), "in"),)),
        categories=frozenset(("extra_skyboard",)),
        check_order=1,
        definition_order=360,
    ),
    Rac5Locations(
        C.Rac5SkyboardChallenges.KALIDON_TRICKY,
        C.Rac5Planets.KALIDON,
        lambda world: True_(),
        Completion("skyboard", 0x088c13c8, 16),
        options=LocationOptions(requirements=(OptionFilter(SkyboardChallenges, (1,), "in"),)),
        categories=frozenset(("extra_skyboard",)),
        check_order=2,
        definition_order=361,
    ),
    Rac5Locations(
        C.Rac5ShrinkRayGrindrail.KALIDON_ENTER_FACTORY,
        C.Rac5Planets.KALIDON,
        lambda world: Has(Rac5Gadgets.SHRINK_RAY),
        Completion("events", C.Rac5ShrinkRayGrindrail.KALIDON_ENTER_FACTORY),
        options=LocationOptions(requirements=(OptionFilter(ShrinkRayOptions, (1,), "in"),)),
        categories=frozenset(("shrink_ray_skip",)),
        definition_order=364,
    ),
    Rac5Locations(
        C.Rac5ShrinkRayGrindrail.KALIDON_INSIDE_FACTORY,
        C.Rac5Planets.KALIDON,
        lambda world: Has(Rac5Gadgets.HYPERSHOT) & HasShrinkRayDoorAccess(world),
        Completion("events", C.Rac5ShrinkRayGrindrail.KALIDON_INSIDE_FACTORY),
        options=LocationOptions(requirements=(OptionFilter(ShrinkRayOptions, (1,), "in"),)),
        categories=frozenset(("shrink_ray_skip",)),
        definition_order=365,
    ),
)
