from functools import partial

from .. import constants as C
from .model import Completion, LocationOptions, Rac5Locations
from .nanotech_levels import access_rule as nanotech_level_rule

LOCATIONS = (
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_6,
        "Menu",
        partial(nanotech_level_rule, level=6),
        Completion("nanotech_levels", 6),
        options=LocationOptions(nanotech_level=6),
        categories=frozenset(("nanotech_level",)),
        level=6,
        definition_order=243,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_7,
        "Menu",
        partial(nanotech_level_rule, level=7),
        Completion("nanotech_levels", 7),
        options=LocationOptions(nanotech_level=7),
        categories=frozenset(("nanotech_level",)),
        level=7,
        definition_order=244,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_8,
        "Menu",
        partial(nanotech_level_rule, level=8),
        Completion("nanotech_levels", 8),
        options=LocationOptions(nanotech_level=8),
        categories=frozenset(("nanotech_level",)),
        level=8,
        definition_order=245,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_9,
        "Menu",
        partial(nanotech_level_rule, level=9),
        Completion("nanotech_levels", 9),
        options=LocationOptions(nanotech_level=9),
        categories=frozenset(("nanotech_level",)),
        level=9,
        definition_order=246,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_10,
        "Menu",
        partial(nanotech_level_rule, level=10),
        Completion("nanotech_levels", 10),
        options=LocationOptions(nanotech_level=10),
        categories=frozenset(("nanotech_level",)),
        level=10,
        definition_order=247,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_11,
        "Menu",
        partial(nanotech_level_rule, level=11),
        Completion("nanotech_levels", 11),
        options=LocationOptions(nanotech_level=11),
        categories=frozenset(("nanotech_level",)),
        level=11,
        definition_order=248,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_12,
        "Menu",
        partial(nanotech_level_rule, level=12),
        Completion("nanotech_levels", 12),
        options=LocationOptions(nanotech_level=12),
        categories=frozenset(("nanotech_level",)),
        level=12,
        definition_order=249,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_13,
        "Menu",
        partial(nanotech_level_rule, level=13),
        Completion("nanotech_levels", 13),
        options=LocationOptions(nanotech_level=13),
        categories=frozenset(("nanotech_level",)),
        level=13,
        definition_order=250,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_14,
        "Menu",
        partial(nanotech_level_rule, level=14),
        Completion("nanotech_levels", 14),
        options=LocationOptions(nanotech_level=14),
        categories=frozenset(("nanotech_level",)),
        level=14,
        definition_order=251,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_15,
        "Menu",
        partial(nanotech_level_rule, level=15),
        Completion("nanotech_levels", 15),
        options=LocationOptions(nanotech_level=15),
        categories=frozenset(("nanotech_level",)),
        level=15,
        definition_order=252,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_16,
        "Menu",
        partial(nanotech_level_rule, level=16),
        Completion("nanotech_levels", 16),
        options=LocationOptions(nanotech_level=16),
        categories=frozenset(("nanotech_level",)),
        level=16,
        definition_order=253,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_17,
        "Menu",
        partial(nanotech_level_rule, level=17),
        Completion("nanotech_levels", 17),
        options=LocationOptions(nanotech_level=17),
        categories=frozenset(("nanotech_level",)),
        level=17,
        definition_order=254,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_18,
        "Menu",
        partial(nanotech_level_rule, level=18),
        Completion("nanotech_levels", 18),
        options=LocationOptions(nanotech_level=18),
        categories=frozenset(("nanotech_level",)),
        level=18,
        definition_order=255,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_19,
        "Menu",
        partial(nanotech_level_rule, level=19),
        Completion("nanotech_levels", 19),
        options=LocationOptions(nanotech_level=19),
        categories=frozenset(("nanotech_level",)),
        level=19,
        definition_order=256,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_20,
        "Menu",
        partial(nanotech_level_rule, level=20),
        Completion("nanotech_levels", 20),
        options=LocationOptions(nanotech_level=20),
        categories=frozenset(("nanotech_level",)),
        level=20,
        definition_order=257,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_21,
        "Menu",
        partial(nanotech_level_rule, level=21),
        Completion("nanotech_levels", 21),
        options=LocationOptions(nanotech_level=21),
        categories=frozenset(("nanotech_level",)),
        level=21,
        definition_order=258,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_22,
        "Menu",
        partial(nanotech_level_rule, level=22),
        Completion("nanotech_levels", 22),
        options=LocationOptions(nanotech_level=22),
        categories=frozenset(("nanotech_level",)),
        level=22,
        definition_order=259,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_23,
        "Menu",
        partial(nanotech_level_rule, level=23),
        Completion("nanotech_levels", 23),
        options=LocationOptions(nanotech_level=23),
        categories=frozenset(("nanotech_level",)),
        level=23,
        definition_order=260,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_24,
        "Menu",
        partial(nanotech_level_rule, level=24),
        Completion("nanotech_levels", 24),
        options=LocationOptions(nanotech_level=24),
        categories=frozenset(("nanotech_level",)),
        level=24,
        definition_order=261,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_25,
        "Menu",
        partial(nanotech_level_rule, level=25),
        Completion("nanotech_levels", 25),
        options=LocationOptions(nanotech_level=25),
        categories=frozenset(("nanotech_level",)),
        level=25,
        definition_order=262,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_26,
        "Menu",
        partial(nanotech_level_rule, level=26),
        Completion("nanotech_levels", 26),
        options=LocationOptions(nanotech_level=26),
        categories=frozenset(("nanotech_level",)),
        level=26,
        definition_order=263,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_27,
        "Menu",
        partial(nanotech_level_rule, level=27),
        Completion("nanotech_levels", 27),
        options=LocationOptions(nanotech_level=27),
        categories=frozenset(("nanotech_level",)),
        level=27,
        definition_order=264,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_28,
        "Menu",
        partial(nanotech_level_rule, level=28),
        Completion("nanotech_levels", 28),
        options=LocationOptions(nanotech_level=28),
        categories=frozenset(("nanotech_level",)),
        level=28,
        definition_order=265,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_29,
        "Menu",
        partial(nanotech_level_rule, level=29),
        Completion("nanotech_levels", 29),
        options=LocationOptions(nanotech_level=29),
        categories=frozenset(("nanotech_level",)),
        level=29,
        definition_order=266,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_30,
        "Menu",
        partial(nanotech_level_rule, level=30),
        Completion("nanotech_levels", 30),
        options=LocationOptions(nanotech_level=30),
        categories=frozenset(("nanotech_level",)),
        level=30,
        definition_order=267,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_31,
        "Menu",
        partial(nanotech_level_rule, level=31),
        Completion("nanotech_levels", 31),
        options=LocationOptions(nanotech_level=31),
        categories=frozenset(("nanotech_level",)),
        level=31,
        definition_order=268,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_32,
        "Menu",
        partial(nanotech_level_rule, level=32),
        Completion("nanotech_levels", 32),
        options=LocationOptions(nanotech_level=32),
        categories=frozenset(("nanotech_level",)),
        level=32,
        definition_order=269,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_33,
        "Menu",
        partial(nanotech_level_rule, level=33),
        Completion("nanotech_levels", 33),
        options=LocationOptions(nanotech_level=33),
        categories=frozenset(("nanotech_level",)),
        level=33,
        definition_order=270,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_34,
        "Menu",
        partial(nanotech_level_rule, level=34),
        Completion("nanotech_levels", 34),
        options=LocationOptions(nanotech_level=34),
        categories=frozenset(("nanotech_level",)),
        level=34,
        definition_order=271,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_35,
        "Menu",
        partial(nanotech_level_rule, level=35),
        Completion("nanotech_levels", 35),
        options=LocationOptions(nanotech_level=35),
        categories=frozenset(("nanotech_level",)),
        level=35,
        definition_order=272,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_36,
        "Menu",
        partial(nanotech_level_rule, level=36),
        Completion("nanotech_levels", 36),
        options=LocationOptions(nanotech_level=36),
        categories=frozenset(("nanotech_level",)),
        level=36,
        definition_order=273,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_37,
        "Menu",
        partial(nanotech_level_rule, level=37),
        Completion("nanotech_levels", 37),
        options=LocationOptions(nanotech_level=37),
        categories=frozenset(("nanotech_level",)),
        level=37,
        definition_order=274,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_38,
        "Menu",
        partial(nanotech_level_rule, level=38),
        Completion("nanotech_levels", 38),
        options=LocationOptions(nanotech_level=38),
        categories=frozenset(("nanotech_level",)),
        level=38,
        definition_order=275,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_39,
        "Menu",
        partial(nanotech_level_rule, level=39),
        Completion("nanotech_levels", 39),
        options=LocationOptions(nanotech_level=39),
        categories=frozenset(("nanotech_level",)),
        level=39,
        definition_order=276,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_40,
        "Menu",
        partial(nanotech_level_rule, level=40),
        Completion("nanotech_levels", 40),
        options=LocationOptions(nanotech_level=40),
        categories=frozenset(("nanotech_level",)),
        level=40,
        definition_order=277,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_41,
        "Menu",
        partial(nanotech_level_rule, level=41),
        Completion("nanotech_levels", 41),
        options=LocationOptions(nanotech_level=41),
        categories=frozenset(("nanotech_level",)),
        level=41,
        definition_order=278,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_42,
        "Menu",
        partial(nanotech_level_rule, level=42),
        Completion("nanotech_levels", 42),
        options=LocationOptions(nanotech_level=42),
        categories=frozenset(("nanotech_level",)),
        level=42,
        definition_order=279,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_43,
        "Menu",
        partial(nanotech_level_rule, level=43),
        Completion("nanotech_levels", 43),
        options=LocationOptions(nanotech_level=43),
        categories=frozenset(("nanotech_level",)),
        level=43,
        definition_order=280,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_44,
        "Menu",
        partial(nanotech_level_rule, level=44),
        Completion("nanotech_levels", 44),
        options=LocationOptions(nanotech_level=44),
        categories=frozenset(("nanotech_level",)),
        level=44,
        definition_order=281,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_45,
        "Menu",
        partial(nanotech_level_rule, level=45),
        Completion("nanotech_levels", 45),
        options=LocationOptions(nanotech_level=45),
        categories=frozenset(("nanotech_level",)),
        level=45,
        definition_order=282,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_46,
        "Menu",
        partial(nanotech_level_rule, level=46),
        Completion("nanotech_levels", 46),
        options=LocationOptions(nanotech_level=46),
        categories=frozenset(("nanotech_level",)),
        level=46,
        definition_order=283,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_47,
        "Menu",
        partial(nanotech_level_rule, level=47),
        Completion("nanotech_levels", 47),
        options=LocationOptions(nanotech_level=47),
        categories=frozenset(("nanotech_level",)),
        level=47,
        definition_order=284,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_48,
        "Menu",
        partial(nanotech_level_rule, level=48),
        Completion("nanotech_levels", 48),
        options=LocationOptions(nanotech_level=48),
        categories=frozenset(("nanotech_level",)),
        level=48,
        definition_order=285,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_49,
        "Menu",
        partial(nanotech_level_rule, level=49),
        Completion("nanotech_levels", 49),
        options=LocationOptions(nanotech_level=49),
        categories=frozenset(("nanotech_level",)),
        level=49,
        definition_order=286,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_50,
        "Menu",
        partial(nanotech_level_rule, level=50),
        Completion("nanotech_levels", 50),
        options=LocationOptions(nanotech_level=50),
        categories=frozenset(("nanotech_level",)),
        level=50,
        definition_order=287,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_51,
        "Menu",
        partial(nanotech_level_rule, level=51),
        Completion("nanotech_levels", 51),
        options=LocationOptions(nanotech_level=51),
        categories=frozenset(("nanotech_level",)),
        level=51,
        definition_order=288,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_52,
        "Menu",
        partial(nanotech_level_rule, level=52),
        Completion("nanotech_levels", 52),
        options=LocationOptions(nanotech_level=52),
        categories=frozenset(("nanotech_level",)),
        level=52,
        definition_order=289,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_53,
        "Menu",
        partial(nanotech_level_rule, level=53),
        Completion("nanotech_levels", 53),
        options=LocationOptions(nanotech_level=53),
        categories=frozenset(("nanotech_level",)),
        level=53,
        definition_order=290,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_54,
        "Menu",
        partial(nanotech_level_rule, level=54),
        Completion("nanotech_levels", 54),
        options=LocationOptions(nanotech_level=54),
        categories=frozenset(("nanotech_level",)),
        level=54,
        definition_order=291,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_55,
        "Menu",
        partial(nanotech_level_rule, level=55),
        Completion("nanotech_levels", 55),
        options=LocationOptions(nanotech_level=55),
        categories=frozenset(("nanotech_level",)),
        level=55,
        definition_order=292,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_56,
        "Menu",
        partial(nanotech_level_rule, level=56),
        Completion("nanotech_levels", 56),
        options=LocationOptions(nanotech_level=56),
        categories=frozenset(("nanotech_level",)),
        level=56,
        definition_order=293,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_57,
        "Menu",
        partial(nanotech_level_rule, level=57),
        Completion("nanotech_levels", 57),
        options=LocationOptions(nanotech_level=57),
        categories=frozenset(("nanotech_level",)),
        level=57,
        definition_order=294,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_58,
        "Menu",
        partial(nanotech_level_rule, level=58),
        Completion("nanotech_levels", 58),
        options=LocationOptions(nanotech_level=58),
        categories=frozenset(("nanotech_level",)),
        level=58,
        definition_order=295,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_59,
        "Menu",
        partial(nanotech_level_rule, level=59),
        Completion("nanotech_levels", 59),
        options=LocationOptions(nanotech_level=59),
        categories=frozenset(("nanotech_level",)),
        level=59,
        definition_order=296,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_60,
        "Menu",
        partial(nanotech_level_rule, level=60),
        Completion("nanotech_levels", 60),
        options=LocationOptions(nanotech_level=60),
        categories=frozenset(("nanotech_level",)),
        level=60,
        definition_order=297,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_61,
        "Menu",
        partial(nanotech_level_rule, level=61),
        Completion("nanotech_levels", 61),
        options=LocationOptions(nanotech_level=61),
        categories=frozenset(("nanotech_level",)),
        level=61,
        definition_order=298,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_62,
        "Menu",
        partial(nanotech_level_rule, level=62),
        Completion("nanotech_levels", 62),
        options=LocationOptions(nanotech_level=62),
        categories=frozenset(("nanotech_level",)),
        level=62,
        definition_order=299,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_63,
        "Menu",
        partial(nanotech_level_rule, level=63),
        Completion("nanotech_levels", 63),
        options=LocationOptions(nanotech_level=63),
        categories=frozenset(("nanotech_level",)),
        level=63,
        definition_order=300,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_64,
        "Menu",
        partial(nanotech_level_rule, level=64),
        Completion("nanotech_levels", 64),
        options=LocationOptions(nanotech_level=64),
        categories=frozenset(("nanotech_level",)),
        level=64,
        definition_order=301,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_65,
        "Menu",
        partial(nanotech_level_rule, level=65),
        Completion("nanotech_levels", 65),
        options=LocationOptions(nanotech_level=65),
        categories=frozenset(("nanotech_level",)),
        level=65,
        definition_order=302,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_66,
        "Menu",
        partial(nanotech_level_rule, level=66),
        Completion("nanotech_levels", 66),
        options=LocationOptions(nanotech_level=66),
        categories=frozenset(("nanotech_level",)),
        level=66,
        definition_order=303,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_67,
        "Menu",
        partial(nanotech_level_rule, level=67),
        Completion("nanotech_levels", 67),
        options=LocationOptions(nanotech_level=67),
        categories=frozenset(("nanotech_level",)),
        level=67,
        definition_order=304,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_68,
        "Menu",
        partial(nanotech_level_rule, level=68),
        Completion("nanotech_levels", 68),
        options=LocationOptions(nanotech_level=68),
        categories=frozenset(("nanotech_level",)),
        level=68,
        definition_order=305,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_69,
        "Menu",
        partial(nanotech_level_rule, level=69),
        Completion("nanotech_levels", 69),
        options=LocationOptions(nanotech_level=69),
        categories=frozenset(("nanotech_level",)),
        level=69,
        definition_order=306,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_70,
        "Menu",
        partial(nanotech_level_rule, level=70),
        Completion("nanotech_levels", 70),
        options=LocationOptions(nanotech_level=70),
        categories=frozenset(("nanotech_level",)),
        level=70,
        definition_order=307,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_71,
        "Menu",
        partial(nanotech_level_rule, level=71),
        Completion("nanotech_levels", 71),
        options=LocationOptions(nanotech_level=71),
        categories=frozenset(("nanotech_level",)),
        level=71,
        definition_order=308,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_72,
        "Menu",
        partial(nanotech_level_rule, level=72),
        Completion("nanotech_levels", 72),
        options=LocationOptions(nanotech_level=72),
        categories=frozenset(("nanotech_level",)),
        level=72,
        definition_order=309,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_73,
        "Menu",
        partial(nanotech_level_rule, level=73),
        Completion("nanotech_levels", 73),
        options=LocationOptions(nanotech_level=73),
        categories=frozenset(("nanotech_level",)),
        level=73,
        definition_order=310,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_74,
        "Menu",
        partial(nanotech_level_rule, level=74),
        Completion("nanotech_levels", 74),
        options=LocationOptions(nanotech_level=74),
        categories=frozenset(("nanotech_level",)),
        level=74,
        definition_order=311,
    ),
    Rac5Locations(
        C.Rac5NanotechLevels.LEVEL_75,
        "Menu",
        partial(nanotech_level_rule, level=75),
        Completion("nanotech_levels", 75),
        options=LocationOptions(nanotech_level=75),
        categories=frozenset(("nanotech_level",)),
        level=75,
        definition_order=312,
    ),
)
