from rule_builder.options import OptionFilter
from rule_builder.rules import HasAll, True_

from .. import constants as C
from ..constants import Rac5Gadgets
from ..options import AllCutscenes, AllMissions, ChallengeMode, EnableSkyboardChallengeSkillPoints, SkyboardChallenges
from ..rules._helpers import HasChallengeMode
from .model import Completion, LocationOptions, Rac5Locations

LOCATIONS = (
    Rac5Locations(
        C.Rac5TBolts.OUTPOST_OMEGA_DREAM,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: True_(),
        Completion("bolt_bits", None, 1048576),
        categories=frozenset(("titanium_bolt",)),
        native_planets=(6, 23),
        definition_order=11,
    ),
    Rac5Locations(
        C.Rac5Locations.OUTPOST_OMEGA_BOOTS,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: True_(),
        Completion("armour", "crystallix", 16),
        categories=frozenset(("armour_pickup",)),
        definition_order=27,
    ),
    Rac5Locations(
        C.Rac5Locations.OUTPOST_OMEGA_CHAMELEON_GLOVES,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: HasChallengeMode(world, 2),
        Completion("armour", "chameleon", 4),
        options=LocationOptions(requirements=(OptionFilter(ChallengeMode, (2,), "in"),)),
        categories=frozenset(("armour_pickup", "challenge_mode_2_armour")),
        definition_order=39,
    ),
    Rac5Locations(
        C.Rac5SkillPoints.OUTPOST_OMEGA_AWESOME,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: True_(),
        Completion("skill_bits", None, 1048576),
        options=LocationOptions(requirements=(OptionFilter(EnableSkyboardChallengeSkillPoints, (1,), "in"),)),
        categories=frozenset(("skill_point", "skyboard_challenge_skill_point")),
        native_planets=(23,),
        definition_order=57,
    ),
    Rac5Locations(
        C.Rac5CutsceneLocations.OUTPOST_OMEGA_ESCAPE,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: HasAll(Rac5Gadgets.HYPERSHOT, Rac5Gadgets.SPROUT_O_MATIC),
        Completion("missions", 0x088c138e, 128, 6),
        options=LocationOptions(requirements=(OptionFilter(AllMissions, (1,), "in"),)),
        categories=frozenset(("story_mission", "mission")),
        check_order=9,
        definition_order=74,
    ),
    Rac5Locations(
        C.Rac5CutsceneLocations.OUTPOST_OMEGA_REMATCH,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: True_(),
        Completion("missions", 0x088c138e, 16, 6),
        options=LocationOptions(requirements=(OptionFilter(AllMissions, (1,), "in"),)),
        categories=frozenset(("story_mission", "mission")),
        check_order=10,
        definition_order=75,
    ),
    Rac5Locations(
        C.Rac5CutsceneLocations.OUTPOST_OMEGA,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: HasAll(Rac5Gadgets.HYPERSHOT, Rac5Gadgets.SPROUT_O_MATIC),
        Completion("missions", 0x088c138e, 2, 6),
        options=LocationOptions(requirements=(OptionFilter(AllCutscenes, (1,), "in"),)),
        categories=frozenset(("cutscene", "mission")),
        check_order=28,
        definition_order=88,
    ),
    Rac5Locations(
        C.Rac5CutsceneLocations.OUTPOST_OMEGA_ENTER,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: HasAll(Rac5Gadgets.HYPERSHOT, Rac5Gadgets.SPROUT_O_MATIC),
        Completion("missions", 0x088c138e, 1, 6),
        options=LocationOptions(requirements=(OptionFilter(AllCutscenes, (1,), "in"),)),
        categories=frozenset(("cutscene", "mission")),
        check_order=22,
        definition_order=99,
    ),
    Rac5Locations(
        C.Rac5VendorLocations.OUTPOST_OMEGA_BEE,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: True_(),
        Completion("events", C.Rac5VendorLocations.OUTPOST_OMEGA_BEE),
        options=LocationOptions(weapon=C.Rac5Weapons.BEE_MINE_GLOVE),
        categories=frozenset(("weapon_vendor",)),
        weapon="bee_mine_glove",
        definition_order=110,
    ),
    Rac5Locations(
        C.Rac5VendorLocations.OUTPOST_OMEGA_BOX_BREAKER,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: True_(),
        Completion("events", C.Rac5VendorLocations.OUTPOST_OMEGA_BOX_BREAKER),
        categories=frozenset(("gadget_vendor",)),
        gadget="box_breaker",
        definition_order=120,
    ),
    Rac5Locations(
        C.Rac5TitanVendorLocations.OUTPOST_OMEGA_BEE_TITAN,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: HasChallengeMode(world, 1),
        Completion("events", C.Rac5TitanVendorLocations.OUTPOST_OMEGA_BEE_TITAN),
        options=LocationOptions(
            requirements=(OptionFilter(ChallengeMode, (1, 2), "in"),), weapon=C.Rac5Weapons.BEE_MINE_GLOVE
        ),
        categories=frozenset(("weapon_titan_vendor",)),
        weapon="bee_mine_glove",
        definition_order=150,
    ),
    Rac5Locations(
        C.Rac5SkyboardChallenges.OUTPOST_OMEGA_VERTIGO,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: True_(),
        Completion("skyboard", 0x088c13ca, 64),
        options=LocationOptions(requirements=(OptionFilter(SkyboardChallenges, (1,), "in"),)),
        categories=frozenset(("skyboard_item",)),
        check_order=7,
        definition_order=358,
    ),
    Rac5Locations(
        C.Rac5SkyboardChallenges.OUTPOST_OMEGA_INTERIOR,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: True_(),
        Completion("skyboard", 0x088c13ca, 1),
        options=LocationOptions(requirements=(OptionFilter(SkyboardChallenges, (1,), "in"),)),
        categories=frozenset(("skyboard_item",)),
        check_order=4,
        definition_order=359,
    ),
    Rac5Locations(
        C.Rac5SkyboardChallenges.OUTPOST_OMEGA_DANGER,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: True_(),
        Completion("skyboard", 0x088c13ca, 4),
        options=LocationOptions(requirements=(OptionFilter(SkyboardChallenges, (1,), "in"),)),
        categories=frozenset(("extra_skyboard",)),
        check_order=5,
        definition_order=362,
    ),
    Rac5Locations(
        C.Rac5SkyboardChallenges.OUTPOST_OMEGA_VORTEX,
        C.Rac5Planets.OUTPOST_OMEGA,
        lambda world: True_(),
        Completion("skyboard", 0x088c13ca, 16),
        options=LocationOptions(requirements=(OptionFilter(SkyboardChallenges, (1,), "in"),)),
        categories=frozenset(("extra_skyboard",)),
        check_order=6,
        definition_order=363,
    ),
)
