"""Generated. Re-exports every DLC level's location constants, grouped by kit."""
from .creator_pack import GlobalLightingObjectLocations, InfiniteLifeCheckpointLocations, TetherlessJetpackAndEnhancementRemoverLocations, TweakableAngleRangeForSwitchesLocations, TweakableVisibilityForConnectorsLocations
from .goty_bonus import BeavercowsInsomniaLocations, BunniesInSpaceLocations, CerealIsleLocations, EvilDuckiesLocations, InSearchLocations, MightyMiteLbp8LittleBigMountainMissionLocations, PandamoniumLocations, PrismPanicLocations, StoneLocations, TaklamakanGoAndNeverComeBackLocations, TalesOfTheLittleBigCrystalLocations, TheCatBurglarLocations, TheGreatGratuitousRaidOfGoblinBergLocations, TheSteampunkSamuraiLocations, TheTumblerizerLocations, TubeRacer2Locations, UntilTheCowsComeHomeLocations, WatermillValleyLocations
from .history_kit import StepThroughTimeLocations
from .incredibles_kit import MissionIncredibleLocations
from .marvel_kit import MarvelIssue1DowntownDoomLocations, MarvelIssue2FreewayFrenzyLocations, MarvelIssue3MadLabLocations, MarvelIssue4RocketRampageLocations
from .metal_gear_solid_kit import MetalGearSolidAct1IntroductionLocations, MetalGearSolidAct2VrTrainingLocations, MetalGearSolidAct3TheMissionLocations, MetalGearSolidAct4TheLevelFactoryLocations, MetalGearSolidAct5TheBossLocations, MetalGearSolidVrSurvivalChallengeLocations
from .monster_kit import GhostTrainLocations
from .pirates_of_the_caribbean_kit import ANavyFrigateLocations, CursedBayLocations, DivingForTreasureLocations, GlobalWaterObjectLocations, PirateTownLocations, PortRoyalLocations, TheKrakenLocations, WaterSwitchLocations
