from rule_builder.rules import Has

from ..model import Kind, LBPLocationData

LEVEL = 'g26698'

LOCATIONS = (
    LBPLocationData('Burning Forest - Score Bubble 1', LEVEL, Kind.SCORE, uid=16119),
    LBPLocationData('Burning Forest - Score Bubble 2', LEVEL, Kind.SCORE, uid=16123),
    LBPLocationData('Burning Forest - Score Bubble 3', LEVEL, Kind.SCORE, uid=16124),
    LBPLocationData('Burning Forest - Score Bubble 4', LEVEL, Kind.SCORE, uid=16130),
    LBPLocationData('Burning Forest - Score Bubble 5', LEVEL, Kind.SCORE, uid=16134),
    LBPLocationData('Burning Forest - Score Bubble 6', LEVEL, Kind.SCORE, uid=16135),
    LBPLocationData('Burning Forest - Score Bubble 7', LEVEL, Kind.SCORE, uid=16345),
    LBPLocationData('Burning Forest - Score Bubble 8', LEVEL, Kind.SCORE, uid=16346),
    LBPLocationData('Burning Forest - Score Bubble 9', LEVEL, Kind.SCORE, uid=16347),
    LBPLocationData('Burning Forest - Score Bubble 10', LEVEL, Kind.SCORE, uid=16348),
    LBPLocationData('Burning Forest - Score Bubble 11', LEVEL, Kind.SCORE, uid=16349),
    LBPLocationData('Burning Forest - Score Bubble 12', LEVEL, Kind.SCORE, uid=16350),
    LBPLocationData('Burning Forest - Score Bubble 13', LEVEL, Kind.SCORE, uid=16352),
    LBPLocationData('Burning Forest - Score Bubble 14', LEVEL, Kind.SCORE, uid=16353),
    LBPLocationData('Burning Forest - Score Bubble 15', LEVEL, Kind.SCORE, uid=16354),
    LBPLocationData('Burning Forest - Score Bubble 16', LEVEL, Kind.SCORE, uid=16355),
    LBPLocationData('Burning Forest - Score Bubble 17', LEVEL, Kind.SCORE, uid=16356),
    LBPLocationData('Burning Forest - Score Bubble 18', LEVEL, Kind.SCORE, uid=16357),
    LBPLocationData('Burning Forest - Score Bubble 19', LEVEL, Kind.SCORE, uid=16358),
    LBPLocationData('Burning Forest - Score Bubble 20', LEVEL, Kind.SCORE, uid=16360),
    LBPLocationData('Burning Forest - Score Bubble 21', LEVEL, Kind.SCORE, uid=18062),
    LBPLocationData('Burning Forest - Score Bubble 22', LEVEL, Kind.SCORE, uid=18063),
    LBPLocationData('Burning Forest - Score Bubble 23', LEVEL, Kind.SCORE, uid=18064),
    LBPLocationData('Burning Forest - Score Bubble 24', LEVEL, Kind.SCORE, uid=18065),
    LBPLocationData('Burning Forest - Score Bubble 25', LEVEL, Kind.SCORE, uid=18066),
    LBPLocationData('Burning Forest - Score Bubble 26', LEVEL, Kind.SCORE, uid=18067),
    LBPLocationData('Burning Forest - Score Bubble 27', LEVEL, Kind.SCORE, uid=18070),
    LBPLocationData('Burning Forest - Score Bubble 28', LEVEL, Kind.SCORE, uid=18071),
    LBPLocationData('Burning Forest - Score Bubble 29', LEVEL, Kind.SCORE, uid=18072),
    LBPLocationData('Burning Forest - Score Bubble 30', LEVEL, Kind.SCORE, uid=18073),
    LBPLocationData('Burning Forest - Score Bubble 31', LEVEL, Kind.SCORE, uid=18074),
    LBPLocationData('Burning Forest - Score Bubble 32', LEVEL, Kind.SCORE, uid=18075),
    LBPLocationData('Burning Forest - Score Bubble 33', LEVEL, Kind.SCORE, uid=18076),
    LBPLocationData('Burning Forest - Score Bubble 34', LEVEL, Kind.SCORE, uid=18077),
    LBPLocationData('Burning Forest - Score Bubble 35', LEVEL, Kind.SCORE, uid=18078),
    LBPLocationData('Burning Forest - Score Bubble 36', LEVEL, Kind.SCORE, uid=18079),
    LBPLocationData('Burning Forest - Score Bubble 37', LEVEL, Kind.SCORE, uid=18080),
    LBPLocationData('Burning Forest - Score Bubble 38', LEVEL, Kind.SCORE, uid=18081),
    LBPLocationData('Burning Forest - Score Bubble 39', LEVEL, Kind.SCORE, uid=18082),
    LBPLocationData('Burning Forest - Score Bubble 40', LEVEL, Kind.SCORE, uid=18083),
    LBPLocationData('Burning Forest - Score Bubble 41', LEVEL, Kind.SCORE, uid=18084),
    LBPLocationData('Burning Forest - Score Bubble 42', LEVEL, Kind.SCORE, uid=18085),
    LBPLocationData('Burning Forest - Score Bubble 43', LEVEL, Kind.SCORE, uid=18086),
    LBPLocationData('Burning Forest - Score Bubble 44', LEVEL, Kind.SCORE, uid=18087),
    LBPLocationData('Burning Forest - Score Bubble 45', LEVEL, Kind.SCORE, uid=36704),
    LBPLocationData('Burning Forest - Score Bubble 46', LEVEL, Kind.SCORE, uid=36705),
    LBPLocationData('Burning Forest - Score Bubble 47', LEVEL, Kind.SCORE, uid=36706),
    LBPLocationData('Burning Forest - Score Bubble 48', LEVEL, Kind.SCORE, uid=36707),
    LBPLocationData('Burning Forest - Score Bubble 49', LEVEL, Kind.SCORE, uid=36708),
    LBPLocationData('Burning Forest - Score Bubble 50', LEVEL, Kind.SCORE, uid=36709),
    LBPLocationData('Burning Forest - Score Bubble 51', LEVEL, Kind.SCORE, uid=36713),
    LBPLocationData('Burning Forest - Score Bubble 52', LEVEL, Kind.SCORE, uid=36714),
    LBPLocationData('Burning Forest - Score Bubble 53', LEVEL, Kind.SCORE, uid=36715),
    LBPLocationData('Burning Forest - Score Bubble 54', LEVEL, Kind.SCORE, uid=36728),
    LBPLocationData('Burning Forest - Score Bubble 55', LEVEL, Kind.SCORE, uid=36729),
    LBPLocationData('Burning Forest - Score Bubble 56', LEVEL, Kind.SCORE, uid=36730),
    LBPLocationData('Burning Forest - Score Bubble 57', LEVEL, Kind.SCORE, uid=36731),
    LBPLocationData('Burning Forest - Score Bubble 58', LEVEL, Kind.SCORE, uid=36732),
    LBPLocationData('Burning Forest - Score Bubble 59', LEVEL, Kind.SCORE, uid=36733),
    LBPLocationData('Burning Forest - Score Bubble 60', LEVEL, Kind.SCORE, uid=36737),
    LBPLocationData('Burning Forest - Score Bubble 61', LEVEL, Kind.SCORE, uid=36738),
    LBPLocationData('Burning Forest - Score Bubble 62', LEVEL, Kind.SCORE, uid=36739),
    LBPLocationData('Burning Forest - Score Bubble 63', LEVEL, Kind.SCORE, uid=36740),
    LBPLocationData('Burning Forest - Score Bubble 64', LEVEL, Kind.SCORE, uid=36741),
    LBPLocationData('Burning Forest - Score Bubble 65', LEVEL, Kind.SCORE, uid=36742),
    LBPLocationData('Burning Forest - Score Bubble 66', LEVEL, Kind.SCORE, uid=36746),
    LBPLocationData('Burning Forest - Score Bubble 67', LEVEL, Kind.SCORE, uid=36747),
    LBPLocationData('Burning Forest - Score Bubble 68', LEVEL, Kind.SCORE, uid=36748),
    LBPLocationData('Burning Forest - Score Bubble 69', LEVEL, Kind.SCORE, uid=36752),
    LBPLocationData('Burning Forest - Score Bubble 70', LEVEL, Kind.SCORE, uid=36753),
    LBPLocationData('Burning Forest - Score Bubble 71', LEVEL, Kind.SCORE, uid=36754),
    LBPLocationData('Burning Forest - Score Bubble 72', LEVEL, Kind.SCORE, uid=36755),
    LBPLocationData('Burning Forest - Score Bubble 73', LEVEL, Kind.SCORE, uid=36756),
    LBPLocationData('Burning Forest - Score Bubble 74', LEVEL, Kind.SCORE, uid=36757),
    LBPLocationData('Burning Forest - Score Bubble 75', LEVEL, Kind.SCORE, uid=36758),
    LBPLocationData('Burning Forest - Score Bubble 76', LEVEL, Kind.SCORE, uid=36759),
    LBPLocationData('Burning Forest - Score Bubble 77', LEVEL, Kind.SCORE, uid=36760),
    LBPLocationData('Burning Forest - Score Bubble 78', LEVEL, Kind.SCORE, uid=36765),
    LBPLocationData('Burning Forest - Score Bubble 79', LEVEL, Kind.SCORE, uid=36766),
    LBPLocationData('Burning Forest - Score Bubble 80', LEVEL, Kind.SCORE, uid=36767),
    LBPLocationData('Burning Forest - Score Bubble 81', LEVEL, Kind.SCORE, uid=36768),
    LBPLocationData('Burning Forest - Score Bubble 82', LEVEL, Kind.SCORE, uid=36769),
    LBPLocationData('Burning Forest - Score Bubble 83', LEVEL, Kind.SCORE, uid=36770),
    LBPLocationData('Burning Forest - Score Bubble 84', LEVEL, Kind.SCORE, uid=36771),
    LBPLocationData('Burning Forest - Score Bubble 85', LEVEL, Kind.SCORE, uid=36772),
    LBPLocationData('Burning Forest - Score Bubble 86', LEVEL, Kind.SCORE, uid=36773),
    LBPLocationData('Burning Forest - Score Bubble 87', LEVEL, Kind.SCORE, uid=243444),
    LBPLocationData('Burning Forest - Score Bubble 88', LEVEL, Kind.SCORE, uid=243445),
    LBPLocationData('Burning Forest - Score Bubble 89', LEVEL, Kind.SCORE, uid=243446),
    LBPLocationData('Burning Forest - Score Bubble 90', LEVEL, Kind.SCORE, uid=243913),
    LBPLocationData('Burning Forest - Score Bubble 91', LEVEL, Kind.SCORE, uid=243914),
    LBPLocationData('Burning Forest - Score Bubble 92', LEVEL, Kind.SCORE, uid=243915),
    LBPLocationData('Burning Forest - Score Bubble 93', LEVEL, Kind.SCORE, uid=243916),
    LBPLocationData('Burning Forest - Score Bubble 94', LEVEL, Kind.SCORE, uid=243917),
    LBPLocationData('Burning Forest - Score Bubble 95', LEVEL, Kind.SCORE, uid=243918),
    LBPLocationData('Burning Forest - Score Bubble 96', LEVEL, Kind.SCORE, uid=243919),
    LBPLocationData('Burning Forest - Score Bubble 97', LEVEL, Kind.SCORE, uid=243920),
    LBPLocationData('Burning Forest - Score Bubble 98', LEVEL, Kind.SCORE, uid=243921),
    LBPLocationData('Burning Forest - Score Bubble 99', LEVEL, Kind.SCORE, uid=243922),
    LBPLocationData('Burning Forest - Score Bubble 100', LEVEL, Kind.SCORE, uid=243923),
    LBPLocationData('Burning Forest - Score Bubble 101', LEVEL, Kind.SCORE, uid=243924),
    LBPLocationData('Burning Forest - Score Bubble 102', LEVEL, Kind.SCORE, uid=245311),
    LBPLocationData('Burning Forest - Score Bubble 103', LEVEL, Kind.SCORE, uid=245315),
    LBPLocationData('Burning Forest - Score Bubble 104', LEVEL, Kind.SCORE, uid=245316),
    LBPLocationData('Burning Forest - Score Bubble 105', LEVEL, Kind.SCORE, uid=245317),
    LBPLocationData('Burning Forest - Score Bubble 106', LEVEL, Kind.SCORE, uid=256143),
    LBPLocationData('Burning Forest - Score Bubble 107', LEVEL, Kind.SCORE, uid=256144),
    LBPLocationData('Burning Forest - Score Bubble 108', LEVEL, Kind.SCORE, uid=256145),
    LBPLocationData('Burning Forest - Score Bubble 109', LEVEL, Kind.SCORE, uid=256146),
    LBPLocationData('Burning Forest - Score Bubble 110', LEVEL, Kind.SCORE, uid=256147),
    LBPLocationData('Burning Forest - Score Bubble 111', LEVEL, Kind.SCORE, uid=256148),
    LBPLocationData('Burning Forest - Score Bubble 112', LEVEL, Kind.SCORE, uid=256149),
    LBPLocationData('Burning Forest - Score Bubble 113', LEVEL, Kind.SCORE, uid=256150),
    LBPLocationData('Burning Forest - Score Bubble 114', LEVEL, Kind.SCORE, uid=256151),
    LBPLocationData('Burning Forest - Score Bubble 115', LEVEL, Kind.SCORE, uid=256152),
    LBPLocationData('Burning Forest - Score Bubble 116', LEVEL, Kind.SCORE, uid=256153),
    LBPLocationData('Burning Forest - Score Bubble 117', LEVEL, Kind.SCORE, uid=256154),
    LBPLocationData('Burning Forest - Score Bubble 118', LEVEL, Kind.SCORE, uid=258510),
    LBPLocationData('Burning Forest - Score Bubble 119', LEVEL, Kind.SCORE, uid=258511),
    LBPLocationData('Burning Forest - Score Bubble 120', LEVEL, Kind.SCORE, uid=258512),
    LBPLocationData('Burning Forest - Score Bubble 121', LEVEL, Kind.SCORE, uid=258516),
    LBPLocationData('Burning Forest - Score Bubble 122', LEVEL, Kind.SCORE, uid=258517),
    LBPLocationData('Burning Forest - Score Bubble 123', LEVEL, Kind.SCORE, uid=258518),
    LBPLocationData('Burning Forest - Score Bubble 124', LEVEL, Kind.SCORE, uid=259538),
    LBPLocationData('Burning Forest - Score Bubble 125', LEVEL, Kind.SCORE, uid=259539),
    LBPLocationData('Burning Forest - Score Bubble 126', LEVEL, Kind.SCORE, uid=259540),
    LBPLocationData('Burning Forest - Score Bubble 127', LEVEL, Kind.SCORE, uid=259541),
    LBPLocationData('Burning Forest - Score Bubble 128', LEVEL, Kind.SCORE, uid=259542),
    LBPLocationData('Burning Forest - Score Bubble 129', LEVEL, Kind.SCORE, uid=259543),
    LBPLocationData('Burning Forest - Score Bubble 130', LEVEL, Kind.SCORE, uid=259544),
    LBPLocationData('Burning Forest - Score Bubble 131', LEVEL, Kind.SCORE, uid=364868),
    LBPLocationData('Burning Forest - Score Bubble 132', LEVEL, Kind.SCORE, uid=364869),
    LBPLocationData('Burning Forest - Score Bubble 133', LEVEL, Kind.SCORE, uid=364870),
    LBPLocationData('Burning Forest - Score Bubble 134', LEVEL, Kind.SCORE, uid=364871),
    LBPLocationData('Burning Forest - Score Bubble 135', LEVEL, Kind.SCORE, uid=364872),
    LBPLocationData('Burning Forest - Score Bubble 136', LEVEL, Kind.SCORE, uid=364873),
    LBPLocationData('Burning Forest - Score Bubble 137', LEVEL, Kind.SCORE, uid=364874),
    LBPLocationData('Burning Forest - Score Bubble 138', LEVEL, Kind.SCORE, uid=364875),
    LBPLocationData('Burning Forest - Score Bubble 139', LEVEL, Kind.SCORE, uid=364876),
    LBPLocationData('Burning Forest - Score Bubble 140', LEVEL, Kind.SCORE, uid=364877),
    LBPLocationData('Burning Forest - Score Bubble 141', LEVEL, Kind.SCORE, uid=364878),
    LBPLocationData('Burning Forest - Score Bubble 142', LEVEL, Kind.SCORE, uid=364879),
    LBPLocationData('Burning Forest - Prize Bubble 1 - Dangly Motif', LEVEL, Kind.PRIZE, uid=16344, plan='g33375'),
    LBPLocationData('Burning Forest - Prize Bubble 2 - Croc King', LEVEL, Kind.PRIZE, uid=16658, plan='g46788'),
    LBPLocationData('Burning Forest - Prize Bubble 3 - Tiger Nose', LEVEL, Kind.PRIZE, uid=16660, plan='g33376', players=2),
    LBPLocationData('Burning Forest - Prize Bubble 4 - Big Snappy Croc', LEVEL, Kind.PRIZE, uid=16663, plan='g45461'),
    LBPLocationData('Burning Forest - Prize Bubble 5 - Wooden Buffalo', LEVEL, Kind.PRIZE, uid=16665, plan='g46786'),
    LBPLocationData('Burning Forest - Prize Bubble 6 - Pigeon House', LEVEL, Kind.PRIZE, uid=245780, plan='g33392'),
    LBPLocationData('Burning Forest - Prize Bubble 7 - Crazy Eyes', LEVEL, Kind.PRIZE, uid=256156, plan='g33390', rule=Has('Stylised Antelope')),
    LBPLocationData('Burning Forest - Prize Bubble 8 - Buffalo Emitter', LEVEL, Kind.PRIZE, uid=259006, plan='g46783', rule=Has('Cat Head')),
    LBPLocationData('Burning Forest - Prize Bubble 9 - Large Red Vase', LEVEL, Kind.PRIZE, uid=259523, plan='g33450'),
    LBPLocationData('Burning Forest - Prize Bubble 10 - Zebra Fabric', LEVEL, Kind.PRIZE, uid=259534, plan='g33434'),
    LBPLocationData('Burning Forest - Prize Bubble 11 - Scary Ornament', LEVEL, Kind.PRIZE, uid=315189, plan='g33451', rule=Has('Cat Head')),
    LBPLocationData('Burning Forest - Prize Bubble 12 - Amazing Diamond', LEVEL, Kind.PRIZE, uid=343627, plan='g33384'),
    LBPLocationData('Burning Forest - Prize Bubble 13 - Coco Wood', LEVEL, Kind.PRIZE, uid=344091, plan='g51141'),
    LBPLocationData('Burning Forest - Prize Bubble 14 - Mahogany Wood', LEVEL, Kind.PRIZE, uid=344092, plan='g51142', players=2),
    LBPLocationData('Burning Forest - Prize Bubble 15 - Attitude Face', LEVEL, Kind.PRIZE, uid=353783, plan='g33393'),
    LBPLocationData("Burning Forest - Prize Bubble 16 - 'Rock The Jungle'", LEVEL, Kind.PRIZE, uid=354707, plan='g52640'),
    LBPLocationData('Burning Forest - Prize Bubble 17 - Antlers', LEVEL, Kind.PRIZE, uid=354709, plan='g32475', players=2),
    LBPLocationData('Burning Forest - Prize Bubble 18 - Green Rope', LEVEL, Kind.PRIZE, uid=355171, plan='g32727'),
    LBPLocationData('Burning Forest - Prize Bubble 19 - Cardboard Support', LEVEL, Kind.PRIZE, uid=355172, plan='g41497'),
    LBPLocationData('Burning Forest - Prize Bubble 20 - Shield 1', LEVEL, Kind.PRIZE, uid=355634, plan='g33377'),
    LBPLocationData('Burning Forest - Prize Bubble 21 - Bear Nose', LEVEL, Kind.PRIZE, uid=355635, plan='g51258'),
    LBPLocationData('Burning Forest - Prize Bubble 22 - Orange Stripy', LEVEL, Kind.PRIZE, uid=357943, plan='g32517'),
    LBPLocationData('Burning Forest - Prize Bubble 23 - Feathered Spiky', LEVEL, Kind.PRIZE, uid=390845, plan='g54642'),
    LBPLocationData('Burning Forest - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Burning Forest - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('Burning Forest - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('Burning Forest - Completion Reward 1 - Black and Pink Dress', LEVEL, Kind.REWARD, plan='g32363', condition=Kind.COMPLETE),
    LBPLocationData('Burning Forest - Completion Reward 2 - Green Checked', LEVEL, Kind.REWARD, plan='g34385', condition=Kind.COMPLETE),
    LBPLocationData('Burning Forest - All Prizes Reward 1 - Big Cat Concept with Frame', LEVEL, Kind.REWARD, plan='g52801', condition=Kind.ALL_PRIZES),
    LBPLocationData('Burning Forest - All Prizes Reward 2 - Bigcat Concept', LEVEL, Kind.REWARD, plan='g52789', condition=Kind.ALL_PRIZES),
    LBPLocationData('Burning Forest - Ace Reward 1 - Moustache', LEVEL, Kind.REWARD, plan='g51063', condition=Kind.ACE),
    LBPLocationData('Burning Forest - Sticker Switch 1 - Stylised Antelope', LEVEL, Kind.STICKER_SWITCH, uid=253809, plan='g33391'),
    LBPLocationData('Burning Forest - Sticker Switch 2 - Amazing Diamond', LEVEL, Kind.STICKER_SWITCH, uid=257574, plan='g33384'),
    LBPLocationData('Burning Forest - Sticker Switch 3 - Cat Head', LEVEL, Kind.STICKER_SWITCH, uid=258994, plan='g33394'),
    LBPLocationData('Burning Forest - Key 1', LEVEL, Kind.KEY, uid=32506, target_slot='SlotID{DEVELOPER, 26873}'),
)
