from rule_builder.rules import Has

from ..model import Kind, LBPLocationData

LEVEL = 'g20355'

LOCATIONS = (
    LBPLocationData('Elephant Temple - Score Bubble 1', LEVEL, Kind.SCORE, uid=16703),
    LBPLocationData('Elephant Temple - Score Bubble 2', LEVEL, Kind.SCORE, uid=16704),
    LBPLocationData('Elephant Temple - Score Bubble 3', LEVEL, Kind.SCORE, uid=16705),
    LBPLocationData('Elephant Temple - Score Bubble 4', LEVEL, Kind.SCORE, uid=16706),
    LBPLocationData('Elephant Temple - Score Bubble 5', LEVEL, Kind.SCORE, uid=16707),
    LBPLocationData('Elephant Temple - Score Bubble 6', LEVEL, Kind.SCORE, uid=16708),
    LBPLocationData('Elephant Temple - Score Bubble 7', LEVEL, Kind.SCORE, uid=16709),
    LBPLocationData('Elephant Temple - Score Bubble 8', LEVEL, Kind.SCORE, uid=16783),
    LBPLocationData('Elephant Temple - Score Bubble 9', LEVEL, Kind.SCORE, uid=16784),
    LBPLocationData('Elephant Temple - Score Bubble 10', LEVEL, Kind.SCORE, uid=16788),
    LBPLocationData('Elephant Temple - Score Bubble 11', LEVEL, Kind.SCORE, uid=16789),
    LBPLocationData('Elephant Temple - Score Bubble 12', LEVEL, Kind.SCORE, uid=16791),
    LBPLocationData('Elephant Temple - Score Bubble 13', LEVEL, Kind.SCORE, uid=16792),
    LBPLocationData('Elephant Temple - Score Bubble 14', LEVEL, Kind.SCORE, uid=16793),
    LBPLocationData('Elephant Temple - Score Bubble 15', LEVEL, Kind.SCORE, uid=16794),
    LBPLocationData('Elephant Temple - Score Bubble 16', LEVEL, Kind.SCORE, uid=16821),
    LBPLocationData('Elephant Temple - Score Bubble 17', LEVEL, Kind.SCORE, uid=16822),
    LBPLocationData('Elephant Temple - Score Bubble 18', LEVEL, Kind.SCORE, uid=16823),
    LBPLocationData('Elephant Temple - Score Bubble 19', LEVEL, Kind.SCORE, uid=16824),
    LBPLocationData('Elephant Temple - Score Bubble 20', LEVEL, Kind.SCORE, uid=16825),
    LBPLocationData('Elephant Temple - Score Bubble 21', LEVEL, Kind.SCORE, uid=16826),
    LBPLocationData('Elephant Temple - Score Bubble 22', LEVEL, Kind.SCORE, uid=16832),
    LBPLocationData('Elephant Temple - Score Bubble 23', LEVEL, Kind.SCORE, uid=16833),
    LBPLocationData('Elephant Temple - Score Bubble 24', LEVEL, Kind.SCORE, uid=16834),
    LBPLocationData('Elephant Temple - Score Bubble 25', LEVEL, Kind.SCORE, uid=16835),
    LBPLocationData('Elephant Temple - Score Bubble 26', LEVEL, Kind.SCORE, uid=16836),
    LBPLocationData('Elephant Temple - Score Bubble 27', LEVEL, Kind.SCORE, uid=16837),
    LBPLocationData('Elephant Temple - Score Bubble 28', LEVEL, Kind.SCORE, uid=16838),
    LBPLocationData('Elephant Temple - Score Bubble 29', LEVEL, Kind.SCORE, uid=16839),
    LBPLocationData('Elephant Temple - Score Bubble 30', LEVEL, Kind.SCORE, uid=16840),
    LBPLocationData('Elephant Temple - Score Bubble 31', LEVEL, Kind.SCORE, uid=16841),
    LBPLocationData('Elephant Temple - Score Bubble 32', LEVEL, Kind.SCORE, uid=39077),
    LBPLocationData('Elephant Temple - Score Bubble 33', LEVEL, Kind.SCORE, uid=39762),
    LBPLocationData('Elephant Temple - Score Bubble 34', LEVEL, Kind.SCORE, uid=39765),
    LBPLocationData('Elephant Temple - Score Bubble 35', LEVEL, Kind.SCORE, uid=44544),
    LBPLocationData('Elephant Temple - Score Bubble 36', LEVEL, Kind.SCORE, uid=44546),
    LBPLocationData('Elephant Temple - Score Bubble 37', LEVEL, Kind.SCORE, uid=44548),
    LBPLocationData('Elephant Temple - Score Bubble 38', LEVEL, Kind.SCORE, uid=45233),
    LBPLocationData('Elephant Temple - Score Bubble 39', LEVEL, Kind.SCORE, uid=45235),
    LBPLocationData('Elephant Temple - Score Bubble 40', LEVEL, Kind.SCORE, uid=45237),
    LBPLocationData('Elephant Temple - Score Bubble 41', LEVEL, Kind.SCORE, uid=49350),
    LBPLocationData('Elephant Temple - Score Bubble 42', LEVEL, Kind.SCORE, uid=49352),
    LBPLocationData('Elephant Temple - Score Bubble 43', LEVEL, Kind.SCORE, uid=49353),
    LBPLocationData('Elephant Temple - Score Bubble 44', LEVEL, Kind.SCORE, uid=49354),
    LBPLocationData('Elephant Temple - Score Bubble 45', LEVEL, Kind.SCORE, uid=49355),
    LBPLocationData('Elephant Temple - Score Bubble 46', LEVEL, Kind.SCORE, uid=49356),
    LBPLocationData('Elephant Temple - Score Bubble 47', LEVEL, Kind.SCORE, uid=50045),
    LBPLocationData('Elephant Temple - Score Bubble 48', LEVEL, Kind.SCORE, uid=50052),
    LBPLocationData('Elephant Temple - Score Bubble 49', LEVEL, Kind.SCORE, uid=50055),
    LBPLocationData('Elephant Temple - Score Bubble 50', LEVEL, Kind.SCORE, uid=50058),
    LBPLocationData('Elephant Temple - Score Bubble 51', LEVEL, Kind.SCORE, uid=50061),
    LBPLocationData('Elephant Temple - Score Bubble 52', LEVEL, Kind.SCORE, uid=50064),
    LBPLocationData('Elephant Temple - Score Bubble 53', LEVEL, Kind.SCORE, uid=50067),
    LBPLocationData('Elephant Temple - Score Bubble 54', LEVEL, Kind.SCORE, uid=50070),
    LBPLocationData('Elephant Temple - Score Bubble 55', LEVEL, Kind.SCORE, uid=50082),
    LBPLocationData('Elephant Temple - Score Bubble 56', LEVEL, Kind.SCORE, uid=50084),
    LBPLocationData('Elephant Temple - Score Bubble 57', LEVEL, Kind.SCORE, uid=50086),
    LBPLocationData('Elephant Temple - Score Bubble 58', LEVEL, Kind.SCORE, uid=50770),
    LBPLocationData('Elephant Temple - Score Bubble 59', LEVEL, Kind.SCORE, uid=50771),
    LBPLocationData('Elephant Temple - Score Bubble 60', LEVEL, Kind.SCORE, uid=50772),
    LBPLocationData('Elephant Temple - Score Bubble 61', LEVEL, Kind.SCORE, uid=50773),
    LBPLocationData('Elephant Temple - Score Bubble 62', LEVEL, Kind.SCORE, uid=50774),
    LBPLocationData('Elephant Temple - Score Bubble 63', LEVEL, Kind.SCORE, uid=50775),
    LBPLocationData('Elephant Temple - Score Bubble 64', LEVEL, Kind.SCORE, uid=50776),
    LBPLocationData('Elephant Temple - Score Bubble 65', LEVEL, Kind.SCORE, uid=50777),
    LBPLocationData('Elephant Temple - Score Bubble 66', LEVEL, Kind.SCORE, uid=50778),
    LBPLocationData('Elephant Temple - Score Bubble 67', LEVEL, Kind.SCORE, uid=51462),
    LBPLocationData('Elephant Temple - Score Bubble 68', LEVEL, Kind.SCORE, uid=51464),
    LBPLocationData('Elephant Temple - Score Bubble 69', LEVEL, Kind.SCORE, uid=51466),
    LBPLocationData('Elephant Temple - Score Bubble 70', LEVEL, Kind.SCORE, uid=52150),
    LBPLocationData('Elephant Temple - Score Bubble 71', LEVEL, Kind.SCORE, uid=52151),
    LBPLocationData('Elephant Temple - Score Bubble 72', LEVEL, Kind.SCORE, uid=52152),
    LBPLocationData('Elephant Temple - Score Bubble 73', LEVEL, Kind.SCORE, uid=55572),
    LBPLocationData('Elephant Temple - Score Bubble 74', LEVEL, Kind.SCORE, uid=55573),
    LBPLocationData('Elephant Temple - Score Bubble 75', LEVEL, Kind.SCORE, uid=55574),
    LBPLocationData('Elephant Temple - Score Bubble 76', LEVEL, Kind.SCORE, uid=55576),
    LBPLocationData('Elephant Temple - Score Bubble 77', LEVEL, Kind.SCORE, uid=55579),
    LBPLocationData('Elephant Temple - Score Bubble 78', LEVEL, Kind.SCORE, uid=55582),
    LBPLocationData('Elephant Temple - Score Bubble 79', LEVEL, Kind.SCORE, uid=55585),
    LBPLocationData('Elephant Temple - Score Bubble 80', LEVEL, Kind.SCORE, uid=55588),
    LBPLocationData('Elephant Temple - Score Bubble 81', LEVEL, Kind.SCORE, uid=55591),
    LBPLocationData('Elephant Temple - Score Bubble 82', LEVEL, Kind.SCORE, uid=55594),
    LBPLocationData('Elephant Temple - Score Bubble 83', LEVEL, Kind.SCORE, uid=55597),
    LBPLocationData('Elephant Temple - Score Bubble 84', LEVEL, Kind.SCORE, uid=56281),
    LBPLocationData('Elephant Temple - Score Bubble 85', LEVEL, Kind.SCORE, uid=56282),
    LBPLocationData('Elephant Temple - Score Bubble 86', LEVEL, Kind.SCORE, uid=56283),
    LBPLocationData('Elephant Temple - Score Bubble 87', LEVEL, Kind.SCORE, uid=56284),
    LBPLocationData('Elephant Temple - Score Bubble 88', LEVEL, Kind.SCORE, uid=56285),
    LBPLocationData('Elephant Temple - Score Bubble 89', LEVEL, Kind.SCORE, uid=56286),
    LBPLocationData('Elephant Temple - Score Bubble 90', LEVEL, Kind.SCORE, uid=56287),
    LBPLocationData('Elephant Temple - Score Bubble 91', LEVEL, Kind.SCORE, uid=56288),
    LBPLocationData('Elephant Temple - Score Bubble 92', LEVEL, Kind.SCORE, uid=56289),
    LBPLocationData('Elephant Temple - Score Bubble 93', LEVEL, Kind.SCORE, uid=56291),
    LBPLocationData('Elephant Temple - Score Bubble 94', LEVEL, Kind.SCORE, uid=56293),
    LBPLocationData('Elephant Temple - Score Bubble 95', LEVEL, Kind.SCORE, uid=56295),
    LBPLocationData('Elephant Temple - Score Bubble 96', LEVEL, Kind.SCORE, uid=56298),
    LBPLocationData('Elephant Temple - Score Bubble 97', LEVEL, Kind.SCORE, uid=56300),
    LBPLocationData('Elephant Temple - Score Bubble 98', LEVEL, Kind.SCORE, uid=56302),
    LBPLocationData('Elephant Temple - Score Bubble 99', LEVEL, Kind.SCORE, uid=56986),
    LBPLocationData('Elephant Temple - Score Bubble 100', LEVEL, Kind.SCORE, uid=56987),
    LBPLocationData('Elephant Temple - Score Bubble 101', LEVEL, Kind.SCORE, uid=56988),
    LBPLocationData('Elephant Temple - Score Bubble 102', LEVEL, Kind.SCORE, uid=56989),
    LBPLocationData('Elephant Temple - Score Bubble 103', LEVEL, Kind.SCORE, uid=56990),
    LBPLocationData('Elephant Temple - Score Bubble 104', LEVEL, Kind.SCORE, uid=56991),
    LBPLocationData('Elephant Temple - Score Bubble 105', LEVEL, Kind.SCORE, uid=56992),
    LBPLocationData('Elephant Temple - Score Bubble 106', LEVEL, Kind.SCORE, uid=56993),
    LBPLocationData('Elephant Temple - Score Bubble 107', LEVEL, Kind.SCORE, uid=56994),
    LBPLocationData('Elephant Temple - Score Bubble 108', LEVEL, Kind.SCORE, uid=56995),
    LBPLocationData('Elephant Temple - Score Bubble 109', LEVEL, Kind.SCORE, uid=56996),
    LBPLocationData('Elephant Temple - Score Bubble 110', LEVEL, Kind.SCORE, uid=56997),
    LBPLocationData('Elephant Temple - Score Bubble 111', LEVEL, Kind.SCORE, uid=57681),
    LBPLocationData('Elephant Temple - Score Bubble 112', LEVEL, Kind.SCORE, uid=57683),
    LBPLocationData('Elephant Temple - Score Bubble 113', LEVEL, Kind.SCORE, uid=57685),
    LBPLocationData('Elephant Temple - Score Bubble 114', LEVEL, Kind.SCORE, uid=57695),
    LBPLocationData('Elephant Temple - Score Bubble 115', LEVEL, Kind.SCORE, uid=57697),
    LBPLocationData('Elephant Temple - Score Bubble 116', LEVEL, Kind.SCORE, uid=57698),
    LBPLocationData('Elephant Temple - Score Bubble 117', LEVEL, Kind.SCORE, uid=57699),
    LBPLocationData('Elephant Temple - Score Bubble 118', LEVEL, Kind.SCORE, uid=59757),
    LBPLocationData('Elephant Temple - Score Bubble 119', LEVEL, Kind.SCORE, uid=59759),
    LBPLocationData('Elephant Temple - Score Bubble 120', LEVEL, Kind.SCORE, uid=59761),
    LBPLocationData('Elephant Temple - Score Bubble 121', LEVEL, Kind.SCORE, uid=59764),
    LBPLocationData('Elephant Temple - Score Bubble 122', LEVEL, Kind.SCORE, uid=59766),
    LBPLocationData('Elephant Temple - Score Bubble 123', LEVEL, Kind.SCORE, uid=59768),
    LBPLocationData('Elephant Temple - Score Bubble 124', LEVEL, Kind.SCORE, uid=59771),
    LBPLocationData('Elephant Temple - Score Bubble 125', LEVEL, Kind.SCORE, uid=59773),
    LBPLocationData('Elephant Temple - Score Bubble 126', LEVEL, Kind.SCORE, uid=59775),
    LBPLocationData('Elephant Temple - Score Bubble 127', LEVEL, Kind.SCORE, uid=59778),
    LBPLocationData('Elephant Temple - Score Bubble 128', LEVEL, Kind.SCORE, uid=59780),
    LBPLocationData('Elephant Temple - Score Bubble 129', LEVEL, Kind.SCORE, uid=59782),
    LBPLocationData('Elephant Temple - Score Bubble 130', LEVEL, Kind.SCORE, uid=59785),
    LBPLocationData('Elephant Temple - Score Bubble 131', LEVEL, Kind.SCORE, uid=59787),
    LBPLocationData('Elephant Temple - Score Bubble 132', LEVEL, Kind.SCORE, uid=59789),
    LBPLocationData('Elephant Temple - Score Bubble 133', LEVEL, Kind.SCORE, uid=60474),
    LBPLocationData('Elephant Temple - Score Bubble 134', LEVEL, Kind.SCORE, uid=60476),
    LBPLocationData('Elephant Temple - Score Bubble 135', LEVEL, Kind.SCORE, uid=60478),
    LBPLocationData('Elephant Temple - Score Bubble 136', LEVEL, Kind.SCORE, uid=60481),
    LBPLocationData('Elephant Temple - Score Bubble 137', LEVEL, Kind.SCORE, uid=60483),
    LBPLocationData('Elephant Temple - Score Bubble 138', LEVEL, Kind.SCORE, uid=60485),
    LBPLocationData('Elephant Temple - Score Bubble 139', LEVEL, Kind.SCORE, uid=60487),
    LBPLocationData('Elephant Temple - Score Bubble 140', LEVEL, Kind.SCORE, uid=60488),
    LBPLocationData('Elephant Temple - Score Bubble 141', LEVEL, Kind.SCORE, uid=60489),
    LBPLocationData('Elephant Temple - Score Bubble 142', LEVEL, Kind.SCORE, uid=60490),
    LBPLocationData('Elephant Temple - Score Bubble 143', LEVEL, Kind.SCORE, uid=60491),
    LBPLocationData('Elephant Temple - Score Bubble 144', LEVEL, Kind.SCORE, uid=60492),
    LBPLocationData('Elephant Temple - Score Bubble 145', LEVEL, Kind.SCORE, uid=61868),
    LBPLocationData('Elephant Temple - Score Bubble 146', LEVEL, Kind.SCORE, uid=61870),
    LBPLocationData('Elephant Temple - Score Bubble 147', LEVEL, Kind.SCORE, uid=61872),
    LBPLocationData('Elephant Temple - Score Bubble 148', LEVEL, Kind.SCORE, uid=61875),
    LBPLocationData('Elephant Temple - Score Bubble 149', LEVEL, Kind.SCORE, uid=61877),
    LBPLocationData('Elephant Temple - Score Bubble 150', LEVEL, Kind.SCORE, uid=61879),
    LBPLocationData('Elephant Temple - Score Bubble 151', LEVEL, Kind.SCORE, uid=61882),
    LBPLocationData('Elephant Temple - Score Bubble 152', LEVEL, Kind.SCORE, uid=61884),
    LBPLocationData('Elephant Temple - Score Bubble 153', LEVEL, Kind.SCORE, uid=61886),
    LBPLocationData('Elephant Temple - Score Bubble 154', LEVEL, Kind.SCORE, uid=61896),
    LBPLocationData('Elephant Temple - Score Bubble 155', LEVEL, Kind.SCORE, uid=61898),
    LBPLocationData('Elephant Temple - Score Bubble 156', LEVEL, Kind.SCORE, uid=61900),
    LBPLocationData('Elephant Temple - Score Bubble 157', LEVEL, Kind.SCORE, uid=61910),
    LBPLocationData('Elephant Temple - Score Bubble 158', LEVEL, Kind.SCORE, uid=61912),
    LBPLocationData('Elephant Temple - Score Bubble 159', LEVEL, Kind.SCORE, uid=61914),
    LBPLocationData('Elephant Temple - Score Bubble 160', LEVEL, Kind.SCORE, uid=61917),
    LBPLocationData('Elephant Temple - Score Bubble 161', LEVEL, Kind.SCORE, uid=61919),
    LBPLocationData('Elephant Temple - Score Bubble 162', LEVEL, Kind.SCORE, uid=61921),
    LBPLocationData('Elephant Temple - Score Bubble 163', LEVEL, Kind.SCORE, uid=61924),
    LBPLocationData('Elephant Temple - Score Bubble 164', LEVEL, Kind.SCORE, uid=61926),
    LBPLocationData('Elephant Temple - Score Bubble 165', LEVEL, Kind.SCORE, uid=61928),
    LBPLocationData('Elephant Temple - Score Bubble 166', LEVEL, Kind.SCORE, uid=61931),
    LBPLocationData('Elephant Temple - Score Bubble 167', LEVEL, Kind.SCORE, uid=61933),
    LBPLocationData('Elephant Temple - Score Bubble 168', LEVEL, Kind.SCORE, uid=61935),
    LBPLocationData('Elephant Temple - Score Bubble 169', LEVEL, Kind.SCORE, uid=61938),
    LBPLocationData('Elephant Temple - Score Bubble 170', LEVEL, Kind.SCORE, uid=61940),
    LBPLocationData('Elephant Temple - Score Bubble 171', LEVEL, Kind.SCORE, uid=61942),
    LBPLocationData('Elephant Temple - Score Bubble 172', LEVEL, Kind.SCORE, uid=62641),
    LBPLocationData('Elephant Temple - Score Bubble 173', LEVEL, Kind.SCORE, uid=64704),
    LBPLocationData('Elephant Temple - Score Bubble 174', LEVEL, Kind.SCORE, uid=64705),
    LBPLocationData('Elephant Temple - Score Bubble 175', LEVEL, Kind.SCORE, uid=64706),
    LBPLocationData('Elephant Temple - Score Bubble 176', LEVEL, Kind.SCORE, uid=64707),
    LBPLocationData('Elephant Temple - Score Bubble 177', LEVEL, Kind.SCORE, uid=64708),
    LBPLocationData('Elephant Temple - Score Bubble 178', LEVEL, Kind.SCORE, uid=64709),
    LBPLocationData('Elephant Temple - Score Bubble 179', LEVEL, Kind.SCORE, uid=65393),
    LBPLocationData('Elephant Temple - Score Bubble 180', LEVEL, Kind.SCORE, uid=65395),
    LBPLocationData('Elephant Temple - Score Bubble 181', LEVEL, Kind.SCORE, uid=65397),
    LBPLocationData('Elephant Temple - Score Bubble 182', LEVEL, Kind.SCORE, uid=72241),
    LBPLocationData('Elephant Temple - Score Bubble 183', LEVEL, Kind.SCORE, uid=72243),
    LBPLocationData('Elephant Temple - Score Bubble 184', LEVEL, Kind.SCORE, uid=72244),
    LBPLocationData('Elephant Temple - Score Bubble 185', LEVEL, Kind.SCORE, uid=72245),
    LBPLocationData('Elephant Temple - Score Bubble 186', LEVEL, Kind.SCORE, uid=72246),
    LBPLocationData('Elephant Temple - Score Bubble 187', LEVEL, Kind.SCORE, uid=72252),
    LBPLocationData('Elephant Temple - Score Bubble 188', LEVEL, Kind.SCORE, uid=72254),
    LBPLocationData('Elephant Temple - Score Bubble 189', LEVEL, Kind.SCORE, uid=72256),
    LBPLocationData('Elephant Temple - Score Bubble 190', LEVEL, Kind.SCORE, uid=72258),
    LBPLocationData('Elephant Temple - Score Bubble 191', LEVEL, Kind.SCORE, uid=72260),
    LBPLocationData('Elephant Temple - Score Bubble 192', LEVEL, Kind.SCORE, uid=72261),
    LBPLocationData('Elephant Temple - Score Bubble 193', LEVEL, Kind.SCORE, uid=72262),
    LBPLocationData('Elephant Temple - Score Bubble 194', LEVEL, Kind.SCORE, uid=72266),
    LBPLocationData('Elephant Temple - Score Bubble 195', LEVEL, Kind.SCORE, uid=72267),
    LBPLocationData('Elephant Temple - Score Bubble 196', LEVEL, Kind.SCORE, uid=72268),
    LBPLocationData('Elephant Temple - Score Bubble 197', LEVEL, Kind.SCORE, uid=76370),
    LBPLocationData('Elephant Temple - Score Bubble 198', LEVEL, Kind.SCORE, uid=80465),
    LBPLocationData('Elephant Temple - Score Bubble 199', LEVEL, Kind.SCORE, uid=80466),
    LBPLocationData('Elephant Temple - Score Bubble 200', LEVEL, Kind.SCORE, uid=80467),
    LBPLocationData('Elephant Temple - Score Bubble 201', LEVEL, Kind.SCORE, uid=80468),
    LBPLocationData('Elephant Temple - Score Bubble 202', LEVEL, Kind.SCORE, uid=80469),
    LBPLocationData('Elephant Temple - Score Bubble 203', LEVEL, Kind.SCORE, uid=81835),
    LBPLocationData('Elephant Temple - Score Bubble 204', LEVEL, Kind.SCORE, uid=81836),
    LBPLocationData('Elephant Temple - Score Bubble 205', LEVEL, Kind.SCORE, uid=81837),
    LBPLocationData('Elephant Temple - Score Bubble 206', LEVEL, Kind.SCORE, uid=81849),
    LBPLocationData('Elephant Temple - Score Bubble 207', LEVEL, Kind.SCORE, uid=81850),
    LBPLocationData('Elephant Temple - Score Bubble 208', LEVEL, Kind.SCORE, uid=81851),
    LBPLocationData('Elephant Temple - Score Bubble 209', LEVEL, Kind.SCORE, uid=94836),
    LBPLocationData('Elephant Temple - Score Bubble 210', LEVEL, Kind.SCORE, uid=94838),
    LBPLocationData('Elephant Temple - Score Bubble 211', LEVEL, Kind.SCORE, uid=94840),
    LBPLocationData('Elephant Temple - Score Bubble 212', LEVEL, Kind.SCORE, uid=166684),
    LBPLocationData('Elephant Temple - Score Bubble 213', LEVEL, Kind.SCORE, uid=166685),
    LBPLocationData('Elephant Temple - Score Bubble 214', LEVEL, Kind.SCORE, uid=166686),
    LBPLocationData('Elephant Temple - Score Bubble 215', LEVEL, Kind.SCORE, uid=166687),
    LBPLocationData('Elephant Temple - Score Bubble 216', LEVEL, Kind.SCORE, uid=166688),
    LBPLocationData('Elephant Temple - Score Bubble 217', LEVEL, Kind.SCORE, uid=166689),
    LBPLocationData('Elephant Temple - Score Bubble 218', LEVEL, Kind.SCORE, uid=166690),
    LBPLocationData('Elephant Temple - Score Bubble 219', LEVEL, Kind.SCORE, uid=166691),
    LBPLocationData('Elephant Temple - Score Bubble 220', LEVEL, Kind.SCORE, uid=166692),
    LBPLocationData('Elephant Temple - Score Bubble 221', LEVEL, Kind.SCORE, uid=166754),
    LBPLocationData('Elephant Temple - Score Bubble 222', LEVEL, Kind.SCORE, uid=166755),
    LBPLocationData('Elephant Temple - Score Bubble 223', LEVEL, Kind.SCORE, uid=166756),
    LBPLocationData('Elephant Temple - Score Bubble 224', LEVEL, Kind.SCORE, uid=166947),
    LBPLocationData('Elephant Temple - Score Bubble 225', LEVEL, Kind.SCORE, uid=166951),
    LBPLocationData('Elephant Temple - Score Bubble 226', LEVEL, Kind.SCORE, uid=166952),
    LBPLocationData('Elephant Temple - Score Bubble 227', LEVEL, Kind.SCORE, uid=166953),
    LBPLocationData('Elephant Temple - Score Bubble 228', LEVEL, Kind.SCORE, uid=166954),
    LBPLocationData('Elephant Temple - Score Bubble 229', LEVEL, Kind.SCORE, uid=166955),
    LBPLocationData('Elephant Temple - Score Bubble 230', LEVEL, Kind.SCORE, uid=205898),
    LBPLocationData('Elephant Temple - Score Bubble 231', LEVEL, Kind.SCORE, uid=205899),
    LBPLocationData('Elephant Temple - Score Bubble 232', LEVEL, Kind.SCORE, uid=205900),
    LBPLocationData('Elephant Temple - Score Bubble 233', LEVEL, Kind.SCORE, uid=263471),
    LBPLocationData('Elephant Temple - Score Bubble 234', LEVEL, Kind.SCORE, uid=263472),
    LBPLocationData('Elephant Temple - Score Bubble 235', LEVEL, Kind.SCORE, uid=263473),
    LBPLocationData('Elephant Temple - Score Bubble 236', LEVEL, Kind.SCORE, uid=263474),
    LBPLocationData('Elephant Temple - Score Bubble 237', LEVEL, Kind.SCORE, uid=263475),
    LBPLocationData('Elephant Temple - Score Bubble 238', LEVEL, Kind.SCORE, uid=263476),
    LBPLocationData('Elephant Temple - Score Bubble 239', LEVEL, Kind.SCORE, uid=263477),
    LBPLocationData('Elephant Temple - Score Bubble 240', LEVEL, Kind.SCORE, uid=263478),
    LBPLocationData('Elephant Temple - Score Bubble 241', LEVEL, Kind.SCORE, uid=263479),
    LBPLocationData('Elephant Temple - Score Bubble 242', LEVEL, Kind.SCORE, uid=263480),
    LBPLocationData('Elephant Temple - Score Bubble 243', LEVEL, Kind.SCORE, uid=263481),
    LBPLocationData('Elephant Temple - Score Bubble 244', LEVEL, Kind.SCORE, uid=263482),
    LBPLocationData('Elephant Temple - Score Bubble 245', LEVEL, Kind.SCORE, uid=263483),
    LBPLocationData('Elephant Temple - Score Bubble 246', LEVEL, Kind.SCORE, uid=263484),
    LBPLocationData('Elephant Temple - Prize Bubble 1 - Sliding Block Platforms', LEVEL, Kind.PRIZE, uid=87999, plan='g48770'),
    LBPLocationData('Elephant Temple - Prize Bubble 2 - Elephant Head Statue', LEVEL, Kind.PRIZE, uid=88000, plan='g50734'),
    LBPLocationData('Elephant Temple - Prize Bubble 3 - Stone', LEVEL, Kind.PRIZE, uid=88685, plan='g31958'),
    LBPLocationData('Elephant Temple - Prize Bubble 4 - Large Wave Platform', LEVEL, Kind.PRIZE, uid=88686, plan='g48777'),
    LBPLocationData('Elephant Temple - Prize Bubble 5 - Green Fabric', LEVEL, Kind.PRIZE, uid=89369, plan='g31954'),
    LBPLocationData('Elephant Temple - Prize Bubble 6 - Mechanical Stone Elephant', LEVEL, Kind.PRIZE, uid=90736, plan='g48778'),
    LBPLocationData('Elephant Temple - Prize Bubble 7 - Blue Wood', LEVEL, Kind.PRIZE, uid=90737, plan='g41597'),
    LBPLocationData('Elephant Temple - Prize Bubble 8 - Temple Stone', LEVEL, Kind.PRIZE, uid=96898, plan='g34602'),
    LBPLocationData('Elephant Temple - Prize Bubble 9 - Puzzle Platform', LEVEL, Kind.PRIZE, uid=98949, plan='g48772'),
    LBPLocationData('Elephant Temple - Prize Bubble 10 - Elephant Mosaic', LEVEL, Kind.PRIZE, uid=98950, plan='g31920'),
    LBPLocationData('Elephant Temple - Prize Bubble 11 - Emerald Jewel', LEVEL, Kind.PRIZE, uid=166749, plan='g31915', players=2),
    LBPLocationData('Elephant Temple - Prize Bubble 12 - Ruby Jewel', LEVEL, Kind.PRIZE, uid=166750, plan='g31918', players=2),
    LBPLocationData('Elephant Temple - Prize Bubble 13 - Green Fabric Star', LEVEL, Kind.PRIZE, uid=166751, plan='g31921', players=2),
    LBPLocationData('Elephant Temple - Prize Bubble 14 - Tiger Pattern', LEVEL, Kind.PRIZE, uid=166877, plan='g31940', rule=Has('Blue Elephant')),
    LBPLocationData('Elephant Temple - Prize Bubble 15 - Oscillating Platform', LEVEL, Kind.PRIZE, uid=166929, plan='g48775'),
    LBPLocationData('Elephant Temple - Prize Bubble 16 - Crown', LEVEL, Kind.PRIZE, uid=182626, plan='g31927', rule=Has('Blue Elephant')),
    LBPLocationData('Elephant Temple - Prize Bubble 17 - Jewel Crown Motif', LEVEL, Kind.PRIZE, uid=182627, plan='g31928', rule=Has('Blue Elephant')),
    LBPLocationData('Elephant Temple - Prize Bubble 18 - Stone Elephant', LEVEL, Kind.PRIZE, uid=183273, plan='g47927'),
    LBPLocationData('Elephant Temple - Prize Bubble 19 - Extendable Stairs', LEVEL, Kind.PRIZE, uid=183920, plan='g48771'),
    LBPLocationData('Elephant Temple - Prize Bubble 20 - Straight Cobra Body', LEVEL, Kind.PRIZE, uid=192954, plan='g31925'),
    LBPLocationData('Elephant Temple - Prize Bubble 21 - Latticed Stone', LEVEL, Kind.PRIZE, uid=193600, plan='g31953'),
    LBPLocationData('Elephant Temple - Prize Bubble 22 - Silk Pattern', LEVEL, Kind.PRIZE, uid=193601, plan='g31955'),
    LBPLocationData('Elephant Temple - Prize Bubble 23 - Gold Sequin Fabric', LEVEL, Kind.PRIZE, uid=193602, plan='g31957'),
    LBPLocationData('Elephant Temple - Prize Bubble 24 - Pink Elephant', LEVEL, Kind.PRIZE, uid=198771, plan='g31931', rule=Has('Monkey')),
    LBPLocationData('Elephant Temple - Prize Bubble 25 - Brown Carpet', LEVEL, Kind.PRIZE, uid=198773, plan='g32530', rule=Has('Monkey')),
    LBPLocationData('Elephant Temple - Prize Bubble 26 - Brown Burlap', LEVEL, Kind.PRIZE, uid=198774, plan='g32519', rule=Has('Monkey')),
    LBPLocationData('Elephant Temple - Prize Bubble 27 - Mini Sackboy™', LEVEL, Kind.PRIZE, uid=198781, plan='g34447', players=2),
    LBPLocationData('Elephant Temple - Prize Bubble 28 - Short Sleeved Shirt', LEVEL, Kind.PRIZE, uid=198782, plan='g39760', players=2),
    LBPLocationData('Elephant Temple - Prize Bubble 29 - Bollywood Collage', LEVEL, Kind.PRIZE, uid=199435, plan='g31956'),
    LBPLocationData('Elephant Temple - Prize Bubble 30 - Green Star', LEVEL, Kind.PRIZE, uid=200728, plan='g51319'),
    LBPLocationData('Elephant Temple - Prize Bubble 31 - Double Oscillating Platform', LEVEL, Kind.PRIZE, uid=237545, plan='g48776'),
    LBPLocationData('Elephant Temple - Prize Bubble 32 - Gold Metal', LEVEL, Kind.PRIZE, uid=249832, plan='g34601'),
    LBPLocationData('Elephant Temple - Prize Bubble 33 - Monkey', LEVEL, Kind.PRIZE, uid=249833, plan='g31937'),
    LBPLocationData('Elephant Temple - Prize Bubble 34 - Crystal Earring', LEVEL, Kind.PRIZE, uid=249836, plan='g51320'),
    LBPLocationData('Elephant Temple - Prize Bubble 35 - Five Section Wave Platform', LEVEL, Kind.PRIZE, uid=266748, plan='g48768'),
    LBPLocationData('Elephant Temple - Prize Bubble 36 - Six Section Wave Platform', LEVEL, Kind.PRIZE, uid=266749, plan='g48769'),
    LBPLocationData('Elephant Temple - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Elephant Temple - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('Elephant Temple - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('Elephant Temple - Completion Reward 1 - Life Ring', LEVEL, Kind.REWARD, plan='g51057', condition=Kind.COMPLETE),
    LBPLocationData('Elephant Temple - Completion Reward 2 - White Knit', LEVEL, Kind.REWARD, plan='g32524', condition=Kind.COMPLETE),
    LBPLocationData('Elephant Temple - All Prizes Reward 1 - Costumes Concept with Frame', LEVEL, Kind.REWARD, plan='g52817', condition=Kind.ALL_PRIZES),
    LBPLocationData('Elephant Temple - All Prizes Reward 2 - Copyright Costumes Concept', LEVEL, Kind.REWARD, plan='g52746', condition=Kind.ALL_PRIZES),
    LBPLocationData('Elephant Temple - Ace Reward 1 - Chicken Tail', LEVEL, Kind.REWARD, plan='g32393', condition=Kind.ACE),
    LBPLocationData('Elephant Temple - Sticker Switch 1 - Blue Elephant', LEVEL, Kind.STICKER_SWITCH, uid=166892, plan='g31933'),
    LBPLocationData('Elephant Temple - Sticker Switch 2 - Tiger', LEVEL, Kind.STICKER_SWITCH, uid=166945, plan='g31932'),
    LBPLocationData('Elephant Temple - Sticker Switch 3 - Monkey', LEVEL, Kind.STICKER_SWITCH, uid=166962, plan='g31937'),
    LBPLocationData('Elephant Temple - Key 1', LEVEL, Kind.KEY, uid=102375, target_slot='SlotID{DEVELOPER, 43150}'),
    LBPLocationData('Elephant Temple - Key 2', LEVEL, Kind.KEY, uid=163785, target_slot='SlotID{DEVELOPER, 31076}'),
)
