from rule_builder.rules import Has

from ..model import Kind, LBPLocationData

LEVEL = 'g20357'

LOCATIONS = (
    LBPLocationData('Endurance Dojo - Score Bubble 1', LEVEL, Kind.SCORE, uid=23934),
    LBPLocationData('Endurance Dojo - Score Bubble 2', LEVEL, Kind.SCORE, uid=23940),
    LBPLocationData('Endurance Dojo - Score Bubble 3', LEVEL, Kind.SCORE, uid=23942),
    LBPLocationData('Endurance Dojo - Score Bubble 4', LEVEL, Kind.SCORE, uid=27703),
    LBPLocationData('Endurance Dojo - Score Bubble 5', LEVEL, Kind.SCORE, uid=27704),
    LBPLocationData('Endurance Dojo - Score Bubble 6', LEVEL, Kind.SCORE, uid=27705),
    LBPLocationData('Endurance Dojo - Score Bubble 7', LEVEL, Kind.SCORE, uid=27706),
    LBPLocationData('Endurance Dojo - Score Bubble 8', LEVEL, Kind.SCORE, uid=27707),
    LBPLocationData('Endurance Dojo - Score Bubble 9', LEVEL, Kind.SCORE, uid=27708),
    LBPLocationData('Endurance Dojo - Score Bubble 10', LEVEL, Kind.SCORE, uid=27712),
    LBPLocationData('Endurance Dojo - Score Bubble 11', LEVEL, Kind.SCORE, uid=27713),
    LBPLocationData('Endurance Dojo - Score Bubble 12', LEVEL, Kind.SCORE, uid=27714),
    LBPLocationData('Endurance Dojo - Score Bubble 13', LEVEL, Kind.SCORE, uid=30695),
    LBPLocationData('Endurance Dojo - Score Bubble 14', LEVEL, Kind.SCORE, uid=30696),
    LBPLocationData('Endurance Dojo - Score Bubble 15', LEVEL, Kind.SCORE, uid=30697),
    LBPLocationData('Endurance Dojo - Score Bubble 16', LEVEL, Kind.SCORE, uid=31502),
    LBPLocationData('Endurance Dojo - Score Bubble 17', LEVEL, Kind.SCORE, uid=31503),
    LBPLocationData('Endurance Dojo - Score Bubble 18', LEVEL, Kind.SCORE, uid=31504),
    LBPLocationData('Endurance Dojo - Score Bubble 19', LEVEL, Kind.SCORE, uid=31505),
    LBPLocationData('Endurance Dojo - Score Bubble 20', LEVEL, Kind.SCORE, uid=31506),
    LBPLocationData('Endurance Dojo - Score Bubble 21', LEVEL, Kind.SCORE, uid=31507),
    LBPLocationData('Endurance Dojo - Score Bubble 22', LEVEL, Kind.SCORE, uid=38705),
    LBPLocationData('Endurance Dojo - Score Bubble 23', LEVEL, Kind.SCORE, uid=38706),
    LBPLocationData('Endurance Dojo - Score Bubble 24', LEVEL, Kind.SCORE, uid=38707),
    LBPLocationData('Endurance Dojo - Score Bubble 25', LEVEL, Kind.SCORE, uid=38708),
    LBPLocationData('Endurance Dojo - Score Bubble 26', LEVEL, Kind.SCORE, uid=38709),
    LBPLocationData('Endurance Dojo - Score Bubble 27', LEVEL, Kind.SCORE, uid=38710),
    LBPLocationData('Endurance Dojo - Score Bubble 28', LEVEL, Kind.SCORE, uid=40193),
    LBPLocationData('Endurance Dojo - Score Bubble 29', LEVEL, Kind.SCORE, uid=40194),
    LBPLocationData('Endurance Dojo - Score Bubble 30', LEVEL, Kind.SCORE, uid=40195),
    LBPLocationData('Endurance Dojo - Score Bubble 31', LEVEL, Kind.SCORE, uid=40697),
    LBPLocationData('Endurance Dojo - Score Bubble 32', LEVEL, Kind.SCORE, uid=40698),
    LBPLocationData('Endurance Dojo - Score Bubble 33', LEVEL, Kind.SCORE, uid=40699),
    LBPLocationData('Endurance Dojo - Score Bubble 34', LEVEL, Kind.SCORE, uid=48650),
    LBPLocationData('Endurance Dojo - Score Bubble 35', LEVEL, Kind.SCORE, uid=48651),
    LBPLocationData('Endurance Dojo - Score Bubble 36', LEVEL, Kind.SCORE, uid=49401),
    LBPLocationData('Endurance Dojo - Score Bubble 37', LEVEL, Kind.SCORE, uid=49402),
    LBPLocationData('Endurance Dojo - Score Bubble 38', LEVEL, Kind.SCORE, uid=49403),
    LBPLocationData('Endurance Dojo - Score Bubble 39', LEVEL, Kind.SCORE, uid=65064),
    LBPLocationData('Endurance Dojo - Score Bubble 40', LEVEL, Kind.SCORE, uid=65065),
    LBPLocationData('Endurance Dojo - Score Bubble 41', LEVEL, Kind.SCORE, uid=65066),
    LBPLocationData('Endurance Dojo - Score Bubble 42', LEVEL, Kind.SCORE, uid=76730),
    LBPLocationData('Endurance Dojo - Score Bubble 43', LEVEL, Kind.SCORE, uid=76731),
    LBPLocationData('Endurance Dojo - Score Bubble 44', LEVEL, Kind.SCORE, uid=76732),
    LBPLocationData('Endurance Dojo - Score Bubble 45', LEVEL, Kind.SCORE, uid=79494),
    LBPLocationData('Endurance Dojo - Score Bubble 46', LEVEL, Kind.SCORE, uid=79495),
    LBPLocationData('Endurance Dojo - Score Bubble 47', LEVEL, Kind.SCORE, uid=79496),
    LBPLocationData('Endurance Dojo - Score Bubble 48', LEVEL, Kind.SCORE, uid=79497),
    LBPLocationData('Endurance Dojo - Score Bubble 49', LEVEL, Kind.SCORE, uid=79498),
    LBPLocationData('Endurance Dojo - Score Bubble 50', LEVEL, Kind.SCORE, uid=79499),
    LBPLocationData('Endurance Dojo - Score Bubble 51', LEVEL, Kind.SCORE, uid=79500),
    LBPLocationData('Endurance Dojo - Score Bubble 52', LEVEL, Kind.SCORE, uid=79501),
    LBPLocationData('Endurance Dojo - Score Bubble 53', LEVEL, Kind.SCORE, uid=79502),
    LBPLocationData('Endurance Dojo - Score Bubble 54', LEVEL, Kind.SCORE, uid=79503),
    LBPLocationData('Endurance Dojo - Score Bubble 55', LEVEL, Kind.SCORE, uid=79504),
    LBPLocationData('Endurance Dojo - Score Bubble 56', LEVEL, Kind.SCORE, uid=79506),
    LBPLocationData('Endurance Dojo - Score Bubble 57', LEVEL, Kind.SCORE, uid=79507),
    LBPLocationData('Endurance Dojo - Score Bubble 58', LEVEL, Kind.SCORE, uid=79508),
    LBPLocationData('Endurance Dojo - Score Bubble 59', LEVEL, Kind.SCORE, uid=79509),
    LBPLocationData('Endurance Dojo - Score Bubble 60', LEVEL, Kind.SCORE, uid=79510),
    LBPLocationData('Endurance Dojo - Score Bubble 61', LEVEL, Kind.SCORE, uid=79511),
    LBPLocationData('Endurance Dojo - Score Bubble 62', LEVEL, Kind.SCORE, uid=79512),
    LBPLocationData('Endurance Dojo - Score Bubble 63', LEVEL, Kind.SCORE, uid=79513),
    LBPLocationData('Endurance Dojo - Score Bubble 64', LEVEL, Kind.SCORE, uid=79514),
    LBPLocationData('Endurance Dojo - Score Bubble 65', LEVEL, Kind.SCORE, uid=79515),
    LBPLocationData('Endurance Dojo - Score Bubble 66', LEVEL, Kind.SCORE, uid=79516),
    LBPLocationData('Endurance Dojo - Score Bubble 67', LEVEL, Kind.SCORE, uid=84874),
    LBPLocationData('Endurance Dojo - Score Bubble 68', LEVEL, Kind.SCORE, uid=84875),
    LBPLocationData('Endurance Dojo - Score Bubble 69', LEVEL, Kind.SCORE, uid=84876),
    LBPLocationData('Endurance Dojo - Score Bubble 70', LEVEL, Kind.SCORE, uid=113584),
    LBPLocationData('Endurance Dojo - Score Bubble 71', LEVEL, Kind.SCORE, uid=113585),
    LBPLocationData('Endurance Dojo - Score Bubble 72', LEVEL, Kind.SCORE, uid=113586),
    LBPLocationData('Endurance Dojo - Score Bubble 73', LEVEL, Kind.SCORE, uid=113587),
    LBPLocationData('Endurance Dojo - Score Bubble 74', LEVEL, Kind.SCORE, uid=113588),
    LBPLocationData('Endurance Dojo - Score Bubble 75', LEVEL, Kind.SCORE, uid=113589),
    LBPLocationData('Endurance Dojo - Score Bubble 76', LEVEL, Kind.SCORE, uid=113591),
    LBPLocationData('Endurance Dojo - Score Bubble 77', LEVEL, Kind.SCORE, uid=120073),
    LBPLocationData('Endurance Dojo - Score Bubble 78', LEVEL, Kind.SCORE, uid=120074),
    LBPLocationData('Endurance Dojo - Score Bubble 79', LEVEL, Kind.SCORE, uid=120075),
    LBPLocationData('Endurance Dojo - Score Bubble 80', LEVEL, Kind.SCORE, uid=122097),
    LBPLocationData('Endurance Dojo - Score Bubble 81', LEVEL, Kind.SCORE, uid=122098),
    LBPLocationData('Endurance Dojo - Score Bubble 82', LEVEL, Kind.SCORE, uid=122099),
    LBPLocationData('Endurance Dojo - Score Bubble 83', LEVEL, Kind.SCORE, uid=124096),
    LBPLocationData('Endurance Dojo - Score Bubble 84', LEVEL, Kind.SCORE, uid=124098),
    LBPLocationData('Endurance Dojo - Score Bubble 85', LEVEL, Kind.SCORE, uid=124349),
    LBPLocationData('Endurance Dojo - Score Bubble 86', LEVEL, Kind.SCORE, uid=124351),
    LBPLocationData('Endurance Dojo - Score Bubble 87', LEVEL, Kind.SCORE, uid=126585),
    LBPLocationData('Endurance Dojo - Score Bubble 88', LEVEL, Kind.SCORE, uid=126586),
    LBPLocationData('Endurance Dojo - Score Bubble 89', LEVEL, Kind.SCORE, uid=126587),
    LBPLocationData('Endurance Dojo - Score Bubble 90', LEVEL, Kind.SCORE, uid=126588),
    LBPLocationData('Endurance Dojo - Score Bubble 91', LEVEL, Kind.SCORE, uid=126589),
    LBPLocationData('Endurance Dojo - Score Bubble 92', LEVEL, Kind.SCORE, uid=126590),
    LBPLocationData('Endurance Dojo - Score Bubble 93', LEVEL, Kind.SCORE, uid=128426),
    LBPLocationData('Endurance Dojo - Score Bubble 94', LEVEL, Kind.SCORE, uid=128427),
    LBPLocationData('Endurance Dojo - Score Bubble 95', LEVEL, Kind.SCORE, uid=128428),
    LBPLocationData('Endurance Dojo - Score Bubble 96', LEVEL, Kind.SCORE, uid=128429),
    LBPLocationData('Endurance Dojo - Score Bubble 97', LEVEL, Kind.SCORE, uid=128430),
    LBPLocationData('Endurance Dojo - Score Bubble 98', LEVEL, Kind.SCORE, uid=128431),
    LBPLocationData('Endurance Dojo - Score Bubble 99', LEVEL, Kind.SCORE, uid=131703),
    LBPLocationData('Endurance Dojo - Score Bubble 100', LEVEL, Kind.SCORE, uid=131704),
    LBPLocationData('Endurance Dojo - Score Bubble 101', LEVEL, Kind.SCORE, uid=131705),
    LBPLocationData('Endurance Dojo - Score Bubble 102', LEVEL, Kind.SCORE, uid=132713),
    LBPLocationData('Endurance Dojo - Score Bubble 103', LEVEL, Kind.SCORE, uid=132722),
    LBPLocationData('Endurance Dojo - Score Bubble 104', LEVEL, Kind.SCORE, uid=132731),
    LBPLocationData('Endurance Dojo - Score Bubble 105', LEVEL, Kind.SCORE, uid=132740),
    LBPLocationData('Endurance Dojo - Score Bubble 106', LEVEL, Kind.SCORE, uid=134234),
    LBPLocationData('Endurance Dojo - Score Bubble 107', LEVEL, Kind.SCORE, uid=134236),
    LBPLocationData('Endurance Dojo - Score Bubble 108', LEVEL, Kind.SCORE, uid=134238),
    LBPLocationData('Endurance Dojo - Score Bubble 109', LEVEL, Kind.SCORE, uid=134240),
    LBPLocationData('Endurance Dojo - Score Bubble 110', LEVEL, Kind.SCORE, uid=134242),
    LBPLocationData('Endurance Dojo - Score Bubble 111', LEVEL, Kind.SCORE, uid=134244),
    LBPLocationData('Endurance Dojo - Score Bubble 112', LEVEL, Kind.SCORE, uid=134251),
    LBPLocationData('Endurance Dojo - Score Bubble 113', LEVEL, Kind.SCORE, uid=134252),
    LBPLocationData('Endurance Dojo - Score Bubble 114', LEVEL, Kind.SCORE, uid=134254),
    LBPLocationData('Endurance Dojo - Score Bubble 115', LEVEL, Kind.SCORE, uid=134256),
    LBPLocationData('Endurance Dojo - Score Bubble 116', LEVEL, Kind.SCORE, uid=134259),
    LBPLocationData('Endurance Dojo - Score Bubble 117', LEVEL, Kind.SCORE, uid=134261),
    LBPLocationData('Endurance Dojo - Score Bubble 118', LEVEL, Kind.SCORE, uid=134264),
    LBPLocationData('Endurance Dojo - Score Bubble 119', LEVEL, Kind.SCORE, uid=136522),
    LBPLocationData('Endurance Dojo - Score Bubble 120', LEVEL, Kind.SCORE, uid=136523),
    LBPLocationData('Endurance Dojo - Score Bubble 121', LEVEL, Kind.SCORE, uid=136524),
    LBPLocationData('Endurance Dojo - Score Bubble 122', LEVEL, Kind.SCORE, uid=1359753),
    LBPLocationData('Endurance Dojo - Score Bubble 123', LEVEL, Kind.SCORE, uid=1359759),
    LBPLocationData('Endurance Dojo - Score Bubble 124', LEVEL, Kind.SCORE, uid=1359760),
    LBPLocationData('Endurance Dojo - Score Bubble 125', LEVEL, Kind.SCORE, uid=1359761),
    LBPLocationData('Endurance Dojo - Score Bubble 126', LEVEL, Kind.SCORE, uid=1359762),
    LBPLocationData('Endurance Dojo - Score Bubble 127', LEVEL, Kind.SCORE, uid=1360485),
    LBPLocationData('Endurance Dojo - Score Bubble 128', LEVEL, Kind.SCORE, uid=1360486),
    LBPLocationData('Endurance Dojo - Score Bubble 129', LEVEL, Kind.SCORE, uid=1360487),
    LBPLocationData('Endurance Dojo - Score Bubble 130', LEVEL, Kind.SCORE, uid=1360488),
    LBPLocationData('Endurance Dojo - Score Bubble 131', LEVEL, Kind.SCORE, uid=1360489),
    LBPLocationData('Endurance Dojo - Score Bubble 132', LEVEL, Kind.SCORE, uid=1360490),
    LBPLocationData('Endurance Dojo - Score Bubble 133', LEVEL, Kind.SCORE, uid=1360491),
    LBPLocationData('Endurance Dojo - Score Bubble 134', LEVEL, Kind.SCORE, uid=1360492),
    LBPLocationData('Endurance Dojo - Score Bubble 135', LEVEL, Kind.SCORE, uid=1360493),
    LBPLocationData('Endurance Dojo - Score Bubble 136', LEVEL, Kind.SCORE, uid=1360494),
    LBPLocationData('Endurance Dojo - Score Bubble 137', LEVEL, Kind.SCORE, uid=1360495),
    LBPLocationData('Endurance Dojo - Score Bubble 138', LEVEL, Kind.SCORE, uid=1360496),
    LBPLocationData('Endurance Dojo - Score Bubble 139', LEVEL, Kind.SCORE, uid=1360497),
    LBPLocationData('Endurance Dojo - Score Bubble 140', LEVEL, Kind.SCORE, uid=1360498),
    LBPLocationData('Endurance Dojo - Score Bubble 141', LEVEL, Kind.SCORE, uid=1360499),
    LBPLocationData('Endurance Dojo - Score Bubble 142', LEVEL, Kind.SCORE, uid=1360500),
    LBPLocationData('Endurance Dojo - Score Bubble 143', LEVEL, Kind.SCORE, uid=1360501),
    LBPLocationData('Endurance Dojo - Score Bubble 144', LEVEL, Kind.SCORE, uid=1360502),
    LBPLocationData('Endurance Dojo - Score Bubble 145', LEVEL, Kind.SCORE, uid=1360503),
    LBPLocationData('Endurance Dojo - Score Bubble 146', LEVEL, Kind.SCORE, uid=1360504),
    LBPLocationData('Endurance Dojo - Score Bubble 147', LEVEL, Kind.SCORE, uid=1360505),
    LBPLocationData('Endurance Dojo - Score Bubble 148', LEVEL, Kind.SCORE, uid=1360506),
    LBPLocationData('Endurance Dojo - Score Bubble 149', LEVEL, Kind.SCORE, uid=1360507),
    LBPLocationData('Endurance Dojo - Score Bubble 150', LEVEL, Kind.SCORE, uid=1360508),
    LBPLocationData('Endurance Dojo - Score Bubble 151', LEVEL, Kind.SCORE, uid=1360603),
    LBPLocationData('Endurance Dojo - Score Bubble 152', LEVEL, Kind.SCORE, uid=1360604),
    LBPLocationData('Endurance Dojo - Score Bubble 153', LEVEL, Kind.SCORE, uid=1360605),
    LBPLocationData('Endurance Dojo - Score Bubble 154', LEVEL, Kind.SCORE, uid=1360675),
    LBPLocationData('Endurance Dojo - Score Bubble 155', LEVEL, Kind.SCORE, uid=1360746),
    LBPLocationData('Endurance Dojo - Score Bubble 156', LEVEL, Kind.SCORE, uid=1360747),
    LBPLocationData('Endurance Dojo - Score Bubble 157', LEVEL, Kind.SCORE, uid=1360748),
    LBPLocationData('Endurance Dojo - Score Bubble 158', LEVEL, Kind.SCORE, uid=1360749),
    LBPLocationData('Endurance Dojo - Score Bubble 159', LEVEL, Kind.SCORE, uid=1360750),
    LBPLocationData('Endurance Dojo - Score Bubble 160', LEVEL, Kind.SCORE, uid=1360751),
    LBPLocationData('Endurance Dojo - Score Bubble 161', LEVEL, Kind.SCORE, uid=1360752),
    LBPLocationData('Endurance Dojo - Score Bubble 162', LEVEL, Kind.SCORE, uid=1360753),
    LBPLocationData('Endurance Dojo - Score Bubble 163', LEVEL, Kind.SCORE, uid=1360754),
    LBPLocationData('Endurance Dojo - Score Bubble 164', LEVEL, Kind.SCORE, uid=1360755),
    LBPLocationData('Endurance Dojo - Score Bubble 165', LEVEL, Kind.SCORE, uid=1360756),
    LBPLocationData('Endurance Dojo - Score Bubble 166', LEVEL, Kind.SCORE, uid=1360757),
    LBPLocationData('Endurance Dojo - Score Bubble 167', LEVEL, Kind.SCORE, uid=1360758),
    LBPLocationData('Endurance Dojo - Score Bubble 168', LEVEL, Kind.SCORE, uid=1360759),
    LBPLocationData('Endurance Dojo - Score Bubble 169', LEVEL, Kind.SCORE, uid=1360760),
    LBPLocationData('Endurance Dojo - Score Bubble 170', LEVEL, Kind.SCORE, uid=1360761),
    LBPLocationData('Endurance Dojo - Score Bubble 171', LEVEL, Kind.SCORE, uid=1360762),
    LBPLocationData('Endurance Dojo - Score Bubble 172', LEVEL, Kind.SCORE, uid=1360763),
    LBPLocationData('Endurance Dojo - Score Bubble 173', LEVEL, Kind.SCORE, uid=1360764),
    LBPLocationData('Endurance Dojo - Score Bubble 174', LEVEL, Kind.SCORE, uid=1360765),
    LBPLocationData('Endurance Dojo - Score Bubble 175', LEVEL, Kind.SCORE, uid=1360766),
    LBPLocationData('Endurance Dojo - Score Bubble 176', LEVEL, Kind.SCORE, uid=1360767),
    LBPLocationData('Endurance Dojo - Score Bubble 177', LEVEL, Kind.SCORE, uid=1360768),
    LBPLocationData('Endurance Dojo - Score Bubble 178', LEVEL, Kind.SCORE, uid=1360769),
    LBPLocationData('Endurance Dojo - Score Bubble 179', LEVEL, Kind.SCORE, uid=1360770),
    LBPLocationData('Endurance Dojo - Score Bubble 180', LEVEL, Kind.SCORE, uid=1360771),
    LBPLocationData('Endurance Dojo - Score Bubble 181', LEVEL, Kind.SCORE, uid=1360772),
    LBPLocationData('Endurance Dojo - Score Bubble 182', LEVEL, Kind.SCORE, uid=1360773),
    LBPLocationData('Endurance Dojo - Score Bubble 183', LEVEL, Kind.SCORE, uid=1360774),
    LBPLocationData('Endurance Dojo - Score Bubble 184', LEVEL, Kind.SCORE, uid=1360775),
    LBPLocationData('Endurance Dojo - Score Bubble 185', LEVEL, Kind.SCORE, uid=1361218),
    LBPLocationData('Endurance Dojo - Score Bubble 186', LEVEL, Kind.SCORE, uid=1361410),
    LBPLocationData('Endurance Dojo - Score Bubble 187', LEVEL, Kind.SCORE, uid=1361411),
    LBPLocationData('Endurance Dojo - Score Bubble 188', LEVEL, Kind.SCORE, uid=1361412),
    LBPLocationData('Endurance Dojo - Score Bubble 189', LEVEL, Kind.SCORE, uid=1361522),
    LBPLocationData('Endurance Dojo - Score Bubble 190', LEVEL, Kind.SCORE, uid=1361523),
    LBPLocationData('Endurance Dojo - Score Bubble 191', LEVEL, Kind.SCORE, uid=1361524),
    LBPLocationData('Endurance Dojo - Score Bubble 192', LEVEL, Kind.SCORE, uid=1361525),
    LBPLocationData('Endurance Dojo - Score Bubble 193', LEVEL, Kind.SCORE, uid=1361526),
    LBPLocationData('Endurance Dojo - Score Bubble 194', LEVEL, Kind.SCORE, uid=1361527),
    LBPLocationData('Endurance Dojo - Score Bubble 195', LEVEL, Kind.SCORE, uid=1361528),
    LBPLocationData('Endurance Dojo - Score Bubble 196', LEVEL, Kind.SCORE, uid=1361529),
    LBPLocationData('Endurance Dojo - Score Bubble 197', LEVEL, Kind.SCORE, uid=1361530),
    LBPLocationData('Endurance Dojo - Score Bubble 198', LEVEL, Kind.SCORE, uid=1361531),
    LBPLocationData('Endurance Dojo - Score Bubble 199', LEVEL, Kind.SCORE, uid=1361532),
    LBPLocationData('Endurance Dojo - Score Bubble 200', LEVEL, Kind.SCORE, uid=1361533),
    LBPLocationData('Endurance Dojo - Score Bubble 201', LEVEL, Kind.SCORE, uid=1361548),
    LBPLocationData('Endurance Dojo - Score Bubble 202', LEVEL, Kind.SCORE, uid=1361550),
    LBPLocationData('Endurance Dojo - Score Bubble 203', LEVEL, Kind.SCORE, uid=1361552),
    LBPLocationData('Endurance Dojo - Score Bubble 204', LEVEL, Kind.SCORE, uid=1361554),
    LBPLocationData('Endurance Dojo - Score Bubble 205', LEVEL, Kind.SCORE, uid=1361556),
    LBPLocationData('Endurance Dojo - Score Bubble 206', LEVEL, Kind.SCORE, uid=1361558),
    LBPLocationData('Endurance Dojo - Score Bubble 207', LEVEL, Kind.SCORE, uid=1361563),
    LBPLocationData('Endurance Dojo - Score Bubble 208', LEVEL, Kind.SCORE, uid=1361564),
    LBPLocationData('Endurance Dojo - Score Bubble 209', LEVEL, Kind.SCORE, uid=1361566),
    LBPLocationData('Endurance Dojo - Score Bubble 210', LEVEL, Kind.SCORE, uid=1361568),
    LBPLocationData('Endurance Dojo - Score Bubble 211', LEVEL, Kind.SCORE, uid=1361571),
    LBPLocationData('Endurance Dojo - Score Bubble 212', LEVEL, Kind.SCORE, uid=1361573),
    LBPLocationData('Endurance Dojo - Score Bubble 213', LEVEL, Kind.SCORE, uid=1361576),
    LBPLocationData('Endurance Dojo - Score Bubble 214', LEVEL, Kind.SCORE, uid=1361641),
    LBPLocationData('Endurance Dojo - Score Bubble 215', LEVEL, Kind.SCORE, uid=1361642),
    LBPLocationData('Endurance Dojo - Score Bubble 216', LEVEL, Kind.SCORE, uid=1361643),
    LBPLocationData('Endurance Dojo - Score Bubble 217', LEVEL, Kind.SCORE, uid=1361644),
    LBPLocationData('Endurance Dojo - Score Bubble 218', LEVEL, Kind.SCORE, uid=1361645),
    LBPLocationData('Endurance Dojo - Score Bubble 219', LEVEL, Kind.SCORE, uid=1361646),
    LBPLocationData('Endurance Dojo - Score Bubble 220', LEVEL, Kind.SCORE, uid=1361647),
    LBPLocationData('Endurance Dojo - Score Bubble 221', LEVEL, Kind.SCORE, uid=1361648),
    LBPLocationData('Endurance Dojo - Score Bubble 222', LEVEL, Kind.SCORE, uid=1361649),
    LBPLocationData('Endurance Dojo - Score Bubble 223', LEVEL, Kind.SCORE, uid=1361650),
    LBPLocationData('Endurance Dojo - Score Bubble 224', LEVEL, Kind.SCORE, uid=1361651),
    LBPLocationData('Endurance Dojo - Score Bubble 225', LEVEL, Kind.SCORE, uid=1361652),
    LBPLocationData('Endurance Dojo - Score Bubble 226', LEVEL, Kind.SCORE, uid=1361672),
    LBPLocationData('Endurance Dojo - Score Bubble 227', LEVEL, Kind.SCORE, uid=1361674),
    LBPLocationData('Endurance Dojo - Score Bubble 228', LEVEL, Kind.SCORE, uid=1361679),
    LBPLocationData('Endurance Dojo - Score Bubble 229', LEVEL, Kind.SCORE, uid=1361680),
    LBPLocationData('Endurance Dojo - Score Bubble 230', LEVEL, Kind.SCORE, uid=1361681),
    LBPLocationData('Endurance Dojo - Score Bubble 231', LEVEL, Kind.SCORE, uid=1361690),
    LBPLocationData('Endurance Dojo - Score Bubble 232', LEVEL, Kind.SCORE, uid=1361694),
    LBPLocationData('Endurance Dojo - Score Bubble 233', LEVEL, Kind.SCORE, uid=1361696),
    LBPLocationData('Endurance Dojo - Score Bubble 234', LEVEL, Kind.SCORE, uid=1361697),
    LBPLocationData('Endurance Dojo - Score Bubble 235', LEVEL, Kind.SCORE, uid=1361698),
    LBPLocationData('Endurance Dojo - Score Bubble 236', LEVEL, Kind.SCORE, uid=1361699),
    LBPLocationData('Endurance Dojo - Score Bubble 237', LEVEL, Kind.SCORE, uid=1361700),
    LBPLocationData('Endurance Dojo - Score Bubble 238', LEVEL, Kind.SCORE, uid=1361701),
    LBPLocationData('Endurance Dojo - Score Bubble 239', LEVEL, Kind.SCORE, uid=1361824),
    LBPLocationData('Endurance Dojo - Score Bubble 240', LEVEL, Kind.SCORE, uid=1361825),
    LBPLocationData('Endurance Dojo - Score Bubble 241', LEVEL, Kind.SCORE, uid=1361826),
    LBPLocationData('Endurance Dojo - Score Bubble 242', LEVEL, Kind.SCORE, uid=1361827),
    LBPLocationData('Endurance Dojo - Score Bubble 243', LEVEL, Kind.SCORE, uid=1361828),
    LBPLocationData('Endurance Dojo - Score Bubble 244', LEVEL, Kind.SCORE, uid=1361829),
    LBPLocationData('Endurance Dojo - Score Bubble 245', LEVEL, Kind.SCORE, uid=1361830),
    LBPLocationData('Endurance Dojo - Score Bubble 246', LEVEL, Kind.SCORE, uid=1361831),
    LBPLocationData('Endurance Dojo - Score Bubble 247', LEVEL, Kind.SCORE, uid=1361832),
    LBPLocationData('Endurance Dojo - Score Bubble 248', LEVEL, Kind.SCORE, uid=1406514),
    LBPLocationData('Endurance Dojo - Score Bubble 249', LEVEL, Kind.SCORE, uid=1406515),
    LBPLocationData('Endurance Dojo - Score Bubble 250', LEVEL, Kind.SCORE, uid=1406516),
    LBPLocationData('Endurance Dojo - Score Bubble 251', LEVEL, Kind.SCORE, uid=1442776),
    LBPLocationData('Endurance Dojo - Score Bubble 252', LEVEL, Kind.SCORE, uid=1443147),
    LBPLocationData('Endurance Dojo - Score Bubble 253', LEVEL, Kind.SCORE, uid=1443148),
    LBPLocationData('Endurance Dojo - Score Bubble 254', LEVEL, Kind.SCORE, uid=1444940),
    LBPLocationData('Endurance Dojo - Score Bubble 255', LEVEL, Kind.SCORE, uid=1444941),
    LBPLocationData('Endurance Dojo - Score Bubble 256', LEVEL, Kind.SCORE, uid=1444942),
    LBPLocationData('Endurance Dojo - Score Bubble 257', LEVEL, Kind.SCORE, uid=1444943),
    LBPLocationData('Endurance Dojo - Score Bubble 258', LEVEL, Kind.SCORE, uid=1475242),
    LBPLocationData('Endurance Dojo - Prize Bubble 1 - Wooden Tower Platform', LEVEL, Kind.PRIZE, uid=1359582, plan='g48837'),
    LBPLocationData('Endurance Dojo - Prize Bubble 2 - Tall Prawn Sushi Monster', LEVEL, Kind.PRIZE, uid=1360553, plan='g48848'),
    LBPLocationData('Endurance Dojo - Prize Bubble 3 - Rotating Wheel Platform', LEVEL, Kind.PRIZE, uid=1360950, plan='g51445'),
    LBPLocationData('Endurance Dojo - Prize Bubble 4 - Tilting Kanji Platform', LEVEL, Kind.PRIZE, uid=1361135, plan='g48839'),
    LBPLocationData('Endurance Dojo - Prize Bubble 5 - Piñata Cloth', LEVEL, Kind.PRIZE, uid=1361147, plan='g32733', players=2),
    LBPLocationData('Endurance Dojo - Prize Bubble 6 - Wooden Tower Platform', LEVEL, Kind.PRIZE, uid=1361217, plan='g48838'),
    LBPLocationData('Endurance Dojo - Prize Bubble 7 - Short Fence', LEVEL, Kind.PRIZE, uid=1361855, plan='g48852', rule=Has('Geisha')),
    LBPLocationData('Endurance Dojo - Prize Bubble 8 - Clockwork Box', LEVEL, Kind.PRIZE, uid=1361858, plan='g48857', rule=Has('Japanese Samurai')),
    LBPLocationData('Endurance Dojo - Prize Bubble 9 - Jumbo Flower Button', LEVEL, Kind.PRIZE, uid=1361879, plan='g34397'),
    LBPLocationData('Endurance Dojo - Prize Bubble 10 - Samurai Fan', LEVEL, Kind.PRIZE, uid=1363816, plan='g60325'),
    LBPLocationData('Endurance Dojo - Prize Bubble 11 - Blue Wave Fan', LEVEL, Kind.PRIZE, uid=1363817, plan='g52103'),
    LBPLocationData('Endurance Dojo - Prize Bubble 12 - Salmon Sushi Monster', LEVEL, Kind.PRIZE, uid=1364542, plan='g48849', players=2),
    LBPLocationData('Endurance Dojo - Prize Bubble 13 - Prawn Sushi Monster', LEVEL, Kind.PRIZE, uid=1364905, plan='g48850'),
    LBPLocationData('Endurance Dojo - Prize Bubble 14 - Egg Sushi Monster', LEVEL, Kind.PRIZE, uid=1365268, plan='g48847'),
    LBPLocationData('Endurance Dojo - Prize Bubble 15 - Long Fence', LEVEL, Kind.PRIZE, uid=1365632, plan='g48853', rule=Has('Japanese Samurai')),
    LBPLocationData('Endurance Dojo - Prize Bubble 16 - Domino Platform', LEVEL, Kind.PRIZE, uid=1365995, plan='g48851'),
    LBPLocationData('Endurance Dojo - Prize Bubble 17 - Green & Gold Pattern', LEVEL, Kind.PRIZE, uid=1367444, plan='g38992'),
    LBPLocationData('Endurance Dojo - Prize Bubble 18 - Green Mosaic', LEVEL, Kind.PRIZE, uid=1367807, plan='g38993'),
    LBPLocationData('Endurance Dojo - Prize Bubble 19 - Black & Gold Leaves', LEVEL, Kind.PRIZE, uid=1368170, plan='g38994'),
    LBPLocationData('Endurance Dojo - Prize Bubble 20 - Rough Stone Bricks', LEVEL, Kind.PRIZE, uid=1368533, plan='g34468'),
    LBPLocationData('Endurance Dojo - Prize Bubble 21 - Ninja Scarf', LEVEL, Kind.PRIZE, uid=1368534, plan='g32063'),
    LBPLocationData('Endurance Dojo - Prize Bubble 22 - Ninja Skin', LEVEL, Kind.PRIZE, uid=1368535, plan='g52900'),
    LBPLocationData('Endurance Dojo - Prize Bubble 23 - Wooden Wig', LEVEL, Kind.PRIZE, uid=1368536, plan='g32064'),
    LBPLocationData('Endurance Dojo - Prize Bubble 24 - Red Kimono', LEVEL, Kind.PRIZE, uid=1368537, plan='g32065'),
    LBPLocationData('Endurance Dojo - Prize Bubble 25 - Red Charm', LEVEL, Kind.PRIZE, uid=1369986, plan='g32034'),
    LBPLocationData('Endurance Dojo - Prize Bubble 26 - Gold Charm', LEVEL, Kind.PRIZE, uid=1369987, plan='g32035'),
    LBPLocationData('Endurance Dojo - Prize Bubble 27 - Egg Sushi', LEVEL, Kind.PRIZE, uid=1369988, plan='g32066'),
    LBPLocationData('Endurance Dojo - Prize Bubble 28 - Prawn Sushi', LEVEL, Kind.PRIZE, uid=1369989, plan='g32067'),
    LBPLocationData('Endurance Dojo - Prize Bubble 29 - Salmon Sushi', LEVEL, Kind.PRIZE, uid=1369990, plan='g32068'),
    LBPLocationData('Endurance Dojo - Prize Bubble 30 - Pink Cupcake', LEVEL, Kind.PRIZE, uid=1369991, plan='g51355'),
    LBPLocationData('Endurance Dojo - Prize Bubble 31 - Triple Cone', LEVEL, Kind.PRIZE, uid=1369992, plan='g51357'),
    LBPLocationData('Endurance Dojo - Prize Bubble 32 - Moshi Moshi Logo', LEVEL, Kind.PRIZE, uid=1369993, plan='g51272'),
    LBPLocationData('Endurance Dojo - Prize Bubble 33 - Pink Umbrella Top', LEVEL, Kind.PRIZE, uid=1370356, plan='g51359', players=2),
    LBPLocationData('Endurance Dojo - Prize Bubble 34 - Wooden Cane', LEVEL, Kind.PRIZE, uid=1370357, plan='g51358', players=2),
    LBPLocationData('Endurance Dojo - Prize Bubble 35 - Fried Egg', LEVEL, Kind.PRIZE, uid=1370358, plan='g51353', players=2),
    LBPLocationData('Endurance Dojo - Prize Bubble 36 - Straight Whiskers', LEVEL, Kind.PRIZE, uid=1370359, plan='g48589'),
    LBPLocationData('Endurance Dojo - Prize Bubble 37 - Wavy Beige Motif', LEVEL, Kind.PRIZE, uid=1370360, plan='g48590', rule=Has('Japanese Samurai')),
    LBPLocationData('Endurance Dojo - Prize Bubble 38 - Black & Blue Tie', LEVEL, Kind.PRIZE, uid=1370361, plan='g48587'),
    LBPLocationData('Endurance Dojo - Prize Bubble 39 - Pink Microchip Motif', LEVEL, Kind.PRIZE, uid=1370362, plan='g48588', players=2),
    LBPLocationData('Endurance Dojo - Prize Bubble 40 - Play', LEVEL, Kind.PRIZE, uid=1370363, plan='g51273'),
    LBPLocationData('Endurance Dojo - Prize Bubble 41 - Pink Sundae', LEVEL, Kind.PRIZE, uid=1370724, plan='g51356', rule=Has('Geisha')),
    LBPLocationData('Endurance Dojo - Prize Bubble 42 - Japanese Angry Eye', LEVEL, Kind.PRIZE, uid=1374335, plan='g32037'),
    LBPLocationData('Endurance Dojo - Prize Bubble 43 - Black Japanese Text', LEVEL, Kind.PRIZE, uid=1374696, plan='g32048', rule=Has('Geisha')),
    LBPLocationData('Endurance Dojo - Prize Bubble 44 - Green Flower Button', LEVEL, Kind.PRIZE, uid=1376492, plan='g34393'),
    LBPLocationData('Endurance Dojo - Prize Bubble 45 - Red Flower Button', LEVEL, Kind.PRIZE, uid=1376851, plan='g34406'),
    LBPLocationData('Endurance Dojo - Prize Bubble 46 - Red Lantern', LEVEL, Kind.PRIZE, uid=1379731, plan='g44384'),
    LBPLocationData('Endurance Dojo - Prize Bubble 47 - Grab-Swing Platform', LEVEL, Kind.PRIZE, uid=1380090, plan='g48846'),
    LBPLocationData('Endurance Dojo - Prize Bubble 48 - Short Rocker Platform', LEVEL, Kind.PRIZE, uid=1380091, plan='g47776'),
    LBPLocationData('Endurance Dojo - Prize Bubble 49 - Long Rocker Platform', LEVEL, Kind.PRIZE, uid=1380092, plan='g47774'),
    LBPLocationData('Endurance Dojo - Prize Bubble 50 - Double Rocker Platform', LEVEL, Kind.PRIZE, uid=1380093, plan='g47778'),
    LBPLocationData('Endurance Dojo - Prize Bubble 51 - Quadruple Rocker Platform', LEVEL, Kind.PRIZE, uid=1380094, plan='g47780'),
    LBPLocationData('Endurance Dojo - Prize Bubble 52 - Lemon Graphic', LEVEL, Kind.PRIZE, uid=1380453, plan='g51354'),
    LBPLocationData('Endurance Dojo - Prize Bubble 53 - Coat Hanger', LEVEL, Kind.PRIZE, uid=1380814, plan='g33196'),
    LBPLocationData("Endurance Dojo - Prize Bubble 54 - 'Girly Goodie Two Shoes'", LEVEL, Kind.PRIZE, uid=1381173, plan='g52636'),
    LBPLocationData('Endurance Dojo - Prize Bubble 55 - Geisha', LEVEL, Kind.PRIZE, uid=1428824, plan='g32038'),
    LBPLocationData('Endurance Dojo - Prize Bubble 56 - Daruma San', LEVEL, Kind.PRIZE, uid=1463948, plan='g54761'),
    LBPLocationData('Endurance Dojo - Prize Bubble 57 - Islands IntMusic', LEVEL, Kind.PRIZE, uid=1480709, plan='g33158'),
    LBPLocationData('Endurance Dojo - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Endurance Dojo - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('Endurance Dojo - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('Endurance Dojo - Completion Reward 1 - Dungaree Dress', LEVEL, Kind.REWARD, plan='g40432', condition=Kind.COMPLETE),
    LBPLocationData('Endurance Dojo - Completion Reward 2 - Escaped Convict', LEVEL, Kind.REWARD, plan='g34380', condition=Kind.COMPLETE),
    LBPLocationData('Endurance Dojo - All Prizes Reward 1 - The Islands - Temple Detail Concept with Frame', LEVEL, Kind.REWARD, plan='g52813', condition=Kind.ALL_PRIZES),
    LBPLocationData('Endurance Dojo - All Prizes Reward 2 - The Temple Concept', LEVEL, Kind.REWARD, plan='g52757', condition=Kind.ALL_PRIZES),
    LBPLocationData('Endurance Dojo - All Prizes Reward 3 - Mystical Dragon', LEVEL, Kind.REWARD, plan='g34370', condition=Kind.ALL_PRIZES),
    LBPLocationData('Endurance Dojo - Ace Reward 1 - Japanese Festival Robe', LEVEL, Kind.REWARD, plan='g45276', condition=Kind.ACE),
    LBPLocationData('Endurance Dojo - Sticker Switch 1 - Geisha', LEVEL, Kind.STICKER_SWITCH, uid=1361844, plan='g32038'),
    LBPLocationData('Endurance Dojo - Sticker Switch 2 - Japanese Samurai', LEVEL, Kind.STICKER_SWITCH, uid=1361888, plan='g32036'),
    LBPLocationData('Endurance Dojo - Sticker Switch 3 - Japanese Stork', LEVEL, Kind.STICKER_SWITCH, uid=1444944, plan='g32043'),
    LBPLocationData('Endurance Dojo - Key 1', LEVEL, Kind.KEY, uid=1361906, target_slot='SlotID{DEVELOPER, 27520}'),
)
