from ..model import Kind, LBPLocationData

LEVEL = 'g26374'

LOCATIONS = (
    LBPLocationData('First Steps - Score Bubble 1', LEVEL, Kind.SCORE, uid=15269),
    LBPLocationData('First Steps - Score Bubble 2', LEVEL, Kind.SCORE, uid=15270),
    LBPLocationData('First Steps - Score Bubble 3', LEVEL, Kind.SCORE, uid=15271),
    LBPLocationData('First Steps - Score Bubble 4', LEVEL, Kind.SCORE, uid=15272),
    LBPLocationData('First Steps - Score Bubble 5', LEVEL, Kind.SCORE, uid=15273),
    LBPLocationData('First Steps - Score Bubble 6', LEVEL, Kind.SCORE, uid=15274),
    LBPLocationData('First Steps - Score Bubble 7', LEVEL, Kind.SCORE, uid=15275),
    LBPLocationData('First Steps - Score Bubble 8', LEVEL, Kind.SCORE, uid=15294),
    LBPLocationData('First Steps - Score Bubble 9', LEVEL, Kind.SCORE, uid=15303),
    LBPLocationData('First Steps - Score Bubble 10', LEVEL, Kind.SCORE, uid=15304),
    LBPLocationData('First Steps - Score Bubble 11', LEVEL, Kind.SCORE, uid=15305),
    LBPLocationData('First Steps - Score Bubble 12', LEVEL, Kind.SCORE, uid=15306),
    LBPLocationData('First Steps - Score Bubble 13', LEVEL, Kind.SCORE, uid=15307),
    LBPLocationData('First Steps - Score Bubble 14', LEVEL, Kind.SCORE, uid=15308),
    LBPLocationData('First Steps - Score Bubble 15', LEVEL, Kind.SCORE, uid=15309),
    LBPLocationData('First Steps - Score Bubble 16', LEVEL, Kind.SCORE, uid=15478),
    LBPLocationData('First Steps - Score Bubble 17', LEVEL, Kind.SCORE, uid=15479),
    LBPLocationData('First Steps - Score Bubble 18', LEVEL, Kind.SCORE, uid=15480),
    LBPLocationData('First Steps - Score Bubble 19', LEVEL, Kind.SCORE, uid=15481),
    LBPLocationData('First Steps - Score Bubble 20', LEVEL, Kind.SCORE, uid=15482),
    LBPLocationData('First Steps - Score Bubble 21', LEVEL, Kind.SCORE, uid=15489),
    LBPLocationData('First Steps - Score Bubble 22', LEVEL, Kind.SCORE, uid=15490),
    LBPLocationData('First Steps - Score Bubble 23', LEVEL, Kind.SCORE, uid=15491),
    LBPLocationData('First Steps - Score Bubble 24', LEVEL, Kind.SCORE, uid=311582),
    LBPLocationData('First Steps - Score Bubble 25', LEVEL, Kind.SCORE, uid=311584),
    LBPLocationData('First Steps - Score Bubble 26', LEVEL, Kind.SCORE, uid=311585),
    LBPLocationData('First Steps - Score Bubble 27', LEVEL, Kind.SCORE, uid=311586),
    LBPLocationData('First Steps - Score Bubble 28', LEVEL, Kind.SCORE, uid=318884),
    LBPLocationData('First Steps - Score Bubble 29', LEVEL, Kind.SCORE, uid=318885),
    LBPLocationData('First Steps - Score Bubble 30', LEVEL, Kind.SCORE, uid=318886),
    LBPLocationData('First Steps - Score Bubble 31', LEVEL, Kind.SCORE, uid=318887),
    LBPLocationData('First Steps - Score Bubble 32', LEVEL, Kind.SCORE, uid=318888),
    LBPLocationData('First Steps - Score Bubble 33', LEVEL, Kind.SCORE, uid=318889),
    LBPLocationData('First Steps - Score Bubble 34', LEVEL, Kind.SCORE, uid=318890),
    LBPLocationData('First Steps - Score Bubble 35', LEVEL, Kind.SCORE, uid=321328),
    LBPLocationData('First Steps - Score Bubble 36', LEVEL, Kind.SCORE, uid=321329),
    LBPLocationData('First Steps - Score Bubble 37', LEVEL, Kind.SCORE, uid=321330),
    LBPLocationData('First Steps - Score Bubble 38', LEVEL, Kind.SCORE, uid=321331),
    LBPLocationData('First Steps - Score Bubble 39', LEVEL, Kind.SCORE, uid=321332),
    LBPLocationData('First Steps - Score Bubble 40', LEVEL, Kind.SCORE, uid=321333),
    LBPLocationData('First Steps - Score Bubble 41', LEVEL, Kind.SCORE, uid=321334),
    LBPLocationData('First Steps - Score Bubble 42', LEVEL, Kind.SCORE, uid=321335),
    LBPLocationData('First Steps - Score Bubble 43', LEVEL, Kind.SCORE, uid=351800),
    LBPLocationData('First Steps - Score Bubble 44', LEVEL, Kind.SCORE, uid=351801),
    LBPLocationData('First Steps - Score Bubble 45', LEVEL, Kind.SCORE, uid=351802),
    LBPLocationData('First Steps - Score Bubble 46', LEVEL, Kind.SCORE, uid=351803),
    LBPLocationData('First Steps - Score Bubble 47', LEVEL, Kind.SCORE, uid=351804),
    LBPLocationData('First Steps - Score Bubble 48', LEVEL, Kind.SCORE, uid=351805),
    LBPLocationData('First Steps - Score Bubble 49', LEVEL, Kind.SCORE, uid=354238),
    LBPLocationData('First Steps - Score Bubble 50', LEVEL, Kind.SCORE, uid=354239),
    LBPLocationData('First Steps - Score Bubble 51', LEVEL, Kind.SCORE, uid=354240),
    LBPLocationData('First Steps - Score Bubble 52', LEVEL, Kind.SCORE, uid=354242),
    LBPLocationData('First Steps - Score Bubble 53', LEVEL, Kind.SCORE, uid=354243),
    LBPLocationData('First Steps - Score Bubble 54', LEVEL, Kind.SCORE, uid=354244),
    LBPLocationData('First Steps - Score Bubble 55', LEVEL, Kind.SCORE, uid=567380),
    LBPLocationData('First Steps - Score Bubble 56', LEVEL, Kind.SCORE, uid=567381),
    LBPLocationData('First Steps - Score Bubble 57', LEVEL, Kind.SCORE, uid=567383),
    LBPLocationData('First Steps - Score Bubble 58', LEVEL, Kind.SCORE, uid=567384),
    LBPLocationData('First Steps - Score Bubble 59', LEVEL, Kind.SCORE, uid=567385),
    LBPLocationData('First Steps - Score Bubble 60', LEVEL, Kind.SCORE, uid=567386),
    LBPLocationData('First Steps - Score Bubble 61', LEVEL, Kind.SCORE, uid=567387),
    LBPLocationData('First Steps - Score Bubble 62', LEVEL, Kind.SCORE, uid=567388),
    LBPLocationData('First Steps - Score Bubble 63', LEVEL, Kind.SCORE, uid=567389),
    LBPLocationData('First Steps - Score Bubble 64', LEVEL, Kind.SCORE, uid=650870),
    LBPLocationData('First Steps - Score Bubble 65', LEVEL, Kind.SCORE, uid=675971),
    LBPLocationData('First Steps - Score Bubble 66', LEVEL, Kind.SCORE, uid=675972),
    LBPLocationData('First Steps - Score Bubble 67', LEVEL, Kind.SCORE, uid=675973),
    LBPLocationData('First Steps - Score Bubble 68', LEVEL, Kind.SCORE, uid=675974),
    LBPLocationData('First Steps - Score Bubble 69', LEVEL, Kind.SCORE, uid=675975),
    LBPLocationData('First Steps - Score Bubble 70', LEVEL, Kind.SCORE, uid=675976),
    LBPLocationData('First Steps - Score Bubble 71', LEVEL, Kind.SCORE, uid=675977),
    LBPLocationData('First Steps - Score Bubble 72', LEVEL, Kind.SCORE, uid=675978),
    LBPLocationData('First Steps - Score Bubble 73', LEVEL, Kind.SCORE, uid=675979),
    LBPLocationData('First Steps - Score Bubble 74', LEVEL, Kind.SCORE, uid=675980),
    LBPLocationData('First Steps - Score Bubble 75', LEVEL, Kind.SCORE, uid=702458),
    LBPLocationData('First Steps - Score Bubble 76', LEVEL, Kind.SCORE, uid=736284),
    LBPLocationData('First Steps - Score Bubble 77', LEVEL, Kind.SCORE, uid=736285),
    LBPLocationData('First Steps - Score Bubble 78', LEVEL, Kind.SCORE, uid=736286),
    LBPLocationData('First Steps - Score Bubble 79', LEVEL, Kind.SCORE, uid=736287),
    LBPLocationData('First Steps - Score Bubble 80', LEVEL, Kind.SCORE, uid=736288),
    LBPLocationData('First Steps - Score Bubble 81', LEVEL, Kind.SCORE, uid=1225410),
    LBPLocationData('First Steps - Score Bubble 82', LEVEL, Kind.SCORE, uid=1225411),
    LBPLocationData('First Steps - Score Bubble 83', LEVEL, Kind.SCORE, uid=1225412),
    LBPLocationData('First Steps - Score Bubble 84', LEVEL, Kind.SCORE, uid=1225413),
    LBPLocationData('First Steps - Score Bubble 85', LEVEL, Kind.SCORE, uid=1225414),
    LBPLocationData('First Steps - Score Bubble 86', LEVEL, Kind.SCORE, uid=1225415),
    LBPLocationData('First Steps - Score Bubble 87', LEVEL, Kind.SCORE, uid=1225416),
    LBPLocationData('First Steps - Score Bubble 88', LEVEL, Kind.SCORE, uid=1225417),
    LBPLocationData('First Steps - Score Bubble 89', LEVEL, Kind.SCORE, uid=1225418),
    LBPLocationData('First Steps - Score Bubble 90', LEVEL, Kind.SCORE, uid=1225419),
    LBPLocationData('First Steps - Score Bubble 91', LEVEL, Kind.SCORE, uid=1225420),
    LBPLocationData('First Steps - Score Bubble 92', LEVEL, Kind.SCORE, uid=1236972),
    LBPLocationData('First Steps - Score Bubble 93', LEVEL, Kind.SCORE, uid=1236973),
    LBPLocationData('First Steps - Score Bubble 94', LEVEL, Kind.SCORE, uid=1236974),
    LBPLocationData('First Steps - Score Bubble 95', LEVEL, Kind.SCORE, uid=1249041),
    LBPLocationData('First Steps - Score Bubble 96', LEVEL, Kind.SCORE, uid=1258912),
    LBPLocationData('First Steps - Score Bubble 97', LEVEL, Kind.SCORE, uid=1258913),
    LBPLocationData('First Steps - Score Bubble 98', LEVEL, Kind.SCORE, uid=1258914),
    LBPLocationData('First Steps - Score Bubble 99', LEVEL, Kind.SCORE, uid=1259470),
    LBPLocationData('First Steps - Score Bubble 100', LEVEL, Kind.SCORE, uid=1259471),
    LBPLocationData('First Steps - Score Bubble 101', LEVEL, Kind.SCORE, uid=1259472),
    LBPLocationData('First Steps - Score Bubble 102', LEVEL, Kind.SCORE, uid=1259473),
    LBPLocationData('First Steps - Score Bubble 103', LEVEL, Kind.SCORE, uid=1259474),
    LBPLocationData('First Steps - Score Bubble 104', LEVEL, Kind.SCORE, uid=1259475),
    LBPLocationData('First Steps - Score Bubble 105', LEVEL, Kind.SCORE, uid=1259476),
    LBPLocationData('First Steps - Score Bubble 106', LEVEL, Kind.SCORE, uid=1259477),
    LBPLocationData('First Steps - Score Bubble 107', LEVEL, Kind.SCORE, uid=1259478),
    LBPLocationData('First Steps - Score Bubble 108', LEVEL, Kind.SCORE, uid=1259479),
    LBPLocationData('First Steps - Score Bubble 109', LEVEL, Kind.SCORE, uid=1259480),
    LBPLocationData('First Steps - Score Bubble 110', LEVEL, Kind.SCORE, uid=1259481),
    LBPLocationData('First Steps - Score Bubble 111', LEVEL, Kind.SCORE, uid=1259482),
    LBPLocationData('First Steps - Score Bubble 112', LEVEL, Kind.SCORE, uid=1259483),
    LBPLocationData('First Steps - Score Bubble 113', LEVEL, Kind.SCORE, uid=1259484),
    LBPLocationData('First Steps - Score Bubble 114', LEVEL, Kind.SCORE, uid=1259485),
    LBPLocationData('First Steps - Score Bubble 115', LEVEL, Kind.SCORE, uid=1259486),
    LBPLocationData('First Steps - Score Bubble 116', LEVEL, Kind.SCORE, uid=1259487),
    LBPLocationData('First Steps - Score Bubble 117', LEVEL, Kind.SCORE, uid=1259488),
    LBPLocationData('First Steps - Score Bubble 118', LEVEL, Kind.SCORE, uid=1259489),
    LBPLocationData('First Steps - Score Bubble 119', LEVEL, Kind.SCORE, uid=1259490),
    LBPLocationData('First Steps - Score Bubble 120', LEVEL, Kind.SCORE, uid=1261683),
    LBPLocationData('First Steps - Score Bubble 121', LEVEL, Kind.SCORE, uid=1272131),
    LBPLocationData('First Steps - Score Bubble 122', LEVEL, Kind.SCORE, uid=1272132),
    LBPLocationData('First Steps - Score Bubble 123', LEVEL, Kind.SCORE, uid=1272133),
    LBPLocationData('First Steps - Score Bubble 124', LEVEL, Kind.SCORE, uid=1272134),
    LBPLocationData('First Steps - Score Bubble 125', LEVEL, Kind.SCORE, uid=1272135),
    LBPLocationData('First Steps - Score Bubble 126', LEVEL, Kind.SCORE, uid=1272136),
    LBPLocationData('First Steps - Score Bubble 127', LEVEL, Kind.SCORE, uid=1272137),
    LBPLocationData('First Steps - Score Bubble 128', LEVEL, Kind.SCORE, uid=1272140),
    LBPLocationData('First Steps - Score Bubble 129', LEVEL, Kind.SCORE, uid=1272141),
    LBPLocationData('First Steps - Score Bubble 130', LEVEL, Kind.SCORE, uid=1272142),
    LBPLocationData('First Steps - Score Bubble 131', LEVEL, Kind.SCORE, uid=1288718),
    LBPLocationData('First Steps - Score Bubble 132', LEVEL, Kind.SCORE, uid=1288719),
    LBPLocationData('First Steps - Score Bubble 133', LEVEL, Kind.SCORE, uid=1288720),
    LBPLocationData('First Steps - Score Bubble 134', LEVEL, Kind.SCORE, uid=1288721),
    LBPLocationData('First Steps - Score Bubble 135', LEVEL, Kind.SCORE, uid=1288722),
    LBPLocationData('First Steps - Score Bubble 136', LEVEL, Kind.SCORE, uid=1288723),
    LBPLocationData('First Steps - Score Bubble 137', LEVEL, Kind.SCORE, uid=1308518),
    LBPLocationData('First Steps - Score Bubble 138', LEVEL, Kind.SCORE, uid=1308519),
    LBPLocationData('First Steps - Prize Bubble 1 - Henry Face', LEVEL, Kind.PRIZE, uid=15460, plan='g32150'),
    LBPLocationData('First Steps - Prize Bubble 2 - Rainbow Shoe', LEVEL, Kind.PRIZE, uid=15461, plan='g32641'),
    LBPLocationData('First Steps - Prize Bubble 3 - Round Blue Body', LEVEL, Kind.PRIZE, uid=15462, plan='g32149'),
    LBPLocationData('First Steps - Prize Bubble 4 - Fancy Moustache', LEVEL, Kind.PRIZE, uid=1229812, plan='g32175'),
    LBPLocationData('First Steps - Prize Bubble 5 - Bonnet', LEVEL, Kind.PRIZE, uid=1229813, plan='g32176'),
    LBPLocationData('First Steps - Prize Bubble 6 - Elizabethan Hat', LEVEL, Kind.PRIZE, uid=1229814, plan='g32178'),
    LBPLocationData('First Steps - Prize Bubble 7 - White Ruff', LEVEL, Kind.PRIZE, uid=1229815, plan='g32179'),
    LBPLocationData('First Steps - Prize Bubble 8 - Elizabethan Dress', LEVEL, Kind.PRIZE, uid=1229816, plan='g32180'),
    LBPLocationData('First Steps - Prize Bubble 9 - Elizabethan Doublet', LEVEL, Kind.PRIZE, uid=1229817, plan='g32181'),
    LBPLocationData('First Steps - Prize Bubble 10 - Elizabethan Trousers', LEVEL, Kind.PRIZE, uid=1229818, plan='g32209'),
    LBPLocationData('First Steps - Prize Bubble 11 - Red Star Frame', LEVEL, Kind.PRIZE, uid=1298094, plan='g40786'),
    LBPLocationData('First Steps - Prize Bubble 12 - Mouth Frame', LEVEL, Kind.PRIZE, uid=1298095, plan='g40688'),
    LBPLocationData('First Steps - Prize Bubble 13 - Circle Frame', LEVEL, Kind.PRIZE, uid=1298096, plan='g34441'),
    LBPLocationData('First Steps - Prize Bubble 14 - Square Frame', LEVEL, Kind.PRIZE, uid=1298097, plan='g34438'),
    LBPLocationData('First Steps - Prize Bubble 15 - Body-Outline Frame', LEVEL, Kind.PRIZE, uid=1298098, plan='g40809'),
    LBPLocationData('First Steps - Prize Bubble 16 - Speech Bubble Frame', LEVEL, Kind.PRIZE, uid=1298099, plan='g40687'),
    LBPLocationData('First Steps - Prize Bubble 17 - Black And White Photo Frame', LEVEL, Kind.PRIZE, uid=1298100, plan='g34440'),
    LBPLocationData('First Steps - Prize Bubble 18 - Photo Frame', LEVEL, Kind.PRIZE, uid=1298101, plan='g34439'),
    LBPLocationData('First Steps - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('First Steps - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('First Steps - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('First Steps - Completion Reward 1 - Bunny Ears', LEVEL, Kind.REWARD, plan='g32471', condition=Kind.COMPLETE),
    LBPLocationData('First Steps - Completion Reward 2 - Big Kiss', LEVEL, Kind.REWARD, plan='g32533', condition=Kind.COMPLETE),
    LBPLocationData('First Steps - All Prizes Reward 1 - The Gardens Concept with Frame', LEVEL, Kind.REWARD, plan='g52797', condition=Kind.ALL_PRIZES),
    LBPLocationData('First Steps - All Prizes Reward 2 - The Gardens Concept', LEVEL, Kind.REWARD, plan='g52785', condition=Kind.ALL_PRIZES),
    LBPLocationData('First Steps - Ace Reward 1 - Pirate Hook', LEVEL, Kind.REWARD, plan='g32365', condition=Kind.ACE),
    LBPLocationData('First Steps - Ace Reward 2 - Pirate Eye Patch', LEVEL, Kind.REWARD, plan='g32431', condition=Kind.ACE),
    LBPLocationData('First Steps - Sticker Switch 1 - Round Blue Body', LEVEL, Kind.STICKER_SWITCH, uid=158184, plan='g32149'),
    LBPLocationData('First Steps - Sticker Switch 2 - Rainbow Shoe', LEVEL, Kind.STICKER_SWITCH, uid=158185, plan='g32641'),
    LBPLocationData('First Steps - Sticker Switch 3 - Rainbow Shoe', LEVEL, Kind.STICKER_SWITCH, uid=158186, plan='g32641'),
    LBPLocationData('First Steps - Sticker Switch 4 - Rainbow Shoe', LEVEL, Kind.STICKER_SWITCH, uid=1013514, plan='g32641'),
)
