from rule_builder.rules import Has

from ..model import Kind, LBPLocationData

LEVEL = 'g26375'

LOCATIONS = (
    LBPLocationData('Get a Grip - Score Bubble 1', LEVEL, Kind.SCORE, uid=39206),
    LBPLocationData('Get a Grip - Score Bubble 2', LEVEL, Kind.SCORE, uid=39207),
    LBPLocationData('Get a Grip - Score Bubble 3', LEVEL, Kind.SCORE, uid=39211),
    LBPLocationData('Get a Grip - Score Bubble 4', LEVEL, Kind.SCORE, uid=39212),
    LBPLocationData('Get a Grip - Score Bubble 5', LEVEL, Kind.SCORE, uid=39213),
    LBPLocationData('Get a Grip - Score Bubble 6', LEVEL, Kind.SCORE, uid=39214),
    LBPLocationData('Get a Grip - Score Bubble 7', LEVEL, Kind.SCORE, uid=39215),
    LBPLocationData('Get a Grip - Score Bubble 8', LEVEL, Kind.SCORE, uid=39216),
    LBPLocationData('Get a Grip - Score Bubble 9', LEVEL, Kind.SCORE, uid=154875),
    LBPLocationData('Get a Grip - Score Bubble 10', LEVEL, Kind.SCORE, uid=154876),
    LBPLocationData('Get a Grip - Score Bubble 11', LEVEL, Kind.SCORE, uid=154877),
    LBPLocationData('Get a Grip - Score Bubble 12', LEVEL, Kind.SCORE, uid=154878),
    LBPLocationData('Get a Grip - Score Bubble 13', LEVEL, Kind.SCORE, uid=154879),
    LBPLocationData('Get a Grip - Score Bubble 14', LEVEL, Kind.SCORE, uid=154880),
    LBPLocationData('Get a Grip - Score Bubble 15', LEVEL, Kind.SCORE, uid=522412),
    LBPLocationData('Get a Grip - Score Bubble 16', LEVEL, Kind.SCORE, uid=522416),
    LBPLocationData('Get a Grip - Score Bubble 17', LEVEL, Kind.SCORE, uid=714798),
    LBPLocationData('Get a Grip - Score Bubble 18', LEVEL, Kind.SCORE, uid=714799),
    LBPLocationData('Get a Grip - Score Bubble 19', LEVEL, Kind.SCORE, uid=714801),
    LBPLocationData('Get a Grip - Score Bubble 20', LEVEL, Kind.SCORE, uid=714802),
    LBPLocationData('Get a Grip - Score Bubble 21', LEVEL, Kind.SCORE, uid=714803),
    LBPLocationData('Get a Grip - Score Bubble 22', LEVEL, Kind.SCORE, uid=717246),
    LBPLocationData('Get a Grip - Score Bubble 23', LEVEL, Kind.SCORE, uid=717247),
    LBPLocationData('Get a Grip - Score Bubble 24', LEVEL, Kind.SCORE, uid=717248),
    LBPLocationData('Get a Grip - Score Bubble 25', LEVEL, Kind.SCORE, uid=717249),
    LBPLocationData('Get a Grip - Score Bubble 26', LEVEL, Kind.SCORE, uid=717250),
    LBPLocationData('Get a Grip - Score Bubble 27', LEVEL, Kind.SCORE, uid=726982),
    LBPLocationData('Get a Grip - Score Bubble 28', LEVEL, Kind.SCORE, uid=726983),
    LBPLocationData('Get a Grip - Score Bubble 29', LEVEL, Kind.SCORE, uid=726984),
    LBPLocationData('Get a Grip - Score Bubble 30', LEVEL, Kind.SCORE, uid=726985),
    LBPLocationData('Get a Grip - Score Bubble 31', LEVEL, Kind.SCORE, uid=726986),
    LBPLocationData('Get a Grip - Prize Bubble 1 - Unresolved prize None', LEVEL, Kind.PRIZE, uid=7714),
    LBPLocationData('Get a Grip - Prize Bubble 2 - Wooden Steed', LEVEL, Kind.PRIZE, uid=9520, plan='g32128'),
    LBPLocationData('Get a Grip - Prize Bubble 3 - Pink Flower', LEVEL, Kind.PRIZE, uid=9528, plan='g32204'),
    LBPLocationData('Get a Grip - Prize Bubble 4 - Eye Spring', LEVEL, Kind.PRIZE, uid=9529, plan='g32726'),
    LBPLocationData('Get a Grip - Prize Bubble 5 - Purple Flower', LEVEL, Kind.PRIZE, uid=9530, plan='g32203'),
    LBPLocationData('Get a Grip - Prize Bubble 6 - Orange Flower', LEVEL, Kind.PRIZE, uid=9531, plan='g32205'),
    LBPLocationData('Get a Grip - Prize Bubble 7 - Red Mushroom', LEVEL, Kind.PRIZE, uid=9532, plan='g32130'),
    LBPLocationData('Get a Grip - Prize Bubble 8 - Sun Doodle', LEVEL, Kind.PRIZE, uid=569866, plan='g32134'),
    LBPLocationData('Get a Grip - Prize Bubble 9 - English Rose', LEVEL, Kind.PRIZE, uid=571093, plan='g32153'),
    LBPLocationData('Get a Grip - Prize Bubble 10 - Tudor House', LEVEL, Kind.PRIZE, uid=807341, plan='g32145'),
    LBPLocationData('Get a Grip - Prize Bubble 11 - Tudor View', LEVEL, Kind.PRIZE, uid=807342, plan='g32143'),
    LBPLocationData('Get a Grip - Prize Bubble 12 - Red Flowers', LEVEL, Kind.PRIZE, uid=807346, plan='g32140'),
    LBPLocationData('Get a Grip - Prize Bubble 13 - Orange Flowers', LEVEL, Kind.PRIZE, uid=807347, plan='g32141'),
    LBPLocationData('Get a Grip - Prize Bubble 14 - Victorian Man Sketch', LEVEL, Kind.PRIZE, uid=807896, plan='g32157'),
    LBPLocationData('Get a Grip - Prize Bubble 15 - Green Castle Banner', LEVEL, Kind.PRIZE, uid=807900, plan='g32156'),
    LBPLocationData('Get a Grip - Prize Bubble 16 - Castle Sketch Window', LEVEL, Kind.PRIZE, uid=807901, plan='g32131'),
    LBPLocationData('Get a Grip - Prize Bubble 17 - Blue Monkey', LEVEL, Kind.PRIZE, uid=808451, plan='g51217'),
    LBPLocationData('Get a Grip - Prize Bubble 18 - Grass Rough Doodle', LEVEL, Kind.PRIZE, uid=808452, plan='g32135'),
    LBPLocationData('Get a Grip - Prize Bubble 19 - Golf Club Bottom', LEVEL, Kind.PRIZE, uid=808453, plan='g51381', rule=Has('Tea Pot')),
    LBPLocationData('Get a Grip - Prize Bubble 20 - Noughts & Crosses', LEVEL, Kind.PRIZE, uid=808454, plan='g32132', rule=Has('Tea Pot')),
    LBPLocationData('Get a Grip - Prize Bubble 21 - Moody Cloud', LEVEL, Kind.PRIZE, uid=808455, plan='g51223'),
    LBPLocationData('Get a Grip - Prize Bubble 22 - Black Crown Outline', LEVEL, Kind.PRIZE, uid=808456, plan='g32152'),
    LBPLocationData('Get a Grip - Prize Bubble 23 - Oak Tree', LEVEL, Kind.PRIZE, uid=812302, plan='g48476'),
    LBPLocationData('Get a Grip - Prize Bubble 24 - Large Wooden Steed', LEVEL, Kind.PRIZE, uid=813403, plan='g48556'),
    LBPLocationData('Get a Grip - Prize Bubble 25 - Mushroom Block', LEVEL, Kind.PRIZE, uid=813952, plan='g48474'),
    LBPLocationData('Get a Grip - Prize Bubble 26 - Seesaw', LEVEL, Kind.PRIZE, uid=814501, plan='g48460'),
    LBPLocationData('Get a Grip - Prize Bubble 27 - Hovel', LEVEL, Kind.PRIZE, uid=815050, plan='g51438'),
    LBPLocationData('Get a Grip - Prize Bubble 28 - Smart Hovel', LEVEL, Kind.PRIZE, uid=815599, plan='g51441'),
    LBPLocationData('Get a Grip - Prize Bubble 29 - Tower', LEVEL, Kind.PRIZE, uid=816696, plan='g51440'),
    LBPLocationData('Get a Grip - Prize Bubble 30 - Dark Green Wood', LEVEL, Kind.PRIZE, uid=818893, plan='g32186'),
    LBPLocationData('Get a Grip - Prize Bubble 31 - Orange Floral Fabric', LEVEL, Kind.PRIZE, uid=819444, plan='g32188'),
    LBPLocationData('Get a Grip - Prize Bubble 32 - Grass', LEVEL, Kind.PRIZE, uid=819995, plan='g51151'),
    LBPLocationData('Get a Grip - Prize Bubble 33 - Green Check Denim', LEVEL, Kind.PRIZE, uid=819996, plan='g51148'),
    LBPLocationData('Get a Grip - Prize Bubble 34 - Grey Tweed', LEVEL, Kind.PRIZE, uid=820549, plan='g51149'),
    LBPLocationData('Get a Grip - Prize Bubble 35 - Round Cloud', LEVEL, Kind.PRIZE, uid=832628, plan='g51397'),
    LBPLocationData('Get a Grip - Prize Bubble 36 - Twisty Cloud', LEVEL, Kind.PRIZE, uid=832629, plan='g51398'),
    LBPLocationData('Get a Grip - Prize Bubble 37 - Curly Cloud', LEVEL, Kind.PRIZE, uid=832630, plan='g51401'),
    LBPLocationData('Get a Grip - Prize Bubble 38 - Loose Cloud', LEVEL, Kind.PRIZE, uid=832631, plan='g51402'),
    LBPLocationData('Get a Grip - Prize Bubble 39 - Fancy Cloud', LEVEL, Kind.PRIZE, uid=832632, plan='g51403'),
    LBPLocationData('Get a Grip - Prize Bubble 40 - Small Flag', LEVEL, Kind.PRIZE, uid=834280, plan='g32159'),
    LBPLocationData('Get a Grip - Prize Bubble 41 - Tall Tree', LEVEL, Kind.PRIZE, uid=835380, plan='g32165'),
    LBPLocationData('Get a Grip - Prize Bubble 42 - Snail Shell', LEVEL, Kind.PRIZE, uid=835931, plan='g32160'),
    LBPLocationData('Get a Grip - Prize Bubble 43 - Blue Moon', LEVEL, Kind.PRIZE, uid=840866, plan='g50796'),
    LBPLocationData('Get a Grip - Prize Bubble 44 - Soccer Ball', LEVEL, Kind.PRIZE, uid=908449, plan='g51266'),
    LBPLocationData('Get a Grip - Prize Bubble 45 - Tea Pot', LEVEL, Kind.PRIZE, uid=968129, plan='g32125'),
    LBPLocationData('Get a Grip - Prize Bubble 46 - Gold Tea Cup', LEVEL, Kind.PRIZE, uid=968142, plan='g32220'),
    LBPLocationData('Get a Grip - Prize Bubble 47 - Donkey Tail', LEVEL, Kind.PRIZE, uid=968172, plan='g51260'),
    LBPLocationData('Get a Grip - Prize Bubble 48 - Sticker & Decoration Edit Tool', LEVEL, Kind.PRIZE, uid=973137, plan='g42944'),
    LBPLocationData('Get a Grip - Prize Bubble 49 - Small Wooden Steed', LEVEL, Kind.PRIZE, uid=978955, plan='g48470'),
    LBPLocationData('Get a Grip - Prize Bubble 50 - Green Floral Fabric', LEVEL, Kind.PRIZE, uid=978956, plan='g32190'),
    LBPLocationData('Get a Grip - Prize Bubble 51 - Cheering Crowd', LEVEL, Kind.PRIZE, uid=979503, plan='g56153'),
    LBPLocationData('Get a Grip - Prize Bubble 52 - Leaf Doodle', LEVEL, Kind.PRIZE, uid=983336, plan='g32136'),
    LBPLocationData('Get a Grip - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Get a Grip - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('Get a Grip - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('Get a Grip - Completion Reward 1 - Pink Cat Nose', LEVEL, Kind.REWARD, plan='g32430', condition=Kind.COMPLETE),
    LBPLocationData('Get a Grip - Completion Reward 2 - Happy Eyes', LEVEL, Kind.REWARD, plan='g34376', condition=Kind.COMPLETE),
    LBPLocationData('Get a Grip - All Prizes Reward 1 - The Fairy Tale Concept with Frame', LEVEL, Kind.REWARD, plan='g52798', condition=Kind.ALL_PRIZES),
    LBPLocationData('Get a Grip - All Prizes Reward 2 - The Fairy Tale Concept', LEVEL, Kind.REWARD, plan='g52786', condition=Kind.ALL_PRIZES),
    LBPLocationData('Get a Grip - Ace Reward 1 - Pirate Waistcoat', LEVEL, Kind.REWARD, plan='g32387', condition=Kind.ACE),
    LBPLocationData('Get a Grip - Ace Reward 2 - Pirate Shorts', LEVEL, Kind.REWARD, plan='g32388', condition=Kind.ACE),
    LBPLocationData('Get a Grip - Sticker Switch 1 - Yellow Star', LEVEL, Kind.STICKER_SWITCH, uid=822743, plan='g48682'),
    LBPLocationData('Get a Grip - Sticker Switch 2 - Tea Pot', LEVEL, Kind.STICKER_SWITCH, uid=824392, plan='g32125'),
    LBPLocationData('Get a Grip - Sticker Switch 3 - Donkey Tail', LEVEL, Kind.STICKER_SWITCH, uid=874419, plan='g51260'),
    LBPLocationData('Get a Grip - Sticker Switch 4 - Yellow Star', LEVEL, Kind.STICKER_SWITCH, uid=983884, plan='g48682'),
    LBPLocationData('Get a Grip - Sticker Switch 5 - Yellow Star', LEVEL, Kind.STICKER_SWITCH, uid=983892, plan='g48682'),
    LBPLocationData('Get a Grip - Sticker Switch 6 - Yellow Star', LEVEL, Kind.STICKER_SWITCH, uid=983897, plan='g48682'),
    LBPLocationData('Get a Grip - Sticker Switch 7 - Yellow Star', LEVEL, Kind.STICKER_SWITCH, uid=983902, plan='g48682'),
    LBPLocationData('Get a Grip - Sticker Switch 8 - Yellow Star', LEVEL, Kind.STICKER_SWITCH, uid=983907, plan='g48682'),
    LBPLocationData('Get a Grip - Key 1', LEVEL, Kind.KEY, uid=7714, target_slot='SlotID{DEVELOPER, 26368}'),
)
