from rule_builder.rules import HasAll

from ..model import Kind, LBPLocationData

LEVEL = 'g20356'

LOCATIONS = (
    LBPLocationData("Great Magician's Palace - Score Bubble 1", LEVEL, Kind.SCORE, uid=16838),
    LBPLocationData("Great Magician's Palace - Score Bubble 2", LEVEL, Kind.SCORE, uid=16840),
    LBPLocationData("Great Magician's Palace - Score Bubble 3", LEVEL, Kind.SCORE, uid=16841),
    LBPLocationData("Great Magician's Palace - Score Bubble 4", LEVEL, Kind.SCORE, uid=16842),
    LBPLocationData("Great Magician's Palace - Score Bubble 5", LEVEL, Kind.SCORE, uid=16843),
    LBPLocationData("Great Magician's Palace - Score Bubble 6", LEVEL, Kind.SCORE, uid=16844),
    LBPLocationData("Great Magician's Palace - Score Bubble 7", LEVEL, Kind.SCORE, uid=27068),
    LBPLocationData("Great Magician's Palace - Score Bubble 8", LEVEL, Kind.SCORE, uid=27069),
    LBPLocationData("Great Magician's Palace - Score Bubble 9", LEVEL, Kind.SCORE, uid=27070),
    LBPLocationData("Great Magician's Palace - Score Bubble 10", LEVEL, Kind.SCORE, uid=27071),
    LBPLocationData("Great Magician's Palace - Score Bubble 11", LEVEL, Kind.SCORE, uid=27072),
    LBPLocationData("Great Magician's Palace - Score Bubble 12", LEVEL, Kind.SCORE, uid=27073),
    LBPLocationData("Great Magician's Palace - Score Bubble 13", LEVEL, Kind.SCORE, uid=27080),
    LBPLocationData("Great Magician's Palace - Score Bubble 14", LEVEL, Kind.SCORE, uid=27081),
    LBPLocationData("Great Magician's Palace - Score Bubble 15", LEVEL, Kind.SCORE, uid=27082),
    LBPLocationData("Great Magician's Palace - Score Bubble 16", LEVEL, Kind.SCORE, uid=27083),
    LBPLocationData("Great Magician's Palace - Score Bubble 17", LEVEL, Kind.SCORE, uid=27084),
    LBPLocationData("Great Magician's Palace - Score Bubble 18", LEVEL, Kind.SCORE, uid=27085),
    LBPLocationData("Great Magician's Palace - Score Bubble 19", LEVEL, Kind.SCORE, uid=27086),
    LBPLocationData("Great Magician's Palace - Score Bubble 20", LEVEL, Kind.SCORE, uid=27087),
    LBPLocationData("Great Magician's Palace - Score Bubble 21", LEVEL, Kind.SCORE, uid=27088),
    LBPLocationData("Great Magician's Palace - Score Bubble 22", LEVEL, Kind.SCORE, uid=27089),
    LBPLocationData("Great Magician's Palace - Score Bubble 23", LEVEL, Kind.SCORE, uid=27090),
    LBPLocationData("Great Magician's Palace - Score Bubble 24", LEVEL, Kind.SCORE, uid=27091),
    LBPLocationData("Great Magician's Palace - Score Bubble 25", LEVEL, Kind.SCORE, uid=27111),
    LBPLocationData("Great Magician's Palace - Score Bubble 26", LEVEL, Kind.SCORE, uid=27114),
    LBPLocationData("Great Magician's Palace - Score Bubble 27", LEVEL, Kind.SCORE, uid=27117),
    LBPLocationData("Great Magician's Palace - Score Bubble 28", LEVEL, Kind.SCORE, uid=27120),
    LBPLocationData("Great Magician's Palace - Score Bubble 29", LEVEL, Kind.SCORE, uid=27123),
    LBPLocationData("Great Magician's Palace - Score Bubble 30", LEVEL, Kind.SCORE, uid=27149),
    LBPLocationData("Great Magician's Palace - Score Bubble 31", LEVEL, Kind.SCORE, uid=27150),
    LBPLocationData("Great Magician's Palace - Score Bubble 32", LEVEL, Kind.SCORE, uid=27151),
    LBPLocationData("Great Magician's Palace - Score Bubble 33", LEVEL, Kind.SCORE, uid=27153),
    LBPLocationData("Great Magician's Palace - Score Bubble 34", LEVEL, Kind.SCORE, uid=27154),
    LBPLocationData("Great Magician's Palace - Score Bubble 35", LEVEL, Kind.SCORE, uid=27155),
    LBPLocationData("Great Magician's Palace - Score Bubble 36", LEVEL, Kind.SCORE, uid=27165),
    LBPLocationData("Great Magician's Palace - Score Bubble 37", LEVEL, Kind.SCORE, uid=27166),
    LBPLocationData("Great Magician's Palace - Score Bubble 38", LEVEL, Kind.SCORE, uid=27167),
    LBPLocationData("Great Magician's Palace - Score Bubble 39", LEVEL, Kind.SCORE, uid=27173),
    LBPLocationData("Great Magician's Palace - Score Bubble 40", LEVEL, Kind.SCORE, uid=27174),
    LBPLocationData("Great Magician's Palace - Score Bubble 41", LEVEL, Kind.SCORE, uid=27175),
    LBPLocationData("Great Magician's Palace - Score Bubble 42", LEVEL, Kind.SCORE, uid=27182),
    LBPLocationData("Great Magician's Palace - Score Bubble 43", LEVEL, Kind.SCORE, uid=27183),
    LBPLocationData("Great Magician's Palace - Score Bubble 44", LEVEL, Kind.SCORE, uid=27184),
    LBPLocationData("Great Magician's Palace - Score Bubble 45", LEVEL, Kind.SCORE, uid=27185),
    LBPLocationData("Great Magician's Palace - Score Bubble 46", LEVEL, Kind.SCORE, uid=27186),
    LBPLocationData("Great Magician's Palace - Score Bubble 47", LEVEL, Kind.SCORE, uid=27187),
    LBPLocationData("Great Magician's Palace - Score Bubble 48", LEVEL, Kind.SCORE, uid=27188),
    LBPLocationData("Great Magician's Palace - Score Bubble 49", LEVEL, Kind.SCORE, uid=27189),
    LBPLocationData("Great Magician's Palace - Score Bubble 50", LEVEL, Kind.SCORE, uid=27190),
    LBPLocationData("Great Magician's Palace - Score Bubble 51", LEVEL, Kind.SCORE, uid=27390),
    LBPLocationData("Great Magician's Palace - Score Bubble 52", LEVEL, Kind.SCORE, uid=27391),
    LBPLocationData("Great Magician's Palace - Score Bubble 53", LEVEL, Kind.SCORE, uid=27392),
    LBPLocationData("Great Magician's Palace - Score Bubble 54", LEVEL, Kind.SCORE, uid=27393),
    LBPLocationData("Great Magician's Palace - Score Bubble 55", LEVEL, Kind.SCORE, uid=27394),
    LBPLocationData("Great Magician's Palace - Score Bubble 56", LEVEL, Kind.SCORE, uid=27395),
    LBPLocationData("Great Magician's Palace - Score Bubble 57", LEVEL, Kind.SCORE, uid=161787),
    LBPLocationData("Great Magician's Palace - Score Bubble 58", LEVEL, Kind.SCORE, uid=161788),
    LBPLocationData("Great Magician's Palace - Score Bubble 59", LEVEL, Kind.SCORE, uid=161789),
    LBPLocationData("Great Magician's Palace - Score Bubble 60", LEVEL, Kind.SCORE, uid=161790),
    LBPLocationData("Great Magician's Palace - Score Bubble 61", LEVEL, Kind.SCORE, uid=161791),
    LBPLocationData("Great Magician's Palace - Score Bubble 62", LEVEL, Kind.SCORE, uid=161792),
    LBPLocationData("Great Magician's Palace - Score Bubble 63", LEVEL, Kind.SCORE, uid=239783),
    LBPLocationData("Great Magician's Palace - Score Bubble 64", LEVEL, Kind.SCORE, uid=239784),
    LBPLocationData("Great Magician's Palace - Score Bubble 65", LEVEL, Kind.SCORE, uid=239785),
    LBPLocationData("Great Magician's Palace - Score Bubble 66", LEVEL, Kind.SCORE, uid=239786),
    LBPLocationData("Great Magician's Palace - Score Bubble 67", LEVEL, Kind.SCORE, uid=239787),
    LBPLocationData("Great Magician's Palace - Score Bubble 68", LEVEL, Kind.SCORE, uid=239788),
    LBPLocationData("Great Magician's Palace - Score Bubble 69", LEVEL, Kind.SCORE, uid=239789),
    LBPLocationData("Great Magician's Palace - Score Bubble 70", LEVEL, Kind.SCORE, uid=239790),
    LBPLocationData("Great Magician's Palace - Score Bubble 71", LEVEL, Kind.SCORE, uid=239791),
    LBPLocationData("Great Magician's Palace - Score Bubble 72", LEVEL, Kind.SCORE, uid=239792),
    LBPLocationData("Great Magician's Palace - Score Bubble 73", LEVEL, Kind.SCORE, uid=265651),
    LBPLocationData("Great Magician's Palace - Score Bubble 74", LEVEL, Kind.SCORE, uid=265652),
    LBPLocationData("Great Magician's Palace - Score Bubble 75", LEVEL, Kind.SCORE, uid=265653),
    LBPLocationData("Great Magician's Palace - Score Bubble 76", LEVEL, Kind.SCORE, uid=265654),
    LBPLocationData("Great Magician's Palace - Score Bubble 77", LEVEL, Kind.SCORE, uid=268892),
    LBPLocationData("Great Magician's Palace - Score Bubble 78", LEVEL, Kind.SCORE, uid=268893),
    LBPLocationData("Great Magician's Palace - Score Bubble 79", LEVEL, Kind.SCORE, uid=268894),
    LBPLocationData("Great Magician's Palace - Score Bubble 80", LEVEL, Kind.SCORE, uid=268895),
    LBPLocationData("Great Magician's Palace - Score Bubble 81", LEVEL, Kind.SCORE, uid=268896),
    LBPLocationData("Great Magician's Palace - Score Bubble 82", LEVEL, Kind.SCORE, uid=268897),
    LBPLocationData("Great Magician's Palace - Prize Bubble 1 - Shehnai", LEVEL, Kind.PRIZE, uid=16845, plan='g31960'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 2 - Magic Flower Bridge", LEVEL, Kind.PRIZE, uid=16849, plan='g47980'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 3 - Descending Stone Barrier", LEVEL, Kind.PRIZE, uid=16850, plan='g47981'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 4 - Mechanical Magic Bridge", LEVEL, Kind.PRIZE, uid=16853, plan='g47868'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 5 - Sackboy™ Symbol", LEVEL, Kind.PRIZE, uid=16857, plan='g51332'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 6 - Cobra Tail", LEVEL, Kind.PRIZE, uid=16858, plan='g31926'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 7 - Oval Jewel", LEVEL, Kind.PRIZE, uid=16863, plan='g31962'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 8 - Ornate Arch", LEVEL, Kind.PRIZE, uid=16880, plan='g47974'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 9 - Gold Coin Chain", LEVEL, Kind.PRIZE, uid=23028, plan='g31914', players=2),
    LBPLocationData("Great Magician's Palace - Prize Bubble 10 - Cream Handkerchief", LEVEL, Kind.PRIZE, uid=160416, plan='g31963'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 11 - Golden Sun", LEVEL, Kind.PRIZE, uid=161785, plan='g31919'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 12 - Large Magic Bridge", LEVEL, Kind.PRIZE, uid=166578, plan='g47865'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 13 - Sun & Moon", LEVEL, Kind.PRIZE, uid=166579, plan='g47975'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 14 - Gold Earring", LEVEL, Kind.PRIZE, uid=206041, plan='g31916'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 15 - Small Magic Bridge", LEVEL, Kind.PRIZE, uid=206042, plan='g47863'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 16 - Yellow Motif", LEVEL, Kind.PRIZE, uid=207333, plan='g31922'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 17 - Indian Motif", LEVEL, Kind.PRIZE, uid=207334, plan='g31929'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 18 - Medium Magic Bridge", LEVEL, Kind.PRIZE, uid=207335, plan='g47986'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 19 - Elephant Motif", LEVEL, Kind.PRIZE, uid=207336, plan='g31930'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 20 - Stone Block Emitter", LEVEL, Kind.PRIZE, uid=208627, plan='g47877'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 21 - Great Magician's Magic Box", LEVEL, Kind.PRIZE, uid=209273, plan='g48000'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 22 - Fire Pit Triple Jump", LEVEL, Kind.PRIZE, uid=209919, plan='g56355'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 23 - Grab-Bridge", LEVEL, Kind.PRIZE, uid=209920, plan='g47977'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 24 - Fire Pit  Swing", LEVEL, Kind.PRIZE, uid=209921, plan='g47996'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 25 - Fire Pit Double Jump", LEVEL, Kind.PRIZE, uid=209922, plan='g47998'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 26 - Green Tassels", LEVEL, Kind.PRIZE, uid=213148, plan='g31913'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 27 - Gold Swirly Chain", LEVEL, Kind.PRIZE, uid=213149, plan='g31917'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 28 - Blue Elephant", LEVEL, Kind.PRIZE, uid=216379, plan='g31933'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 29 - Curvy Cobra Body", LEVEL, Kind.PRIZE, uid=217025, plan='g31923'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 30 - Cardboard Mask", LEVEL, Kind.PRIZE, uid=217671, plan='g32487', players=2),
    LBPLocationData("Great Magician's Palace - Prize Bubble 31 - Grey Side Parting Wig", LEVEL, Kind.PRIZE, uid=217672, plan='g32485', players=2),
    LBPLocationData("Great Magician's Palace - Prize Bubble 32 - Cartoon Eyes", LEVEL, Kind.PRIZE, uid=217673, plan='g34377', players=2),
    LBPLocationData("Great Magician's Palace - Prize Bubble 33 - Green Felt", LEVEL, Kind.PRIZE, uid=217674, plan='g34386', rule=HasAll('Cobra Head', 'Cobra Tail', 'Straight Cobra Body')),
    LBPLocationData("Great Magician's Palace - Prize Bubble 34 - Brown Felt", LEVEL, Kind.PRIZE, uid=218324, plan='g32525', rule=HasAll('Cobra Head', 'Cobra Tail', 'Straight Cobra Body')),
    LBPLocationData("Great Magician's Palace - Prize Bubble 35 - Trainers", LEVEL, Kind.PRIZE, uid=218971, plan='g32394', players=2),
    LBPLocationData("Great Magician's Palace - Prize Bubble 36 - Pink Straw", LEVEL, Kind.PRIZE, uid=220973, plan='g33193'),
    LBPLocationData("Great Magician's Palace - Prize Bubble 37 - 'New Delhi Dawn'", LEVEL, Kind.PRIZE, uid=221619, plan='g43829', players=2),
    LBPLocationData("Great Magician's Palace - Prize Bubble 38 - Temples IntMusic", LEVEL, Kind.PRIZE, uid=316062, plan='g34410', rule=HasAll('Cobra Head', 'Cobra Tail', 'Straight Cobra Body')),
    LBPLocationData("Great Magician's Palace - Level Complete", LEVEL, Kind.COMPLETE),
    LBPLocationData("Great Magician's Palace - All Prize Bubbles", LEVEL, Kind.ALL_PRIZES),
    LBPLocationData("Great Magician's Palace - Ace (No Deaths)", LEVEL, Kind.ACE),
    LBPLocationData("Great Magician's Palace - Completion Reward 1 - Green Swimsuit", LEVEL, Kind.REWARD, plan='g32364', condition=Kind.COMPLETE),
    LBPLocationData("Great Magician's Palace - Completion Reward 2 - The Temples", LEVEL, Kind.REWARD, plan='g32025', condition=Kind.COMPLETE),
    LBPLocationData("Great Magician's Palace - All Prizes Reward 1 - Great Magician's Magic Box", LEVEL, Kind.REWARD, plan='g48000', condition=Kind.ALL_PRIZES),
    LBPLocationData("Great Magician's Palace - All Prizes Reward 2 - Craft Cosmos Concept with Frame", LEVEL, Kind.REWARD, plan='g52816', condition=Kind.ALL_PRIZES),
    LBPLocationData("Great Magician's Palace - All Prizes Reward 3 - LittleBigPlanet™ Cosmos Concept", LEVEL, Kind.REWARD, plan='g52745', condition=Kind.ALL_PRIZES),
    LBPLocationData("Great Magician's Palace - Ace Reward 1 - Chicken Wings", LEVEL, Kind.REWARD, plan='g32392', condition=Kind.ACE),
    LBPLocationData("Great Magician's Palace - Sticker Switch 1 - Straight Cobra Body", LEVEL, Kind.STICKER_SWITCH, uid=120832, plan='g31925'),
    LBPLocationData("Great Magician's Palace - Sticker Switch 2 - Straight Cobra Body", LEVEL, Kind.STICKER_SWITCH, uid=120833, plan='g31925'),
    LBPLocationData("Great Magician's Palace - Sticker Switch 3 - Cobra Head", LEVEL, Kind.STICKER_SWITCH, uid=120834, plan='g31924'),
    LBPLocationData("Great Magician's Palace - Sticker Switch 4 - Cobra Tail", LEVEL, Kind.STICKER_SWITCH, uid=120835, plan='g31926'),
    LBPLocationData("Great Magician's Palace - Key 1", LEVEL, Kind.KEY, uid=22341, target_slot='SlotID{DEVELOPER, 42375}'),
)
