from ..model import Kind, LBPLocationData

LEVEL = 'g27485'

LOCATIONS = (
    LBPLocationData('Roller Run - Medium - Score Bubble 1', LEVEL, Kind.SCORE, uid=28464),
    LBPLocationData('Roller Run - Medium - Score Bubble 2', LEVEL, Kind.SCORE, uid=28465),
    LBPLocationData('Roller Run - Medium - Score Bubble 3', LEVEL, Kind.SCORE, uid=28466),
    LBPLocationData('Roller Run - Medium - Score Bubble 4', LEVEL, Kind.SCORE, uid=28467),
    LBPLocationData('Roller Run - Medium - Score Bubble 5', LEVEL, Kind.SCORE, uid=28468),
    LBPLocationData('Roller Run - Medium - Score Bubble 6', LEVEL, Kind.SCORE, uid=28469),
    LBPLocationData('Roller Run - Medium - Score Bubble 7', LEVEL, Kind.SCORE, uid=28470),
    LBPLocationData('Roller Run - Medium - Score Bubble 8', LEVEL, Kind.SCORE, uid=28471),
    LBPLocationData('Roller Run - Medium - Score Bubble 9', LEVEL, Kind.SCORE, uid=28477),
    LBPLocationData('Roller Run - Medium - Score Bubble 10', LEVEL, Kind.SCORE, uid=28478),
    LBPLocationData('Roller Run - Medium - Score Bubble 11', LEVEL, Kind.SCORE, uid=28479),
    LBPLocationData('Roller Run - Medium - Score Bubble 12', LEVEL, Kind.SCORE, uid=28480),
    LBPLocationData('Roller Run - Medium - Score Bubble 13', LEVEL, Kind.SCORE, uid=28481),
    LBPLocationData('Roller Run - Medium - Score Bubble 14', LEVEL, Kind.SCORE, uid=28482),
    LBPLocationData('Roller Run - Medium - Score Bubble 15', LEVEL, Kind.SCORE, uid=28483),
    LBPLocationData('Roller Run - Medium - Score Bubble 16', LEVEL, Kind.SCORE, uid=28484),
    LBPLocationData('Roller Run - Medium - Score Bubble 17', LEVEL, Kind.SCORE, uid=28489),
    LBPLocationData('Roller Run - Medium - Score Bubble 18', LEVEL, Kind.SCORE, uid=28490),
    LBPLocationData('Roller Run - Medium - Score Bubble 19', LEVEL, Kind.SCORE, uid=28491),
    LBPLocationData('Roller Run - Medium - Score Bubble 20', LEVEL, Kind.SCORE, uid=28492),
    LBPLocationData('Roller Run - Medium - Score Bubble 21', LEVEL, Kind.SCORE, uid=28493),
    LBPLocationData('Roller Run - Medium - Score Bubble 22', LEVEL, Kind.SCORE, uid=28494),
    LBPLocationData('Roller Run - Medium - Score Bubble 23', LEVEL, Kind.SCORE, uid=28495),
    LBPLocationData('Roller Run - Medium - Score Bubble 24', LEVEL, Kind.SCORE, uid=28496),
    LBPLocationData('Roller Run - Medium - Score Bubble 25', LEVEL, Kind.SCORE, uid=28501),
    LBPLocationData('Roller Run - Medium - Score Bubble 26', LEVEL, Kind.SCORE, uid=28502),
    LBPLocationData('Roller Run - Medium - Score Bubble 27', LEVEL, Kind.SCORE, uid=28503),
    LBPLocationData('Roller Run - Medium - Score Bubble 28', LEVEL, Kind.SCORE, uid=28504),
    LBPLocationData('Roller Run - Medium - Score Bubble 29', LEVEL, Kind.SCORE, uid=28505),
    LBPLocationData('Roller Run - Medium - Score Bubble 30', LEVEL, Kind.SCORE, uid=28506),
    LBPLocationData('Roller Run - Medium - Score Bubble 31', LEVEL, Kind.SCORE, uid=28507),
    LBPLocationData('Roller Run - Medium - Score Bubble 32', LEVEL, Kind.SCORE, uid=28508),
    LBPLocationData('Roller Run - Medium - Score Bubble 33', LEVEL, Kind.SCORE, uid=31610),
    LBPLocationData('Roller Run - Medium - Score Bubble 34', LEVEL, Kind.SCORE, uid=31611),
    LBPLocationData('Roller Run - Medium - Score Bubble 35', LEVEL, Kind.SCORE, uid=31612),
    LBPLocationData('Roller Run - Medium - Score Bubble 36', LEVEL, Kind.SCORE, uid=31613),
    LBPLocationData('Roller Run - Medium - Score Bubble 37', LEVEL, Kind.SCORE, uid=31614),
    LBPLocationData('Roller Run - Medium - Score Bubble 38', LEVEL, Kind.SCORE, uid=31615),
    LBPLocationData('Roller Run - Medium - Score Bubble 39', LEVEL, Kind.SCORE, uid=31616),
    LBPLocationData('Roller Run - Medium - Score Bubble 40', LEVEL, Kind.SCORE, uid=31617),
    LBPLocationData('Roller Run - Medium - Score Bubble 41', LEVEL, Kind.SCORE, uid=31618),
    LBPLocationData('Roller Run - Medium - Score Bubble 42', LEVEL, Kind.SCORE, uid=31619),
    LBPLocationData('Roller Run - Medium - Score Bubble 43', LEVEL, Kind.SCORE, uid=31620),
    LBPLocationData('Roller Run - Medium - Score Bubble 44', LEVEL, Kind.SCORE, uid=31621),
    LBPLocationData('Roller Run - Medium - Score Bubble 45', LEVEL, Kind.SCORE, uid=31623),
    LBPLocationData('Roller Run - Medium - Score Bubble 46', LEVEL, Kind.SCORE, uid=31626),
    LBPLocationData('Roller Run - Medium - Score Bubble 47', LEVEL, Kind.SCORE, uid=31627),
    LBPLocationData('Roller Run - Medium - Score Bubble 48', LEVEL, Kind.SCORE, uid=31628),
    LBPLocationData('Roller Run - Medium - Score Bubble 49', LEVEL, Kind.SCORE, uid=32400),
    LBPLocationData('Roller Run - Medium - Score Bubble 50', LEVEL, Kind.SCORE, uid=32401),
    LBPLocationData('Roller Run - Medium - Score Bubble 51', LEVEL, Kind.SCORE, uid=32402),
    LBPLocationData('Roller Run - Medium - Score Bubble 52', LEVEL, Kind.SCORE, uid=32403),
    LBPLocationData('Roller Run - Medium - Score Bubble 53', LEVEL, Kind.SCORE, uid=32404),
    LBPLocationData('Roller Run - Medium - Score Bubble 54', LEVEL, Kind.SCORE, uid=32405),
    LBPLocationData('Roller Run - Medium - Score Bubble 55', LEVEL, Kind.SCORE, uid=32406),
    LBPLocationData('Roller Run - Medium - Score Bubble 56', LEVEL, Kind.SCORE, uid=32407),
    LBPLocationData('Roller Run - Medium - Score Bubble 57', LEVEL, Kind.SCORE, uid=34718),
    LBPLocationData('Roller Run - Medium - Score Bubble 58', LEVEL, Kind.SCORE, uid=34719),
    LBPLocationData('Roller Run - Medium - Score Bubble 59', LEVEL, Kind.SCORE, uid=34720),
    LBPLocationData('Roller Run - Medium - Score Bubble 60', LEVEL, Kind.SCORE, uid=34721),
    LBPLocationData('Roller Run - Medium - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Roller Run - Medium - Ace (No Deaths)', LEVEL, Kind.ACE),
)
