from rule_builder.rules import HasAll

from ..model import Kind, LBPLocationData

LEVEL = 'g20358'

LOCATIONS = (
    LBPLocationData("Sensei's Lost Castle - Score Bubble 1", LEVEL, Kind.SCORE, uid=19091),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 2", LEVEL, Kind.SCORE, uid=19095),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 3", LEVEL, Kind.SCORE, uid=19096),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 4", LEVEL, Kind.SCORE, uid=19103),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 5", LEVEL, Kind.SCORE, uid=19394),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 6", LEVEL, Kind.SCORE, uid=19395),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 7", LEVEL, Kind.SCORE, uid=19396),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 8", LEVEL, Kind.SCORE, uid=19397),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 9", LEVEL, Kind.SCORE, uid=19398),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 10", LEVEL, Kind.SCORE, uid=19405),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 11", LEVEL, Kind.SCORE, uid=19406),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 12", LEVEL, Kind.SCORE, uid=19408),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 13", LEVEL, Kind.SCORE, uid=19409),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 14", LEVEL, Kind.SCORE, uid=19410),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 15", LEVEL, Kind.SCORE, uid=19411),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 16", LEVEL, Kind.SCORE, uid=19412),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 17", LEVEL, Kind.SCORE, uid=19413),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 18", LEVEL, Kind.SCORE, uid=19414),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 19", LEVEL, Kind.SCORE, uid=19415),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 20", LEVEL, Kind.SCORE, uid=19416),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 21", LEVEL, Kind.SCORE, uid=19418),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 22", LEVEL, Kind.SCORE, uid=19419),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 23", LEVEL, Kind.SCORE, uid=19420),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 24", LEVEL, Kind.SCORE, uid=19421),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 25", LEVEL, Kind.SCORE, uid=19422),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 26", LEVEL, Kind.SCORE, uid=19423),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 27", LEVEL, Kind.SCORE, uid=19424),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 28", LEVEL, Kind.SCORE, uid=19457),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 29", LEVEL, Kind.SCORE, uid=19458),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 30", LEVEL, Kind.SCORE, uid=19459),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 31", LEVEL, Kind.SCORE, uid=19460),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 32", LEVEL, Kind.SCORE, uid=30271),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 33", LEVEL, Kind.SCORE, uid=30272),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 34", LEVEL, Kind.SCORE, uid=30273),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 35", LEVEL, Kind.SCORE, uid=30274),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 36", LEVEL, Kind.SCORE, uid=30275),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 37", LEVEL, Kind.SCORE, uid=30281),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 38", LEVEL, Kind.SCORE, uid=30282),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 39", LEVEL, Kind.SCORE, uid=30283),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 40", LEVEL, Kind.SCORE, uid=30284),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 41", LEVEL, Kind.SCORE, uid=30285),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 42", LEVEL, Kind.SCORE, uid=30286),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 43", LEVEL, Kind.SCORE, uid=30287),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 44", LEVEL, Kind.SCORE, uid=30288),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 45", LEVEL, Kind.SCORE, uid=30289),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 46", LEVEL, Kind.SCORE, uid=30290),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 47", LEVEL, Kind.SCORE, uid=30300),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 48", LEVEL, Kind.SCORE, uid=133281),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 49", LEVEL, Kind.SCORE, uid=133282),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 50", LEVEL, Kind.SCORE, uid=133283),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 51", LEVEL, Kind.SCORE, uid=133673),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 52", LEVEL, Kind.SCORE, uid=133674),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 53", LEVEL, Kind.SCORE, uid=133675),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 54", LEVEL, Kind.SCORE, uid=134092),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 55", LEVEL, Kind.SCORE, uid=134093),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 56", LEVEL, Kind.SCORE, uid=134094),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 57", LEVEL, Kind.SCORE, uid=134096),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 58", LEVEL, Kind.SCORE, uid=134097),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 59", LEVEL, Kind.SCORE, uid=134098),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 60", LEVEL, Kind.SCORE, uid=134099),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 61", LEVEL, Kind.SCORE, uid=134100),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 62", LEVEL, Kind.SCORE, uid=134101),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 63", LEVEL, Kind.SCORE, uid=134102),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 64", LEVEL, Kind.SCORE, uid=134103),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 65", LEVEL, Kind.SCORE, uid=134104),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 66", LEVEL, Kind.SCORE, uid=134206),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 67", LEVEL, Kind.SCORE, uid=134207),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 68", LEVEL, Kind.SCORE, uid=134208),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 69", LEVEL, Kind.SCORE, uid=134209),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 70", LEVEL, Kind.SCORE, uid=134210),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 71", LEVEL, Kind.SCORE, uid=134211),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 72", LEVEL, Kind.SCORE, uid=134212),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 73", LEVEL, Kind.SCORE, uid=134213),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 74", LEVEL, Kind.SCORE, uid=134214),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 75", LEVEL, Kind.SCORE, uid=134216),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 76", LEVEL, Kind.SCORE, uid=134233),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 77", LEVEL, Kind.SCORE, uid=134234),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 78", LEVEL, Kind.SCORE, uid=134235),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 79", LEVEL, Kind.SCORE, uid=146919),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 80", LEVEL, Kind.SCORE, uid=146920),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 81", LEVEL, Kind.SCORE, uid=146921),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 82", LEVEL, Kind.SCORE, uid=146922),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 83", LEVEL, Kind.SCORE, uid=146923),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 84", LEVEL, Kind.SCORE, uid=146933),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 85", LEVEL, Kind.SCORE, uid=146934),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 86", LEVEL, Kind.SCORE, uid=146936),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 87", LEVEL, Kind.SCORE, uid=146937),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 88", LEVEL, Kind.SCORE, uid=146943),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 89", LEVEL, Kind.SCORE, uid=146944),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 90", LEVEL, Kind.SCORE, uid=146946),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 91", LEVEL, Kind.SCORE, uid=146947),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 92", LEVEL, Kind.SCORE, uid=155789),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 93", LEVEL, Kind.SCORE, uid=155790),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 94", LEVEL, Kind.SCORE, uid=155795),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 95", LEVEL, Kind.SCORE, uid=155796),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 96", LEVEL, Kind.SCORE, uid=155799),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 97", LEVEL, Kind.SCORE, uid=155800),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 98", LEVEL, Kind.SCORE, uid=155803),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 99", LEVEL, Kind.SCORE, uid=155804),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 100", LEVEL, Kind.SCORE, uid=155807),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 101", LEVEL, Kind.SCORE, uid=155808),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 102", LEVEL, Kind.SCORE, uid=155811),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 103", LEVEL, Kind.SCORE, uid=155812),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 104", LEVEL, Kind.SCORE, uid=155813),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 105", LEVEL, Kind.SCORE, uid=155814),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 106", LEVEL, Kind.SCORE, uid=155815),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 107", LEVEL, Kind.SCORE, uid=155816),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 108", LEVEL, Kind.SCORE, uid=155817),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 109", LEVEL, Kind.SCORE, uid=155818),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 110", LEVEL, Kind.SCORE, uid=155819),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 111", LEVEL, Kind.SCORE, uid=155820),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 112", LEVEL, Kind.SCORE, uid=156182),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 113", LEVEL, Kind.SCORE, uid=156183),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 114", LEVEL, Kind.SCORE, uid=156184),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 115", LEVEL, Kind.SCORE, uid=156185),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 116", LEVEL, Kind.SCORE, uid=156186),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 117", LEVEL, Kind.SCORE, uid=156187),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 118", LEVEL, Kind.SCORE, uid=156188),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 119", LEVEL, Kind.SCORE, uid=156189),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 120", LEVEL, Kind.SCORE, uid=156190),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 121", LEVEL, Kind.SCORE, uid=156191),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 122", LEVEL, Kind.SCORE, uid=156192),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 123", LEVEL, Kind.SCORE, uid=156194),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 124", LEVEL, Kind.SCORE, uid=156196),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 125", LEVEL, Kind.SCORE, uid=156198),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 126", LEVEL, Kind.SCORE, uid=156200),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 127", LEVEL, Kind.SCORE, uid=156202),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 128", LEVEL, Kind.SCORE, uid=156203),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 129", LEVEL, Kind.SCORE, uid=156204),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 130", LEVEL, Kind.SCORE, uid=156205),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 131", LEVEL, Kind.SCORE, uid=156206),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 132", LEVEL, Kind.SCORE, uid=156207),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 133", LEVEL, Kind.SCORE, uid=156208),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 134", LEVEL, Kind.SCORE, uid=156209),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 135", LEVEL, Kind.SCORE, uid=156210),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 136", LEVEL, Kind.SCORE, uid=156211),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 137", LEVEL, Kind.SCORE, uid=159945),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 138", LEVEL, Kind.SCORE, uid=159946),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 139", LEVEL, Kind.SCORE, uid=159947),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 140", LEVEL, Kind.SCORE, uid=159948),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 141", LEVEL, Kind.SCORE, uid=159949),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 142", LEVEL, Kind.SCORE, uid=159950),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 143", LEVEL, Kind.SCORE, uid=159951),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 144", LEVEL, Kind.SCORE, uid=159952),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 145", LEVEL, Kind.SCORE, uid=159953),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 146", LEVEL, Kind.SCORE, uid=159954),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 147", LEVEL, Kind.SCORE, uid=159955),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 148", LEVEL, Kind.SCORE, uid=160678),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 149", LEVEL, Kind.SCORE, uid=160679),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 150", LEVEL, Kind.SCORE, uid=160680),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 151", LEVEL, Kind.SCORE, uid=160681),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 152", LEVEL, Kind.SCORE, uid=160682),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 153", LEVEL, Kind.SCORE, uid=160688),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 154", LEVEL, Kind.SCORE, uid=160689),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 155", LEVEL, Kind.SCORE, uid=160690),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 156", LEVEL, Kind.SCORE, uid=160691),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 157", LEVEL, Kind.SCORE, uid=160692),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 158", LEVEL, Kind.SCORE, uid=160693),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 159", LEVEL, Kind.SCORE, uid=160694),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 160", LEVEL, Kind.SCORE, uid=160695),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 161", LEVEL, Kind.SCORE, uid=160696),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 162", LEVEL, Kind.SCORE, uid=160697),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 163", LEVEL, Kind.SCORE, uid=160698),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 164", LEVEL, Kind.SCORE, uid=160699),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 165", LEVEL, Kind.SCORE, uid=160700),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 166", LEVEL, Kind.SCORE, uid=160701),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 167", LEVEL, Kind.SCORE, uid=160702),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 168", LEVEL, Kind.SCORE, uid=160703),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 169", LEVEL, Kind.SCORE, uid=160704),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 170", LEVEL, Kind.SCORE, uid=160705),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 171", LEVEL, Kind.SCORE, uid=160706),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 172", LEVEL, Kind.SCORE, uid=160707),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 173", LEVEL, Kind.SCORE, uid=160708),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 174", LEVEL, Kind.SCORE, uid=160709),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 175", LEVEL, Kind.SCORE, uid=160710),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 176", LEVEL, Kind.SCORE, uid=160711),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 177", LEVEL, Kind.SCORE, uid=160712),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 178", LEVEL, Kind.SCORE, uid=163634),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 179", LEVEL, Kind.SCORE, uid=163996),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 180", LEVEL, Kind.SCORE, uid=163998),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 181", LEVEL, Kind.SCORE, uid=163999),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 182", LEVEL, Kind.SCORE, uid=167635),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 183", LEVEL, Kind.SCORE, uid=167997),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 184", LEVEL, Kind.SCORE, uid=167998),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 185", LEVEL, Kind.SCORE, uid=167999),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 186", LEVEL, Kind.SCORE, uid=168000),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 187", LEVEL, Kind.SCORE, uid=168001),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 188", LEVEL, Kind.SCORE, uid=168002),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 189", LEVEL, Kind.SCORE, uid=168003),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 190", LEVEL, Kind.SCORE, uid=168004),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 191", LEVEL, Kind.SCORE, uid=168005),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 192", LEVEL, Kind.SCORE, uid=168006),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 193", LEVEL, Kind.SCORE, uid=168007),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 194", LEVEL, Kind.SCORE, uid=168008),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 195", LEVEL, Kind.SCORE, uid=168009),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 196", LEVEL, Kind.SCORE, uid=168010),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 197", LEVEL, Kind.SCORE, uid=168011),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 198", LEVEL, Kind.SCORE, uid=168012),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 199", LEVEL, Kind.SCORE, uid=168013),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 200", LEVEL, Kind.SCORE, uid=168014),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 201", LEVEL, Kind.SCORE, uid=168015),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 202", LEVEL, Kind.SCORE, uid=168024),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 203", LEVEL, Kind.SCORE, uid=168025),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 204", LEVEL, Kind.SCORE, uid=168027),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 205", LEVEL, Kind.SCORE, uid=168029),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 206", LEVEL, Kind.SCORE, uid=168032),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 207", LEVEL, Kind.SCORE, uid=169126),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 208", LEVEL, Kind.SCORE, uid=169135),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 209", LEVEL, Kind.SCORE, uid=169137),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 210", LEVEL, Kind.SCORE, uid=169139),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 211", LEVEL, Kind.SCORE, uid=169141),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 212", LEVEL, Kind.SCORE, uid=169864),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 213", LEVEL, Kind.SCORE, uid=169867),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 214", LEVEL, Kind.SCORE, uid=169869),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 215", LEVEL, Kind.SCORE, uid=169871),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 216", LEVEL, Kind.SCORE, uid=169873),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 217", LEVEL, Kind.SCORE, uid=170235),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 218", LEVEL, Kind.SCORE, uid=170236),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 219", LEVEL, Kind.SCORE, uid=170237),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 220", LEVEL, Kind.SCORE, uid=170238),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 221", LEVEL, Kind.SCORE, uid=170239),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 222", LEVEL, Kind.SCORE, uid=170240),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 223", LEVEL, Kind.SCORE, uid=170241),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 224", LEVEL, Kind.SCORE, uid=170242),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 225", LEVEL, Kind.SCORE, uid=170243),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 226", LEVEL, Kind.SCORE, uid=170244),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 227", LEVEL, Kind.SCORE, uid=170245),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 228", LEVEL, Kind.SCORE, uid=170246),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 229", LEVEL, Kind.SCORE, uid=170247),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 230", LEVEL, Kind.SCORE, uid=170248),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 231", LEVEL, Kind.SCORE, uid=170249),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 232", LEVEL, Kind.SCORE, uid=170250),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 233", LEVEL, Kind.SCORE, uid=170251),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 234", LEVEL, Kind.SCORE, uid=170252),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 235", LEVEL, Kind.SCORE, uid=170253),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 236", LEVEL, Kind.SCORE, uid=170254),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 237", LEVEL, Kind.SCORE, uid=171338),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 238", LEVEL, Kind.SCORE, uid=171339),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 239", LEVEL, Kind.SCORE, uid=171340),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 240", LEVEL, Kind.SCORE, uid=171341),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 241", LEVEL, Kind.SCORE, uid=171342),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 242", LEVEL, Kind.SCORE, uid=172427),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 243", LEVEL, Kind.SCORE, uid=172428),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 244", LEVEL, Kind.SCORE, uid=172429),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 245", LEVEL, Kind.SCORE, uid=172430),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 246", LEVEL, Kind.SCORE, uid=172431),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 247", LEVEL, Kind.SCORE, uid=172432),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 248", LEVEL, Kind.SCORE, uid=172433),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 249", LEVEL, Kind.SCORE, uid=172434),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 250", LEVEL, Kind.SCORE, uid=172435),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 251", LEVEL, Kind.SCORE, uid=172436),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 252", LEVEL, Kind.SCORE, uid=172437),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 253", LEVEL, Kind.SCORE, uid=172438),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 254", LEVEL, Kind.SCORE, uid=172439),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 255", LEVEL, Kind.SCORE, uid=172440),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 256", LEVEL, Kind.SCORE, uid=172441),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 257", LEVEL, Kind.SCORE, uid=172443),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 258", LEVEL, Kind.SCORE, uid=172444),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 259", LEVEL, Kind.SCORE, uid=172445),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 260", LEVEL, Kind.SCORE, uid=172446),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 261", LEVEL, Kind.SCORE, uid=172447),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 262", LEVEL, Kind.SCORE, uid=172448),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 263", LEVEL, Kind.SCORE, uid=172449),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 264", LEVEL, Kind.SCORE, uid=172450),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 265", LEVEL, Kind.SCORE, uid=172451),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 266", LEVEL, Kind.SCORE, uid=172452),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 267", LEVEL, Kind.SCORE, uid=177372),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 268", LEVEL, Kind.SCORE, uid=177373),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 269", LEVEL, Kind.SCORE, uid=177375),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 270", LEVEL, Kind.SCORE, uid=177376),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 271", LEVEL, Kind.SCORE, uid=185716),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 272", LEVEL, Kind.SCORE, uid=185717),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 273", LEVEL, Kind.SCORE, uid=185718),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 274", LEVEL, Kind.SCORE, uid=185727),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 275", LEVEL, Kind.SCORE, uid=185728),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 276", LEVEL, Kind.SCORE, uid=194790),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 277", LEVEL, Kind.SCORE, uid=194791),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 278", LEVEL, Kind.SCORE, uid=194792),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 279", LEVEL, Kind.SCORE, uid=194798),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 280", LEVEL, Kind.SCORE, uid=194799),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 281", LEVEL, Kind.SCORE, uid=195531),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 282", LEVEL, Kind.SCORE, uid=195532),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 283", LEVEL, Kind.SCORE, uid=195533),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 284", LEVEL, Kind.SCORE, uid=195539),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 285", LEVEL, Kind.SCORE, uid=195540),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 286", LEVEL, Kind.SCORE, uid=195550),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 287", LEVEL, Kind.SCORE, uid=195551),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 288", LEVEL, Kind.SCORE, uid=195552),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 289", LEVEL, Kind.SCORE, uid=195558),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 290", LEVEL, Kind.SCORE, uid=195559),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 291", LEVEL, Kind.SCORE, uid=252825),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 292", LEVEL, Kind.SCORE, uid=252826),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 293", LEVEL, Kind.SCORE, uid=252827),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 294", LEVEL, Kind.SCORE, uid=252828),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 295", LEVEL, Kind.SCORE, uid=307743),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 296", LEVEL, Kind.SCORE, uid=307744),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 297", LEVEL, Kind.SCORE, uid=307745),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 298", LEVEL, Kind.SCORE, uid=307746),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 299", LEVEL, Kind.SCORE, uid=307747),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 300", LEVEL, Kind.SCORE, uid=323462),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 301", LEVEL, Kind.SCORE, uid=323463),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 302", LEVEL, Kind.SCORE, uid=323464),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 303", LEVEL, Kind.SCORE, uid=323465),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 304", LEVEL, Kind.SCORE, uid=323466),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 305", LEVEL, Kind.SCORE, uid=323467),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 306", LEVEL, Kind.SCORE, uid=327041),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 307", LEVEL, Kind.SCORE, uid=327042),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 308", LEVEL, Kind.SCORE, uid=327043),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 309", LEVEL, Kind.SCORE, uid=327044),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 310", LEVEL, Kind.SCORE, uid=327045),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 311", LEVEL, Kind.SCORE, uid=327046),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 312", LEVEL, Kind.SCORE, uid=327047),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 313", LEVEL, Kind.SCORE, uid=327048),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 314", LEVEL, Kind.SCORE, uid=327049),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 315", LEVEL, Kind.SCORE, uid=327050),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 316", LEVEL, Kind.SCORE, uid=327061),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 317", LEVEL, Kind.SCORE, uid=327062),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 318", LEVEL, Kind.SCORE, uid=327063),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 319", LEVEL, Kind.SCORE, uid=327064),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 320", LEVEL, Kind.SCORE, uid=327065),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 321", LEVEL, Kind.SCORE, uid=330409),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 322", LEVEL, Kind.SCORE, uid=369525),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 323", LEVEL, Kind.SCORE, uid=369526),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 324", LEVEL, Kind.SCORE, uid=369527),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 325", LEVEL, Kind.SCORE, uid=369528),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 326", LEVEL, Kind.SCORE, uid=369529),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 327", LEVEL, Kind.SCORE, uid=369530),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 328", LEVEL, Kind.SCORE, uid=369531),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 329", LEVEL, Kind.SCORE, uid=369532),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 330", LEVEL, Kind.SCORE, uid=369533),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 331", LEVEL, Kind.SCORE, uid=369534),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 332", LEVEL, Kind.SCORE, uid=369535),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 333", LEVEL, Kind.SCORE, uid=369536),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 334", LEVEL, Kind.SCORE, uid=369537),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 335", LEVEL, Kind.SCORE, uid=371703),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 336", LEVEL, Kind.SCORE, uid=371704),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 337", LEVEL, Kind.SCORE, uid=371705),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 338", LEVEL, Kind.SCORE, uid=371706),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 339", LEVEL, Kind.SCORE, uid=377085),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 340", LEVEL, Kind.SCORE, uid=377086),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 341", LEVEL, Kind.SCORE, uid=377087),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 342", LEVEL, Kind.SCORE, uid=377088),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 343", LEVEL, Kind.SCORE, uid=377089),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 344", LEVEL, Kind.SCORE, uid=377090),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 345", LEVEL, Kind.SCORE, uid=377091),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 346", LEVEL, Kind.SCORE, uid=377092),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 347", LEVEL, Kind.SCORE, uid=377093),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 348", LEVEL, Kind.SCORE, uid=377094),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 349", LEVEL, Kind.SCORE, uid=377095),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 350", LEVEL, Kind.SCORE, uid=377096),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 351", LEVEL, Kind.SCORE, uid=377097),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 352", LEVEL, Kind.SCORE, uid=377098),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 353", LEVEL, Kind.SCORE, uid=377099),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 354", LEVEL, Kind.SCORE, uid=377100),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 355", LEVEL, Kind.SCORE, uid=377101),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 356", LEVEL, Kind.SCORE, uid=377102),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 357", LEVEL, Kind.SCORE, uid=377103),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 358", LEVEL, Kind.SCORE, uid=377104),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 359", LEVEL, Kind.SCORE, uid=377105),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 360", LEVEL, Kind.SCORE, uid=377106),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 361", LEVEL, Kind.SCORE, uid=377109),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 362", LEVEL, Kind.SCORE, uid=377110),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 363", LEVEL, Kind.SCORE, uid=377111),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 364", LEVEL, Kind.SCORE, uid=377112),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 365", LEVEL, Kind.SCORE, uid=377113),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 366", LEVEL, Kind.SCORE, uid=377114),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 367", LEVEL, Kind.SCORE, uid=377115),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 368", LEVEL, Kind.SCORE, uid=377116),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 369", LEVEL, Kind.SCORE, uid=377117),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 370", LEVEL, Kind.SCORE, uid=377118),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 371", LEVEL, Kind.SCORE, uid=377119),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 372", LEVEL, Kind.SCORE, uid=377120),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 373", LEVEL, Kind.SCORE, uid=377121),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 374", LEVEL, Kind.SCORE, uid=377122),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 375", LEVEL, Kind.SCORE, uid=377123),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 376", LEVEL, Kind.SCORE, uid=377124),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 377", LEVEL, Kind.SCORE, uid=377125),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 378", LEVEL, Kind.SCORE, uid=377126),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 379", LEVEL, Kind.SCORE, uid=377127),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 380", LEVEL, Kind.SCORE, uid=377128),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 381", LEVEL, Kind.SCORE, uid=377129),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 382", LEVEL, Kind.SCORE, uid=377130),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 383", LEVEL, Kind.SCORE, uid=377131),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 384", LEVEL, Kind.SCORE, uid=377132),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 385", LEVEL, Kind.SCORE, uid=377133),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 386", LEVEL, Kind.SCORE, uid=377134),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 387", LEVEL, Kind.SCORE, uid=377135),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 388", LEVEL, Kind.SCORE, uid=377136),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 389", LEVEL, Kind.SCORE, uid=377137),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 390", LEVEL, Kind.SCORE, uid=377138),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 391", LEVEL, Kind.SCORE, uid=377139),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 392", LEVEL, Kind.SCORE, uid=377140),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 393", LEVEL, Kind.SCORE, uid=377141),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 394", LEVEL, Kind.SCORE, uid=377142),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 395", LEVEL, Kind.SCORE, uid=377143),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 396", LEVEL, Kind.SCORE, uid=377144),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 397", LEVEL, Kind.SCORE, uid=377145),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 398", LEVEL, Kind.SCORE, uid=377146),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 399", LEVEL, Kind.SCORE, uid=377147),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 400", LEVEL, Kind.SCORE, uid=377148),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 401", LEVEL, Kind.SCORE, uid=377149),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 402", LEVEL, Kind.SCORE, uid=377150),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 403", LEVEL, Kind.SCORE, uid=377151),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 404", LEVEL, Kind.SCORE, uid=377152),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 405", LEVEL, Kind.SCORE, uid=377153),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 406", LEVEL, Kind.SCORE, uid=377154),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 407", LEVEL, Kind.SCORE, uid=377155),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 408", LEVEL, Kind.SCORE, uid=377156),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 409", LEVEL, Kind.SCORE, uid=377159),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 410", LEVEL, Kind.SCORE, uid=377160),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 411", LEVEL, Kind.SCORE, uid=377161),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 412", LEVEL, Kind.SCORE, uid=377162),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 413", LEVEL, Kind.SCORE, uid=377163),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 414", LEVEL, Kind.SCORE, uid=377164),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 415", LEVEL, Kind.SCORE, uid=377165),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 416", LEVEL, Kind.SCORE, uid=377166),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 417", LEVEL, Kind.SCORE, uid=377167),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 418", LEVEL, Kind.SCORE, uid=377168),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 419", LEVEL, Kind.SCORE, uid=379322),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 420", LEVEL, Kind.SCORE, uid=379323),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 421", LEVEL, Kind.SCORE, uid=379324),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 422", LEVEL, Kind.SCORE, uid=379325),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 423", LEVEL, Kind.SCORE, uid=379326),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 424", LEVEL, Kind.SCORE, uid=379327),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 425", LEVEL, Kind.SCORE, uid=379328),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 426", LEVEL, Kind.SCORE, uid=379329),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 427", LEVEL, Kind.SCORE, uid=379330),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 428", LEVEL, Kind.SCORE, uid=383966),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 429", LEVEL, Kind.SCORE, uid=383967),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 430", LEVEL, Kind.SCORE, uid=383968),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 431", LEVEL, Kind.SCORE, uid=383969),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 432", LEVEL, Kind.SCORE, uid=383970),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 433", LEVEL, Kind.SCORE, uid=383971),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 434", LEVEL, Kind.SCORE, uid=383972),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 435", LEVEL, Kind.SCORE, uid=383973),
    LBPLocationData("Sensei's Lost Castle - Score Bubble 436", LEVEL, Kind.SCORE, uid=383974),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 1 - Wooden Catapult", LEVEL, Kind.PRIZE, uid=172426, plan='g48859'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 2 - Cherry Blossom Tree", LEVEL, Kind.PRIZE, uid=220784, plan='g47782'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 3 - Mini Sumo", LEVEL, Kind.PRIZE, uid=252829, plan='g56182'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 4 - Diagonal Large Wheel", LEVEL, Kind.PRIZE, uid=252830, plan='g48862'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 5 - Diagonal Small Wheel", LEVEL, Kind.PRIZE, uid=252832, plan='g48861'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 6 - Brushcloud with Sponge", LEVEL, Kind.PRIZE, uid=252834, plan='g47787'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 7 - Spiked Rotating Wheel", LEVEL, Kind.PRIZE, uid=252836, plan='g51446'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 8 - Shuriken Tower", LEVEL, Kind.PRIZE, uid=252837, plan='g47791'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 9 - Brushcloud", LEVEL, Kind.PRIZE, uid=252840, plan='g48860', players=2),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 10 - Red Wicker", LEVEL, Kind.PRIZE, uid=252845, plan='g32070', players=2),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 11 - Screen", LEVEL, Kind.PRIZE, uid=252846, plan='g32072'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 12 - Little Doll", LEVEL, Kind.PRIZE, uid=252847, plan='g34364', rule=HasAll('Blue Mountain', 'Japanese Wave')),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 13 - Green Bamboo Stick", LEVEL, Kind.PRIZE, uid=252848, plan='g32078', rule=HasAll('Blue Mountain', 'Japanese Wave')),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 14 - Pink Warrior Mask", LEVEL, Kind.PRIZE, uid=252849, plan='g32039', rule=HasAll('Blue Mountain', 'Japanese Wave')),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 15 - Big Cute Eye", LEVEL, Kind.PRIZE, uid=252850, plan='g48585', rule=HasAll('Blue Mountain', 'Japanese Wave')),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 16 - Sakura", LEVEL, Kind.PRIZE, uid=252852, plan='g32031', players=2),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 17 - Dragon Eye", LEVEL, Kind.PRIZE, uid=252856, plan='g32051'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 18 - Sakura Flower", LEVEL, Kind.PRIZE, uid=252859, plan='g32054'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 19 - Sushi", LEVEL, Kind.PRIZE, uid=252860, plan='g32069'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 20 - Pale Green Wood", LEVEL, Kind.PRIZE, uid=252861, plan='g51144'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 21 - Dragon Scale", LEVEL, Kind.PRIZE, uid=252863, plan='g32050', players=2),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 22 - Fat Ninja", LEVEL, Kind.PRIZE, uid=252867, plan='g47783'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 23 - Shuriken", LEVEL, Kind.PRIZE, uid=252869, plan='g44631'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 24 - Thin Ninja", LEVEL, Kind.PRIZE, uid=252871, plan='g47796', players=2),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 25 - Japanese Fish", LEVEL, Kind.PRIZE, uid=252877, plan='g32045'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 26 - Big Rotating Sponge", LEVEL, Kind.PRIZE, uid=252878, plan='g48865'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 27 - Swinging Ninja", LEVEL, Kind.PRIZE, uid=252879, plan='g48901'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 28 - Purple Button", LEVEL, Kind.PRIZE, uid=253951, plan='g34403'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 29 - Pink Flower Button", LEVEL, Kind.PRIZE, uid=253953, plan='g34396'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 30 - White Flowers Button", LEVEL, Kind.PRIZE, uid=253955, plan='g34394'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 31 - Yellow Button", LEVEL, Kind.PRIZE, uid=253957, plan='g34404'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 32 - Japanese Samurai", LEVEL, Kind.PRIZE, uid=254671, plan='g32036'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 33 - 'Tricky Business’", LEVEL, Kind.PRIZE, uid=255385, plan='g52641', players=2),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 34 - Flip Flops", LEVEL, Kind.PRIZE, uid=255742, plan='g39985', players=2),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 35 - Metallic Tunic", LEVEL, Kind.PRIZE, uid=255743, plan='g43293', players=2),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 36 - Japanese Wave", LEVEL, Kind.PRIZE, uid=307379, plan='g32044'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 37 - Blue Mountain", LEVEL, Kind.PRIZE, uid=307380, plan='g32040'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 38 - Gold Charm", LEVEL, Kind.PRIZE, uid=316199, plan='g32030'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 39 - Grass Doodle", LEVEL, Kind.PRIZE, uid=323473, plan='g32046'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 40 - Red Japanese Text", LEVEL, Kind.PRIZE, uid=328973, plan='g32047'),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 41 - Daruma San", LEVEL, Kind.PRIZE, uid=328974, plan='g47772', players=2),
    LBPLocationData("Sensei's Lost Castle - Prize Bubble 42 - 'Song 2'", LEVEL, Kind.PRIZE, uid=392229, plan='g33152'),
    LBPLocationData("Sensei's Lost Castle - Level Complete", LEVEL, Kind.COMPLETE),
    LBPLocationData("Sensei's Lost Castle - All Prize Bubbles", LEVEL, Kind.ALL_PRIZES),
    LBPLocationData("Sensei's Lost Castle - Ace (No Deaths)", LEVEL, Kind.ACE),
    LBPLocationData("Sensei's Lost Castle - Completion Reward 1 - Angel Halo", LEVEL, Kind.REWARD, plan='g32473', condition=Kind.COMPLETE),
    LBPLocationData("Sensei's Lost Castle - Completion Reward 2 - Rainbow Squares", LEVEL, Kind.REWARD, plan='g34388', condition=Kind.COMPLETE),
    LBPLocationData("Sensei's Lost Castle - All Prizes Reward 1 - Big Sumo", LEVEL, Kind.REWARD, plan='g56181', condition=Kind.ALL_PRIZES),
    LBPLocationData("Sensei's Lost Castle - All Prizes Reward 2 - The Islands Concept with Frame", LEVEL, Kind.REWARD, plan='g52814', condition=Kind.ALL_PRIZES),
    LBPLocationData("Sensei's Lost Castle - All Prizes Reward 3 - The Islands Concept", LEVEL, Kind.REWARD, plan='g52754', condition=Kind.ALL_PRIZES),
    LBPLocationData("Sensei's Lost Castle - Ace Reward 1 - Googly Eye Glasses", LEVEL, Kind.REWARD, plan='g32429', condition=Kind.ACE),
    LBPLocationData("Sensei's Lost Castle - Sticker Switch 1 - Blue Mountain", LEVEL, Kind.STICKER_SWITCH, uid=186451, plan='g32040'),
    LBPLocationData("Sensei's Lost Castle - Sticker Switch 2 - Japanese Wave", LEVEL, Kind.STICKER_SWITCH, uid=186452, plan='g32044'),
    LBPLocationData("Sensei's Lost Castle - Sticker Switch 3 - Japanese Wave", LEVEL, Kind.STICKER_SWITCH, uid=186453, plan='g32044'),
    LBPLocationData("Sensei's Lost Castle - Sticker Switch 4 - Japanese Wave", LEVEL, Kind.STICKER_SWITCH, uid=186454, plan='g32044'),
    LBPLocationData("Sensei's Lost Castle - Key 1", LEVEL, Kind.KEY, uid=20036, target_slot='SlotID{DEVELOPER, 39230}'),
    LBPLocationData("Sensei's Lost Castle - Key 2", LEVEL, Kind.KEY, uid=198504, target_slot='SlotID{DEVELOPER, 44554}'),
)
