from rule_builder.rules import Has

from ..model import Kind, LBPLocationData

LEVEL = 'g26614'

LOCATIONS = (
    LBPLocationData('Serpent Shrine - Score Bubble 1', LEVEL, Kind.SCORE, uid=62349),
    LBPLocationData('Serpent Shrine - Score Bubble 2', LEVEL, Kind.SCORE, uid=62350),
    LBPLocationData('Serpent Shrine - Score Bubble 3', LEVEL, Kind.SCORE, uid=62351),
    LBPLocationData('Serpent Shrine - Score Bubble 4', LEVEL, Kind.SCORE, uid=62370),
    LBPLocationData('Serpent Shrine - Score Bubble 5', LEVEL, Kind.SCORE, uid=62371),
    LBPLocationData('Serpent Shrine - Score Bubble 6', LEVEL, Kind.SCORE, uid=62372),
    LBPLocationData('Serpent Shrine - Score Bubble 7', LEVEL, Kind.SCORE, uid=62379),
    LBPLocationData('Serpent Shrine - Score Bubble 8', LEVEL, Kind.SCORE, uid=62380),
    LBPLocationData('Serpent Shrine - Score Bubble 9', LEVEL, Kind.SCORE, uid=62381),
    LBPLocationData('Serpent Shrine - Score Bubble 10', LEVEL, Kind.SCORE, uid=62382),
    LBPLocationData('Serpent Shrine - Score Bubble 11', LEVEL, Kind.SCORE, uid=62383),
    LBPLocationData('Serpent Shrine - Score Bubble 12', LEVEL, Kind.SCORE, uid=62384),
    LBPLocationData('Serpent Shrine - Score Bubble 13', LEVEL, Kind.SCORE, uid=62385),
    LBPLocationData('Serpent Shrine - Score Bubble 14', LEVEL, Kind.SCORE, uid=62386),
    LBPLocationData('Serpent Shrine - Score Bubble 15', LEVEL, Kind.SCORE, uid=62387),
    LBPLocationData('Serpent Shrine - Score Bubble 16', LEVEL, Kind.SCORE, uid=62394),
    LBPLocationData('Serpent Shrine - Score Bubble 17', LEVEL, Kind.SCORE, uid=62395),
    LBPLocationData('Serpent Shrine - Score Bubble 18', LEVEL, Kind.SCORE, uid=62396),
    LBPLocationData('Serpent Shrine - Score Bubble 19', LEVEL, Kind.SCORE, uid=62406),
    LBPLocationData('Serpent Shrine - Score Bubble 20', LEVEL, Kind.SCORE, uid=62407),
    LBPLocationData('Serpent Shrine - Score Bubble 21', LEVEL, Kind.SCORE, uid=62408),
    LBPLocationData('Serpent Shrine - Score Bubble 22', LEVEL, Kind.SCORE, uid=62409),
    LBPLocationData('Serpent Shrine - Score Bubble 23', LEVEL, Kind.SCORE, uid=62410),
    LBPLocationData('Serpent Shrine - Score Bubble 24', LEVEL, Kind.SCORE, uid=62411),
    LBPLocationData('Serpent Shrine - Score Bubble 25', LEVEL, Kind.SCORE, uid=62418),
    LBPLocationData('Serpent Shrine - Score Bubble 26', LEVEL, Kind.SCORE, uid=62419),
    LBPLocationData('Serpent Shrine - Score Bubble 27', LEVEL, Kind.SCORE, uid=62420),
    LBPLocationData('Serpent Shrine - Score Bubble 28', LEVEL, Kind.SCORE, uid=62436),
    LBPLocationData('Serpent Shrine - Score Bubble 29', LEVEL, Kind.SCORE, uid=62437),
    LBPLocationData('Serpent Shrine - Score Bubble 30', LEVEL, Kind.SCORE, uid=62438),
    LBPLocationData('Serpent Shrine - Score Bubble 31', LEVEL, Kind.SCORE, uid=62439),
    LBPLocationData('Serpent Shrine - Score Bubble 32', LEVEL, Kind.SCORE, uid=62440),
    LBPLocationData('Serpent Shrine - Score Bubble 33', LEVEL, Kind.SCORE, uid=62441),
    LBPLocationData('Serpent Shrine - Score Bubble 34', LEVEL, Kind.SCORE, uid=62442),
    LBPLocationData('Serpent Shrine - Score Bubble 35', LEVEL, Kind.SCORE, uid=62443),
    LBPLocationData('Serpent Shrine - Score Bubble 36', LEVEL, Kind.SCORE, uid=62444),
    LBPLocationData('Serpent Shrine - Score Bubble 37', LEVEL, Kind.SCORE, uid=62445),
    LBPLocationData('Serpent Shrine - Score Bubble 38', LEVEL, Kind.SCORE, uid=62446),
    LBPLocationData('Serpent Shrine - Score Bubble 39', LEVEL, Kind.SCORE, uid=62447),
    LBPLocationData('Serpent Shrine - Score Bubble 40', LEVEL, Kind.SCORE, uid=62448),
    LBPLocationData('Serpent Shrine - Score Bubble 41', LEVEL, Kind.SCORE, uid=62449),
    LBPLocationData('Serpent Shrine - Score Bubble 42', LEVEL, Kind.SCORE, uid=62450),
    LBPLocationData('Serpent Shrine - Score Bubble 43', LEVEL, Kind.SCORE, uid=62460),
    LBPLocationData('Serpent Shrine - Score Bubble 44', LEVEL, Kind.SCORE, uid=62461),
    LBPLocationData('Serpent Shrine - Score Bubble 45', LEVEL, Kind.SCORE, uid=62462),
    LBPLocationData('Serpent Shrine - Score Bubble 46', LEVEL, Kind.SCORE, uid=62463),
    LBPLocationData('Serpent Shrine - Score Bubble 47', LEVEL, Kind.SCORE, uid=62464),
    LBPLocationData('Serpent Shrine - Score Bubble 48', LEVEL, Kind.SCORE, uid=62465),
    LBPLocationData('Serpent Shrine - Score Bubble 49', LEVEL, Kind.SCORE, uid=62469),
    LBPLocationData('Serpent Shrine - Score Bubble 50', LEVEL, Kind.SCORE, uid=62471),
    LBPLocationData('Serpent Shrine - Score Bubble 51', LEVEL, Kind.SCORE, uid=64289),
    LBPLocationData('Serpent Shrine - Score Bubble 52', LEVEL, Kind.SCORE, uid=64290),
    LBPLocationData('Serpent Shrine - Score Bubble 53', LEVEL, Kind.SCORE, uid=64291),
    LBPLocationData('Serpent Shrine - Score Bubble 54', LEVEL, Kind.SCORE, uid=64292),
    LBPLocationData('Serpent Shrine - Score Bubble 55', LEVEL, Kind.SCORE, uid=64294),
    LBPLocationData('Serpent Shrine - Score Bubble 56', LEVEL, Kind.SCORE, uid=64295),
    LBPLocationData('Serpent Shrine - Score Bubble 57', LEVEL, Kind.SCORE, uid=64296),
    LBPLocationData('Serpent Shrine - Score Bubble 58', LEVEL, Kind.SCORE, uid=64297),
    LBPLocationData('Serpent Shrine - Score Bubble 59', LEVEL, Kind.SCORE, uid=73156),
    LBPLocationData('Serpent Shrine - Score Bubble 60', LEVEL, Kind.SCORE, uid=73157),
    LBPLocationData('Serpent Shrine - Score Bubble 61', LEVEL, Kind.SCORE, uid=73158),
    LBPLocationData('Serpent Shrine - Score Bubble 62', LEVEL, Kind.SCORE, uid=73159),
    LBPLocationData('Serpent Shrine - Score Bubble 63', LEVEL, Kind.SCORE, uid=73160),
    LBPLocationData('Serpent Shrine - Score Bubble 64', LEVEL, Kind.SCORE, uid=73161),
    LBPLocationData('Serpent Shrine - Score Bubble 65', LEVEL, Kind.SCORE, uid=73162),
    LBPLocationData('Serpent Shrine - Score Bubble 66', LEVEL, Kind.SCORE, uid=73163),
    LBPLocationData('Serpent Shrine - Score Bubble 67', LEVEL, Kind.SCORE, uid=73164),
    LBPLocationData('Serpent Shrine - Score Bubble 68', LEVEL, Kind.SCORE, uid=78708),
    LBPLocationData('Serpent Shrine - Score Bubble 69', LEVEL, Kind.SCORE, uid=78709),
    LBPLocationData('Serpent Shrine - Score Bubble 70', LEVEL, Kind.SCORE, uid=78710),
    LBPLocationData('Serpent Shrine - Score Bubble 71', LEVEL, Kind.SCORE, uid=78711),
    LBPLocationData('Serpent Shrine - Score Bubble 72', LEVEL, Kind.SCORE, uid=78712),
    LBPLocationData('Serpent Shrine - Score Bubble 73', LEVEL, Kind.SCORE, uid=78713),
    LBPLocationData('Serpent Shrine - Score Bubble 74', LEVEL, Kind.SCORE, uid=102554),
    LBPLocationData('Serpent Shrine - Score Bubble 75', LEVEL, Kind.SCORE, uid=102555),
    LBPLocationData('Serpent Shrine - Score Bubble 76', LEVEL, Kind.SCORE, uid=102556),
    LBPLocationData('Serpent Shrine - Score Bubble 77', LEVEL, Kind.SCORE, uid=102560),
    LBPLocationData('Serpent Shrine - Score Bubble 78', LEVEL, Kind.SCORE, uid=102561),
    LBPLocationData('Serpent Shrine - Score Bubble 79', LEVEL, Kind.SCORE, uid=102562),
    LBPLocationData('Serpent Shrine - Score Bubble 80', LEVEL, Kind.SCORE, uid=102563),
    LBPLocationData('Serpent Shrine - Score Bubble 81', LEVEL, Kind.SCORE, uid=111575),
    LBPLocationData('Serpent Shrine - Score Bubble 82', LEVEL, Kind.SCORE, uid=111577),
    LBPLocationData('Serpent Shrine - Score Bubble 83', LEVEL, Kind.SCORE, uid=111578),
    LBPLocationData('Serpent Shrine - Score Bubble 84', LEVEL, Kind.SCORE, uid=111579),
    LBPLocationData('Serpent Shrine - Score Bubble 85', LEVEL, Kind.SCORE, uid=111580),
    LBPLocationData('Serpent Shrine - Score Bubble 86', LEVEL, Kind.SCORE, uid=111633),
    LBPLocationData('Serpent Shrine - Score Bubble 87', LEVEL, Kind.SCORE, uid=111634),
    LBPLocationData('Serpent Shrine - Score Bubble 88', LEVEL, Kind.SCORE, uid=111635),
    LBPLocationData('Serpent Shrine - Score Bubble 89', LEVEL, Kind.SCORE, uid=111636),
    LBPLocationData('Serpent Shrine - Score Bubble 90', LEVEL, Kind.SCORE, uid=111637),
    LBPLocationData('Serpent Shrine - Score Bubble 91', LEVEL, Kind.SCORE, uid=111638),
    LBPLocationData('Serpent Shrine - Score Bubble 92', LEVEL, Kind.SCORE, uid=111639),
    LBPLocationData('Serpent Shrine - Score Bubble 93', LEVEL, Kind.SCORE, uid=111640),
    LBPLocationData('Serpent Shrine - Score Bubble 94', LEVEL, Kind.SCORE, uid=111641),
    LBPLocationData('Serpent Shrine - Score Bubble 95', LEVEL, Kind.SCORE, uid=111642),
    LBPLocationData('Serpent Shrine - Score Bubble 96', LEVEL, Kind.SCORE, uid=128919),
    LBPLocationData('Serpent Shrine - Score Bubble 97', LEVEL, Kind.SCORE, uid=134298),
    LBPLocationData('Serpent Shrine - Score Bubble 98', LEVEL, Kind.SCORE, uid=134299),
    LBPLocationData('Serpent Shrine - Score Bubble 99', LEVEL, Kind.SCORE, uid=134300),
    LBPLocationData('Serpent Shrine - Score Bubble 100', LEVEL, Kind.SCORE, uid=134301),
    LBPLocationData('Serpent Shrine - Score Bubble 101', LEVEL, Kind.SCORE, uid=134302),
    LBPLocationData('Serpent Shrine - Score Bubble 102', LEVEL, Kind.SCORE, uid=134303),
    LBPLocationData('Serpent Shrine - Score Bubble 103', LEVEL, Kind.SCORE, uid=134304),
    LBPLocationData('Serpent Shrine - Score Bubble 104', LEVEL, Kind.SCORE, uid=134305),
    LBPLocationData('Serpent Shrine - Score Bubble 105', LEVEL, Kind.SCORE, uid=134306),
    LBPLocationData('Serpent Shrine - Score Bubble 106', LEVEL, Kind.SCORE, uid=134307),
    LBPLocationData('Serpent Shrine - Score Bubble 107', LEVEL, Kind.SCORE, uid=134308),
    LBPLocationData('Serpent Shrine - Score Bubble 108', LEVEL, Kind.SCORE, uid=134309),
    LBPLocationData('Serpent Shrine - Score Bubble 109', LEVEL, Kind.SCORE, uid=134310),
    LBPLocationData('Serpent Shrine - Score Bubble 110', LEVEL, Kind.SCORE, uid=134311),
    LBPLocationData('Serpent Shrine - Score Bubble 111', LEVEL, Kind.SCORE, uid=134312),
    LBPLocationData('Serpent Shrine - Score Bubble 112', LEVEL, Kind.SCORE, uid=134313),
    LBPLocationData('Serpent Shrine - Score Bubble 113', LEVEL, Kind.SCORE, uid=134314),
    LBPLocationData('Serpent Shrine - Score Bubble 114', LEVEL, Kind.SCORE, uid=134315),
    LBPLocationData('Serpent Shrine - Score Bubble 115', LEVEL, Kind.SCORE, uid=134316),
    LBPLocationData('Serpent Shrine - Score Bubble 116', LEVEL, Kind.SCORE, uid=134317),
    LBPLocationData('Serpent Shrine - Score Bubble 117', LEVEL, Kind.SCORE, uid=134318),
    LBPLocationData('Serpent Shrine - Score Bubble 118', LEVEL, Kind.SCORE, uid=134319),
    LBPLocationData('Serpent Shrine - Score Bubble 119', LEVEL, Kind.SCORE, uid=134320),
    LBPLocationData('Serpent Shrine - Score Bubble 120', LEVEL, Kind.SCORE, uid=134321),
    LBPLocationData('Serpent Shrine - Score Bubble 121', LEVEL, Kind.SCORE, uid=134322),
    LBPLocationData('Serpent Shrine - Score Bubble 122', LEVEL, Kind.SCORE, uid=134323),
    LBPLocationData('Serpent Shrine - Score Bubble 123', LEVEL, Kind.SCORE, uid=134324),
    LBPLocationData('Serpent Shrine - Score Bubble 124', LEVEL, Kind.SCORE, uid=134325),
    LBPLocationData('Serpent Shrine - Score Bubble 125', LEVEL, Kind.SCORE, uid=134329),
    LBPLocationData('Serpent Shrine - Score Bubble 126', LEVEL, Kind.SCORE, uid=134330),
    LBPLocationData('Serpent Shrine - Score Bubble 127', LEVEL, Kind.SCORE, uid=134331),
    LBPLocationData('Serpent Shrine - Score Bubble 128', LEVEL, Kind.SCORE, uid=134332),
    LBPLocationData('Serpent Shrine - Score Bubble 129', LEVEL, Kind.SCORE, uid=134333),
    LBPLocationData('Serpent Shrine - Score Bubble 130', LEVEL, Kind.SCORE, uid=134334),
    LBPLocationData('Serpent Shrine - Score Bubble 131', LEVEL, Kind.SCORE, uid=134335),
    LBPLocationData('Serpent Shrine - Score Bubble 132', LEVEL, Kind.SCORE, uid=134336),
    LBPLocationData('Serpent Shrine - Score Bubble 133', LEVEL, Kind.SCORE, uid=134337),
    LBPLocationData('Serpent Shrine - Score Bubble 134', LEVEL, Kind.SCORE, uid=134338),
    LBPLocationData('Serpent Shrine - Score Bubble 135', LEVEL, Kind.SCORE, uid=134339),
    LBPLocationData('Serpent Shrine - Score Bubble 136', LEVEL, Kind.SCORE, uid=134340),
    LBPLocationData('Serpent Shrine - Score Bubble 137', LEVEL, Kind.SCORE, uid=148949),
    LBPLocationData('Serpent Shrine - Score Bubble 138', LEVEL, Kind.SCORE, uid=148950),
    LBPLocationData('Serpent Shrine - Score Bubble 139', LEVEL, Kind.SCORE, uid=155874),
    LBPLocationData('Serpent Shrine - Score Bubble 140', LEVEL, Kind.SCORE, uid=155875),
    LBPLocationData('Serpent Shrine - Score Bubble 141', LEVEL, Kind.SCORE, uid=155876),
    LBPLocationData('Serpent Shrine - Score Bubble 142', LEVEL, Kind.SCORE, uid=155877),
    LBPLocationData('Serpent Shrine - Score Bubble 143', LEVEL, Kind.SCORE, uid=246046),
    LBPLocationData('Serpent Shrine - Score Bubble 144', LEVEL, Kind.SCORE, uid=246047),
    LBPLocationData('Serpent Shrine - Score Bubble 145', LEVEL, Kind.SCORE, uid=246048),
    LBPLocationData('Serpent Shrine - Score Bubble 146', LEVEL, Kind.SCORE, uid=246049),
    LBPLocationData('Serpent Shrine - Score Bubble 147', LEVEL, Kind.SCORE, uid=246050),
    LBPLocationData('Serpent Shrine - Score Bubble 148', LEVEL, Kind.SCORE, uid=246051),
    LBPLocationData('Serpent Shrine - Score Bubble 149', LEVEL, Kind.SCORE, uid=286243),
    LBPLocationData('Serpent Shrine - Prize Bubble 1 - Wooden Mask', LEVEL, Kind.PRIZE, uid=20331, plan='g31857'),
    LBPLocationData('Serpent Shrine - Prize Bubble 2 - Aztec Gold', LEVEL, Kind.PRIZE, uid=64288, plan='g31890'),
    LBPLocationData('Serpent Shrine - Prize Bubble 3 - Aztec Sackboy™', LEVEL, Kind.PRIZE, uid=78666, plan='g31831'),
    LBPLocationData('Serpent Shrine - Prize Bubble 4 - Jade Track Straight', LEVEL, Kind.PRIZE, uid=79500, plan='g47114'),
    LBPLocationData('Serpent Shrine - Prize Bubble 5 - Snake Bubble Guardian', LEVEL, Kind.PRIZE, uid=84299, plan='g56178'),
    LBPLocationData('Serpent Shrine - Prize Bubble 6 - Orange Mexican Pattern', LEVEL, Kind.PRIZE, uid=111514, plan='g31834', players=2),
    LBPLocationData('Serpent Shrine - Prize Bubble 7 - Man Stone', LEVEL, Kind.PRIZE, uid=111522, plan='g31822', players=2),
    LBPLocationData('Serpent Shrine - Prize Bubble 8 - Quetzal Feather', LEVEL, Kind.PRIZE, uid=111581, plan='g31911'),
    LBPLocationData('Serpent Shrine - Prize Bubble 9 - Jade Track Turn', LEVEL, Kind.PRIZE, uid=111659, plan='g47112'),
    LBPLocationData('Serpent Shrine - Prize Bubble 10 - Mexican Dollar', LEVEL, Kind.PRIZE, uid=111671, plan='g31840', rule=Has('Aztec Face')),
    LBPLocationData('Serpent Shrine - Prize Bubble 11 - Strong Man Logo', LEVEL, Kind.PRIZE, uid=111672, plan='g31828', rule=Has('Aztec Face')),
    LBPLocationData('Serpent Shrine - Prize Bubble 12 - Jade Track Emitter', LEVEL, Kind.PRIZE, uid=111749, plan='g47115', rule=Has('Green Gecko')),
    LBPLocationData('Serpent Shrine - Prize Bubble 13 - Face Stone', LEVEL, Kind.PRIZE, uid=111750, plan='g31821'),
    LBPLocationData('Serpent Shrine - Prize Bubble 14 - Jade Track Gate', LEVEL, Kind.PRIZE, uid=111751, plan='g47111'),
    LBPLocationData('Serpent Shrine - Prize Bubble 15 - Aztec Stone', LEVEL, Kind.PRIZE, uid=143562, plan='g31900'),
    LBPLocationData('Serpent Shrine - Prize Bubble 16 - Jade Track Circle', LEVEL, Kind.PRIZE, uid=148176, plan='g47117'),
    LBPLocationData('Serpent Shrine - Prize Bubble 17 - Bevel Aztec Jade', LEVEL, Kind.PRIZE, uid=148178, plan='g31891'),
    LBPLocationData('Serpent Shrine - Prize Bubble 18 - Jade Track Cross', LEVEL, Kind.PRIZE, uid=151257, plan='g47113'),
    LBPLocationData('Serpent Shrine - Prize Bubble 19 - Gold Motif', LEVEL, Kind.PRIZE, uid=151259, plan='g31912', rule=Has('Aztec Face')),
    LBPLocationData('Serpent Shrine - Prize Bubble 20 - Aztec Jade', LEVEL, Kind.PRIZE, uid=151260, plan='g50780'),
    LBPLocationData('Serpent Shrine - Prize Bubble 21 - Face Motifs', LEVEL, Kind.PRIZE, uid=151261, plan='g31853'),
    LBPLocationData('Serpent Shrine - Prize Bubble 22 - Raising Steps', LEVEL, Kind.PRIZE, uid=154335, plan='g47122'),
    LBPLocationData('Serpent Shrine - Prize Bubble 23 - Orange Motif', LEVEL, Kind.PRIZE, uid=185099, plan='g31845', rule=Has('Green Gecko')),
    LBPLocationData('Serpent Shrine - Prize Bubble 24 - Mexican Scary Mask', LEVEL, Kind.PRIZE, uid=185100, plan='g31836'),
    LBPLocationData('Serpent Shrine - Prize Bubble 25 - Clown', LEVEL, Kind.PRIZE, uid=192020, plan='g32538', rule=Has('Green Gecko')),
    LBPLocationData('Serpent Shrine - Prize Bubble 26 - Zombie Brain', LEVEL, Kind.PRIZE, uid=192021, plan='g32470', players=2),
    LBPLocationData('Serpent Shrine - Prize Bubble 27 - Snake Stone', LEVEL, Kind.PRIZE, uid=192790, plan='g31818'),
    LBPLocationData('Serpent Shrine - Prize Bubble 28 - Jade Snake', LEVEL, Kind.PRIZE, uid=193560, plan='g47110'),
    LBPLocationData('Serpent Shrine - Prize Bubble 29 - Sheriff Zapata', LEVEL, Kind.PRIZE, uid=197405, plan='g48738'),
    LBPLocationData('Serpent Shrine - Prize Bubble 30 - Aztec Face', LEVEL, Kind.PRIZE, uid=215126, plan='g31846'),
    LBPLocationData('Serpent Shrine - Prize Bubble 31 - Canyons IntMusic', LEVEL, Kind.PRIZE, uid=328629, plan='g33141'),
    LBPLocationData('Serpent Shrine - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Serpent Shrine - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('Serpent Shrine - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('Serpent Shrine - Completion Reward 1 - Frying Pan', LEVEL, Kind.REWARD, plan='g40568', condition=Kind.COMPLETE),
    LBPLocationData('Serpent Shrine - Completion Reward 2 - The Canyons', LEVEL, Kind.REWARD, plan='g31966', condition=Kind.COMPLETE),
    LBPLocationData("Serpent Shrine - All Prizes Reward 1 - Sheriff Zapata's Explosives Machine", LEVEL, Kind.REWARD, plan='g51347', condition=Kind.ALL_PRIZES),
    LBPLocationData('Serpent Shrine - All Prizes Reward 2 - The Mines Concept with Frame', LEVEL, Kind.REWARD, plan='g52808', condition=Kind.ALL_PRIZES),
    LBPLocationData('Serpent Shrine - All Prizes Reward 3 - The Mines Concept', LEVEL, Kind.REWARD, plan='g52796', condition=Kind.ALL_PRIZES),
    LBPLocationData('Serpent Shrine - Ace Reward 1 - Cowboy Hat', LEVEL, Kind.REWARD, plan='g39752', condition=Kind.ACE),
    LBPLocationData('Serpent Shrine - Sticker Switch 1 - Aztec Face', LEVEL, Kind.STICKER_SWITCH, uid=111629, plan='g31846'),
    LBPLocationData('Serpent Shrine - Sticker Switch 2 - Orange Motif', LEVEL, Kind.STICKER_SWITCH, uid=111662, plan='g31845'),
    LBPLocationData('Serpent Shrine - Sticker Switch 3 - Green Gecko', LEVEL, Kind.STICKER_SWITCH, uid=111736, plan='g31849'),
)
