from ..model import Kind, LBPLocationData

LEVEL = 'g26376'

LOCATIONS = (
    LBPLocationData('Skate to Victory - Score Bubble 1', LEVEL, Kind.SCORE, uid=11597),
    LBPLocationData('Skate to Victory - Score Bubble 2', LEVEL, Kind.SCORE, uid=11598),
    LBPLocationData('Skate to Victory - Score Bubble 3', LEVEL, Kind.SCORE, uid=11601),
    LBPLocationData('Skate to Victory - Score Bubble 4', LEVEL, Kind.SCORE, uid=11602),
    LBPLocationData('Skate to Victory - Score Bubble 5', LEVEL, Kind.SCORE, uid=11603),
    LBPLocationData('Skate to Victory - Score Bubble 6', LEVEL, Kind.SCORE, uid=46227),
    LBPLocationData('Skate to Victory - Score Bubble 7', LEVEL, Kind.SCORE, uid=46228),
    LBPLocationData('Skate to Victory - Score Bubble 8', LEVEL, Kind.SCORE, uid=46229),
    LBPLocationData('Skate to Victory - Score Bubble 9', LEVEL, Kind.SCORE, uid=46230),
    LBPLocationData('Skate to Victory - Score Bubble 10', LEVEL, Kind.SCORE, uid=46231),
    LBPLocationData('Skate to Victory - Score Bubble 11', LEVEL, Kind.SCORE, uid=46232),
    LBPLocationData('Skate to Victory - Score Bubble 12', LEVEL, Kind.SCORE, uid=46233),
    LBPLocationData('Skate to Victory - Score Bubble 13', LEVEL, Kind.SCORE, uid=1092210),
    LBPLocationData('Skate to Victory - Score Bubble 14', LEVEL, Kind.SCORE, uid=1092426),
    LBPLocationData('Skate to Victory - Score Bubble 15', LEVEL, Kind.SCORE, uid=1092427),
    LBPLocationData('Skate to Victory - Score Bubble 16', LEVEL, Kind.SCORE, uid=1092428),
    LBPLocationData('Skate to Victory - Score Bubble 17', LEVEL, Kind.SCORE, uid=1092429),
    LBPLocationData('Skate to Victory - Score Bubble 18', LEVEL, Kind.SCORE, uid=1092430),
    LBPLocationData('Skate to Victory - Score Bubble 19', LEVEL, Kind.SCORE, uid=1337271),
    LBPLocationData('Skate to Victory - Score Bubble 20', LEVEL, Kind.SCORE, uid=1337272),
    LBPLocationData('Skate to Victory - Score Bubble 21', LEVEL, Kind.SCORE, uid=1338153),
    LBPLocationData('Skate to Victory - Score Bubble 22', LEVEL, Kind.SCORE, uid=1338322),
    LBPLocationData('Skate to Victory - Score Bubble 23', LEVEL, Kind.SCORE, uid=1338323),
    LBPLocationData('Skate to Victory - Score Bubble 24', LEVEL, Kind.SCORE, uid=2561033),
    LBPLocationData('Skate to Victory - Score Bubble 25', LEVEL, Kind.SCORE, uid=2562250),
    LBPLocationData('Skate to Victory - Score Bubble 26', LEVEL, Kind.SCORE, uid=2562251),
    LBPLocationData('Skate to Victory - Score Bubble 27', LEVEL, Kind.SCORE, uid=2562252),
    LBPLocationData('Skate to Victory - Score Bubble 28', LEVEL, Kind.SCORE, uid=2562253),
    LBPLocationData('Skate to Victory - Score Bubble 29', LEVEL, Kind.SCORE, uid=2572262),
    LBPLocationData('Skate to Victory - Score Bubble 30', LEVEL, Kind.SCORE, uid=2572263),
    LBPLocationData('Skate to Victory - Score Bubble 31', LEVEL, Kind.SCORE, uid=2572264),
    LBPLocationData('Skate to Victory - Score Bubble 32', LEVEL, Kind.SCORE, uid=2572265),
    LBPLocationData('Skate to Victory - Score Bubble 33', LEVEL, Kind.SCORE, uid=2572266),
    LBPLocationData('Skate to Victory - Score Bubble 34', LEVEL, Kind.SCORE, uid=2733181),
    LBPLocationData('Skate to Victory - Score Bubble 35', LEVEL, Kind.SCORE, uid=2733182),
    LBPLocationData('Skate to Victory - Score Bubble 36', LEVEL, Kind.SCORE, uid=2733183),
    LBPLocationData('Skate to Victory - Score Bubble 37', LEVEL, Kind.SCORE, uid=2733184),
    LBPLocationData('Skate to Victory - Score Bubble 38', LEVEL, Kind.SCORE, uid=2733752),
    LBPLocationData('Skate to Victory - Score Bubble 39', LEVEL, Kind.SCORE, uid=2733753),
    LBPLocationData('Skate to Victory - Score Bubble 40', LEVEL, Kind.SCORE, uid=2757443),
    LBPLocationData('Skate to Victory - Score Bubble 41', LEVEL, Kind.SCORE, uid=2757444),
    LBPLocationData('Skate to Victory - Score Bubble 42', LEVEL, Kind.SCORE, uid=2757445),
    LBPLocationData('Skate to Victory - Score Bubble 43', LEVEL, Kind.SCORE, uid=2757446),
    LBPLocationData('Skate to Victory - Score Bubble 44', LEVEL, Kind.SCORE, uid=2757447),
    LBPLocationData('Skate to Victory - Score Bubble 45', LEVEL, Kind.SCORE, uid=2757448),
    LBPLocationData('Skate to Victory - Score Bubble 46', LEVEL, Kind.SCORE, uid=2757449),
    LBPLocationData('Skate to Victory - Score Bubble 47', LEVEL, Kind.SCORE, uid=2757450),
    LBPLocationData('Skate to Victory - Score Bubble 48', LEVEL, Kind.SCORE, uid=2757451),
    LBPLocationData('Skate to Victory - Score Bubble 49', LEVEL, Kind.SCORE, uid=2757452),
    LBPLocationData('Skate to Victory - Score Bubble 50', LEVEL, Kind.SCORE, uid=2757453),
    LBPLocationData('Skate to Victory - Score Bubble 51', LEVEL, Kind.SCORE, uid=2757454),
    LBPLocationData('Skate to Victory - Score Bubble 52', LEVEL, Kind.SCORE, uid=2757455),
    LBPLocationData('Skate to Victory - Score Bubble 53', LEVEL, Kind.SCORE, uid=2757456),
    LBPLocationData('Skate to Victory - Score Bubble 54', LEVEL, Kind.SCORE, uid=2757457),
    LBPLocationData('Skate to Victory - Score Bubble 55', LEVEL, Kind.SCORE, uid=2758556),
    LBPLocationData('Skate to Victory - Score Bubble 56', LEVEL, Kind.SCORE, uid=2758557),
    LBPLocationData('Skate to Victory - Score Bubble 57', LEVEL, Kind.SCORE, uid=2767395),
    LBPLocationData('Skate to Victory - Score Bubble 58', LEVEL, Kind.SCORE, uid=2767396),
    LBPLocationData('Skate to Victory - Score Bubble 59', LEVEL, Kind.SCORE, uid=2767397),
    LBPLocationData('Skate to Victory - Score Bubble 60', LEVEL, Kind.SCORE, uid=2767398),
    LBPLocationData('Skate to Victory - Score Bubble 61', LEVEL, Kind.SCORE, uid=2767399),
    LBPLocationData('Skate to Victory - Score Bubble 62', LEVEL, Kind.SCORE, uid=2771263),
    LBPLocationData('Skate to Victory - Score Bubble 63', LEVEL, Kind.SCORE, uid=2771264),
    LBPLocationData('Skate to Victory - Score Bubble 64', LEVEL, Kind.SCORE, uid=2771265),
    LBPLocationData('Skate to Victory - Score Bubble 65', LEVEL, Kind.SCORE, uid=2771266),
    LBPLocationData('Skate to Victory - Score Bubble 66', LEVEL, Kind.SCORE, uid=2771271),
    LBPLocationData('Skate to Victory - Score Bubble 67', LEVEL, Kind.SCORE, uid=2771272),
    LBPLocationData('Skate to Victory - Score Bubble 68', LEVEL, Kind.SCORE, uid=2771273),
    LBPLocationData('Skate to Victory - Score Bubble 69', LEVEL, Kind.SCORE, uid=2771274),
    LBPLocationData('Skate to Victory - Score Bubble 70', LEVEL, Kind.SCORE, uid=2772948),
    LBPLocationData('Skate to Victory - Score Bubble 71', LEVEL, Kind.SCORE, uid=2772949),
    LBPLocationData('Skate to Victory - Score Bubble 72', LEVEL, Kind.SCORE, uid=2772950),
    LBPLocationData('Skate to Victory - Score Bubble 73', LEVEL, Kind.SCORE, uid=2772951),
    LBPLocationData('Skate to Victory - Score Bubble 74', LEVEL, Kind.SCORE, uid=2772952),
    LBPLocationData('Skate to Victory - Score Bubble 75', LEVEL, Kind.SCORE, uid=2772953),
    LBPLocationData('Skate to Victory - Score Bubble 76', LEVEL, Kind.SCORE, uid=2837801),
    LBPLocationData('Skate to Victory - Score Bubble 77', LEVEL, Kind.SCORE, uid=2837802),
    LBPLocationData('Skate to Victory - Score Bubble 78', LEVEL, Kind.SCORE, uid=2837803),
    LBPLocationData('Skate to Victory - Score Bubble 79', LEVEL, Kind.SCORE, uid=2837804),
    LBPLocationData('Skate to Victory - Score Bubble 80', LEVEL, Kind.SCORE, uid=2837805),
    LBPLocationData('Skate to Victory - Score Bubble 81', LEVEL, Kind.SCORE, uid=2837806),
    LBPLocationData('Skate to Victory - Score Bubble 82', LEVEL, Kind.SCORE, uid=2837807),
    LBPLocationData('Skate to Victory - Score Bubble 83', LEVEL, Kind.SCORE, uid=2899633),
    LBPLocationData('Skate to Victory - Score Bubble 84', LEVEL, Kind.SCORE, uid=2920552),
    LBPLocationData('Skate to Victory - Score Bubble 85', LEVEL, Kind.SCORE, uid=2920553),
    LBPLocationData('Skate to Victory - Score Bubble 86', LEVEL, Kind.SCORE, uid=2920555),
    LBPLocationData('Skate to Victory - Score Bubble 87', LEVEL, Kind.SCORE, uid=2920556),
    LBPLocationData('Skate to Victory - Score Bubble 88', LEVEL, Kind.SCORE, uid=2922811),
    LBPLocationData('Skate to Victory - Score Bubble 89', LEVEL, Kind.SCORE, uid=2922812),
    LBPLocationData('Skate to Victory - Score Bubble 90', LEVEL, Kind.SCORE, uid=2922813),
    LBPLocationData('Skate to Victory - Score Bubble 91', LEVEL, Kind.SCORE, uid=2922814),
    LBPLocationData('Skate to Victory - Score Bubble 92', LEVEL, Kind.SCORE, uid=2922815),
    LBPLocationData('Skate to Victory - Score Bubble 93', LEVEL, Kind.SCORE, uid=2922816),
    LBPLocationData('Skate to Victory - Score Bubble 94', LEVEL, Kind.SCORE, uid=2922817),
    LBPLocationData('Skate to Victory - Prize Bubble 1 - Scary Ghost', LEVEL, Kind.PRIZE, uid=1336429, plan='g32127'),
    LBPLocationData('Skate to Victory - Prize Bubble 2 - Green Finish', LEVEL, Kind.PRIZE, uid=1541782, plan='g32147'),
    LBPLocationData('Skate to Victory - Prize Bubble 3 - Neon Kebabs', LEVEL, Kind.PRIZE, uid=1541783, plan='g51221'),
    LBPLocationData('Skate to Victory - Prize Bubble 4 - Blue Postcards', LEVEL, Kind.PRIZE, uid=1541784, plan='g51222'),
    LBPLocationData('Skate to Victory - Prize Bubble 5 - Green Submarine', LEVEL, Kind.PRIZE, uid=1541785, plan='g51371'),
    LBPLocationData('Skate to Victory - Prize Bubble 6 - Start Text', LEVEL, Kind.PRIZE, uid=1541786, plan='g32137'),
    LBPLocationData('Skate to Victory - Prize Bubble 7 - Fancy Swirls', LEVEL, Kind.PRIZE, uid=1541789, plan='g32148'),
    LBPLocationData('Skate to Victory - Prize Bubble 8 - Blue Knight', LEVEL, Kind.PRIZE, uid=1541790, plan='g32129'),
    LBPLocationData('Skate to Victory - Prize Bubble 9 - Green Start', LEVEL, Kind.PRIZE, uid=1543879, plan='g32146'),
    LBPLocationData('Skate to Victory - Prize Bubble 10 - Big Green Bird', LEVEL, Kind.PRIZE, uid=2686442, plan='g32151'),
    LBPLocationData('Skate to Victory - Prize Bubble 11 - Sketch Bricks', LEVEL, Kind.PRIZE, uid=2688089, plan='g32138'),
    LBPLocationData('Skate to Victory - Prize Bubble 12 - Thick Sketch Bricks', LEVEL, Kind.PRIZE, uid=2688090, plan='g32139'),
    LBPLocationData('Skate to Victory - Prize Bubble 13 - Brick Wall Sketch', LEVEL, Kind.PRIZE, uid=2688091, plan='g32142'),
    LBPLocationData('Skate to Victory - Prize Bubble 14 - Tudor Tower', LEVEL, Kind.PRIZE, uid=2688640, plan='g32144'),
    LBPLocationData('Skate to Victory - Prize Bubble 15 - Green Castle Flag', LEVEL, Kind.PRIZE, uid=2688641, plan='g32155'),
    LBPLocationData('Skate to Victory - Prize Bubble 16 - Bingo', LEVEL, Kind.PRIZE, uid=2688645, plan='g51224'),
    LBPLocationData('Skate to Victory - Prize Bubble 17 - Vince Meat Pie', LEVEL, Kind.PRIZE, uid=2688646, plan='g51225', players=2),
    LBPLocationData('Skate to Victory - Prize Bubble 18 - Golf Logo', LEVEL, Kind.PRIZE, uid=2688647, plan='g51226'),
    LBPLocationData('Skate to Victory - Prize Bubble 19 - Yellow Danke', LEVEL, Kind.PRIZE, uid=2688648, plan='g51382', players=2),
    LBPLocationData('Skate to Victory - Prize Bubble 20 - Crazy Sign', LEVEL, Kind.PRIZE, uid=2688649, plan='g51227'),
    LBPLocationData('Skate to Victory - Prize Bubble 21 - Cotton Wheel', LEVEL, Kind.PRIZE, uid=2689198, plan='g51379'),
    LBPLocationData('Skate to Victory - Prize Bubble 22 - King of Hearts', LEVEL, Kind.PRIZE, uid=2689201, plan='g32126'),
    LBPLocationData('Skate to Victory - Prize Bubble 23 - Wheel of Fun', LEVEL, Kind.PRIZE, uid=2689202, plan='g32122'),
    LBPLocationData('Skate to Victory - Prize Bubble 24 - ROFL', LEVEL, Kind.PRIZE, uid=2689203, plan='g51274'),
    LBPLocationData('Skate to Victory - Prize Bubble 25 - King Stamp', LEVEL, Kind.PRIZE, uid=2689204, plan='g32154'),
    LBPLocationData('Skate to Victory - Prize Bubble 26 - Chips Logo', LEVEL, Kind.PRIZE, uid=2689206, plan='g51220'),
    LBPLocationData('Skate to Victory - Prize Bubble 27 - Green Doodle', LEVEL, Kind.PRIZE, uid=2689215, plan='g32133'),
    LBPLocationData('Skate to Victory - Prize Bubble 28 - Kings Head', LEVEL, Kind.PRIZE, uid=2689216, plan='g32123'),
    LBPLocationData('Skate to Victory - Prize Bubble 29 - Leaf', LEVEL, Kind.PRIZE, uid=2689217, plan='g32206'),
    LBPLocationData('Skate to Victory - Prize Bubble 30 - Cloth Leaf', LEVEL, Kind.PRIZE, uid=2691411, plan='g32207'),
    LBPLocationData('Skate to Victory - Prize Bubble 31 - Pink Springy Star', LEVEL, Kind.PRIZE, uid=2691414, plan='g32208'),
    LBPLocationData('Skate to Victory - Prize Bubble 32 - Ghost on String', LEVEL, Kind.PRIZE, uid=2693608, plan='g56293'),
    LBPLocationData('Skate to Victory - Prize Bubble 33 - Windmill', LEVEL, Kind.PRIZE, uid=2696359, plan='g48471'),
    LBPLocationData('Skate to Victory - Prize Bubble 34 - Wobbly Tree', LEVEL, Kind.PRIZE, uid=2696910, plan='g48472'),
    LBPLocationData('Skate to Victory - Prize Bubble 35 - Birdy on String', LEVEL, Kind.PRIZE, uid=2697459, plan='g56292'),
    LBPLocationData('Skate to Victory - Prize Bubble 36 - Cardboard Castle', LEVEL, Kind.PRIZE, uid=2698560, plan='g48475'),
    LBPLocationData('Skate to Victory - Prize Bubble 37 - Rocking Grass', LEVEL, Kind.PRIZE, uid=2699109, plan='g48473'),
    LBPLocationData('Skate to Victory - Prize Bubble 38 - Hessian Fabric', LEVEL, Kind.PRIZE, uid=2700757, plan='g32187'),
    LBPLocationData('Skate to Victory - Prize Bubble 39 - Wooden Struts', LEVEL, Kind.PRIZE, uid=2701310, plan='g32182'),
    LBPLocationData('Skate to Victory - Prize Bubble 40 - Light Brown Wood', LEVEL, Kind.PRIZE, uid=2702408, plan='g32184'),
    LBPLocationData('Skate to Victory - Prize Bubble 41 - Dark Brown Wood', LEVEL, Kind.PRIZE, uid=2703507, plan='g32185'),
    LBPLocationData('Skate to Victory - Prize Bubble 42 - Oak Tree', LEVEL, Kind.PRIZE, uid=2704056, plan='g32183'),
    LBPLocationData('Skate to Victory - Prize Bubble 43 - Pink Floral Fabric', LEVEL, Kind.PRIZE, uid=2706251, plan='g32189'),
    LBPLocationData('Skate to Victory - Prize Bubble 44 - Beige Cotton', LEVEL, Kind.PRIZE, uid=2707898, plan='g51150'),
    LBPLocationData('Skate to Victory - Prize Bubble 45 - Water Wheel', LEVEL, Kind.PRIZE, uid=2709545, plan='g51439'),
    LBPLocationData('Skate to Victory - Prize Bubble 46 - Mushroom Tree', LEVEL, Kind.PRIZE, uid=2711741, plan='g32164'),
    LBPLocationData('Skate to Victory - Prize Bubble 47 - Skateboard', LEVEL, Kind.PRIZE, uid=2712292, plan='g43617'),
    LBPLocationData('Skate to Victory - Prize Bubble 48 - Large Flag', LEVEL, Kind.PRIZE, uid=2713389, plan='g32158'),
    LBPLocationData('Skate to Victory - Prize Bubble 49 - Red Star Light', LEVEL, Kind.PRIZE, uid=2713941, plan='g34570'),
    LBPLocationData('Skate to Victory - Prize Bubble 50 - Green Star Light', LEVEL, Kind.PRIZE, uid=2713942, plan='g34571'),
    LBPLocationData('Skate to Victory - Prize Bubble 51 - Blue Star Light', LEVEL, Kind.PRIZE, uid=2713943, plan='g32163'),
    LBPLocationData('Skate to Victory - Prize Bubble 52 - Pinwheel', LEVEL, Kind.PRIZE, uid=2715042, plan='g51206'),
    LBPLocationData('Skate to Victory - Prize Bubble 53 - Silver Fork', LEVEL, Kind.PRIZE, uid=2715591, plan='g32173'),
    LBPLocationData('Skate to Victory - Prize Bubble 54 - Silver Knife', LEVEL, Kind.PRIZE, uid=2715592, plan='g32174'),
    LBPLocationData('Skate to Victory - Prize Bubble 55 - Pixel Fish Blue', LEVEL, Kind.PRIZE, uid=2737082, plan='g51219'),
    LBPLocationData('Skate to Victory - Prize Bubble 56 - Funny Face Glasses', LEVEL, Kind.PRIZE, uid=2826180, plan='g32434', players=2),
    LBPLocationData("Skate to Victory - Prize Bubble 57 - 'Skipping Syrtaki'", LEVEL, Kind.PRIZE, uid=2831749, plan='g40804'),
    LBPLocationData('Skate to Victory - Prize Bubble 58 - Take A Photo', LEVEL, Kind.PRIZE, uid=2837239, plan='g42946'),
    LBPLocationData('Skate to Victory - Prize Bubble 59 - Dumpty', LEVEL, Kind.PRIZE, uid=2898510, plan='g48463'),
    LBPLocationData('Skate to Victory - Prize Bubble 60 - Yellow Crest', LEVEL, Kind.PRIZE, uid=2900198, plan='g51380'),
    LBPLocationData('Skate to Victory - Prize Bubble 61 - Yellow Star', LEVEL, Kind.PRIZE, uid=2919443, plan='g48682'),
    LBPLocationData("Skate to Victory - Prize Bubble 62 - 'Get It Together'", LEVEL, Kind.PRIZE, uid=2946447, plan='g33148'),
    LBPLocationData('Skate to Victory - Prize Bubble 63 - Blank Background', LEVEL, Kind.PRIZE, uid=2947545, plan='g31968'),
    LBPLocationData('Skate to Victory - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Skate to Victory - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('Skate to Victory - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('Skate to Victory - Completion Reward 1 - Bunny Tail', LEVEL, Kind.REWARD, plan='g36897', condition=Kind.COMPLETE),
    LBPLocationData('Skate to Victory - Completion Reward 2 - The Gardens', LEVEL, Kind.REWARD, plan='g31964', condition=Kind.COMPLETE),
    LBPLocationData('Skate to Victory - All Prizes Reward 1 - Early LittleBigPlanet™ Concept with Frame', LEVEL, Kind.REWARD, plan='g52799', condition=Kind.ALL_PRIZES),
    LBPLocationData('Skate to Victory - All Prizes Reward 2 - Very Early LittleBigPlanet™ Concept', LEVEL, Kind.REWARD, plan='g52787', condition=Kind.ALL_PRIZES),
    LBPLocationData('Skate to Victory - Ace Reward 1 - Pirate Hat', LEVEL, Kind.REWARD, plan='g32467', condition=Kind.ACE),
    LBPLocationData('Skate to Victory - Sticker Switch 1 - Red Lion Emblem', LEVEL, Kind.STICKER_SWITCH, uid=2831746, plan='g32124'),
    LBPLocationData('Skate to Victory - Sticker Switch 2 - Yellow Star', LEVEL, Kind.STICKER_SWITCH, uid=2921103, plan='g48682'),
    LBPLocationData('Skate to Victory - Sticker Switch 3 - Yellow Star', LEVEL, Kind.STICKER_SWITCH, uid=2921115, plan='g48682'),
    LBPLocationData('Skate to Victory - Sticker Switch 4 - Yellow Star', LEVEL, Kind.STICKER_SWITCH, uid=2921122, plan='g48682'),
    LBPLocationData('Skate to Victory - Sticker Switch 5 - Yellow Star', LEVEL, Kind.STICKER_SWITCH, uid=2921698, plan='g48682'),
    LBPLocationData('Skate to Victory - Key 1', LEVEL, Kind.KEY, uid=13970, target_slot='SlotID{DEVELOPER, 26378}'),
    LBPLocationData('Skate to Victory - Key 2', LEVEL, Kind.KEY, uid=1525547, target_slot='SlotID{DEVELOPER, 26373}'),
)
