from ..model import Kind, LBPLocationData

LEVEL = 'g26419'

LOCATIONS = (
    LBPLocationData('Skulldozer - Score Bubble 1', LEVEL, Kind.SCORE, uid=14770),
    LBPLocationData('Skulldozer - Score Bubble 2', LEVEL, Kind.SCORE, uid=14793),
    LBPLocationData('Skulldozer - Score Bubble 3', LEVEL, Kind.SCORE, uid=14794),
    LBPLocationData('Skulldozer - Score Bubble 4', LEVEL, Kind.SCORE, uid=14795),
    LBPLocationData('Skulldozer - Score Bubble 5', LEVEL, Kind.SCORE, uid=14796),
    LBPLocationData('Skulldozer - Score Bubble 6', LEVEL, Kind.SCORE, uid=14797),
    LBPLocationData('Skulldozer - Score Bubble 7', LEVEL, Kind.SCORE, uid=14798),
    LBPLocationData('Skulldozer - Score Bubble 8', LEVEL, Kind.SCORE, uid=14995),
    LBPLocationData('Skulldozer - Score Bubble 9', LEVEL, Kind.SCORE, uid=14996),
    LBPLocationData('Skulldozer - Score Bubble 10', LEVEL, Kind.SCORE, uid=14997),
    LBPLocationData('Skulldozer - Score Bubble 11', LEVEL, Kind.SCORE, uid=14998),
    LBPLocationData('Skulldozer - Score Bubble 12', LEVEL, Kind.SCORE, uid=14999),
    LBPLocationData('Skulldozer - Score Bubble 13', LEVEL, Kind.SCORE, uid=15000),
    LBPLocationData('Skulldozer - Score Bubble 14', LEVEL, Kind.SCORE, uid=15001),
    LBPLocationData('Skulldozer - Score Bubble 15', LEVEL, Kind.SCORE, uid=15002),
    LBPLocationData('Skulldozer - Score Bubble 16', LEVEL, Kind.SCORE, uid=15267),
    LBPLocationData('Skulldozer - Score Bubble 17', LEVEL, Kind.SCORE, uid=15268),
    LBPLocationData('Skulldozer - Score Bubble 18', LEVEL, Kind.SCORE, uid=15269),
    LBPLocationData('Skulldozer - Score Bubble 19', LEVEL, Kind.SCORE, uid=15273),
    LBPLocationData('Skulldozer - Score Bubble 20', LEVEL, Kind.SCORE, uid=15274),
    LBPLocationData('Skulldozer - Score Bubble 21', LEVEL, Kind.SCORE, uid=15275),
    LBPLocationData('Skulldozer - Score Bubble 22', LEVEL, Kind.SCORE, uid=15276),
    LBPLocationData('Skulldozer - Score Bubble 23', LEVEL, Kind.SCORE, uid=15277),
    LBPLocationData('Skulldozer - Score Bubble 24', LEVEL, Kind.SCORE, uid=15278),
    LBPLocationData('Skulldozer - Score Bubble 25', LEVEL, Kind.SCORE, uid=15279),
    LBPLocationData('Skulldozer - Score Bubble 26', LEVEL, Kind.SCORE, uid=15280),
    LBPLocationData('Skulldozer - Score Bubble 27', LEVEL, Kind.SCORE, uid=15281),
    LBPLocationData('Skulldozer - Score Bubble 28', LEVEL, Kind.SCORE, uid=15326),
    LBPLocationData('Skulldozer - Score Bubble 29', LEVEL, Kind.SCORE, uid=15328),
    LBPLocationData('Skulldozer - Score Bubble 30', LEVEL, Kind.SCORE, uid=15329),
    LBPLocationData('Skulldozer - Score Bubble 31', LEVEL, Kind.SCORE, uid=15330),
    LBPLocationData('Skulldozer - Score Bubble 32', LEVEL, Kind.SCORE, uid=15331),
    LBPLocationData('Skulldozer - Score Bubble 33', LEVEL, Kind.SCORE, uid=15332),
    LBPLocationData('Skulldozer - Score Bubble 34', LEVEL, Kind.SCORE, uid=15334),
    LBPLocationData('Skulldozer - Score Bubble 35', LEVEL, Kind.SCORE, uid=15810),
    LBPLocationData('Skulldozer - Score Bubble 36', LEVEL, Kind.SCORE, uid=15811),
    LBPLocationData('Skulldozer - Score Bubble 37', LEVEL, Kind.SCORE, uid=15812),
    LBPLocationData('Skulldozer - Score Bubble 38', LEVEL, Kind.SCORE, uid=15813),
    LBPLocationData('Skulldozer - Score Bubble 39', LEVEL, Kind.SCORE, uid=15814),
    LBPLocationData('Skulldozer - Score Bubble 40', LEVEL, Kind.SCORE, uid=15815),
    LBPLocationData('Skulldozer - Score Bubble 41', LEVEL, Kind.SCORE, uid=16289),
    LBPLocationData('Skulldozer - Score Bubble 42', LEVEL, Kind.SCORE, uid=16291),
    LBPLocationData('Skulldozer - Score Bubble 43', LEVEL, Kind.SCORE, uid=16629),
    LBPLocationData('Skulldozer - Score Bubble 44', LEVEL, Kind.SCORE, uid=16630),
    LBPLocationData('Skulldozer - Score Bubble 45', LEVEL, Kind.SCORE, uid=16631),
    LBPLocationData('Skulldozer - Score Bubble 46', LEVEL, Kind.SCORE, uid=16951),
    LBPLocationData('Skulldozer - Score Bubble 47', LEVEL, Kind.SCORE, uid=16952),
    LBPLocationData('Skulldozer - Score Bubble 48', LEVEL, Kind.SCORE, uid=16953),
    LBPLocationData('Skulldozer - Score Bubble 49', LEVEL, Kind.SCORE, uid=16961),
    LBPLocationData('Skulldozer - Score Bubble 50', LEVEL, Kind.SCORE, uid=16962),
    LBPLocationData('Skulldozer - Score Bubble 51', LEVEL, Kind.SCORE, uid=16963),
    LBPLocationData('Skulldozer - Score Bubble 52', LEVEL, Kind.SCORE, uid=17391),
    LBPLocationData('Skulldozer - Score Bubble 53', LEVEL, Kind.SCORE, uid=17392),
    LBPLocationData('Skulldozer - Score Bubble 54', LEVEL, Kind.SCORE, uid=17393),
    LBPLocationData('Skulldozer - Score Bubble 55', LEVEL, Kind.SCORE, uid=17421),
    LBPLocationData('Skulldozer - Score Bubble 56', LEVEL, Kind.SCORE, uid=17422),
    LBPLocationData('Skulldozer - Score Bubble 57', LEVEL, Kind.SCORE, uid=17423),
    LBPLocationData('Skulldozer - Score Bubble 58', LEVEL, Kind.SCORE, uid=17424),
    LBPLocationData('Skulldozer - Score Bubble 59', LEVEL, Kind.SCORE, uid=17425),
    LBPLocationData('Skulldozer - Score Bubble 60', LEVEL, Kind.SCORE, uid=17426),
    LBPLocationData('Skulldozer - Score Bubble 61', LEVEL, Kind.SCORE, uid=17438),
    LBPLocationData('Skulldozer - Score Bubble 62', LEVEL, Kind.SCORE, uid=17439),
    LBPLocationData('Skulldozer - Score Bubble 63', LEVEL, Kind.SCORE, uid=17440),
    LBPLocationData('Skulldozer - Score Bubble 64', LEVEL, Kind.SCORE, uid=17441),
    LBPLocationData('Skulldozer - Score Bubble 65', LEVEL, Kind.SCORE, uid=17442),
    LBPLocationData('Skulldozer - Score Bubble 66', LEVEL, Kind.SCORE, uid=17443),
    LBPLocationData('Skulldozer - Score Bubble 67', LEVEL, Kind.SCORE, uid=17632),
    LBPLocationData('Skulldozer - Score Bubble 68', LEVEL, Kind.SCORE, uid=17633),
    LBPLocationData('Skulldozer - Score Bubble 69', LEVEL, Kind.SCORE, uid=17634),
    LBPLocationData('Skulldozer - Score Bubble 70', LEVEL, Kind.SCORE, uid=17644),
    LBPLocationData('Skulldozer - Score Bubble 71', LEVEL, Kind.SCORE, uid=17645),
    LBPLocationData('Skulldozer - Score Bubble 72', LEVEL, Kind.SCORE, uid=17646),
    LBPLocationData('Skulldozer - Score Bubble 73', LEVEL, Kind.SCORE, uid=17738),
    LBPLocationData('Skulldozer - Score Bubble 74', LEVEL, Kind.SCORE, uid=17739),
    LBPLocationData('Skulldozer - Score Bubble 75', LEVEL, Kind.SCORE, uid=17740),
    LBPLocationData('Skulldozer - Score Bubble 76', LEVEL, Kind.SCORE, uid=17741),
    LBPLocationData('Skulldozer - Score Bubble 77', LEVEL, Kind.SCORE, uid=23316),
    LBPLocationData('Skulldozer - Score Bubble 78', LEVEL, Kind.SCORE, uid=23318),
    LBPLocationData('Skulldozer - Score Bubble 79', LEVEL, Kind.SCORE, uid=64405),
    LBPLocationData('Skulldozer - Score Bubble 80', LEVEL, Kind.SCORE, uid=64406),
    LBPLocationData('Skulldozer - Score Bubble 81', LEVEL, Kind.SCORE, uid=64407),
    LBPLocationData('Skulldozer - Score Bubble 82', LEVEL, Kind.SCORE, uid=64408),
    LBPLocationData('Skulldozer - Score Bubble 83', LEVEL, Kind.SCORE, uid=64409),
    LBPLocationData('Skulldozer - Score Bubble 84', LEVEL, Kind.SCORE, uid=64410),
    LBPLocationData('Skulldozer - Score Bubble 85', LEVEL, Kind.SCORE, uid=64411),
    LBPLocationData('Skulldozer - Score Bubble 86', LEVEL, Kind.SCORE, uid=64412),
    LBPLocationData('Skulldozer - Score Bubble 87', LEVEL, Kind.SCORE, uid=64413),
    LBPLocationData('Skulldozer - Score Bubble 88', LEVEL, Kind.SCORE, uid=64414),
    LBPLocationData('Skulldozer - Score Bubble 89', LEVEL, Kind.SCORE, uid=64415),
    LBPLocationData('Skulldozer - Score Bubble 90', LEVEL, Kind.SCORE, uid=64416),
    LBPLocationData('Skulldozer - Score Bubble 91', LEVEL, Kind.SCORE, uid=64417),
    LBPLocationData('Skulldozer - Score Bubble 92', LEVEL, Kind.SCORE, uid=64418),
    LBPLocationData('Skulldozer - Score Bubble 93', LEVEL, Kind.SCORE, uid=64419),
    LBPLocationData('Skulldozer - Score Bubble 94', LEVEL, Kind.SCORE, uid=65155),
    LBPLocationData('Skulldozer - Score Bubble 95', LEVEL, Kind.SCORE, uid=65156),
    LBPLocationData('Skulldozer - Score Bubble 96', LEVEL, Kind.SCORE, uid=65157),
    LBPLocationData('Skulldozer - Score Bubble 97', LEVEL, Kind.SCORE, uid=65158),
    LBPLocationData('Skulldozer - Score Bubble 98', LEVEL, Kind.SCORE, uid=65159),
    LBPLocationData('Skulldozer - Score Bubble 99', LEVEL, Kind.SCORE, uid=65160),
    LBPLocationData('Skulldozer - Score Bubble 100', LEVEL, Kind.SCORE, uid=65161),
    LBPLocationData('Skulldozer - Score Bubble 101', LEVEL, Kind.SCORE, uid=65162),
    LBPLocationData('Skulldozer - Score Bubble 102', LEVEL, Kind.SCORE, uid=65163),
    LBPLocationData('Skulldozer - Score Bubble 103', LEVEL, Kind.SCORE, uid=65164),
    LBPLocationData('Skulldozer - Score Bubble 104', LEVEL, Kind.SCORE, uid=65165),
    LBPLocationData('Skulldozer - Score Bubble 105', LEVEL, Kind.SCORE, uid=65166),
    LBPLocationData('Skulldozer - Score Bubble 106', LEVEL, Kind.SCORE, uid=65167),
    LBPLocationData('Skulldozer - Score Bubble 107', LEVEL, Kind.SCORE, uid=65168),
    LBPLocationData('Skulldozer - Score Bubble 108', LEVEL, Kind.SCORE, uid=65169),
    LBPLocationData('Skulldozer - Score Bubble 109', LEVEL, Kind.SCORE, uid=65170),
    LBPLocationData('Skulldozer - Score Bubble 110', LEVEL, Kind.SCORE, uid=65171),
    LBPLocationData('Skulldozer - Score Bubble 111', LEVEL, Kind.SCORE, uid=65172),
    LBPLocationData('Skulldozer - Score Bubble 112', LEVEL, Kind.SCORE, uid=65173),
    LBPLocationData('Skulldozer - Score Bubble 113', LEVEL, Kind.SCORE, uid=65174),
    LBPLocationData('Skulldozer - Score Bubble 114', LEVEL, Kind.SCORE, uid=65175),
    LBPLocationData('Skulldozer - Score Bubble 115', LEVEL, Kind.SCORE, uid=65176),
    LBPLocationData('Skulldozer - Score Bubble 116', LEVEL, Kind.SCORE, uid=65177),
    LBPLocationData('Skulldozer - Score Bubble 117', LEVEL, Kind.SCORE, uid=65178),
    LBPLocationData('Skulldozer - Score Bubble 118', LEVEL, Kind.SCORE, uid=65179),
    LBPLocationData('Skulldozer - Score Bubble 119', LEVEL, Kind.SCORE, uid=65180),
    LBPLocationData('Skulldozer - Score Bubble 120', LEVEL, Kind.SCORE, uid=65181),
    LBPLocationData('Skulldozer - Score Bubble 121', LEVEL, Kind.SCORE, uid=65185),
    LBPLocationData('Skulldozer - Score Bubble 122', LEVEL, Kind.SCORE, uid=65186),
    LBPLocationData('Skulldozer - Score Bubble 123', LEVEL, Kind.SCORE, uid=65187),
    LBPLocationData('Skulldozer - Score Bubble 124', LEVEL, Kind.SCORE, uid=65188),
    LBPLocationData('Skulldozer - Score Bubble 125', LEVEL, Kind.SCORE, uid=65189),
    LBPLocationData('Skulldozer - Score Bubble 126', LEVEL, Kind.SCORE, uid=65190),
    LBPLocationData('Skulldozer - Score Bubble 127', LEVEL, Kind.SCORE, uid=65194),
    LBPLocationData('Skulldozer - Score Bubble 128', LEVEL, Kind.SCORE, uid=65195),
    LBPLocationData('Skulldozer - Score Bubble 129', LEVEL, Kind.SCORE, uid=65196),
    LBPLocationData('Skulldozer - Score Bubble 130', LEVEL, Kind.SCORE, uid=65947),
    LBPLocationData('Skulldozer - Score Bubble 131', LEVEL, Kind.SCORE, uid=65948),
    LBPLocationData('Skulldozer - Score Bubble 132', LEVEL, Kind.SCORE, uid=65949),
    LBPLocationData('Skulldozer - Score Bubble 133', LEVEL, Kind.SCORE, uid=65950),
    LBPLocationData('Skulldozer - Score Bubble 134', LEVEL, Kind.SCORE, uid=65951),
    LBPLocationData('Skulldozer - Score Bubble 135', LEVEL, Kind.SCORE, uid=65952),
    LBPLocationData('Skulldozer - Score Bubble 136', LEVEL, Kind.SCORE, uid=65953),
    LBPLocationData('Skulldozer - Score Bubble 137', LEVEL, Kind.SCORE, uid=65954),
    LBPLocationData('Skulldozer - Score Bubble 138', LEVEL, Kind.SCORE, uid=65955),
    LBPLocationData('Skulldozer - Score Bubble 139', LEVEL, Kind.SCORE, uid=65956),
    LBPLocationData('Skulldozer - Score Bubble 140', LEVEL, Kind.SCORE, uid=65957),
    LBPLocationData('Skulldozer - Score Bubble 141', LEVEL, Kind.SCORE, uid=65958),
    LBPLocationData('Skulldozer - Score Bubble 142', LEVEL, Kind.SCORE, uid=65959),
    LBPLocationData('Skulldozer - Score Bubble 143', LEVEL, Kind.SCORE, uid=65960),
    LBPLocationData('Skulldozer - Score Bubble 144', LEVEL, Kind.SCORE, uid=65961),
    LBPLocationData('Skulldozer - Score Bubble 145', LEVEL, Kind.SCORE, uid=66745),
    LBPLocationData('Skulldozer - Score Bubble 146', LEVEL, Kind.SCORE, uid=66747),
    LBPLocationData('Skulldozer - Score Bubble 147', LEVEL, Kind.SCORE, uid=66751),
    LBPLocationData('Skulldozer - Score Bubble 148', LEVEL, Kind.SCORE, uid=66752),
    LBPLocationData('Skulldozer - Score Bubble 149', LEVEL, Kind.SCORE, uid=66753),
    LBPLocationData('Skulldozer - Score Bubble 150', LEVEL, Kind.SCORE, uid=66757),
    LBPLocationData('Skulldozer - Score Bubble 151', LEVEL, Kind.SCORE, uid=66758),
    LBPLocationData('Skulldozer - Score Bubble 152', LEVEL, Kind.SCORE, uid=66759),
    LBPLocationData('Skulldozer - Score Bubble 153', LEVEL, Kind.SCORE, uid=129603),
    LBPLocationData('Skulldozer - Score Bubble 154', LEVEL, Kind.SCORE, uid=129604),
    LBPLocationData('Skulldozer - Score Bubble 155', LEVEL, Kind.SCORE, uid=129605),
    LBPLocationData('Skulldozer - Score Bubble 156', LEVEL, Kind.SCORE, uid=129606),
    LBPLocationData('Skulldozer - Score Bubble 157', LEVEL, Kind.SCORE, uid=129607),
    LBPLocationData('Skulldozer - Score Bubble 158', LEVEL, Kind.SCORE, uid=129608),
    LBPLocationData('Skulldozer - Score Bubble 159', LEVEL, Kind.SCORE, uid=129609),
    LBPLocationData('Skulldozer - Score Bubble 160', LEVEL, Kind.SCORE, uid=129610),
    LBPLocationData('Skulldozer - Score Bubble 161', LEVEL, Kind.SCORE, uid=129611),
    LBPLocationData('Skulldozer - Score Bubble 162', LEVEL, Kind.SCORE, uid=477985),
    LBPLocationData('Skulldozer - Score Bubble 163', LEVEL, Kind.SCORE, uid=510539),
    LBPLocationData('Skulldozer - Score Bubble 164', LEVEL, Kind.SCORE, uid=510540),
    LBPLocationData('Skulldozer - Score Bubble 165', LEVEL, Kind.SCORE, uid=510541),
    LBPLocationData('Skulldozer - Score Bubble 166', LEVEL, Kind.SCORE, uid=510565),
    LBPLocationData('Skulldozer - Score Bubble 167', LEVEL, Kind.SCORE, uid=510566),
    LBPLocationData('Skulldozer - Score Bubble 168', LEVEL, Kind.SCORE, uid=510567),
    LBPLocationData('Skulldozer - Score Bubble 169', LEVEL, Kind.SCORE, uid=510568),
    LBPLocationData('Skulldozer - Score Bubble 170', LEVEL, Kind.SCORE, uid=510569),
    LBPLocationData('Skulldozer - Score Bubble 171', LEVEL, Kind.SCORE, uid=510570),
    LBPLocationData('Skulldozer - Score Bubble 172', LEVEL, Kind.SCORE, uid=511716),
    LBPLocationData('Skulldozer - Score Bubble 173', LEVEL, Kind.SCORE, uid=511717),
    LBPLocationData('Skulldozer - Score Bubble 174', LEVEL, Kind.SCORE, uid=511718),
    LBPLocationData('Skulldozer - Score Bubble 175', LEVEL, Kind.SCORE, uid=511736),
    LBPLocationData('Skulldozer - Score Bubble 176', LEVEL, Kind.SCORE, uid=511737),
    LBPLocationData('Skulldozer - Score Bubble 177', LEVEL, Kind.SCORE, uid=511738),
    LBPLocationData('Skulldozer - Score Bubble 178', LEVEL, Kind.SCORE, uid=511740),
    LBPLocationData('Skulldozer - Score Bubble 179', LEVEL, Kind.SCORE, uid=511741),
    LBPLocationData('Skulldozer - Score Bubble 180', LEVEL, Kind.SCORE, uid=511742),
    LBPLocationData('Skulldozer - Score Bubble 181', LEVEL, Kind.SCORE, uid=511744),
    LBPLocationData('Skulldozer - Score Bubble 182', LEVEL, Kind.SCORE, uid=511745),
    LBPLocationData('Skulldozer - Score Bubble 183', LEVEL, Kind.SCORE, uid=511746),
    LBPLocationData('Skulldozer - Score Bubble 184', LEVEL, Kind.SCORE, uid=515618),
    LBPLocationData('Skulldozer - Score Bubble 185', LEVEL, Kind.SCORE, uid=515619),
    LBPLocationData('Skulldozer - Score Bubble 186', LEVEL, Kind.SCORE, uid=515620),
    LBPLocationData('Skulldozer - Score Bubble 187', LEVEL, Kind.SCORE, uid=516173),
    LBPLocationData('Skulldozer - Score Bubble 188', LEVEL, Kind.SCORE, uid=516174),
    LBPLocationData('Skulldozer - Score Bubble 189', LEVEL, Kind.SCORE, uid=516175),
    LBPLocationData('Skulldozer - Score Bubble 190', LEVEL, Kind.SCORE, uid=516176),
    LBPLocationData('Skulldozer - Score Bubble 191', LEVEL, Kind.SCORE, uid=516177),
    LBPLocationData('Skulldozer - Score Bubble 192', LEVEL, Kind.SCORE, uid=516178),
    LBPLocationData('Skulldozer - Score Bubble 193', LEVEL, Kind.SCORE, uid=516179),
    LBPLocationData('Skulldozer - Score Bubble 194', LEVEL, Kind.SCORE, uid=516180),
    LBPLocationData('Skulldozer - Score Bubble 195', LEVEL, Kind.SCORE, uid=516181),
    LBPLocationData('Skulldozer - Score Bubble 196', LEVEL, Kind.SCORE, uid=516182),
    LBPLocationData('Skulldozer - Score Bubble 197', LEVEL, Kind.SCORE, uid=516183),
    LBPLocationData('Skulldozer - Score Bubble 198', LEVEL, Kind.SCORE, uid=516184),
    LBPLocationData('Skulldozer - Score Bubble 199', LEVEL, Kind.SCORE, uid=516185),
    LBPLocationData('Skulldozer - Score Bubble 200', LEVEL, Kind.SCORE, uid=516739),
    LBPLocationData('Skulldozer - Score Bubble 201', LEVEL, Kind.SCORE, uid=516740),
    LBPLocationData('Skulldozer - Score Bubble 202', LEVEL, Kind.SCORE, uid=516741),
    LBPLocationData('Skulldozer - Score Bubble 203', LEVEL, Kind.SCORE, uid=516742),
    LBPLocationData('Skulldozer - Score Bubble 204', LEVEL, Kind.SCORE, uid=516743),
    LBPLocationData('Skulldozer - Score Bubble 205', LEVEL, Kind.SCORE, uid=516744),
    LBPLocationData('Skulldozer - Score Bubble 206', LEVEL, Kind.SCORE, uid=516745),
    LBPLocationData('Skulldozer - Score Bubble 207', LEVEL, Kind.SCORE, uid=516746),
    LBPLocationData('Skulldozer - Score Bubble 208', LEVEL, Kind.SCORE, uid=516747),
    LBPLocationData('Skulldozer - Score Bubble 209', LEVEL, Kind.SCORE, uid=516748),
    LBPLocationData('Skulldozer - Score Bubble 210', LEVEL, Kind.SCORE, uid=516749),
    LBPLocationData('Skulldozer - Score Bubble 211', LEVEL, Kind.SCORE, uid=516750),
    LBPLocationData('Skulldozer - Score Bubble 212', LEVEL, Kind.SCORE, uid=516751),
    LBPLocationData('Skulldozer - Score Bubble 213', LEVEL, Kind.SCORE, uid=516752),
    LBPLocationData('Skulldozer - Score Bubble 214', LEVEL, Kind.SCORE, uid=516775),
    LBPLocationData('Skulldozer - Score Bubble 215', LEVEL, Kind.SCORE, uid=516776),
    LBPLocationData('Skulldozer - Score Bubble 216', LEVEL, Kind.SCORE, uid=516777),
    LBPLocationData('Skulldozer - Score Bubble 217', LEVEL, Kind.SCORE, uid=516778),
    LBPLocationData('Skulldozer - Score Bubble 218', LEVEL, Kind.SCORE, uid=516779),
    LBPLocationData('Skulldozer - Score Bubble 219', LEVEL, Kind.SCORE, uid=516780),
    LBPLocationData('Skulldozer - Score Bubble 220', LEVEL, Kind.SCORE, uid=516781),
    LBPLocationData('Skulldozer - Score Bubble 221', LEVEL, Kind.SCORE, uid=516782),
    LBPLocationData('Skulldozer - Score Bubble 222', LEVEL, Kind.SCORE, uid=516783),
    LBPLocationData('Skulldozer - Score Bubble 223', LEVEL, Kind.SCORE, uid=516784),
    LBPLocationData('Skulldozer - Score Bubble 224', LEVEL, Kind.SCORE, uid=516785),
    LBPLocationData('Skulldozer - Score Bubble 225', LEVEL, Kind.SCORE, uid=516786),
    LBPLocationData('Skulldozer - Score Bubble 226', LEVEL, Kind.SCORE, uid=516790),
    LBPLocationData('Skulldozer - Score Bubble 227', LEVEL, Kind.SCORE, uid=516791),
    LBPLocationData('Skulldozer - Score Bubble 228', LEVEL, Kind.SCORE, uid=516792),
    LBPLocationData('Skulldozer - Score Bubble 229', LEVEL, Kind.SCORE, uid=516793),
    LBPLocationData('Skulldozer - Score Bubble 230', LEVEL, Kind.SCORE, uid=516794),
    LBPLocationData('Skulldozer - Score Bubble 231', LEVEL, Kind.SCORE, uid=516795),
    LBPLocationData('Skulldozer - Score Bubble 232', LEVEL, Kind.SCORE, uid=516796),
    LBPLocationData('Skulldozer - Score Bubble 233', LEVEL, Kind.SCORE, uid=516797),
    LBPLocationData('Skulldozer - Score Bubble 234', LEVEL, Kind.SCORE, uid=516798),
    LBPLocationData('Skulldozer - Score Bubble 235', LEVEL, Kind.SCORE, uid=516800),
    LBPLocationData('Skulldozer - Score Bubble 236', LEVEL, Kind.SCORE, uid=516801),
    LBPLocationData('Skulldozer - Score Bubble 237', LEVEL, Kind.SCORE, uid=516802),
    LBPLocationData('Skulldozer - Score Bubble 238', LEVEL, Kind.SCORE, uid=516803),
    LBPLocationData('Skulldozer - Score Bubble 239', LEVEL, Kind.SCORE, uid=516804),
    LBPLocationData('Skulldozer - Score Bubble 240', LEVEL, Kind.SCORE, uid=516805),
    LBPLocationData('Skulldozer - Score Bubble 241', LEVEL, Kind.SCORE, uid=516818),
    LBPLocationData('Skulldozer - Score Bubble 242', LEVEL, Kind.SCORE, uid=516819),
    LBPLocationData('Skulldozer - Score Bubble 243', LEVEL, Kind.SCORE, uid=516820),
    LBPLocationData('Skulldozer - Score Bubble 244', LEVEL, Kind.SCORE, uid=516821),
    LBPLocationData('Skulldozer - Score Bubble 245', LEVEL, Kind.SCORE, uid=516822),
    LBPLocationData('Skulldozer - Score Bubble 246', LEVEL, Kind.SCORE, uid=516823),
    LBPLocationData('Skulldozer - Score Bubble 247', LEVEL, Kind.SCORE, uid=516824),
    LBPLocationData('Skulldozer - Score Bubble 248', LEVEL, Kind.SCORE, uid=516825),
    LBPLocationData('Skulldozer - Score Bubble 249', LEVEL, Kind.SCORE, uid=516826),
    LBPLocationData('Skulldozer - Score Bubble 250', LEVEL, Kind.SCORE, uid=516827),
    LBPLocationData('Skulldozer - Score Bubble 251', LEVEL, Kind.SCORE, uid=516828),
    LBPLocationData('Skulldozer - Score Bubble 252', LEVEL, Kind.SCORE, uid=516829),
    LBPLocationData('Skulldozer - Score Bubble 253', LEVEL, Kind.SCORE, uid=516830),
    LBPLocationData('Skulldozer - Score Bubble 254', LEVEL, Kind.SCORE, uid=516831),
    LBPLocationData('Skulldozer - Score Bubble 255', LEVEL, Kind.SCORE, uid=516832),
    LBPLocationData('Skulldozer - Score Bubble 256', LEVEL, Kind.SCORE, uid=537507),
    LBPLocationData('Skulldozer - Score Bubble 257', LEVEL, Kind.SCORE, uid=537508),
    LBPLocationData('Skulldozer - Score Bubble 258', LEVEL, Kind.SCORE, uid=537509),
    LBPLocationData('Skulldozer - Score Bubble 259', LEVEL, Kind.SCORE, uid=561695),
    LBPLocationData('Skulldozer - Score Bubble 260', LEVEL, Kind.SCORE, uid=561696),
    LBPLocationData('Skulldozer - Score Bubble 261', LEVEL, Kind.SCORE, uid=561697),
    LBPLocationData('Skulldozer - Score Bubble 262', LEVEL, Kind.SCORE, uid=561698),
    LBPLocationData('Skulldozer - Score Bubble 263', LEVEL, Kind.SCORE, uid=561699),
    LBPLocationData('Skulldozer - Score Bubble 264', LEVEL, Kind.SCORE, uid=561700),
    LBPLocationData('Skulldozer - Score Bubble 265', LEVEL, Kind.SCORE, uid=569549),
    LBPLocationData('Skulldozer - Score Bubble 266', LEVEL, Kind.SCORE, uid=569550),
    LBPLocationData('Skulldozer - Score Bubble 267', LEVEL, Kind.SCORE, uid=569551),
    LBPLocationData('Skulldozer - Prize Bubble 1 - Paper Weave', LEVEL, Kind.PRIZE, uid=516768, plan='g32010'),
    LBPLocationData('Skulldozer - Prize Bubble 2 - Treasure Box Body', LEVEL, Kind.PRIZE, uid=516769, plan='g51361'),
    LBPLocationData('Skulldozer - Prize Bubble 3 - Treasure Box Lid', LEVEL, Kind.PRIZE, uid=516770, plan='g51362'),
    LBPLocationData('Skulldozer - Prize Bubble 4 - Treasure Box Inside', LEVEL, Kind.PRIZE, uid=516771, plan='g51363'),
    LBPLocationData('Skulldozer - Prize Bubble 5 - Bowler Hat', LEVEL, Kind.PRIZE, uid=516772, plan='g51254'),
    LBPLocationData('Skulldozer - Prize Bubble 6 - Scary Skull', LEVEL, Kind.PRIZE, uid=516774, plan='g51252'),
    LBPLocationData('Skulldozer - Prize Bubble 7 - Graveyard Tux', LEVEL, Kind.PRIZE, uid=516809, plan='g48596'),
    LBPLocationData('Skulldozer - Prize Bubble 8 - Pirate Skull', LEVEL, Kind.PRIZE, uid=516817, plan='g51255'),
    LBPLocationData('Skulldozer - Prize Bubble 9 - Purple Piano', LEVEL, Kind.PRIZE, uid=516833, plan='g48607'),
    LBPLocationData('Skulldozer - Prize Bubble 10 - Owl Drawing', LEVEL, Kind.PRIZE, uid=516834, plan='g48606'),
    LBPLocationData('Skulldozer - Prize Bubble 11 - Hojaldra', LEVEL, Kind.PRIZE, uid=516835, plan='g48599'),
    LBPLocationData('Skulldozer - Prize Bubble 12 - Los Muertos', LEVEL, Kind.PRIZE, uid=516836, plan='g48598'),
    LBPLocationData('Skulldozer - Prize Bubble 13 - Red Fabric', LEVEL, Kind.PRIZE, uid=534701, plan='g32007'),
    LBPLocationData('Skulldozer - Prize Bubble 14 - Red Stitched Fabric', LEVEL, Kind.PRIZE, uid=534702, plan='g50785'),
    LBPLocationData('Skulldozer - Prize Bubble 15 - Ceramic Tile', LEVEL, Kind.PRIZE, uid=534703, plan='g32005'),
    LBPLocationData('Skulldozer - Prize Bubble 16 - Real Bone', LEVEL, Kind.PRIZE, uid=534704, plan='g36211'),
    LBPLocationData('Skulldozer - Prize Bubble 17 - Candle Stick', LEVEL, Kind.PRIZE, uid=534705, plan='g51307'),
    LBPLocationData('Skulldozer - Prize Bubble 18 - Wedding IntMusic', LEVEL, Kind.PRIZE, uid=575674, plan='g37290'),
    LBPLocationData('Skulldozer - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Skulldozer - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('Skulldozer - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('Skulldozer - Completion Reward 1 - Long Bunches Wig', LEVEL, Kind.REWARD, plan='g32469', condition=Kind.COMPLETE),
    LBPLocationData('Skulldozer - Completion Reward 2 - The Wedding', LEVEL, Kind.REWARD, plan='g31967', condition=Kind.COMPLETE),
    LBPLocationData('Skulldozer - All Prizes Reward 1 - Skulldozer', LEVEL, Kind.REWARD, plan='g52002', condition=Kind.ALL_PRIZES),
    LBPLocationData('Skulldozer - All Prizes Reward 2 - The Wedding Concept with Frame', LEVEL, Kind.REWARD, plan='g52804', condition=Kind.ALL_PRIZES),
    LBPLocationData('Skulldozer - All Prizes Reward 3 - Graveyard Concept', LEVEL, Kind.REWARD, plan='g52793', condition=Kind.ALL_PRIZES),
    LBPLocationData('Skulldozer - Ace Reward 1 - Roman Helmet', LEVEL, Kind.REWARD, plan='g32466', condition=Kind.ACE),
)
