from ..model import Kind, LBPLocationData

LEVEL = 'g26699'

LOCATIONS = (
    LBPLocationData('Swinging Safari - Score Bubble 1', LEVEL, Kind.SCORE, uid=240445),
    LBPLocationData('Swinging Safari - Score Bubble 2', LEVEL, Kind.SCORE, uid=240446),
    LBPLocationData('Swinging Safari - Score Bubble 3', LEVEL, Kind.SCORE, uid=240447),
    LBPLocationData('Swinging Safari - Score Bubble 4', LEVEL, Kind.SCORE, uid=240448),
    LBPLocationData('Swinging Safari - Score Bubble 5', LEVEL, Kind.SCORE, uid=240449),
    LBPLocationData('Swinging Safari - Score Bubble 6', LEVEL, Kind.SCORE, uid=267748),
    LBPLocationData('Swinging Safari - Score Bubble 7', LEVEL, Kind.SCORE, uid=267749),
    LBPLocationData('Swinging Safari - Score Bubble 8', LEVEL, Kind.SCORE, uid=267750),
    LBPLocationData('Swinging Safari - Score Bubble 9', LEVEL, Kind.SCORE, uid=267751),
    LBPLocationData('Swinging Safari - Score Bubble 10', LEVEL, Kind.SCORE, uid=275150),
    LBPLocationData('Swinging Safari - Score Bubble 11', LEVEL, Kind.SCORE, uid=276541),
    LBPLocationData('Swinging Safari - Score Bubble 12', LEVEL, Kind.SCORE, uid=281164),
    LBPLocationData('Swinging Safari - Score Bubble 13', LEVEL, Kind.SCORE, uid=281165),
    LBPLocationData('Swinging Safari - Score Bubble 14', LEVEL, Kind.SCORE, uid=281166),
    LBPLocationData('Swinging Safari - Score Bubble 15', LEVEL, Kind.SCORE, uid=281629),
    LBPLocationData('Swinging Safari - Score Bubble 16', LEVEL, Kind.SCORE, uid=281630),
    LBPLocationData('Swinging Safari - Score Bubble 17', LEVEL, Kind.SCORE, uid=281631),
    LBPLocationData('Swinging Safari - Score Bubble 18', LEVEL, Kind.SCORE, uid=281632),
    LBPLocationData('Swinging Safari - Score Bubble 19', LEVEL, Kind.SCORE, uid=281633),
    LBPLocationData('Swinging Safari - Score Bubble 20', LEVEL, Kind.SCORE, uid=304332),
    LBPLocationData('Swinging Safari - Score Bubble 21', LEVEL, Kind.SCORE, uid=305736),
    LBPLocationData('Swinging Safari - Score Bubble 22', LEVEL, Kind.SCORE, uid=305737),
    LBPLocationData('Swinging Safari - Score Bubble 23', LEVEL, Kind.SCORE, uid=305742),
    LBPLocationData('Swinging Safari - Score Bubble 24', LEVEL, Kind.SCORE, uid=305743),
    LBPLocationData('Swinging Safari - Score Bubble 25', LEVEL, Kind.SCORE, uid=305744),
    LBPLocationData('Swinging Safari - Score Bubble 26', LEVEL, Kind.SCORE, uid=305745),
    LBPLocationData('Swinging Safari - Score Bubble 27', LEVEL, Kind.SCORE, uid=305746),
    LBPLocationData('Swinging Safari - Score Bubble 28', LEVEL, Kind.SCORE, uid=305747),
    LBPLocationData('Swinging Safari - Score Bubble 29', LEVEL, Kind.SCORE, uid=305748),
    LBPLocationData('Swinging Safari - Score Bubble 30', LEVEL, Kind.SCORE, uid=305749),
    LBPLocationData('Swinging Safari - Score Bubble 31', LEVEL, Kind.SCORE, uid=305750),
    LBPLocationData('Swinging Safari - Score Bubble 32', LEVEL, Kind.SCORE, uid=310402),
    LBPLocationData('Swinging Safari - Score Bubble 33', LEVEL, Kind.SCORE, uid=480611),
    LBPLocationData('Swinging Safari - Score Bubble 34', LEVEL, Kind.SCORE, uid=480613),
    LBPLocationData('Swinging Safari - Score Bubble 35', LEVEL, Kind.SCORE, uid=480615),
    LBPLocationData('Swinging Safari - Score Bubble 36', LEVEL, Kind.SCORE, uid=480620),
    LBPLocationData('Swinging Safari - Score Bubble 37', LEVEL, Kind.SCORE, uid=480623),
    LBPLocationData('Swinging Safari - Score Bubble 38', LEVEL, Kind.SCORE, uid=480624),
    LBPLocationData('Swinging Safari - Score Bubble 39', LEVEL, Kind.SCORE, uid=480625),
    LBPLocationData('Swinging Safari - Score Bubble 40', LEVEL, Kind.SCORE, uid=481090),
    LBPLocationData('Swinging Safari - Score Bubble 41', LEVEL, Kind.SCORE, uid=481556),
    LBPLocationData('Swinging Safari - Score Bubble 42', LEVEL, Kind.SCORE, uid=482022),
    LBPLocationData('Swinging Safari - Score Bubble 43', LEVEL, Kind.SCORE, uid=482023),
    LBPLocationData('Swinging Safari - Score Bubble 44', LEVEL, Kind.SCORE, uid=482024),
    LBPLocationData('Swinging Safari - Score Bubble 45', LEVEL, Kind.SCORE, uid=482025),
    LBPLocationData('Swinging Safari - Score Bubble 46', LEVEL, Kind.SCORE, uid=482026),
    LBPLocationData('Swinging Safari - Score Bubble 47', LEVEL, Kind.SCORE, uid=482027),
    LBPLocationData('Swinging Safari - Score Bubble 48', LEVEL, Kind.SCORE, uid=482028),
    LBPLocationData('Swinging Safari - Score Bubble 49', LEVEL, Kind.SCORE, uid=482029),
    LBPLocationData('Swinging Safari - Score Bubble 50', LEVEL, Kind.SCORE, uid=482030),
    LBPLocationData('Swinging Safari - Score Bubble 51', LEVEL, Kind.SCORE, uid=482035),
    LBPLocationData('Swinging Safari - Score Bubble 52', LEVEL, Kind.SCORE, uid=482500),
    LBPLocationData('Swinging Safari - Score Bubble 53', LEVEL, Kind.SCORE, uid=482501),
    LBPLocationData('Swinging Safari - Score Bubble 54', LEVEL, Kind.SCORE, uid=482502),
    LBPLocationData('Swinging Safari - Score Bubble 55', LEVEL, Kind.SCORE, uid=483430),
    LBPLocationData('Swinging Safari - Score Bubble 56', LEVEL, Kind.SCORE, uid=483431),
    LBPLocationData('Swinging Safari - Score Bubble 57', LEVEL, Kind.SCORE, uid=483432),
    LBPLocationData('Swinging Safari - Score Bubble 58', LEVEL, Kind.SCORE, uid=483433),
    LBPLocationData('Swinging Safari - Score Bubble 59', LEVEL, Kind.SCORE, uid=483435),
    LBPLocationData('Swinging Safari - Score Bubble 60', LEVEL, Kind.SCORE, uid=483436),
    LBPLocationData('Swinging Safari - Score Bubble 61', LEVEL, Kind.SCORE, uid=483437),
    LBPLocationData('Swinging Safari - Score Bubble 62', LEVEL, Kind.SCORE, uid=483438),
    LBPLocationData('Swinging Safari - Score Bubble 63', LEVEL, Kind.SCORE, uid=483439),
    LBPLocationData('Swinging Safari - Score Bubble 64', LEVEL, Kind.SCORE, uid=483440),
    LBPLocationData('Swinging Safari - Score Bubble 65', LEVEL, Kind.SCORE, uid=483441),
    LBPLocationData('Swinging Safari - Score Bubble 66', LEVEL, Kind.SCORE, uid=483442),
    LBPLocationData('Swinging Safari - Score Bubble 67', LEVEL, Kind.SCORE, uid=483443),
    LBPLocationData('Swinging Safari - Score Bubble 68', LEVEL, Kind.SCORE, uid=483444),
    LBPLocationData('Swinging Safari - Score Bubble 69', LEVEL, Kind.SCORE, uid=483445),
    LBPLocationData('Swinging Safari - Score Bubble 70', LEVEL, Kind.SCORE, uid=483446),
    LBPLocationData('Swinging Safari - Score Bubble 71', LEVEL, Kind.SCORE, uid=483447),
    LBPLocationData('Swinging Safari - Score Bubble 72', LEVEL, Kind.SCORE, uid=483448),
    LBPLocationData('Swinging Safari - Score Bubble 73', LEVEL, Kind.SCORE, uid=484839),
    LBPLocationData('Swinging Safari - Score Bubble 74', LEVEL, Kind.SCORE, uid=484840),
    LBPLocationData('Swinging Safari - Score Bubble 75', LEVEL, Kind.SCORE, uid=484841),
    LBPLocationData('Swinging Safari - Score Bubble 76', LEVEL, Kind.SCORE, uid=487204),
    LBPLocationData('Swinging Safari - Score Bubble 77', LEVEL, Kind.SCORE, uid=667046),
    LBPLocationData('Swinging Safari - Score Bubble 78', LEVEL, Kind.SCORE, uid=667047),
    LBPLocationData('Swinging Safari - Score Bubble 79', LEVEL, Kind.SCORE, uid=667048),
    LBPLocationData('Swinging Safari - Score Bubble 80', LEVEL, Kind.SCORE, uid=667049),
    LBPLocationData('Swinging Safari - Score Bubble 81', LEVEL, Kind.SCORE, uid=667051),
    LBPLocationData('Swinging Safari - Score Bubble 82', LEVEL, Kind.SCORE, uid=667076),
    LBPLocationData('Swinging Safari - Score Bubble 83', LEVEL, Kind.SCORE, uid=667077),
    LBPLocationData('Swinging Safari - Score Bubble 84', LEVEL, Kind.SCORE, uid=667078),
    LBPLocationData('Swinging Safari - Score Bubble 85', LEVEL, Kind.SCORE, uid=667079),
    LBPLocationData('Swinging Safari - Score Bubble 86', LEVEL, Kind.SCORE, uid=667081),
    LBPLocationData('Swinging Safari - Score Bubble 87', LEVEL, Kind.SCORE, uid=667134),
    LBPLocationData('Swinging Safari - Score Bubble 88', LEVEL, Kind.SCORE, uid=667135),
    LBPLocationData('Swinging Safari - Score Bubble 89', LEVEL, Kind.SCORE, uid=667136),
    LBPLocationData('Swinging Safari - Score Bubble 90', LEVEL, Kind.SCORE, uid=667137),
    LBPLocationData('Swinging Safari - Score Bubble 91', LEVEL, Kind.SCORE, uid=667139),
    LBPLocationData('Swinging Safari - Score Bubble 92', LEVEL, Kind.SCORE, uid=667624),
    LBPLocationData('Swinging Safari - Score Bubble 93', LEVEL, Kind.SCORE, uid=667625),
    LBPLocationData('Swinging Safari - Score Bubble 94', LEVEL, Kind.SCORE, uid=667626),
    LBPLocationData('Swinging Safari - Score Bubble 95', LEVEL, Kind.SCORE, uid=667627),
    LBPLocationData('Swinging Safari - Score Bubble 96', LEVEL, Kind.SCORE, uid=667629),
    LBPLocationData('Swinging Safari - Score Bubble 97', LEVEL, Kind.SCORE, uid=667653),
    LBPLocationData('Swinging Safari - Score Bubble 98', LEVEL, Kind.SCORE, uid=667654),
    LBPLocationData('Swinging Safari - Score Bubble 99', LEVEL, Kind.SCORE, uid=667655),
    LBPLocationData('Swinging Safari - Score Bubble 100', LEVEL, Kind.SCORE, uid=667656),
    LBPLocationData('Swinging Safari - Score Bubble 101', LEVEL, Kind.SCORE, uid=667658),
    LBPLocationData('Swinging Safari - Score Bubble 102', LEVEL, Kind.SCORE, uid=687065),
    LBPLocationData('Swinging Safari - Prize Bubble 1 - Giraffe &Tree & Platform', LEVEL, Kind.PRIZE, uid=118839, plan='g46748'),
    LBPLocationData('Swinging Safari - Prize Bubble 2 - Orange Foliage', LEVEL, Kind.PRIZE, uid=118841, plan='g33425'),
    LBPLocationData('Swinging Safari - Prize Bubble 3 - Horror Face', LEVEL, Kind.PRIZE, uid=119528, plan='g33397'),
    LBPLocationData('Swinging Safari - Prize Bubble 4 - Large Drum', LEVEL, Kind.PRIZE, uid=119551, plan='g33449'),
    LBPLocationData('Swinging Safari - Prize Bubble 5 - Leather & Beaded Wood', LEVEL, Kind.PRIZE, uid=121023, plan='g33422'),
    LBPLocationData('Swinging Safari - Prize Bubble 6 - Hanging Ape', LEVEL, Kind.PRIZE, uid=123106, plan='g56159'),
    LBPLocationData('Swinging Safari - Prize Bubble 7 - Real Green Leaf', LEVEL, Kind.PRIZE, uid=123127, plan='g33373'),
    LBPLocationData('Swinging Safari - Prize Bubble 8 - Zig-Zag Fabric', LEVEL, Kind.PRIZE, uid=234875, plan='g33428'),
    LBPLocationData('Swinging Safari - Prize Bubble 9 - Voodoo Face', LEVEL, Kind.PRIZE, uid=303854, plan='g33398', players=2),
    LBPLocationData('Swinging Safari - Prize Bubble 10 - Real Brown Leaf', LEVEL, Kind.PRIZE, uid=303855, plan='g33374', players=2),
    LBPLocationData('Swinging Safari - Prize Bubble 11 - Grey African Mask', LEVEL, Kind.PRIZE, uid=340174, plan='g33380'),
    LBPLocationData('Swinging Safari - Prize Bubble 12 - Orange African Mask', LEVEL, Kind.PRIZE, uid=340175, plan='g33379'),
    LBPLocationData('Swinging Safari - Prize Bubble 13 - Brown African Mask', LEVEL, Kind.PRIZE, uid=340176, plan='g33378'),
    LBPLocationData('Swinging Safari - Prize Bubble 14 - Giraffe &Tree', LEVEL, Kind.PRIZE, uid=389838, plan='g46757'),
    LBPLocationData('Swinging Safari - Prize Bubble 15 - Shield 2', LEVEL, Kind.PRIZE, uid=478286, plan='g33372'),
    LBPLocationData('Swinging Safari - Prize Bubble 16 - Zebra', LEVEL, Kind.PRIZE, uid=551053, plan='g33448'),
    LBPLocationData('Swinging Safari - Prize Bubble 17 - Zebra Tail', LEVEL, Kind.PRIZE, uid=551054, plan='g33403'),
    LBPLocationData('Swinging Safari - Prize Bubble 18 - Cats Eyes', LEVEL, Kind.PRIZE, uid=551055, plan='g33405'),
    LBPLocationData("Swinging Safari - Prize Bubble 19 - Lion's Mane", LEVEL, Kind.PRIZE, uid=551056, plan='g33406'),
    LBPLocationData('Swinging Safari - Prize Bubble 20 - Zebra Head', LEVEL, Kind.PRIZE, uid=551057, plan='g33407'),
    LBPLocationData('Swinging Safari - Prize Bubble 21 - Cute Lion Ears', LEVEL, Kind.PRIZE, uid=551058, plan='g33408'),
    LBPLocationData("Swinging Safari - Prize Bubble 22 - Lion's Tail", LEVEL, Kind.PRIZE, uid=551059, plan='g33411'),
    LBPLocationData('Swinging Safari - Prize Bubble 23 - Scary Fangs', LEVEL, Kind.PRIZE, uid=551060, plan='g33410'),
    LBPLocationData('Swinging Safari - Prize Bubble 24 - Lion Nose', LEVEL, Kind.PRIZE, uid=551061, plan='g33409'),
    LBPLocationData('Swinging Safari - Prize Bubble 25 - Grin Face', LEVEL, Kind.PRIZE, uid=553382, plan='g33396'),
    LBPLocationData('Swinging Safari - Prize Bubble 26 - Submarine Launcher', LEVEL, Kind.PRIZE, uid=554766, plan='g48193'),
    LBPLocationData('Swinging Safari - Prize Bubble 27 - Peacock Feather', LEVEL, Kind.PRIZE, uid=562144, plan='g51311'),
    LBPLocationData('Swinging Safari - Prize Bubble 28 - Large Peacock Feather', LEVEL, Kind.PRIZE, uid=562145, plan='g51261'),
    LBPLocationData('Swinging Safari - Prize Bubble 29 - Seaweed', LEVEL, Kind.PRIZE, uid=562607, plan='g51316'),
    LBPLocationData('Swinging Safari - Prize Bubble 30 - Blue & Orange Fish', LEVEL, Kind.PRIZE, uid=562608, plan='g51317'),
    LBPLocationData('Swinging Safari - Prize Bubble 31 - Bunny Ear', LEVEL, Kind.PRIZE, uid=563070, plan='g51259'),
    LBPLocationData('Swinging Safari - Prize Bubble 32 - Sea Shell', LEVEL, Kind.PRIZE, uid=563071, plan='g51314'),
    LBPLocationData('Swinging Safari - Prize Bubble 33 - Pink Fish', LEVEL, Kind.PRIZE, uid=563533, plan='g51318'),
    LBPLocationData('Swinging Safari - Prize Bubble 34 - Seahorse', LEVEL, Kind.PRIZE, uid=563534, plan='g51312'),
    LBPLocationData('Swinging Safari - Prize Bubble 35 - Sharp Tooth', LEVEL, Kind.PRIZE, uid=563535, plan='g51262'),
    LBPLocationData('Swinging Safari - Prize Bubble 36 - Barnacle', LEVEL, Kind.PRIZE, uid=563536, plan='g51315'),
    LBPLocationData('Swinging Safari - Prize Bubble 37 - Mean Piranha Fish', LEVEL, Kind.PRIZE, uid=563998, plan='g51276', players=2),
    LBPLocationData('Swinging Safari - Prize Bubble 38 - Orange Boar Fish', LEVEL, Kind.PRIZE, uid=563999, plan='g51277', players=2),
    LBPLocationData('Swinging Safari - Prize Bubble 39 - Octopus Tentacle', LEVEL, Kind.PRIZE, uid=564000, plan='g51280'),
    LBPLocationData('Swinging Safari - Prize Bubble 40 - Big Crab Claw', LEVEL, Kind.PRIZE, uid=564001, plan='g51279', players=2),
    LBPLocationData('Swinging Safari - Prize Bubble 41 - Starfish', LEVEL, Kind.PRIZE, uid=564926, plan='g51313'),
    LBPLocationData('Swinging Safari - Prize Bubble 42 - Stylised Antelope', LEVEL, Kind.PRIZE, uid=572310, plan='g33391'),
    LBPLocationData('Swinging Safari - Prize Bubble 43 - Cork Hat', LEVEL, Kind.PRIZE, uid=573257, plan='g32483', players=2),
    LBPLocationData('Swinging Safari - Prize Bubble 44 - Stripy Lycra', LEVEL, Kind.PRIZE, uid=573258, plan='g34381'),
    LBPLocationData('Swinging Safari - Prize Bubble 45 - Beaded Fabric', LEVEL, Kind.PRIZE, uid=573720, plan='g33431'),
    LBPLocationData('Swinging Safari - Prize Bubble 46 - Wobbly Ape', LEVEL, Kind.PRIZE, uid=574182, plan='g48566'),
    LBPLocationData('Swinging Safari - Prize Bubble 47 - Butterfly', LEVEL, Kind.PRIZE, uid=574645, plan='g51310'),
    LBPLocationData('Swinging Safari - Prize Bubble 48 - Bird Wing', LEVEL, Kind.PRIZE, uid=575108, plan='g51278'),
    LBPLocationData('Swinging Safari - Prize Bubble 49 - Lion Mask', LEVEL, Kind.PRIZE, uid=575571, plan='g33412'),
    LBPLocationData('Swinging Safari - Prize Bubble 50 - Jumping Ape', LEVEL, Kind.PRIZE, uid=581156, plan='g46765'),
    LBPLocationData('Swinging Safari - Prize Bubble 51 - Fluffy Tree', LEVEL, Kind.PRIZE, uid=601044, plan='g33387'),
    LBPLocationData('Swinging Safari - Prize Bubble 52 - Banana', LEVEL, Kind.PRIZE, uid=601045, plan='g51281'),
    LBPLocationData('Swinging Safari - Prize Bubble 53 - Zebra Skin Pattern', LEVEL, Kind.PRIZE, uid=614417, plan='g54783'),
    LBPLocationData("Swinging Safari - Prize Bubble 54 - 'Tapha Niang'", LEVEL, Kind.PRIZE, uid=687529, plan='g33145'),
    LBPLocationData('Swinging Safari - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Swinging Safari - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('Swinging Safari - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('Swinging Safari - Completion Reward 1 - Pink Fashion Sunglasses', LEVEL, Kind.REWARD, plan='g51058', condition=Kind.COMPLETE),
    LBPLocationData('Swinging Safari - Completion Reward 2 - Green Daisy', LEVEL, Kind.REWARD, plan='g34382', condition=Kind.COMPLETE),
    LBPLocationData('Swinging Safari - All Prizes Reward 1 - The Savannah Concept with Frame', LEVEL, Kind.REWARD, plan='g52800', condition=Kind.ALL_PRIZES),
    LBPLocationData('Swinging Safari - All Prizes Reward 2 - Savannah Concept', LEVEL, Kind.REWARD, plan='g52788', condition=Kind.ALL_PRIZES),
    LBPLocationData('Swinging Safari - Ace Reward 1 - Ringmaster Jacket', LEVEL, Kind.REWARD, plan='g39757', condition=Kind.ACE),
    LBPLocationData('Swinging Safari - Sticker Switch 1 - Wooden Steed', LEVEL, Kind.STICKER_SWITCH, uid=312715, plan='g32128'),
    LBPLocationData('Swinging Safari - Sticker Switch 2 - English Rose', LEVEL, Kind.STICKER_SWITCH, uid=386130, plan='g32153'),
)
