from rule_builder.rules import Has

from ..model import Kind, LBPLocationData

LEVEL = 'g26606'

LOCATIONS = (
    LBPLocationData('The Wedding Reception - Score Bubble 1', LEVEL, Kind.SCORE, uid=15880),
    LBPLocationData('The Wedding Reception - Score Bubble 2', LEVEL, Kind.SCORE, uid=15881),
    LBPLocationData('The Wedding Reception - Score Bubble 3', LEVEL, Kind.SCORE, uid=15882),
    LBPLocationData('The Wedding Reception - Score Bubble 4', LEVEL, Kind.SCORE, uid=15883),
    LBPLocationData('The Wedding Reception - Score Bubble 5', LEVEL, Kind.SCORE, uid=15884),
    LBPLocationData('The Wedding Reception - Score Bubble 6', LEVEL, Kind.SCORE, uid=15885),
    LBPLocationData('The Wedding Reception - Score Bubble 7', LEVEL, Kind.SCORE, uid=15886),
    LBPLocationData('The Wedding Reception - Score Bubble 8', LEVEL, Kind.SCORE, uid=15887),
    LBPLocationData('The Wedding Reception - Score Bubble 9', LEVEL, Kind.SCORE, uid=15888),
    LBPLocationData('The Wedding Reception - Score Bubble 10', LEVEL, Kind.SCORE, uid=15889),
    LBPLocationData('The Wedding Reception - Score Bubble 11', LEVEL, Kind.SCORE, uid=15890),
    LBPLocationData('The Wedding Reception - Score Bubble 12', LEVEL, Kind.SCORE, uid=15891),
    LBPLocationData('The Wedding Reception - Score Bubble 13', LEVEL, Kind.SCORE, uid=15892),
    LBPLocationData('The Wedding Reception - Score Bubble 14', LEVEL, Kind.SCORE, uid=15893),
    LBPLocationData('The Wedding Reception - Score Bubble 15', LEVEL, Kind.SCORE, uid=15894),
    LBPLocationData('The Wedding Reception - Score Bubble 16', LEVEL, Kind.SCORE, uid=15895),
    LBPLocationData('The Wedding Reception - Score Bubble 17', LEVEL, Kind.SCORE, uid=15896),
    LBPLocationData('The Wedding Reception - Score Bubble 18', LEVEL, Kind.SCORE, uid=15897),
    LBPLocationData('The Wedding Reception - Score Bubble 19', LEVEL, Kind.SCORE, uid=15898),
    LBPLocationData('The Wedding Reception - Score Bubble 20', LEVEL, Kind.SCORE, uid=15899),
    LBPLocationData('The Wedding Reception - Score Bubble 21', LEVEL, Kind.SCORE, uid=16100),
    LBPLocationData('The Wedding Reception - Score Bubble 22', LEVEL, Kind.SCORE, uid=16101),
    LBPLocationData('The Wedding Reception - Score Bubble 23', LEVEL, Kind.SCORE, uid=16102),
    LBPLocationData('The Wedding Reception - Score Bubble 24', LEVEL, Kind.SCORE, uid=16103),
    LBPLocationData('The Wedding Reception - Score Bubble 25', LEVEL, Kind.SCORE, uid=16104),
    LBPLocationData('The Wedding Reception - Score Bubble 26', LEVEL, Kind.SCORE, uid=41499),
    LBPLocationData('The Wedding Reception - Score Bubble 27', LEVEL, Kind.SCORE, uid=41500),
    LBPLocationData('The Wedding Reception - Score Bubble 28', LEVEL, Kind.SCORE, uid=41501),
    LBPLocationData('The Wedding Reception - Score Bubble 29', LEVEL, Kind.SCORE, uid=41502),
    LBPLocationData('The Wedding Reception - Score Bubble 30', LEVEL, Kind.SCORE, uid=45125),
    LBPLocationData('The Wedding Reception - Score Bubble 31', LEVEL, Kind.SCORE, uid=45126),
    LBPLocationData('The Wedding Reception - Score Bubble 32', LEVEL, Kind.SCORE, uid=45127),
    LBPLocationData('The Wedding Reception - Score Bubble 33', LEVEL, Kind.SCORE, uid=45128),
    LBPLocationData('The Wedding Reception - Score Bubble 34', LEVEL, Kind.SCORE, uid=45129),
    LBPLocationData('The Wedding Reception - Score Bubble 35', LEVEL, Kind.SCORE, uid=45130),
    LBPLocationData('The Wedding Reception - Score Bubble 36', LEVEL, Kind.SCORE, uid=45131),
    LBPLocationData('The Wedding Reception - Score Bubble 37', LEVEL, Kind.SCORE, uid=45132),
    LBPLocationData('The Wedding Reception - Score Bubble 38', LEVEL, Kind.SCORE, uid=45133),
    LBPLocationData('The Wedding Reception - Score Bubble 39', LEVEL, Kind.SCORE, uid=45134),
    LBPLocationData('The Wedding Reception - Score Bubble 40', LEVEL, Kind.SCORE, uid=45135),
    LBPLocationData('The Wedding Reception - Score Bubble 41', LEVEL, Kind.SCORE, uid=45136),
    LBPLocationData('The Wedding Reception - Score Bubble 42', LEVEL, Kind.SCORE, uid=45137),
    LBPLocationData('The Wedding Reception - Score Bubble 43', LEVEL, Kind.SCORE, uid=45140),
    LBPLocationData('The Wedding Reception - Score Bubble 44', LEVEL, Kind.SCORE, uid=45141),
    LBPLocationData('The Wedding Reception - Score Bubble 45', LEVEL, Kind.SCORE, uid=54957),
    LBPLocationData('The Wedding Reception - Score Bubble 46', LEVEL, Kind.SCORE, uid=54958),
    LBPLocationData('The Wedding Reception - Score Bubble 47', LEVEL, Kind.SCORE, uid=54959),
    LBPLocationData('The Wedding Reception - Score Bubble 48', LEVEL, Kind.SCORE, uid=54960),
    LBPLocationData('The Wedding Reception - Score Bubble 49', LEVEL, Kind.SCORE, uid=54961),
    LBPLocationData('The Wedding Reception - Score Bubble 50', LEVEL, Kind.SCORE, uid=54962),
    LBPLocationData('The Wedding Reception - Score Bubble 51', LEVEL, Kind.SCORE, uid=54963),
    LBPLocationData('The Wedding Reception - Score Bubble 52', LEVEL, Kind.SCORE, uid=54964),
    LBPLocationData('The Wedding Reception - Score Bubble 53', LEVEL, Kind.SCORE, uid=54965),
    LBPLocationData('The Wedding Reception - Score Bubble 54', LEVEL, Kind.SCORE, uid=54966),
    LBPLocationData('The Wedding Reception - Score Bubble 55', LEVEL, Kind.SCORE, uid=54967),
    LBPLocationData('The Wedding Reception - Score Bubble 56', LEVEL, Kind.SCORE, uid=54968),
    LBPLocationData('The Wedding Reception - Score Bubble 57', LEVEL, Kind.SCORE, uid=54969),
    LBPLocationData('The Wedding Reception - Score Bubble 58', LEVEL, Kind.SCORE, uid=54972),
    LBPLocationData('The Wedding Reception - Score Bubble 59', LEVEL, Kind.SCORE, uid=54973),
    LBPLocationData('The Wedding Reception - Score Bubble 60', LEVEL, Kind.SCORE, uid=55146),
    LBPLocationData('The Wedding Reception - Score Bubble 61', LEVEL, Kind.SCORE, uid=55147),
    LBPLocationData('The Wedding Reception - Score Bubble 62', LEVEL, Kind.SCORE, uid=55148),
    LBPLocationData('The Wedding Reception - Score Bubble 63', LEVEL, Kind.SCORE, uid=55149),
    LBPLocationData('The Wedding Reception - Score Bubble 64', LEVEL, Kind.SCORE, uid=55150),
    LBPLocationData('The Wedding Reception - Score Bubble 65', LEVEL, Kind.SCORE, uid=55151),
    LBPLocationData('The Wedding Reception - Score Bubble 66', LEVEL, Kind.SCORE, uid=55152),
    LBPLocationData('The Wedding Reception - Score Bubble 67', LEVEL, Kind.SCORE, uid=55153),
    LBPLocationData('The Wedding Reception - Score Bubble 68', LEVEL, Kind.SCORE, uid=55154),
    LBPLocationData('The Wedding Reception - Score Bubble 69', LEVEL, Kind.SCORE, uid=55155),
    LBPLocationData('The Wedding Reception - Score Bubble 70', LEVEL, Kind.SCORE, uid=55156),
    LBPLocationData('The Wedding Reception - Score Bubble 71', LEVEL, Kind.SCORE, uid=55157),
    LBPLocationData('The Wedding Reception - Score Bubble 72', LEVEL, Kind.SCORE, uid=55158),
    LBPLocationData('The Wedding Reception - Score Bubble 73', LEVEL, Kind.SCORE, uid=55161),
    LBPLocationData('The Wedding Reception - Score Bubble 74', LEVEL, Kind.SCORE, uid=55162),
    LBPLocationData('The Wedding Reception - Score Bubble 75', LEVEL, Kind.SCORE, uid=55372),
    LBPLocationData('The Wedding Reception - Score Bubble 76', LEVEL, Kind.SCORE, uid=55373),
    LBPLocationData('The Wedding Reception - Score Bubble 77', LEVEL, Kind.SCORE, uid=55374),
    LBPLocationData('The Wedding Reception - Score Bubble 78', LEVEL, Kind.SCORE, uid=55375),
    LBPLocationData('The Wedding Reception - Score Bubble 79', LEVEL, Kind.SCORE, uid=55376),
    LBPLocationData('The Wedding Reception - Score Bubble 80', LEVEL, Kind.SCORE, uid=55377),
    LBPLocationData('The Wedding Reception - Score Bubble 81', LEVEL, Kind.SCORE, uid=55378),
    LBPLocationData('The Wedding Reception - Score Bubble 82', LEVEL, Kind.SCORE, uid=55379),
    LBPLocationData('The Wedding Reception - Score Bubble 83', LEVEL, Kind.SCORE, uid=55380),
    LBPLocationData('The Wedding Reception - Score Bubble 84', LEVEL, Kind.SCORE, uid=55381),
    LBPLocationData('The Wedding Reception - Score Bubble 85', LEVEL, Kind.SCORE, uid=55382),
    LBPLocationData('The Wedding Reception - Score Bubble 86', LEVEL, Kind.SCORE, uid=55383),
    LBPLocationData('The Wedding Reception - Score Bubble 87', LEVEL, Kind.SCORE, uid=55384),
    LBPLocationData('The Wedding Reception - Score Bubble 88', LEVEL, Kind.SCORE, uid=55387),
    LBPLocationData('The Wedding Reception - Score Bubble 89', LEVEL, Kind.SCORE, uid=55388),
    LBPLocationData('The Wedding Reception - Score Bubble 90', LEVEL, Kind.SCORE, uid=55769),
    LBPLocationData('The Wedding Reception - Score Bubble 91', LEVEL, Kind.SCORE, uid=55770),
    LBPLocationData('The Wedding Reception - Score Bubble 92', LEVEL, Kind.SCORE, uid=55771),
    LBPLocationData('The Wedding Reception - Score Bubble 93', LEVEL, Kind.SCORE, uid=55772),
    LBPLocationData('The Wedding Reception - Score Bubble 94', LEVEL, Kind.SCORE, uid=55773),
    LBPLocationData('The Wedding Reception - Score Bubble 95', LEVEL, Kind.SCORE, uid=55774),
    LBPLocationData('The Wedding Reception - Score Bubble 96', LEVEL, Kind.SCORE, uid=55775),
    LBPLocationData('The Wedding Reception - Score Bubble 97', LEVEL, Kind.SCORE, uid=55776),
    LBPLocationData('The Wedding Reception - Score Bubble 98', LEVEL, Kind.SCORE, uid=55777),
    LBPLocationData('The Wedding Reception - Score Bubble 99', LEVEL, Kind.SCORE, uid=55778),
    LBPLocationData('The Wedding Reception - Score Bubble 100', LEVEL, Kind.SCORE, uid=55779),
    LBPLocationData('The Wedding Reception - Score Bubble 101', LEVEL, Kind.SCORE, uid=55780),
    LBPLocationData('The Wedding Reception - Score Bubble 102', LEVEL, Kind.SCORE, uid=55781),
    LBPLocationData('The Wedding Reception - Score Bubble 103', LEVEL, Kind.SCORE, uid=55784),
    LBPLocationData('The Wedding Reception - Score Bubble 104', LEVEL, Kind.SCORE, uid=55785),
    LBPLocationData('The Wedding Reception - Score Bubble 105', LEVEL, Kind.SCORE, uid=55795),
    LBPLocationData('The Wedding Reception - Score Bubble 106', LEVEL, Kind.SCORE, uid=55796),
    LBPLocationData('The Wedding Reception - Score Bubble 107', LEVEL, Kind.SCORE, uid=55798),
    LBPLocationData('The Wedding Reception - Score Bubble 108', LEVEL, Kind.SCORE, uid=55799),
    LBPLocationData('The Wedding Reception - Score Bubble 109', LEVEL, Kind.SCORE, uid=55800),
    LBPLocationData('The Wedding Reception - Score Bubble 110', LEVEL, Kind.SCORE, uid=55801),
    LBPLocationData('The Wedding Reception - Score Bubble 111', LEVEL, Kind.SCORE, uid=55802),
    LBPLocationData('The Wedding Reception - Score Bubble 112', LEVEL, Kind.SCORE, uid=55803),
    LBPLocationData('The Wedding Reception - Score Bubble 113', LEVEL, Kind.SCORE, uid=56832),
    LBPLocationData('The Wedding Reception - Score Bubble 114', LEVEL, Kind.SCORE, uid=56833),
    LBPLocationData('The Wedding Reception - Score Bubble 115', LEVEL, Kind.SCORE, uid=56834),
    LBPLocationData('The Wedding Reception - Score Bubble 116', LEVEL, Kind.SCORE, uid=56838),
    LBPLocationData('The Wedding Reception - Score Bubble 117', LEVEL, Kind.SCORE, uid=56839),
    LBPLocationData('The Wedding Reception - Score Bubble 118', LEVEL, Kind.SCORE, uid=56840),
    LBPLocationData('The Wedding Reception - Score Bubble 119', LEVEL, Kind.SCORE, uid=57581),
    LBPLocationData('The Wedding Reception - Score Bubble 120', LEVEL, Kind.SCORE, uid=57620),
    LBPLocationData('The Wedding Reception - Score Bubble 121', LEVEL, Kind.SCORE, uid=57621),
    LBPLocationData('The Wedding Reception - Score Bubble 122', LEVEL, Kind.SCORE, uid=57622),
    LBPLocationData('The Wedding Reception - Score Bubble 123', LEVEL, Kind.SCORE, uid=57623),
    LBPLocationData('The Wedding Reception - Score Bubble 124', LEVEL, Kind.SCORE, uid=57628),
    LBPLocationData('The Wedding Reception - Score Bubble 125', LEVEL, Kind.SCORE, uid=57631),
    LBPLocationData('The Wedding Reception - Score Bubble 126', LEVEL, Kind.SCORE, uid=57632),
    LBPLocationData('The Wedding Reception - Score Bubble 127', LEVEL, Kind.SCORE, uid=57633),
    LBPLocationData('The Wedding Reception - Score Bubble 128', LEVEL, Kind.SCORE, uid=57634),
    LBPLocationData('The Wedding Reception - Score Bubble 129', LEVEL, Kind.SCORE, uid=57639),
    LBPLocationData('The Wedding Reception - Score Bubble 130', LEVEL, Kind.SCORE, uid=57642),
    LBPLocationData('The Wedding Reception - Score Bubble 131', LEVEL, Kind.SCORE, uid=57643),
    LBPLocationData('The Wedding Reception - Score Bubble 132', LEVEL, Kind.SCORE, uid=57644),
    LBPLocationData('The Wedding Reception - Score Bubble 133', LEVEL, Kind.SCORE, uid=57645),
    LBPLocationData('The Wedding Reception - Score Bubble 134', LEVEL, Kind.SCORE, uid=57650),
    LBPLocationData('The Wedding Reception - Score Bubble 135', LEVEL, Kind.SCORE, uid=57653),
    LBPLocationData('The Wedding Reception - Score Bubble 136', LEVEL, Kind.SCORE, uid=57654),
    LBPLocationData('The Wedding Reception - Score Bubble 137', LEVEL, Kind.SCORE, uid=57655),
    LBPLocationData('The Wedding Reception - Score Bubble 138', LEVEL, Kind.SCORE, uid=57656),
    LBPLocationData('The Wedding Reception - Score Bubble 139', LEVEL, Kind.SCORE, uid=57661),
    LBPLocationData('The Wedding Reception - Score Bubble 140', LEVEL, Kind.SCORE, uid=57664),
    LBPLocationData('The Wedding Reception - Score Bubble 141', LEVEL, Kind.SCORE, uid=57665),
    LBPLocationData('The Wedding Reception - Score Bubble 142', LEVEL, Kind.SCORE, uid=57666),
    LBPLocationData('The Wedding Reception - Score Bubble 143', LEVEL, Kind.SCORE, uid=57667),
    LBPLocationData('The Wedding Reception - Score Bubble 144', LEVEL, Kind.SCORE, uid=57672),
    LBPLocationData('The Wedding Reception - Score Bubble 145', LEVEL, Kind.SCORE, uid=57675),
    LBPLocationData('The Wedding Reception - Score Bubble 146', LEVEL, Kind.SCORE, uid=57676),
    LBPLocationData('The Wedding Reception - Score Bubble 147', LEVEL, Kind.SCORE, uid=57677),
    LBPLocationData('The Wedding Reception - Score Bubble 148', LEVEL, Kind.SCORE, uid=57678),
    LBPLocationData('The Wedding Reception - Score Bubble 149', LEVEL, Kind.SCORE, uid=57683),
    LBPLocationData('The Wedding Reception - Score Bubble 150', LEVEL, Kind.SCORE, uid=57686),
    LBPLocationData('The Wedding Reception - Score Bubble 151', LEVEL, Kind.SCORE, uid=57687),
    LBPLocationData('The Wedding Reception - Score Bubble 152', LEVEL, Kind.SCORE, uid=57688),
    LBPLocationData('The Wedding Reception - Score Bubble 153', LEVEL, Kind.SCORE, uid=57689),
    LBPLocationData('The Wedding Reception - Score Bubble 154', LEVEL, Kind.SCORE, uid=57694),
    LBPLocationData('The Wedding Reception - Score Bubble 155', LEVEL, Kind.SCORE, uid=57697),
    LBPLocationData('The Wedding Reception - Score Bubble 156', LEVEL, Kind.SCORE, uid=57698),
    LBPLocationData('The Wedding Reception - Score Bubble 157', LEVEL, Kind.SCORE, uid=57699),
    LBPLocationData('The Wedding Reception - Score Bubble 158', LEVEL, Kind.SCORE, uid=57700),
    LBPLocationData('The Wedding Reception - Score Bubble 159', LEVEL, Kind.SCORE, uid=57720),
    LBPLocationData('The Wedding Reception - Score Bubble 160', LEVEL, Kind.SCORE, uid=57723),
    LBPLocationData('The Wedding Reception - Score Bubble 161', LEVEL, Kind.SCORE, uid=57724),
    LBPLocationData('The Wedding Reception - Score Bubble 162', LEVEL, Kind.SCORE, uid=57725),
    LBPLocationData('The Wedding Reception - Score Bubble 163', LEVEL, Kind.SCORE, uid=57726),
    LBPLocationData('The Wedding Reception - Score Bubble 164', LEVEL, Kind.SCORE, uid=57731),
    LBPLocationData('The Wedding Reception - Score Bubble 165', LEVEL, Kind.SCORE, uid=57734),
    LBPLocationData('The Wedding Reception - Score Bubble 166', LEVEL, Kind.SCORE, uid=57735),
    LBPLocationData('The Wedding Reception - Score Bubble 167', LEVEL, Kind.SCORE, uid=57736),
    LBPLocationData('The Wedding Reception - Score Bubble 168', LEVEL, Kind.SCORE, uid=57737),
    LBPLocationData('The Wedding Reception - Score Bubble 169', LEVEL, Kind.SCORE, uid=57911),
    LBPLocationData('The Wedding Reception - Score Bubble 170', LEVEL, Kind.SCORE, uid=57915),
    LBPLocationData('The Wedding Reception - Score Bubble 171', LEVEL, Kind.SCORE, uid=57967),
    LBPLocationData('The Wedding Reception - Score Bubble 172', LEVEL, Kind.SCORE, uid=57969),
    LBPLocationData('The Wedding Reception - Score Bubble 173', LEVEL, Kind.SCORE, uid=57971),
    LBPLocationData('The Wedding Reception - Score Bubble 174', LEVEL, Kind.SCORE, uid=58294),
    LBPLocationData('The Wedding Reception - Score Bubble 175', LEVEL, Kind.SCORE, uid=58295),
    LBPLocationData('The Wedding Reception - Score Bubble 176', LEVEL, Kind.SCORE, uid=58296),
    LBPLocationData('The Wedding Reception - Score Bubble 177', LEVEL, Kind.SCORE, uid=58297),
    LBPLocationData('The Wedding Reception - Score Bubble 178', LEVEL, Kind.SCORE, uid=58298),
    LBPLocationData('The Wedding Reception - Score Bubble 179', LEVEL, Kind.SCORE, uid=58299),
    LBPLocationData('The Wedding Reception - Score Bubble 180', LEVEL, Kind.SCORE, uid=58301),
    LBPLocationData('The Wedding Reception - Score Bubble 181', LEVEL, Kind.SCORE, uid=58302),
    LBPLocationData('The Wedding Reception - Score Bubble 182', LEVEL, Kind.SCORE, uid=58866),
    LBPLocationData('The Wedding Reception - Score Bubble 183', LEVEL, Kind.SCORE, uid=58867),
    LBPLocationData('The Wedding Reception - Score Bubble 184', LEVEL, Kind.SCORE, uid=58868),
    LBPLocationData('The Wedding Reception - Score Bubble 185', LEVEL, Kind.SCORE, uid=58869),
    LBPLocationData('The Wedding Reception - Score Bubble 186', LEVEL, Kind.SCORE, uid=58870),
    LBPLocationData('The Wedding Reception - Score Bubble 187', LEVEL, Kind.SCORE, uid=58871),
    LBPLocationData('The Wedding Reception - Score Bubble 188', LEVEL, Kind.SCORE, uid=59170),
    LBPLocationData('The Wedding Reception - Score Bubble 189', LEVEL, Kind.SCORE, uid=59171),
    LBPLocationData('The Wedding Reception - Score Bubble 190', LEVEL, Kind.SCORE, uid=59172),
    LBPLocationData('The Wedding Reception - Score Bubble 191', LEVEL, Kind.SCORE, uid=59173),
    LBPLocationData('The Wedding Reception - Score Bubble 192', LEVEL, Kind.SCORE, uid=59174),
    LBPLocationData('The Wedding Reception - Score Bubble 193', LEVEL, Kind.SCORE, uid=59175),
    LBPLocationData('The Wedding Reception - Score Bubble 194', LEVEL, Kind.SCORE, uid=59176),
    LBPLocationData('The Wedding Reception - Score Bubble 195', LEVEL, Kind.SCORE, uid=59178),
    LBPLocationData('The Wedding Reception - Score Bubble 196', LEVEL, Kind.SCORE, uid=59179),
    LBPLocationData('The Wedding Reception - Score Bubble 197', LEVEL, Kind.SCORE, uid=59180),
    LBPLocationData('The Wedding Reception - Score Bubble 198', LEVEL, Kind.SCORE, uid=59181),
    LBPLocationData('The Wedding Reception - Score Bubble 199', LEVEL, Kind.SCORE, uid=59182),
    LBPLocationData('The Wedding Reception - Score Bubble 200', LEVEL, Kind.SCORE, uid=59183),
    LBPLocationData('The Wedding Reception - Score Bubble 201', LEVEL, Kind.SCORE, uid=59184),
    LBPLocationData('The Wedding Reception - Score Bubble 202', LEVEL, Kind.SCORE, uid=59185),
    LBPLocationData('The Wedding Reception - Score Bubble 203', LEVEL, Kind.SCORE, uid=59186),
    LBPLocationData('The Wedding Reception - Score Bubble 204', LEVEL, Kind.SCORE, uid=59187),
    LBPLocationData('The Wedding Reception - Score Bubble 205', LEVEL, Kind.SCORE, uid=59188),
    LBPLocationData('The Wedding Reception - Score Bubble 206', LEVEL, Kind.SCORE, uid=59189),
    LBPLocationData('The Wedding Reception - Score Bubble 207', LEVEL, Kind.SCORE, uid=59190),
    LBPLocationData('The Wedding Reception - Score Bubble 208', LEVEL, Kind.SCORE, uid=59191),
    LBPLocationData('The Wedding Reception - Score Bubble 209', LEVEL, Kind.SCORE, uid=59192),
    LBPLocationData('The Wedding Reception - Score Bubble 210', LEVEL, Kind.SCORE, uid=59193),
    LBPLocationData('The Wedding Reception - Score Bubble 211', LEVEL, Kind.SCORE, uid=59194),
    LBPLocationData('The Wedding Reception - Score Bubble 212', LEVEL, Kind.SCORE, uid=59195),
    LBPLocationData('The Wedding Reception - Score Bubble 213', LEVEL, Kind.SCORE, uid=59196),
    LBPLocationData('The Wedding Reception - Score Bubble 214', LEVEL, Kind.SCORE, uid=59197),
    LBPLocationData('The Wedding Reception - Score Bubble 215', LEVEL, Kind.SCORE, uid=59199),
    LBPLocationData('The Wedding Reception - Score Bubble 216', LEVEL, Kind.SCORE, uid=59200),
    LBPLocationData('The Wedding Reception - Score Bubble 217', LEVEL, Kind.SCORE, uid=59202),
    LBPLocationData('The Wedding Reception - Score Bubble 218', LEVEL, Kind.SCORE, uid=447333),
    LBPLocationData('The Wedding Reception - Score Bubble 219', LEVEL, Kind.SCORE, uid=447334),
    LBPLocationData('The Wedding Reception - Score Bubble 220', LEVEL, Kind.SCORE, uid=447335),
    LBPLocationData('The Wedding Reception - Score Bubble 221', LEVEL, Kind.SCORE, uid=633655),
    LBPLocationData('The Wedding Reception - Score Bubble 222', LEVEL, Kind.SCORE, uid=633656),
    LBPLocationData('The Wedding Reception - Score Bubble 223', LEVEL, Kind.SCORE, uid=633657),
    LBPLocationData('The Wedding Reception - Score Bubble 224', LEVEL, Kind.SCORE, uid=633658),
    LBPLocationData('The Wedding Reception - Score Bubble 225', LEVEL, Kind.SCORE, uid=633659),
    LBPLocationData('The Wedding Reception - Score Bubble 226', LEVEL, Kind.SCORE, uid=634377),
    LBPLocationData('The Wedding Reception - Score Bubble 227', LEVEL, Kind.SCORE, uid=634378),
    LBPLocationData('The Wedding Reception - Score Bubble 228', LEVEL, Kind.SCORE, uid=634379),
    LBPLocationData('The Wedding Reception - Score Bubble 229', LEVEL, Kind.SCORE, uid=634380),
    LBPLocationData('The Wedding Reception - Score Bubble 230', LEVEL, Kind.SCORE, uid=634381),
    LBPLocationData('The Wedding Reception - Score Bubble 231', LEVEL, Kind.SCORE, uid=634382),
    LBPLocationData('The Wedding Reception - Score Bubble 232', LEVEL, Kind.SCORE, uid=634414),
    LBPLocationData('The Wedding Reception - Score Bubble 233', LEVEL, Kind.SCORE, uid=634415),
    LBPLocationData('The Wedding Reception - Score Bubble 234', LEVEL, Kind.SCORE, uid=634416),
    LBPLocationData('The Wedding Reception - Score Bubble 235', LEVEL, Kind.SCORE, uid=634417),
    LBPLocationData('The Wedding Reception - Score Bubble 236', LEVEL, Kind.SCORE, uid=634418),
    LBPLocationData('The Wedding Reception - Score Bubble 237', LEVEL, Kind.SCORE, uid=634419),
    LBPLocationData('The Wedding Reception - Score Bubble 238', LEVEL, Kind.SCORE, uid=634420),
    LBPLocationData('The Wedding Reception - Score Bubble 239', LEVEL, Kind.SCORE, uid=634421),
    LBPLocationData('The Wedding Reception - Score Bubble 240', LEVEL, Kind.SCORE, uid=634422),
    LBPLocationData('The Wedding Reception - Score Bubble 241', LEVEL, Kind.SCORE, uid=634423),
    LBPLocationData('The Wedding Reception - Score Bubble 242', LEVEL, Kind.SCORE, uid=634424),
    LBPLocationData('The Wedding Reception - Score Bubble 243', LEVEL, Kind.SCORE, uid=634425),
    LBPLocationData('The Wedding Reception - Score Bubble 244', LEVEL, Kind.SCORE, uid=634426),
    LBPLocationData('The Wedding Reception - Score Bubble 245', LEVEL, Kind.SCORE, uid=634427),
    LBPLocationData('The Wedding Reception - Score Bubble 246', LEVEL, Kind.SCORE, uid=634428),
    LBPLocationData('The Wedding Reception - Score Bubble 247', LEVEL, Kind.SCORE, uid=634638),
    LBPLocationData('The Wedding Reception - Score Bubble 248', LEVEL, Kind.SCORE, uid=634639),
    LBPLocationData('The Wedding Reception - Score Bubble 249', LEVEL, Kind.SCORE, uid=634640),
    LBPLocationData('The Wedding Reception - Score Bubble 250', LEVEL, Kind.SCORE, uid=634641),
    LBPLocationData('The Wedding Reception - Score Bubble 251', LEVEL, Kind.SCORE, uid=634642),
    LBPLocationData('The Wedding Reception - Score Bubble 252', LEVEL, Kind.SCORE, uid=634643),
    LBPLocationData('The Wedding Reception - Score Bubble 253', LEVEL, Kind.SCORE, uid=634653),
    LBPLocationData('The Wedding Reception - Score Bubble 254', LEVEL, Kind.SCORE, uid=634654),
    LBPLocationData('The Wedding Reception - Score Bubble 255', LEVEL, Kind.SCORE, uid=634655),
    LBPLocationData('The Wedding Reception - Score Bubble 256', LEVEL, Kind.SCORE, uid=634656),
    LBPLocationData('The Wedding Reception - Score Bubble 257', LEVEL, Kind.SCORE, uid=634657),
    LBPLocationData('The Wedding Reception - Score Bubble 258', LEVEL, Kind.SCORE, uid=634658),
    LBPLocationData('The Wedding Reception - Score Bubble 259', LEVEL, Kind.SCORE, uid=634659),
    LBPLocationData('The Wedding Reception - Score Bubble 260', LEVEL, Kind.SCORE, uid=634660),
    LBPLocationData('The Wedding Reception - Score Bubble 261', LEVEL, Kind.SCORE, uid=634661),
    LBPLocationData('The Wedding Reception - Score Bubble 262', LEVEL, Kind.SCORE, uid=634662),
    LBPLocationData('The Wedding Reception - Score Bubble 263', LEVEL, Kind.SCORE, uid=634663),
    LBPLocationData('The Wedding Reception - Score Bubble 264', LEVEL, Kind.SCORE, uid=634664),
    LBPLocationData('The Wedding Reception - Score Bubble 265', LEVEL, Kind.SCORE, uid=754236),
    LBPLocationData('The Wedding Reception - Score Bubble 266', LEVEL, Kind.SCORE, uid=754237),
    LBPLocationData('The Wedding Reception - Score Bubble 267', LEVEL, Kind.SCORE, uid=754238),
    LBPLocationData('The Wedding Reception - Score Bubble 268', LEVEL, Kind.SCORE, uid=754239),
    LBPLocationData('The Wedding Reception - Score Bubble 269', LEVEL, Kind.SCORE, uid=754240),
    LBPLocationData('The Wedding Reception - Score Bubble 270', LEVEL, Kind.SCORE, uid=754241),
    LBPLocationData('The Wedding Reception - Prize Bubble 1 - Stained Glass Bouncy Platform', LEVEL, Kind.PRIZE, uid=55900, plan='g46876'),
    LBPLocationData('The Wedding Reception - Prize Bubble 2 - Bow Tie', LEVEL, Kind.PRIZE, uid=57494, plan='g32714'),
    LBPLocationData('The Wedding Reception - Prize Bubble 3 - Basket', LEVEL, Kind.PRIZE, uid=116581, plan='g32009'),
    LBPLocationData('The Wedding Reception - Prize Bubble 4 - Red X', LEVEL, Kind.PRIZE, uid=633350, plan='g31984'),
    LBPLocationData('The Wedding Reception - Prize Bubble 5 - Green Skulls', LEVEL, Kind.PRIZE, uid=633351, plan='g31985'),
    LBPLocationData('The Wedding Reception - Prize Bubble 6 - Skeleton Hat', LEVEL, Kind.PRIZE, uid=633352, plan='g31983'),
    LBPLocationData('The Wedding Reception - Prize Bubble 7 - Screaming Skull', LEVEL, Kind.PRIZE, uid=633609, plan='g51993'),
    LBPLocationData("The Wedding Reception - Prize Bubble 8 - 'Volver a Comenzar'", LEVEL, Kind.PRIZE, uid=633611, plan='g33154', players=2),
    LBPLocationData('The Wedding Reception - Prize Bubble 9 - Red & Gold Cutout Wood', LEVEL, Kind.PRIZE, uid=633661, plan='g32008'),
    LBPLocationData('The Wedding Reception - Prize Bubble 10 - Bevel Concrete', LEVEL, Kind.PRIZE, uid=633662, plan='g32006'),
    LBPLocationData('The Wedding Reception - Prize Bubble 11 - Zombie Boy', LEVEL, Kind.PRIZE, uid=634041, plan='g32013'),
    LBPLocationData('The Wedding Reception - Prize Bubble 12 - Top Hat', LEVEL, Kind.PRIZE, uid=634042, plan='g32000'),
    LBPLocationData('The Wedding Reception - Prize Bubble 13 - Black Tuxedo', LEVEL, Kind.PRIZE, uid=634043, plan='g31999'),
    LBPLocationData('The Wedding Reception - Prize Bubble 14 - White Wedding Dress', LEVEL, Kind.PRIZE, uid=634046, plan='g32001'),
    LBPLocationData('The Wedding Reception - Prize Bubble 15 - Wedding Veil', LEVEL, Kind.PRIZE, uid=634047, plan='g32002'),
    LBPLocationData('The Wedding Reception - Prize Bubble 16 - Zombie Girl', LEVEL, Kind.PRIZE, uid=634048, plan='g32014'),
    LBPLocationData('The Wedding Reception - Prize Bubble 17 - Bow Tie', LEVEL, Kind.PRIZE, uid=634050, plan='g32011'),
    LBPLocationData('The Wedding Reception - Prize Bubble 18 - Red Wig', LEVEL, Kind.PRIZE, uid=634051, plan='g32003'),
    LBPLocationData('The Wedding Reception - Prize Bubble 19 - Glasses', LEVEL, Kind.PRIZE, uid=634386, plan='g32717'),
    LBPLocationData('The Wedding Reception - Prize Bubble 20 - Calavera the Wrestler', LEVEL, Kind.PRIZE, uid=634440, plan='g48609'),
    LBPLocationData('The Wedding Reception - Prize Bubble 21 - Half Moon', LEVEL, Kind.PRIZE, uid=634442, plan='g31989'),
    LBPLocationData('The Wedding Reception - Prize Bubble 22 - Big Chin Skeleton', LEVEL, Kind.PRIZE, uid=634443, plan='g31992'),
    LBPLocationData('The Wedding Reception - Prize Bubble 23 - Red Coffin', LEVEL, Kind.PRIZE, uid=634444, plan='g31991'),
    LBPLocationData('The Wedding Reception - Prize Bubble 24 - Saint', LEVEL, Kind.PRIZE, uid=634519, plan='g31982'),
    LBPLocationData('The Wedding Reception - Prize Bubble 25 - Standing Skeleton', LEVEL, Kind.PRIZE, uid=634526, plan='g31986'),
    LBPLocationData('The Wedding Reception - Prize Bubble 26 - Confused Skull', LEVEL, Kind.PRIZE, uid=634527, plan='g31981'),
    LBPLocationData('The Wedding Reception - Prize Bubble 27 - Skull Lift', LEVEL, Kind.PRIZE, uid=634644, plan='g46892'),
    LBPLocationData('The Wedding Reception - Prize Bubble 28 - Skull Bungie Chord', LEVEL, Kind.PRIZE, uid=637933, plan='g46891'),
    LBPLocationData('The Wedding Reception - Prize Bubble 29 - Yellow Dandelions', LEVEL, Kind.PRIZE, uid=640176, plan='g31978'),
    LBPLocationData('The Wedding Reception - Prize Bubble 30 - Yellow Flower', LEVEL, Kind.PRIZE, uid=640177, plan='g51265'),
    LBPLocationData('The Wedding Reception - Prize Bubble 31 - White Flower', LEVEL, Kind.PRIZE, uid=640178, plan='g51264'),
    LBPLocationData('The Wedding Reception - Prize Bubble 32 - Wobbly Leg', LEVEL, Kind.PRIZE, uid=640179, plan='g32730'),
    LBPLocationData('The Wedding Reception - Prize Bubble 33 - Springy arm', LEVEL, Kind.PRIZE, uid=640180, plan='g32731'),
    LBPLocationData('The Wedding Reception - Prize Bubble 34 - Small Balloon', LEVEL, Kind.PRIZE, uid=640182, plan='g51300'),
    LBPLocationData('The Wedding Reception - Prize Bubble 35 - Medium Balloon', LEVEL, Kind.PRIZE, uid=640183, plan='g51301'),
    LBPLocationData('The Wedding Reception - Prize Bubble 36 - Large Balloon', LEVEL, Kind.PRIZE, uid=640184, plan='g51302'),
    LBPLocationData('The Wedding Reception - Prize Bubble 37 - Wavy Davy Skeleton', LEVEL, Kind.PRIZE, uid=640754, plan='g56305'),
    LBPLocationData('The Wedding Reception - Prize Bubble 38 - Purple Stuff', LEVEL, Kind.PRIZE, uid=641316, plan='g31993'),
    LBPLocationData('The Wedding Reception - Prize Bubble 39 - Purple Skull Torso', LEVEL, Kind.PRIZE, uid=641317, plan='g31995'),
    LBPLocationData('The Wedding Reception - Prize Bubble 40 - Psycho Bunny', LEVEL, Kind.PRIZE, uid=641320, plan='g31994'),
    LBPLocationData('The Wedding Reception - Prize Bubble 41 - Teeter Platform', LEVEL, Kind.PRIZE, uid=641321, plan='g46862'),
    LBPLocationData('The Wedding Reception - Prize Bubble 42 - Purple Glass', LEVEL, Kind.PRIZE, uid=641322, plan='g51390'),
    LBPLocationData('The Wedding Reception - Prize Bubble 43 - Red Glass', LEVEL, Kind.PRIZE, uid=641323, plan='g51391'),
    LBPLocationData('The Wedding Reception - Prize Bubble 44 - Bowler Hat', LEVEL, Kind.PRIZE, uid=641325, plan='g31990'),
    LBPLocationData('The Wedding Reception - Prize Bubble 45 - Plastic Nose', LEVEL, Kind.PRIZE, uid=644704, plan='g32719'),
    LBPLocationData('The Wedding Reception - Prize Bubble 46 - Plastic Ear', LEVEL, Kind.PRIZE, uid=644705, plan='g32715'),
    LBPLocationData('The Wedding Reception - Prize Bubble 47 - Farmers Cap', LEVEL, Kind.PRIZE, uid=645831, plan='g40044', players=2),
    LBPLocationData('The Wedding Reception - Prize Bubble 48 - Straw', LEVEL, Kind.PRIZE, uid=645835, plan='g41490', players=2),
    LBPLocationData('The Wedding Reception - Prize Bubble 49 - Fuzzy Scribble', LEVEL, Kind.PRIZE, uid=645836, plan='g32536', rule=Has('Huge Eye')),
    LBPLocationData('The Wedding Reception - Prize Bubble 50 - Spiked Screaming Skull', LEVEL, Kind.PRIZE, uid=646397, plan='g48694'),
    LBPLocationData('The Wedding Reception - Prize Bubble 51 - Balloon Launcher', LEVEL, Kind.PRIZE, uid=646958, plan='g48591'),
    LBPLocationData("The Wedding Reception - Prize Bubble 52 - 'Disco'n'Tinued'", LEVEL, Kind.PRIZE, uid=648079, plan='g41081'),
    LBPLocationData('The Wedding Reception - Prize Bubble 53 - Lower Teeth', LEVEL, Kind.PRIZE, uid=658759, plan='g42974', rule=Has('Skeleton Hat')),
    LBPLocationData('The Wedding Reception - Prize Bubble 54 - Plastic Moustache', LEVEL, Kind.PRIZE, uid=658760, plan='g32718', rule=Has('Skeleton Hat')),
    LBPLocationData('The Wedding Reception - Prize Bubble 55 - Dismembered Hand', LEVEL, Kind.PRIZE, uid=663269, plan='g48592'),
    LBPLocationData('The Wedding Reception - Prize Bubble 56 - Skeleton Talking Head', LEVEL, Kind.PRIZE, uid=663270, plan='g48593'),
    LBPLocationData('The Wedding Reception - Prize Bubble 57 - Bowler-Hatted Skeleton', LEVEL, Kind.PRIZE, uid=663271, plan='g46871'),
    LBPLocationData('The Wedding Reception - Prize Bubble 58 - Tilting Stained Glass Window', LEVEL, Kind.PRIZE, uid=663272, plan='g56304'),
    LBPLocationData('The Wedding Reception - Prize Bubble 59 - Brown Glass', LEVEL, Kind.PRIZE, uid=663838, plan='g51388'),
    LBPLocationData('The Wedding Reception - Prize Bubble 60 - Blue Glass', LEVEL, Kind.PRIZE, uid=663839, plan='g51387'),
    LBPLocationData('The Wedding Reception - Prize Bubble 61 - Green Glass', LEVEL, Kind.PRIZE, uid=663840, plan='g51389'),
    LBPLocationData('The Wedding Reception - Prize Bubble 62 - Huge Eye', LEVEL, Kind.PRIZE, uid=666757, plan='g31841'),
    LBPLocationData('The Wedding Reception - Prize Bubble 63 - Little Butler', LEVEL, Kind.PRIZE, uid=796768, plan='g56300'),
    LBPLocationData('The Wedding Reception - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('The Wedding Reception - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('The Wedding Reception - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('The Wedding Reception - Completion Reward 1 - Fairy Dress', LEVEL, Kind.REWARD, plan='g32389', condition=Kind.COMPLETE),
    LBPLocationData('The Wedding Reception - Completion Reward 2 - Rainbow Dot', LEVEL, Kind.REWARD, plan='g37936', condition=Kind.COMPLETE),
    LBPLocationData('The Wedding Reception - All Prizes Reward 1 - Wrestling Ring Concept with Frame', LEVEL, Kind.REWARD, plan='g52803', condition=Kind.ALL_PRIZES),
    LBPLocationData('The Wedding Reception - All Prizes Reward 2 - Wrestling Ring Concept', LEVEL, Kind.REWARD, plan='g52791', condition=Kind.ALL_PRIZES),
    LBPLocationData('The Wedding Reception - Ace Reward 1 - Wooden Sword', LEVEL, Kind.REWARD, plan='g32377', condition=Kind.ACE),
    LBPLocationData('The Wedding Reception - Sticker Switch 1 - Skeleton Hat', LEVEL, Kind.STICKER_SWITCH, uid=633604, plan='g31983'),
    LBPLocationData('The Wedding Reception - Sticker Switch 2 - Huge Eye', LEVEL, Kind.STICKER_SWITCH, uid=633613, plan='g31841'),
    LBPLocationData('The Wedding Reception - Key 1', LEVEL, Kind.KEY, uid=63915, target_slot='SlotID{DEVELOPER, 31065}'),
    LBPLocationData('The Wedding Reception - Key 2', LEVEL, Kind.KEY, uid=137253, target_slot='SlotID{DEVELOPER, 27482}'),
)
