from rule_builder.rules import Has

from ..model import Kind, LBPLocationData

LEVEL = 'g26370'

LOCATIONS = (
    LBPLocationData('The Meerkat Kingdom - Score Bubble 1', LEVEL, Kind.SCORE, uid=15241),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 2', LEVEL, Kind.SCORE, uid=15243),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 3', LEVEL, Kind.SCORE, uid=15245),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 4', LEVEL, Kind.SCORE, uid=15324),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 5', LEVEL, Kind.SCORE, uid=15325),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 6', LEVEL, Kind.SCORE, uid=15326),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 7', LEVEL, Kind.SCORE, uid=15327),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 8', LEVEL, Kind.SCORE, uid=15328),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 9', LEVEL, Kind.SCORE, uid=15329),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 10', LEVEL, Kind.SCORE, uid=15330),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 11', LEVEL, Kind.SCORE, uid=15331),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 12', LEVEL, Kind.SCORE, uid=15332),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 13', LEVEL, Kind.SCORE, uid=15402),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 14', LEVEL, Kind.SCORE, uid=15403),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 15', LEVEL, Kind.SCORE, uid=15405),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 16', LEVEL, Kind.SCORE, uid=15407),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 17', LEVEL, Kind.SCORE, uid=15408),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 18', LEVEL, Kind.SCORE, uid=15409),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 19', LEVEL, Kind.SCORE, uid=15410),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 20', LEVEL, Kind.SCORE, uid=15411),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 21', LEVEL, Kind.SCORE, uid=15412),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 22', LEVEL, Kind.SCORE, uid=15413),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 23', LEVEL, Kind.SCORE, uid=15510),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 24', LEVEL, Kind.SCORE, uid=15512),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 25', LEVEL, Kind.SCORE, uid=15515),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 26', LEVEL, Kind.SCORE, uid=15517),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 27', LEVEL, Kind.SCORE, uid=15520),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 28', LEVEL, Kind.SCORE, uid=16214),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 29', LEVEL, Kind.SCORE, uid=16505),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 30', LEVEL, Kind.SCORE, uid=16507),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 31', LEVEL, Kind.SCORE, uid=16509),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 32', LEVEL, Kind.SCORE, uid=16513),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 33', LEVEL, Kind.SCORE, uid=16515),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 34', LEVEL, Kind.SCORE, uid=16517),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 35', LEVEL, Kind.SCORE, uid=16519),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 36', LEVEL, Kind.SCORE, uid=16521),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 37', LEVEL, Kind.SCORE, uid=16523),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 38', LEVEL, Kind.SCORE, uid=16829),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 39', LEVEL, Kind.SCORE, uid=16831),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 40', LEVEL, Kind.SCORE, uid=16833),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 41', LEVEL, Kind.SCORE, uid=16835),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 42', LEVEL, Kind.SCORE, uid=16837),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 43', LEVEL, Kind.SCORE, uid=16839),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 44', LEVEL, Kind.SCORE, uid=16841),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 45', LEVEL, Kind.SCORE, uid=16843),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 46', LEVEL, Kind.SCORE, uid=16845),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 47', LEVEL, Kind.SCORE, uid=16847),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 48', LEVEL, Kind.SCORE, uid=16849),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 49', LEVEL, Kind.SCORE, uid=16870),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 50', LEVEL, Kind.SCORE, uid=16872),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 51', LEVEL, Kind.SCORE, uid=16898),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 52', LEVEL, Kind.SCORE, uid=16899),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 53', LEVEL, Kind.SCORE, uid=16900),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 54', LEVEL, Kind.SCORE, uid=16901),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 55', LEVEL, Kind.SCORE, uid=17087),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 56', LEVEL, Kind.SCORE, uid=17232),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 57', LEVEL, Kind.SCORE, uid=17233),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 58', LEVEL, Kind.SCORE, uid=17234),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 59', LEVEL, Kind.SCORE, uid=17236),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 60', LEVEL, Kind.SCORE, uid=17237),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 61', LEVEL, Kind.SCORE, uid=17238),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 62', LEVEL, Kind.SCORE, uid=17525),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 63', LEVEL, Kind.SCORE, uid=17526),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 64', LEVEL, Kind.SCORE, uid=17527),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 65', LEVEL, Kind.SCORE, uid=17528),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 66', LEVEL, Kind.SCORE, uid=17529),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 67', LEVEL, Kind.SCORE, uid=17530),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 68', LEVEL, Kind.SCORE, uid=17531),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 69', LEVEL, Kind.SCORE, uid=17532),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 70', LEVEL, Kind.SCORE, uid=17533),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 71', LEVEL, Kind.SCORE, uid=17534),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 72', LEVEL, Kind.SCORE, uid=17535),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 73', LEVEL, Kind.SCORE, uid=17536),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 74', LEVEL, Kind.SCORE, uid=17537),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 75', LEVEL, Kind.SCORE, uid=17538),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 76', LEVEL, Kind.SCORE, uid=17539),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 77', LEVEL, Kind.SCORE, uid=17540),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 78', LEVEL, Kind.SCORE, uid=17541),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 79', LEVEL, Kind.SCORE, uid=17542),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 80', LEVEL, Kind.SCORE, uid=17543),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 81', LEVEL, Kind.SCORE, uid=17545),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 82', LEVEL, Kind.SCORE, uid=17615),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 83', LEVEL, Kind.SCORE, uid=17616),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 84', LEVEL, Kind.SCORE, uid=17617),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 85', LEVEL, Kind.SCORE, uid=17848),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 86', LEVEL, Kind.SCORE, uid=17849),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 87', LEVEL, Kind.SCORE, uid=17850),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 88', LEVEL, Kind.SCORE, uid=17851),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 89', LEVEL, Kind.SCORE, uid=17852),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 90', LEVEL, Kind.SCORE, uid=17853),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 91', LEVEL, Kind.SCORE, uid=17866),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 92', LEVEL, Kind.SCORE, uid=17867),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 93', LEVEL, Kind.SCORE, uid=17868),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 94', LEVEL, Kind.SCORE, uid=17869),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 95', LEVEL, Kind.SCORE, uid=17870),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 96', LEVEL, Kind.SCORE, uid=17871),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 97', LEVEL, Kind.SCORE, uid=17872),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 98', LEVEL, Kind.SCORE, uid=17873),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 99', LEVEL, Kind.SCORE, uid=17874),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 100', LEVEL, Kind.SCORE, uid=17875),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 101', LEVEL, Kind.SCORE, uid=17876),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 102', LEVEL, Kind.SCORE, uid=17877),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 103', LEVEL, Kind.SCORE, uid=17878),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 104', LEVEL, Kind.SCORE, uid=17879),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 105', LEVEL, Kind.SCORE, uid=17880),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 106', LEVEL, Kind.SCORE, uid=17881),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 107', LEVEL, Kind.SCORE, uid=17882),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 108', LEVEL, Kind.SCORE, uid=17883),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 109', LEVEL, Kind.SCORE, uid=17884),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 110', LEVEL, Kind.SCORE, uid=17885),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 111', LEVEL, Kind.SCORE, uid=17886),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 112', LEVEL, Kind.SCORE, uid=17887),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 113', LEVEL, Kind.SCORE, uid=17888),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 114', LEVEL, Kind.SCORE, uid=17889),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 115', LEVEL, Kind.SCORE, uid=17891),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 116', LEVEL, Kind.SCORE, uid=17892),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 117', LEVEL, Kind.SCORE, uid=17895),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 118', LEVEL, Kind.SCORE, uid=17896),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 119', LEVEL, Kind.SCORE, uid=17897),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 120', LEVEL, Kind.SCORE, uid=17898),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 121', LEVEL, Kind.SCORE, uid=17899),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 122', LEVEL, Kind.SCORE, uid=17900),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 123', LEVEL, Kind.SCORE, uid=17901),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 124', LEVEL, Kind.SCORE, uid=17906),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 125', LEVEL, Kind.SCORE, uid=17907),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 126', LEVEL, Kind.SCORE, uid=17908),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 127', LEVEL, Kind.SCORE, uid=17909),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 128', LEVEL, Kind.SCORE, uid=17910),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 129', LEVEL, Kind.SCORE, uid=17911),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 130', LEVEL, Kind.SCORE, uid=17912),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 131', LEVEL, Kind.SCORE, uid=20347),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 132', LEVEL, Kind.SCORE, uid=20348),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 133', LEVEL, Kind.SCORE, uid=20349),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 134', LEVEL, Kind.SCORE, uid=20350),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 135', LEVEL, Kind.SCORE, uid=20351),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 136', LEVEL, Kind.SCORE, uid=20352),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 137', LEVEL, Kind.SCORE, uid=20353),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 138', LEVEL, Kind.SCORE, uid=20354),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 139', LEVEL, Kind.SCORE, uid=20355),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 140', LEVEL, Kind.SCORE, uid=217711),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 141', LEVEL, Kind.SCORE, uid=217712),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 142', LEVEL, Kind.SCORE, uid=217713),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 143', LEVEL, Kind.SCORE, uid=217714),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 144', LEVEL, Kind.SCORE, uid=217715),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 145', LEVEL, Kind.SCORE, uid=217716),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 146', LEVEL, Kind.SCORE, uid=217717),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 147', LEVEL, Kind.SCORE, uid=233479),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 148', LEVEL, Kind.SCORE, uid=233480),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 149', LEVEL, Kind.SCORE, uid=233481),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 150', LEVEL, Kind.SCORE, uid=233482),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 151', LEVEL, Kind.SCORE, uid=233483),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 152', LEVEL, Kind.SCORE, uid=233484),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 153', LEVEL, Kind.SCORE, uid=233485),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 154', LEVEL, Kind.SCORE, uid=233486),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 155', LEVEL, Kind.SCORE, uid=233487),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 156', LEVEL, Kind.SCORE, uid=233488),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 157', LEVEL, Kind.SCORE, uid=233489),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 158', LEVEL, Kind.SCORE, uid=233490),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 159', LEVEL, Kind.SCORE, uid=233491),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 160', LEVEL, Kind.SCORE, uid=233492),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 161', LEVEL, Kind.SCORE, uid=233493),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 162', LEVEL, Kind.SCORE, uid=233494),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 163', LEVEL, Kind.SCORE, uid=233495),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 164', LEVEL, Kind.SCORE, uid=233496),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 165', LEVEL, Kind.SCORE, uid=233497),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 166', LEVEL, Kind.SCORE, uid=233498),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 167', LEVEL, Kind.SCORE, uid=233499),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 168', LEVEL, Kind.SCORE, uid=233500),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 169', LEVEL, Kind.SCORE, uid=233501),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 170', LEVEL, Kind.SCORE, uid=233502),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 171', LEVEL, Kind.SCORE, uid=233503),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 172', LEVEL, Kind.SCORE, uid=233504),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 173', LEVEL, Kind.SCORE, uid=233505),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 174', LEVEL, Kind.SCORE, uid=233506),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 175', LEVEL, Kind.SCORE, uid=233507),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 176', LEVEL, Kind.SCORE, uid=233508),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 177', LEVEL, Kind.SCORE, uid=233509),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 178', LEVEL, Kind.SCORE, uid=233510),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 179', LEVEL, Kind.SCORE, uid=242809),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 180', LEVEL, Kind.SCORE, uid=242810),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 181', LEVEL, Kind.SCORE, uid=242811),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 182', LEVEL, Kind.SCORE, uid=242812),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 183', LEVEL, Kind.SCORE, uid=242816),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 184', LEVEL, Kind.SCORE, uid=242817),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 185', LEVEL, Kind.SCORE, uid=242818),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 186', LEVEL, Kind.SCORE, uid=242819),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 187', LEVEL, Kind.SCORE, uid=242820),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 188', LEVEL, Kind.SCORE, uid=242821),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 189', LEVEL, Kind.SCORE, uid=242822),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 190', LEVEL, Kind.SCORE, uid=242823),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 191', LEVEL, Kind.SCORE, uid=242824),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 192', LEVEL, Kind.SCORE, uid=242825),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 193', LEVEL, Kind.SCORE, uid=242826),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 194', LEVEL, Kind.SCORE, uid=242827),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 195', LEVEL, Kind.SCORE, uid=274972),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 196', LEVEL, Kind.SCORE, uid=274973),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 197', LEVEL, Kind.SCORE, uid=274974),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 198', LEVEL, Kind.SCORE, uid=274975),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 199', LEVEL, Kind.SCORE, uid=274976),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 200', LEVEL, Kind.SCORE, uid=274977),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 201', LEVEL, Kind.SCORE, uid=275444),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 202', LEVEL, Kind.SCORE, uid=275445),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 203', LEVEL, Kind.SCORE, uid=275446),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 204', LEVEL, Kind.SCORE, uid=275447),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 205', LEVEL, Kind.SCORE, uid=276839),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 206', LEVEL, Kind.SCORE, uid=276840),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 207', LEVEL, Kind.SCORE, uid=276841),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 208', LEVEL, Kind.SCORE, uid=276842),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 209', LEVEL, Kind.SCORE, uid=276843),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 210', LEVEL, Kind.SCORE, uid=276844),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 211', LEVEL, Kind.SCORE, uid=276848),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 212', LEVEL, Kind.SCORE, uid=276849),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 213', LEVEL, Kind.SCORE, uid=276850),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 214', LEVEL, Kind.SCORE, uid=276851),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 215', LEVEL, Kind.SCORE, uid=276852),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 216', LEVEL, Kind.SCORE, uid=276853),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 217', LEVEL, Kind.SCORE, uid=276854),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 218', LEVEL, Kind.SCORE, uid=277317),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 219', LEVEL, Kind.SCORE, uid=277318),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 220', LEVEL, Kind.SCORE, uid=277319),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 221', LEVEL, Kind.SCORE, uid=277320),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 222', LEVEL, Kind.SCORE, uid=277321),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 223', LEVEL, Kind.SCORE, uid=277322),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 224', LEVEL, Kind.SCORE, uid=277323),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 225', LEVEL, Kind.SCORE, uid=277324),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 226', LEVEL, Kind.SCORE, uid=277325),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 227', LEVEL, Kind.SCORE, uid=277788),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 228', LEVEL, Kind.SCORE, uid=277789),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 229', LEVEL, Kind.SCORE, uid=277790),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 230', LEVEL, Kind.SCORE, uid=277794),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 231', LEVEL, Kind.SCORE, uid=277797),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 232', LEVEL, Kind.SCORE, uid=277799),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 233', LEVEL, Kind.SCORE, uid=277800),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 234', LEVEL, Kind.SCORE, uid=277801),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 235', LEVEL, Kind.SCORE, uid=277802),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 236', LEVEL, Kind.SCORE, uid=277806),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 237', LEVEL, Kind.SCORE, uid=277808),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 238', LEVEL, Kind.SCORE, uid=278273),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 239', LEVEL, Kind.SCORE, uid=278274),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 240', LEVEL, Kind.SCORE, uid=278275),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 241', LEVEL, Kind.SCORE, uid=278276),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 242', LEVEL, Kind.SCORE, uid=278277),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 243', LEVEL, Kind.SCORE, uid=278278),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 244', LEVEL, Kind.SCORE, uid=278279),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 245', LEVEL, Kind.SCORE, uid=278280),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 246', LEVEL, Kind.SCORE, uid=278744),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 247', LEVEL, Kind.SCORE, uid=278745),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 248', LEVEL, Kind.SCORE, uid=278746),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 249', LEVEL, Kind.SCORE, uid=289897),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 250', LEVEL, Kind.SCORE, uid=289898),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 251', LEVEL, Kind.SCORE, uid=289899),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 252', LEVEL, Kind.SCORE, uid=289900),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 253', LEVEL, Kind.SCORE, uid=289901),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 254', LEVEL, Kind.SCORE, uid=289902),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 255', LEVEL, Kind.SCORE, uid=289903),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 256', LEVEL, Kind.SCORE, uid=289904),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 257', LEVEL, Kind.SCORE, uid=292686),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 258', LEVEL, Kind.SCORE, uid=292687),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 259', LEVEL, Kind.SCORE, uid=292688),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 260', LEVEL, Kind.SCORE, uid=332303),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 261', LEVEL, Kind.SCORE, uid=332304),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 262', LEVEL, Kind.SCORE, uid=357852),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 263', LEVEL, Kind.SCORE, uid=363489),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 264', LEVEL, Kind.SCORE, uid=363490),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 265', LEVEL, Kind.SCORE, uid=363491),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 266', LEVEL, Kind.SCORE, uid=363492),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 267', LEVEL, Kind.SCORE, uid=363493),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 268', LEVEL, Kind.SCORE, uid=363494),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 269', LEVEL, Kind.SCORE, uid=363495),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 270', LEVEL, Kind.SCORE, uid=363496),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 271', LEVEL, Kind.SCORE, uid=363497),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 272', LEVEL, Kind.SCORE, uid=363498),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 273', LEVEL, Kind.SCORE, uid=589765),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 274', LEVEL, Kind.SCORE, uid=589766),
    LBPLocationData('The Meerkat Kingdom - Score Bubble 275', LEVEL, Kind.SCORE, uid=589767),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 1 - Growl Face', LEVEL, Kind.PRIZE, uid=15262, plan='g33395'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 2 - Carved Heads', LEVEL, Kind.PRIZE, uid=15264, plan='g33416'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 3 - Black Animal Nose', LEVEL, Kind.PRIZE, uid=15265, plan='g51352', players=2),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 4 - Snapping Claw', LEVEL, Kind.PRIZE, uid=15485, plan='g48565'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 5 - Jet Cheetah', LEVEL, Kind.PRIZE, uid=15489, plan='g48484'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 6 - Red Boy', LEVEL, Kind.PRIZE, uid=15504, plan='g33388'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 7 - Scary Fangs', LEVEL, Kind.PRIZE, uid=16483, plan='g51244'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 8 - Carved Animals', LEVEL, Kind.PRIZE, uid=16929, plan='g33419'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 9 - Wooden Planks', LEVEL, Kind.PRIZE, uid=16982, plan='g33413', players=2),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 10 - Meerkat Popup', LEVEL, Kind.PRIZE, uid=16998, plan='g45498', rule=Has('Voodoo Face')),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 11 - Cat Head', LEVEL, Kind.PRIZE, uid=17302, plan='g33394'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 12 - Wooden Zebra', LEVEL, Kind.PRIZE, uid=17509, plan='g48485'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 13 - Wooden Flamingo', LEVEL, Kind.PRIZE, uid=17510, plan='g48486'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 14 - Wallpaper', LEVEL, Kind.PRIZE, uid=17523, plan='g33437'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 15 - Engraved Metal', LEVEL, Kind.PRIZE, uid=17524, plan='g33440'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 16 - Baby Meerkats', LEVEL, Kind.PRIZE, uid=18107, plan='g48183', rule=Has('Fluffy Tree')),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 17 - Big-Belly Meerkat', LEVEL, Kind.PRIZE, uid=18874, plan='g45483', players=2),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 18 - Red Lobster', LEVEL, Kind.PRIZE, uid=18903, plan='g51230'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 19 - Blue Fish', LEVEL, Kind.PRIZE, uid=18905, plan='g51229'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 20 - Big Cute Nose', LEVEL, Kind.PRIZE, uid=18907, plan='g51275'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 21 - Orange Block', LEVEL, Kind.PRIZE, uid=254445, plan='g51245', players=2),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 22 - Hanging Snapping Claw', LEVEL, Kind.PRIZE, uid=289896, plan='g56167'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 23 - Cow Head', LEVEL, Kind.PRIZE, uid=295058, plan='g51212'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 24 - Sleeping Elephant', LEVEL, Kind.PRIZE, uid=354143, plan='g51350'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 25 - Orange Weave', LEVEL, Kind.PRIZE, uid=386300, plan='g51133'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 26 - Pink Knit', LEVEL, Kind.PRIZE, uid=386302, plan='g51134'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 27 - Green Felt', LEVEL, Kind.PRIZE, uid=386304, plan='g51135'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 28 - Brown Stripy Button', LEVEL, Kind.PRIZE, uid=386306, plan='g51331'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 29 - Brown Wood', LEVEL, Kind.PRIZE, uid=412800, plan='g51143'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 30 - Scratch Pattern', LEVEL, Kind.PRIZE, uid=419304, plan='g33389'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 31 - White Butterfly', LEVEL, Kind.PRIZE, uid=516842, plan='g51216'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 32 - Red Butterfly', LEVEL, Kind.PRIZE, uid=516843, plan='g51215'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 33 - Blue Wing Graphic', LEVEL, Kind.PRIZE, uid=517305, plan='g51228'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 34 - Bat Wing', LEVEL, Kind.PRIZE, uid=517306, plan='g51214'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 35 - Orange Bird', LEVEL, Kind.PRIZE, uid=517307, plan='g51207'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 36 - Birdy Outline', LEVEL, Kind.PRIZE, uid=517769, plan='g51208'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 37 - Rubber Duck', LEVEL, Kind.PRIZE, uid=518231, plan='g51209'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 38 - Mr Beaver Says No', LEVEL, Kind.PRIZE, uid=518232, plan='g51210'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 39 - Crazed Donkey', LEVEL, Kind.PRIZE, uid=518695, plan='g51218'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 40 - Cow Udders', LEVEL, Kind.PRIZE, uid=518696, plan='g51213'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 41 - Red Roman Cape', LEVEL, Kind.PRIZE, uid=522846, plan='g32375', players=2),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 42 - Blue Circles Denim', LEVEL, Kind.PRIZE, uid=522848, plan='g32522'),
    LBPLocationData("The Meerkat Kingdom - Prize Bubble 43 - 'My Patch'", LEVEL, Kind.PRIZE, uid=523311, plan='g33149'),
    LBPLocationData('The Meerkat Kingdom - Prize Bubble 44 - Savannah IntMusic', LEVEL, Kind.PRIZE, uid=626489, plan='g33142'),
    LBPLocationData('The Meerkat Kingdom - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('The Meerkat Kingdom - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('The Meerkat Kingdom - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('The Meerkat Kingdom - Completion Reward 1 - Pink Scarf', LEVEL, Kind.REWARD, plan='g51060', condition=Kind.COMPLETE),
    LBPLocationData('The Meerkat Kingdom - Completion Reward 2 - The Savannah', LEVEL, Kind.REWARD, plan='g33684', condition=Kind.COMPLETE),
    LBPLocationData('The Meerkat Kingdom - All Prizes Reward 1 - Meerkat Mum & Scenery', LEVEL, Kind.REWARD, plan='g59809', condition=Kind.ALL_PRIZES),
    LBPLocationData('The Meerkat Kingdom - All Prizes Reward 2 - Red Wolves Concept with Frame', LEVEL, Kind.REWARD, plan='g52802', condition=Kind.ALL_PRIZES),
    LBPLocationData('The Meerkat Kingdom - All Prizes Reward 3 - Red Wolves Concept', LEVEL, Kind.REWARD, plan='g52790', condition=Kind.ALL_PRIZES),
    LBPLocationData('The Meerkat Kingdom - Ace Reward 1 - Ringmaster Top Hat', LEVEL, Kind.REWARD, plan='g39749', condition=Kind.ACE),
    LBPLocationData('The Meerkat Kingdom - Ace Reward 2 - Gold Monocle', LEVEL, Kind.REWARD, plan='g51059', condition=Kind.ACE),
    LBPLocationData('The Meerkat Kingdom - Sticker Switch 1 - Fluffy Tree', LEVEL, Kind.STICKER_SWITCH, uid=278743, plan='g33387'),
    LBPLocationData('The Meerkat Kingdom - Sticker Switch 2 - Growl Face', LEVEL, Kind.STICKER_SWITCH, uid=282929, plan='g33395'),
    LBPLocationData('The Meerkat Kingdom - Sticker Switch 3 - Voodoo Face', LEVEL, Kind.STICKER_SWITCH, uid=284798, plan='g33398'),
    LBPLocationData('The Meerkat Kingdom - Key 1', LEVEL, Kind.KEY, uid=18875, target_slot='SlotID{DEVELOPER, 26363}'),
    LBPLocationData('The Meerkat Kingdom - Key 2', LEVEL, Kind.KEY, uid=619989, target_slot='SlotID{DEVELOPER, 27481}'),
)
