from rule_builder.rules import Has

from ..model import Kind, LBPLocationData

LEVEL = 'g20359'

LOCATIONS = (
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 1", LEVEL, Kind.SCORE, uid=17620),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 2", LEVEL, Kind.SCORE, uid=17622),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 3", LEVEL, Kind.SCORE, uid=17623),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 4", LEVEL, Kind.SCORE, uid=17694),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 5", LEVEL, Kind.SCORE, uid=17695),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 6", LEVEL, Kind.SCORE, uid=17696),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 7", LEVEL, Kind.SCORE, uid=17852),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 8", LEVEL, Kind.SCORE, uid=17853),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 9", LEVEL, Kind.SCORE, uid=17854),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 10", LEVEL, Kind.SCORE, uid=72502),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 11", LEVEL, Kind.SCORE, uid=72503),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 12", LEVEL, Kind.SCORE, uid=72504),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 13", LEVEL, Kind.SCORE, uid=75486),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 14", LEVEL, Kind.SCORE, uid=75487),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 15", LEVEL, Kind.SCORE, uid=75488),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 16", LEVEL, Kind.SCORE, uid=75489),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 17", LEVEL, Kind.SCORE, uid=75490),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 18", LEVEL, Kind.SCORE, uid=75491),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 19", LEVEL, Kind.SCORE, uid=75492),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 20", LEVEL, Kind.SCORE, uid=75493),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 21", LEVEL, Kind.SCORE, uid=75494),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 22", LEVEL, Kind.SCORE, uid=75495),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 23", LEVEL, Kind.SCORE, uid=75496),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 24", LEVEL, Kind.SCORE, uid=75497),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 25", LEVEL, Kind.SCORE, uid=75867),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 26", LEVEL, Kind.SCORE, uid=75868),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 27", LEVEL, Kind.SCORE, uid=75869),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 28", LEVEL, Kind.SCORE, uid=76361),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 29", LEVEL, Kind.SCORE, uid=76362),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 30", LEVEL, Kind.SCORE, uid=76363),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 31", LEVEL, Kind.SCORE, uid=76364),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 32", LEVEL, Kind.SCORE, uid=76365),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 33", LEVEL, Kind.SCORE, uid=76366),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 34", LEVEL, Kind.SCORE, uid=77816),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 35", LEVEL, Kind.SCORE, uid=77817),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 36", LEVEL, Kind.SCORE, uid=77818),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 37", LEVEL, Kind.SCORE, uid=77833),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 38", LEVEL, Kind.SCORE, uid=77834),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 39", LEVEL, Kind.SCORE, uid=77835),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 40", LEVEL, Kind.SCORE, uid=77845),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 41", LEVEL, Kind.SCORE, uid=77846),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 42", LEVEL, Kind.SCORE, uid=77847),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 43", LEVEL, Kind.SCORE, uid=77862),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 44", LEVEL, Kind.SCORE, uid=77863),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 45", LEVEL, Kind.SCORE, uid=77864),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 46", LEVEL, Kind.SCORE, uid=77874),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 47", LEVEL, Kind.SCORE, uid=77875),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 48", LEVEL, Kind.SCORE, uid=77876),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 49", LEVEL, Kind.SCORE, uid=79958),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 50", LEVEL, Kind.SCORE, uid=79959),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 51", LEVEL, Kind.SCORE, uid=79960),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 52", LEVEL, Kind.SCORE, uid=80066),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 53", LEVEL, Kind.SCORE, uid=80067),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 54", LEVEL, Kind.SCORE, uid=80068),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 55", LEVEL, Kind.SCORE, uid=80069),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 56", LEVEL, Kind.SCORE, uid=80070),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 57", LEVEL, Kind.SCORE, uid=80071),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 58", LEVEL, Kind.SCORE, uid=80075),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 59", LEVEL, Kind.SCORE, uid=80078),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 60", LEVEL, Kind.SCORE, uid=80079),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 61", LEVEL, Kind.SCORE, uid=80255),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 62", LEVEL, Kind.SCORE, uid=80256),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 63", LEVEL, Kind.SCORE, uid=80257),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 64", LEVEL, Kind.SCORE, uid=80885),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 65", LEVEL, Kind.SCORE, uid=80886),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 66", LEVEL, Kind.SCORE, uid=80887),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 67", LEVEL, Kind.SCORE, uid=80888),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 68", LEVEL, Kind.SCORE, uid=80889),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 69", LEVEL, Kind.SCORE, uid=80890),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 70", LEVEL, Kind.SCORE, uid=80897),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 71", LEVEL, Kind.SCORE, uid=80898),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 72", LEVEL, Kind.SCORE, uid=80899),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 73", LEVEL, Kind.SCORE, uid=80900),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 74", LEVEL, Kind.SCORE, uid=80901),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 75", LEVEL, Kind.SCORE, uid=80902),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 76", LEVEL, Kind.SCORE, uid=80903),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 77", LEVEL, Kind.SCORE, uid=80904),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 78", LEVEL, Kind.SCORE, uid=80905),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 79", LEVEL, Kind.SCORE, uid=80976),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 80", LEVEL, Kind.SCORE, uid=80977),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 81", LEVEL, Kind.SCORE, uid=80978),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 82", LEVEL, Kind.SCORE, uid=80979),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 83", LEVEL, Kind.SCORE, uid=80980),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 84", LEVEL, Kind.SCORE, uid=80981),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 85", LEVEL, Kind.SCORE, uid=81114),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 86", LEVEL, Kind.SCORE, uid=81115),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 87", LEVEL, Kind.SCORE, uid=81116),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 88", LEVEL, Kind.SCORE, uid=92589),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 89", LEVEL, Kind.SCORE, uid=92590),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 90", LEVEL, Kind.SCORE, uid=92591),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 91", LEVEL, Kind.SCORE, uid=203262),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 92", LEVEL, Kind.SCORE, uid=203263),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 93", LEVEL, Kind.SCORE, uid=203264),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 94", LEVEL, Kind.SCORE, uid=203265),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 95", LEVEL, Kind.SCORE, uid=203266),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 96", LEVEL, Kind.SCORE, uid=203267),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 97", LEVEL, Kind.SCORE, uid=242309),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 98", LEVEL, Kind.SCORE, uid=242310),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 99", LEVEL, Kind.SCORE, uid=242311),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 100", LEVEL, Kind.SCORE, uid=242312),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 101", LEVEL, Kind.SCORE, uid=242313),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 102", LEVEL, Kind.SCORE, uid=242314),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 103", LEVEL, Kind.SCORE, uid=242315),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 104", LEVEL, Kind.SCORE, uid=242316),
    LBPLocationData("The Terrible Oni's Volcano - Score Bubble 105", LEVEL, Kind.SCORE, uid=242317),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 1 - Dragon Tooth", LEVEL, Kind.PRIZE, uid=81118, plan='g32052'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 2 - Japanese Sun", LEVEL, Kind.PRIZE, uid=81141, plan='g32042'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 3 - Ornate Bridge", LEVEL, Kind.PRIZE, uid=92594, plan='g47805'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 4 - Wooden Pagoda", LEVEL, Kind.PRIZE, uid=92953, plan='g55897'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 5 - Wind Up Teeth", LEVEL, Kind.PRIZE, uid=93311, plan='g51297'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 6 - Dagger", LEVEL, Kind.PRIZE, uid=93312, plan='g34368'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 7 - Japanese Coin", LEVEL, Kind.PRIZE, uid=93313, plan='g32079', players=2),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 8 - Illuminated Screen", LEVEL, Kind.PRIZE, uid=93316, plan='g32071'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 9 - Spike Trap", LEVEL, Kind.PRIZE, uid=93317, plan='g47814'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 10 - Beige Wood", LEVEL, Kind.PRIZE, uid=93318, plan='g51145'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 11 - Japanese Stork", LEVEL, Kind.PRIZE, uid=93319, plan='g32043'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 12 - Kimono Outline", LEVEL, Kind.PRIZE, uid=93323, plan='g32056'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 13 - Black Waveform", LEVEL, Kind.PRIZE, uid=93324, plan='g32057'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 14 - Old-Fashioned Specs", LEVEL, Kind.PRIZE, uid=93325, plan='g48586'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 15 - Wooden Button", LEVEL, Kind.PRIZE, uid=93327, plan='g51333'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 16 - White Wood", LEVEL, Kind.PRIZE, uid=93330, plan='g51147', players=2),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 17 - Cream Marble Button", LEVEL, Kind.PRIZE, uid=93332, plan='g51336', players=2),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 18 - Ceramic", LEVEL, Kind.PRIZE, uid=93690, plan='g32073'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 19 - Rustic Vase", LEVEL, Kind.PRIZE, uid=93691, plan='g34366'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 20 - Dark Wooden Button", LEVEL, Kind.PRIZE, uid=94048, plan='g51334', rule=Has('Pink Warrior Mask')),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 21 - Bonsai Pot", LEVEL, Kind.PRIZE, uid=94049, plan='g34367', rule=Has('Pink Warrior Mask')),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 22 - Golden Wood", LEVEL, Kind.PRIZE, uid=94050, plan='g51146'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 23 - Wind Up Teeth - Top", LEVEL, Kind.PRIZE, uid=94051, plan='g56413'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 24 - Wind Up Teeth - Bottom", LEVEL, Kind.PRIZE, uid=94052, plan='g56412'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 25 - Long Vase", LEVEL, Kind.PRIZE, uid=94769, plan='g34365'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 26 - Square Blue Button", LEVEL, Kind.PRIZE, uid=94770, plan='g51335'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 27 - Pointing Grandmaster Sensei", LEVEL, Kind.PRIZE, uid=95127, plan='g55898'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 28 - Japanese Samurai 2", LEVEL, Kind.PRIZE, uid=97623, plan='g32049'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 29 - Rainbow Tree", LEVEL, Kind.PRIZE, uid=111219, plan='g48904', rule=Has('Sakura Flower')),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 30 - Pretty Leaf", LEVEL, Kind.PRIZE, uid=111220, plan='g32053', rule=Has('Sakura Flower')),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 31 - Fairy Star Wand", LEVEL, Kind.PRIZE, uid=129408, plan='g32373', rule=Has('Bouncy Cloud')),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 32 - Wind Charm", LEVEL, Kind.PRIZE, uid=129409, plan='g32033', rule=Has('Bouncy Cloud')),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 33 - Japanese Pattern", LEVEL, Kind.PRIZE, uid=240877, plan='g32041'),
    LBPLocationData("The Terrible Oni's Volcano - Prize Bubble 34 - Bouncy Cloud", LEVEL, Kind.PRIZE, uid=240878, plan='g32055'),
    LBPLocationData("The Terrible Oni's Volcano - Level Complete", LEVEL, Kind.COMPLETE),
    LBPLocationData("The Terrible Oni's Volcano - All Prize Bubbles", LEVEL, Kind.ALL_PRIZES),
    LBPLocationData("The Terrible Oni's Volcano - Ace (No Deaths)", LEVEL, Kind.ACE),
    LBPLocationData("The Terrible Oni's Volcano - Completion Reward 1 - Pink Hair with Feathers Wig", LEVEL, Kind.REWARD, plan='g32465', condition=Kind.COMPLETE),
    LBPLocationData("The Terrible Oni's Volcano - Completion Reward 2 - The Islands", LEVEL, Kind.REWARD, plan='g31965', condition=Kind.COMPLETE),
    LBPLocationData("The Terrible Oni's Volcano - Completion Reward 3 - Flying Machine", LEVEL, Kind.REWARD, plan='g55899', condition=Kind.COMPLETE),
    LBPLocationData("The Terrible Oni's Volcano - All Prizes Reward 1 - Terrible Oni", LEVEL, Kind.REWARD, plan='g52303', condition=Kind.ALL_PRIZES),
    LBPLocationData("The Terrible Oni's Volcano - All Prizes Reward 2 - The Islands - Mini City Concept with Frame", LEVEL, Kind.REWARD, plan='g52812', condition=Kind.ALL_PRIZES),
    LBPLocationData("The Terrible Oni's Volcano - All Prizes Reward 3 - The Islands City Concept", LEVEL, Kind.REWARD, plan='g52736', condition=Kind.ALL_PRIZES),
    LBPLocationData("The Terrible Oni's Volcano - Ace Reward 1 - Japanese Festival Headband", LEVEL, Kind.REWARD, plan='g45273', condition=Kind.ACE),
    LBPLocationData("The Terrible Oni's Volcano - Sticker Switch 1 - Sakura Flower", LEVEL, Kind.STICKER_SWITCH, uid=81030, plan='g32054'),
    LBPLocationData("The Terrible Oni's Volcano - Sticker Switch 2 - Bouncy Cloud", LEVEL, Kind.STICKER_SWITCH, uid=81132, plan='g32055'),
    LBPLocationData("The Terrible Oni's Volcano - Sticker Switch 3 - Pink Warrior Mask", LEVEL, Kind.STICKER_SWITCH, uid=157542, plan='g32039'),
)
