from rule_builder.rules import Has

from ..model import Kind, LBPLocationData

LEVEL = 'g20366'

LOCATIONS = (
    LBPLocationData('The Frozen Tundra - Score Bubble 1', LEVEL, Kind.SCORE, uid=235947),
    LBPLocationData('The Frozen Tundra - Score Bubble 2', LEVEL, Kind.SCORE, uid=235948),
    LBPLocationData('The Frozen Tundra - Score Bubble 3', LEVEL, Kind.SCORE, uid=235949),
    LBPLocationData('The Frozen Tundra - Score Bubble 4', LEVEL, Kind.SCORE, uid=235952),
    LBPLocationData('The Frozen Tundra - Score Bubble 5', LEVEL, Kind.SCORE, uid=235953),
    LBPLocationData('The Frozen Tundra - Score Bubble 6', LEVEL, Kind.SCORE, uid=235954),
    LBPLocationData('The Frozen Tundra - Score Bubble 7', LEVEL, Kind.SCORE, uid=235956),
    LBPLocationData('The Frozen Tundra - Score Bubble 8', LEVEL, Kind.SCORE, uid=235957),
    LBPLocationData('The Frozen Tundra - Score Bubble 9', LEVEL, Kind.SCORE, uid=235958),
    LBPLocationData('The Frozen Tundra - Score Bubble 10', LEVEL, Kind.SCORE, uid=235960),
    LBPLocationData('The Frozen Tundra - Score Bubble 11', LEVEL, Kind.SCORE, uid=235961),
    LBPLocationData('The Frozen Tundra - Score Bubble 12', LEVEL, Kind.SCORE, uid=235962),
    LBPLocationData('The Frozen Tundra - Score Bubble 13', LEVEL, Kind.SCORE, uid=235964),
    LBPLocationData('The Frozen Tundra - Score Bubble 14', LEVEL, Kind.SCORE, uid=235965),
    LBPLocationData('The Frozen Tundra - Score Bubble 15', LEVEL, Kind.SCORE, uid=235966),
    LBPLocationData('The Frozen Tundra - Score Bubble 16', LEVEL, Kind.SCORE, uid=236183),
    LBPLocationData('The Frozen Tundra - Score Bubble 17', LEVEL, Kind.SCORE, uid=236185),
    LBPLocationData('The Frozen Tundra - Score Bubble 18', LEVEL, Kind.SCORE, uid=236186),
    LBPLocationData('The Frozen Tundra - Score Bubble 19', LEVEL, Kind.SCORE, uid=236199),
    LBPLocationData('The Frozen Tundra - Score Bubble 20', LEVEL, Kind.SCORE, uid=236200),
    LBPLocationData('The Frozen Tundra - Score Bubble 21', LEVEL, Kind.SCORE, uid=236201),
    LBPLocationData('The Frozen Tundra - Score Bubble 22', LEVEL, Kind.SCORE, uid=236202),
    LBPLocationData('The Frozen Tundra - Score Bubble 23', LEVEL, Kind.SCORE, uid=236203),
    LBPLocationData('The Frozen Tundra - Score Bubble 24', LEVEL, Kind.SCORE, uid=236204),
    LBPLocationData('The Frozen Tundra - Score Bubble 25', LEVEL, Kind.SCORE, uid=236208),
    LBPLocationData('The Frozen Tundra - Score Bubble 26', LEVEL, Kind.SCORE, uid=236209),
    LBPLocationData('The Frozen Tundra - Score Bubble 27', LEVEL, Kind.SCORE, uid=236210),
    LBPLocationData('The Frozen Tundra - Score Bubble 28', LEVEL, Kind.SCORE, uid=236214),
    LBPLocationData('The Frozen Tundra - Score Bubble 29', LEVEL, Kind.SCORE, uid=236215),
    LBPLocationData('The Frozen Tundra - Score Bubble 30', LEVEL, Kind.SCORE, uid=236216),
    LBPLocationData('The Frozen Tundra - Score Bubble 31', LEVEL, Kind.SCORE, uid=236217),
    LBPLocationData('The Frozen Tundra - Score Bubble 32', LEVEL, Kind.SCORE, uid=236218),
    LBPLocationData('The Frozen Tundra - Score Bubble 33', LEVEL, Kind.SCORE, uid=236219),
    LBPLocationData('The Frozen Tundra - Score Bubble 34', LEVEL, Kind.SCORE, uid=236220),
    LBPLocationData('The Frozen Tundra - Score Bubble 35', LEVEL, Kind.SCORE, uid=236221),
    LBPLocationData('The Frozen Tundra - Score Bubble 36', LEVEL, Kind.SCORE, uid=236222),
    LBPLocationData('The Frozen Tundra - Score Bubble 37', LEVEL, Kind.SCORE, uid=236223),
    LBPLocationData('The Frozen Tundra - Score Bubble 38', LEVEL, Kind.SCORE, uid=236224),
    LBPLocationData('The Frozen Tundra - Score Bubble 39', LEVEL, Kind.SCORE, uid=236225),
    LBPLocationData('The Frozen Tundra - Score Bubble 40', LEVEL, Kind.SCORE, uid=236229),
    LBPLocationData('The Frozen Tundra - Score Bubble 41', LEVEL, Kind.SCORE, uid=236230),
    LBPLocationData('The Frozen Tundra - Score Bubble 42', LEVEL, Kind.SCORE, uid=236231),
    LBPLocationData('The Frozen Tundra - Score Bubble 43', LEVEL, Kind.SCORE, uid=236235),
    LBPLocationData('The Frozen Tundra - Score Bubble 44', LEVEL, Kind.SCORE, uid=236236),
    LBPLocationData('The Frozen Tundra - Score Bubble 45', LEVEL, Kind.SCORE, uid=236237),
    LBPLocationData('The Frozen Tundra - Score Bubble 46', LEVEL, Kind.SCORE, uid=236241),
    LBPLocationData('The Frozen Tundra - Score Bubble 47', LEVEL, Kind.SCORE, uid=236242),
    LBPLocationData('The Frozen Tundra - Score Bubble 48', LEVEL, Kind.SCORE, uid=236243),
    LBPLocationData('The Frozen Tundra - Score Bubble 49', LEVEL, Kind.SCORE, uid=236272),
    LBPLocationData('The Frozen Tundra - Score Bubble 50', LEVEL, Kind.SCORE, uid=236273),
    LBPLocationData('The Frozen Tundra - Score Bubble 51', LEVEL, Kind.SCORE, uid=236274),
    LBPLocationData('The Frozen Tundra - Score Bubble 52', LEVEL, Kind.SCORE, uid=236395),
    LBPLocationData('The Frozen Tundra - Score Bubble 53', LEVEL, Kind.SCORE, uid=236396),
    LBPLocationData('The Frozen Tundra - Score Bubble 54', LEVEL, Kind.SCORE, uid=236397),
    LBPLocationData('The Frozen Tundra - Score Bubble 55', LEVEL, Kind.SCORE, uid=236398),
    LBPLocationData('The Frozen Tundra - Score Bubble 56', LEVEL, Kind.SCORE, uid=236399),
    LBPLocationData('The Frozen Tundra - Score Bubble 57', LEVEL, Kind.SCORE, uid=236400),
    LBPLocationData('The Frozen Tundra - Score Bubble 58', LEVEL, Kind.SCORE, uid=236401),
    LBPLocationData('The Frozen Tundra - Score Bubble 59', LEVEL, Kind.SCORE, uid=236402),
    LBPLocationData('The Frozen Tundra - Score Bubble 60', LEVEL, Kind.SCORE, uid=236403),
    LBPLocationData('The Frozen Tundra - Score Bubble 61', LEVEL, Kind.SCORE, uid=236404),
    LBPLocationData('The Frozen Tundra - Score Bubble 62', LEVEL, Kind.SCORE, uid=236405),
    LBPLocationData('The Frozen Tundra - Score Bubble 63', LEVEL, Kind.SCORE, uid=236406),
    LBPLocationData('The Frozen Tundra - Score Bubble 64', LEVEL, Kind.SCORE, uid=236446),
    LBPLocationData('The Frozen Tundra - Score Bubble 65', LEVEL, Kind.SCORE, uid=236447),
    LBPLocationData('The Frozen Tundra - Score Bubble 66', LEVEL, Kind.SCORE, uid=236448),
    LBPLocationData('The Frozen Tundra - Score Bubble 67', LEVEL, Kind.SCORE, uid=236450),
    LBPLocationData('The Frozen Tundra - Score Bubble 68', LEVEL, Kind.SCORE, uid=236451),
    LBPLocationData('The Frozen Tundra - Score Bubble 69', LEVEL, Kind.SCORE, uid=236452),
    LBPLocationData('The Frozen Tundra - Score Bubble 70', LEVEL, Kind.SCORE, uid=236454),
    LBPLocationData('The Frozen Tundra - Score Bubble 71', LEVEL, Kind.SCORE, uid=236455),
    LBPLocationData('The Frozen Tundra - Score Bubble 72', LEVEL, Kind.SCORE, uid=236456),
    LBPLocationData('The Frozen Tundra - Score Bubble 73', LEVEL, Kind.SCORE, uid=236458),
    LBPLocationData('The Frozen Tundra - Score Bubble 74', LEVEL, Kind.SCORE, uid=236459),
    LBPLocationData('The Frozen Tundra - Score Bubble 75', LEVEL, Kind.SCORE, uid=236460),
    LBPLocationData('The Frozen Tundra - Score Bubble 76', LEVEL, Kind.SCORE, uid=244899),
    LBPLocationData('The Frozen Tundra - Score Bubble 77', LEVEL, Kind.SCORE, uid=244900),
    LBPLocationData('The Frozen Tundra - Score Bubble 78', LEVEL, Kind.SCORE, uid=244901),
    LBPLocationData('The Frozen Tundra - Score Bubble 79', LEVEL, Kind.SCORE, uid=244902),
    LBPLocationData('The Frozen Tundra - Score Bubble 80', LEVEL, Kind.SCORE, uid=244903),
    LBPLocationData('The Frozen Tundra - Score Bubble 81', LEVEL, Kind.SCORE, uid=244904),
    LBPLocationData('The Frozen Tundra - Score Bubble 82', LEVEL, Kind.SCORE, uid=336488),
    LBPLocationData('The Frozen Tundra - Score Bubble 83', LEVEL, Kind.SCORE, uid=336489),
    LBPLocationData('The Frozen Tundra - Score Bubble 84', LEVEL, Kind.SCORE, uid=336490),
    LBPLocationData('The Frozen Tundra - Score Bubble 85', LEVEL, Kind.SCORE, uid=336491),
    LBPLocationData('The Frozen Tundra - Score Bubble 86', LEVEL, Kind.SCORE, uid=336492),
    LBPLocationData('The Frozen Tundra - Score Bubble 87', LEVEL, Kind.SCORE, uid=336493),
    LBPLocationData('The Frozen Tundra - Score Bubble 88', LEVEL, Kind.SCORE, uid=380695),
    LBPLocationData('The Frozen Tundra - Score Bubble 89', LEVEL, Kind.SCORE, uid=380696),
    LBPLocationData('The Frozen Tundra - Score Bubble 90', LEVEL, Kind.SCORE, uid=380697),
    LBPLocationData('The Frozen Tundra - Score Bubble 91', LEVEL, Kind.SCORE, uid=385787),
    LBPLocationData('The Frozen Tundra - Score Bubble 92', LEVEL, Kind.SCORE, uid=385788),
    LBPLocationData('The Frozen Tundra - Score Bubble 93', LEVEL, Kind.SCORE, uid=385789),
    LBPLocationData('The Frozen Tundra - Score Bubble 94', LEVEL, Kind.SCORE, uid=386055),
    LBPLocationData('The Frozen Tundra - Score Bubble 95', LEVEL, Kind.SCORE, uid=386056),
    LBPLocationData('The Frozen Tundra - Score Bubble 96', LEVEL, Kind.SCORE, uid=386057),
    LBPLocationData('The Frozen Tundra - Score Bubble 97', LEVEL, Kind.SCORE, uid=410537),
    LBPLocationData('The Frozen Tundra - Score Bubble 98', LEVEL, Kind.SCORE, uid=410538),
    LBPLocationData('The Frozen Tundra - Score Bubble 99', LEVEL, Kind.SCORE, uid=410539),
    LBPLocationData('The Frozen Tundra - Score Bubble 100', LEVEL, Kind.SCORE, uid=410540),
    LBPLocationData('The Frozen Tundra - Score Bubble 101', LEVEL, Kind.SCORE, uid=410541),
    LBPLocationData('The Frozen Tundra - Score Bubble 102', LEVEL, Kind.SCORE, uid=410542),
    LBPLocationData('The Frozen Tundra - Score Bubble 103', LEVEL, Kind.SCORE, uid=410543),
    LBPLocationData('The Frozen Tundra - Score Bubble 104', LEVEL, Kind.SCORE, uid=410544),
    LBPLocationData('The Frozen Tundra - Score Bubble 105', LEVEL, Kind.SCORE, uid=410545),
    LBPLocationData('The Frozen Tundra - Score Bubble 106', LEVEL, Kind.SCORE, uid=410546),
    LBPLocationData('The Frozen Tundra - Score Bubble 107', LEVEL, Kind.SCORE, uid=410557),
    LBPLocationData('The Frozen Tundra - Score Bubble 108', LEVEL, Kind.SCORE, uid=410558),
    LBPLocationData('The Frozen Tundra - Score Bubble 109', LEVEL, Kind.SCORE, uid=410559),
    LBPLocationData('The Frozen Tundra - Score Bubble 110', LEVEL, Kind.SCORE, uid=410560),
    LBPLocationData('The Frozen Tundra - Score Bubble 111', LEVEL, Kind.SCORE, uid=410561),
    LBPLocationData('The Frozen Tundra - Score Bubble 112', LEVEL, Kind.SCORE, uid=410562),
    LBPLocationData('The Frozen Tundra - Score Bubble 113', LEVEL, Kind.SCORE, uid=410563),
    LBPLocationData('The Frozen Tundra - Score Bubble 114', LEVEL, Kind.SCORE, uid=410564),
    LBPLocationData('The Frozen Tundra - Score Bubble 115', LEVEL, Kind.SCORE, uid=410565),
    LBPLocationData('The Frozen Tundra - Score Bubble 116', LEVEL, Kind.SCORE, uid=410566),
    LBPLocationData('The Frozen Tundra - Score Bubble 117', LEVEL, Kind.SCORE, uid=410567),
    LBPLocationData('The Frozen Tundra - Score Bubble 118', LEVEL, Kind.SCORE, uid=410568),
    LBPLocationData('The Frozen Tundra - Score Bubble 119', LEVEL, Kind.SCORE, uid=410569),
    LBPLocationData('The Frozen Tundra - Score Bubble 120', LEVEL, Kind.SCORE, uid=410570),
    LBPLocationData('The Frozen Tundra - Score Bubble 121', LEVEL, Kind.SCORE, uid=410571),
    LBPLocationData('The Frozen Tundra - Score Bubble 122', LEVEL, Kind.SCORE, uid=410573),
    LBPLocationData('The Frozen Tundra - Score Bubble 123', LEVEL, Kind.SCORE, uid=410574),
    LBPLocationData('The Frozen Tundra - Score Bubble 124', LEVEL, Kind.SCORE, uid=410575),
    LBPLocationData('The Frozen Tundra - Score Bubble 125', LEVEL, Kind.SCORE, uid=410576),
    LBPLocationData('The Frozen Tundra - Score Bubble 126', LEVEL, Kind.SCORE, uid=410577),
    LBPLocationData('The Frozen Tundra - Score Bubble 127', LEVEL, Kind.SCORE, uid=410578),
    LBPLocationData('The Frozen Tundra - Score Bubble 128', LEVEL, Kind.SCORE, uid=410579),
    LBPLocationData('The Frozen Tundra - Score Bubble 129', LEVEL, Kind.SCORE, uid=410580),
    LBPLocationData('The Frozen Tundra - Score Bubble 130', LEVEL, Kind.SCORE, uid=410581),
    LBPLocationData('The Frozen Tundra - Score Bubble 131', LEVEL, Kind.SCORE, uid=410582),
    LBPLocationData('The Frozen Tundra - Score Bubble 132', LEVEL, Kind.SCORE, uid=410583),
    LBPLocationData('The Frozen Tundra - Score Bubble 133', LEVEL, Kind.SCORE, uid=410584),
    LBPLocationData('The Frozen Tundra - Score Bubble 134', LEVEL, Kind.SCORE, uid=410585),
    LBPLocationData('The Frozen Tundra - Score Bubble 135', LEVEL, Kind.SCORE, uid=410586),
    LBPLocationData('The Frozen Tundra - Score Bubble 136', LEVEL, Kind.SCORE, uid=410587),
    LBPLocationData('The Frozen Tundra - Score Bubble 137', LEVEL, Kind.SCORE, uid=410588),
    LBPLocationData('The Frozen Tundra - Score Bubble 138', LEVEL, Kind.SCORE, uid=410589),
    LBPLocationData('The Frozen Tundra - Score Bubble 139', LEVEL, Kind.SCORE, uid=410590),
    LBPLocationData('The Frozen Tundra - Score Bubble 140', LEVEL, Kind.SCORE, uid=410591),
    LBPLocationData('The Frozen Tundra - Score Bubble 141', LEVEL, Kind.SCORE, uid=410592),
    LBPLocationData('The Frozen Tundra - Score Bubble 142', LEVEL, Kind.SCORE, uid=410593),
    LBPLocationData('The Frozen Tundra - Score Bubble 143', LEVEL, Kind.SCORE, uid=410594),
    LBPLocationData('The Frozen Tundra - Score Bubble 144', LEVEL, Kind.SCORE, uid=410595),
    LBPLocationData('The Frozen Tundra - Score Bubble 145', LEVEL, Kind.SCORE, uid=410596),
    LBPLocationData('The Frozen Tundra - Score Bubble 146', LEVEL, Kind.SCORE, uid=410597),
    LBPLocationData('The Frozen Tundra - Score Bubble 147', LEVEL, Kind.SCORE, uid=410598),
    LBPLocationData('The Frozen Tundra - Score Bubble 148', LEVEL, Kind.SCORE, uid=410599),
    LBPLocationData('The Frozen Tundra - Score Bubble 149', LEVEL, Kind.SCORE, uid=410600),
    LBPLocationData('The Frozen Tundra - Score Bubble 150', LEVEL, Kind.SCORE, uid=410601),
    LBPLocationData('The Frozen Tundra - Score Bubble 151', LEVEL, Kind.SCORE, uid=410602),
    LBPLocationData('The Frozen Tundra - Score Bubble 152', LEVEL, Kind.SCORE, uid=410603),
    LBPLocationData('The Frozen Tundra - Score Bubble 153', LEVEL, Kind.SCORE, uid=410604),
    LBPLocationData('The Frozen Tundra - Score Bubble 154', LEVEL, Kind.SCORE, uid=410605),
    LBPLocationData('The Frozen Tundra - Score Bubble 155', LEVEL, Kind.SCORE, uid=410606),
    LBPLocationData('The Frozen Tundra - Score Bubble 156', LEVEL, Kind.SCORE, uid=410607),
    LBPLocationData('The Frozen Tundra - Score Bubble 157', LEVEL, Kind.SCORE, uid=410608),
    LBPLocationData('The Frozen Tundra - Score Bubble 158', LEVEL, Kind.SCORE, uid=410609),
    LBPLocationData('The Frozen Tundra - Score Bubble 159', LEVEL, Kind.SCORE, uid=410610),
    LBPLocationData('The Frozen Tundra - Score Bubble 160', LEVEL, Kind.SCORE, uid=410611),
    LBPLocationData('The Frozen Tundra - Score Bubble 161', LEVEL, Kind.SCORE, uid=410612),
    LBPLocationData('The Frozen Tundra - Score Bubble 162', LEVEL, Kind.SCORE, uid=410613),
    LBPLocationData('The Frozen Tundra - Score Bubble 163', LEVEL, Kind.SCORE, uid=410614),
    LBPLocationData('The Frozen Tundra - Score Bubble 164', LEVEL, Kind.SCORE, uid=410615),
    LBPLocationData('The Frozen Tundra - Score Bubble 165', LEVEL, Kind.SCORE, uid=410616),
    LBPLocationData('The Frozen Tundra - Score Bubble 166', LEVEL, Kind.SCORE, uid=410617),
    LBPLocationData('The Frozen Tundra - Score Bubble 167', LEVEL, Kind.SCORE, uid=410618),
    LBPLocationData('The Frozen Tundra - Score Bubble 168', LEVEL, Kind.SCORE, uid=410619),
    LBPLocationData('The Frozen Tundra - Score Bubble 169', LEVEL, Kind.SCORE, uid=410620),
    LBPLocationData('The Frozen Tundra - Score Bubble 170', LEVEL, Kind.SCORE, uid=410621),
    LBPLocationData('The Frozen Tundra - Score Bubble 171', LEVEL, Kind.SCORE, uid=410622),
    LBPLocationData('The Frozen Tundra - Score Bubble 172', LEVEL, Kind.SCORE, uid=410623),
    LBPLocationData('The Frozen Tundra - Score Bubble 173', LEVEL, Kind.SCORE, uid=410624),
    LBPLocationData('The Frozen Tundra - Score Bubble 174', LEVEL, Kind.SCORE, uid=410625),
    LBPLocationData('The Frozen Tundra - Score Bubble 175', LEVEL, Kind.SCORE, uid=410626),
    LBPLocationData('The Frozen Tundra - Score Bubble 176', LEVEL, Kind.SCORE, uid=410627),
    LBPLocationData('The Frozen Tundra - Score Bubble 177', LEVEL, Kind.SCORE, uid=410628),
    LBPLocationData('The Frozen Tundra - Score Bubble 178', LEVEL, Kind.SCORE, uid=410629),
    LBPLocationData('The Frozen Tundra - Score Bubble 179', LEVEL, Kind.SCORE, uid=410630),
    LBPLocationData('The Frozen Tundra - Score Bubble 180', LEVEL, Kind.SCORE, uid=410631),
    LBPLocationData('The Frozen Tundra - Score Bubble 181', LEVEL, Kind.SCORE, uid=410632),
    LBPLocationData('The Frozen Tundra - Score Bubble 182', LEVEL, Kind.SCORE, uid=410633),
    LBPLocationData('The Frozen Tundra - Score Bubble 183', LEVEL, Kind.SCORE, uid=410634),
    LBPLocationData('The Frozen Tundra - Score Bubble 184', LEVEL, Kind.SCORE, uid=410635),
    LBPLocationData('The Frozen Tundra - Score Bubble 185', LEVEL, Kind.SCORE, uid=410636),
    LBPLocationData('The Frozen Tundra - Score Bubble 186', LEVEL, Kind.SCORE, uid=410637),
    LBPLocationData('The Frozen Tundra - Score Bubble 187', LEVEL, Kind.SCORE, uid=410638),
    LBPLocationData('The Frozen Tundra - Score Bubble 188', LEVEL, Kind.SCORE, uid=410639),
    LBPLocationData('The Frozen Tundra - Score Bubble 189', LEVEL, Kind.SCORE, uid=410640),
    LBPLocationData('The Frozen Tundra - Score Bubble 190', LEVEL, Kind.SCORE, uid=410641),
    LBPLocationData('The Frozen Tundra - Score Bubble 191', LEVEL, Kind.SCORE, uid=410647),
    LBPLocationData('The Frozen Tundra - Score Bubble 192', LEVEL, Kind.SCORE, uid=410648),
    LBPLocationData('The Frozen Tundra - Score Bubble 193', LEVEL, Kind.SCORE, uid=410649),
    LBPLocationData('The Frozen Tundra - Score Bubble 194', LEVEL, Kind.SCORE, uid=410650),
    LBPLocationData('The Frozen Tundra - Score Bubble 195', LEVEL, Kind.SCORE, uid=410651),
    LBPLocationData('The Frozen Tundra - Score Bubble 196', LEVEL, Kind.SCORE, uid=410652),
    LBPLocationData('The Frozen Tundra - Score Bubble 197', LEVEL, Kind.SCORE, uid=410653),
    LBPLocationData('The Frozen Tundra - Score Bubble 198', LEVEL, Kind.SCORE, uid=410654),
    LBPLocationData('The Frozen Tundra - Score Bubble 199', LEVEL, Kind.SCORE, uid=410655),
    LBPLocationData('The Frozen Tundra - Score Bubble 200', LEVEL, Kind.SCORE, uid=410656),
    LBPLocationData('The Frozen Tundra - Score Bubble 201', LEVEL, Kind.SCORE, uid=410657),
    LBPLocationData('The Frozen Tundra - Score Bubble 202', LEVEL, Kind.SCORE, uid=410658),
    LBPLocationData('The Frozen Tundra - Score Bubble 203', LEVEL, Kind.SCORE, uid=410659),
    LBPLocationData('The Frozen Tundra - Score Bubble 204', LEVEL, Kind.SCORE, uid=410660),
    LBPLocationData('The Frozen Tundra - Score Bubble 205', LEVEL, Kind.SCORE, uid=410661),
    LBPLocationData('The Frozen Tundra - Score Bubble 206', LEVEL, Kind.SCORE, uid=410662),
    LBPLocationData('The Frozen Tundra - Score Bubble 207', LEVEL, Kind.SCORE, uid=410663),
    LBPLocationData('The Frozen Tundra - Score Bubble 208', LEVEL, Kind.SCORE, uid=410664),
    LBPLocationData('The Frozen Tundra - Score Bubble 209', LEVEL, Kind.SCORE, uid=410665),
    LBPLocationData('The Frozen Tundra - Score Bubble 210', LEVEL, Kind.SCORE, uid=410666),
    LBPLocationData('The Frozen Tundra - Score Bubble 211', LEVEL, Kind.SCORE, uid=410667),
    LBPLocationData('The Frozen Tundra - Score Bubble 212', LEVEL, Kind.SCORE, uid=410668),
    LBPLocationData('The Frozen Tundra - Score Bubble 213', LEVEL, Kind.SCORE, uid=410669),
    LBPLocationData('The Frozen Tundra - Score Bubble 214', LEVEL, Kind.SCORE, uid=410670),
    LBPLocationData('The Frozen Tundra - Score Bubble 215', LEVEL, Kind.SCORE, uid=410671),
    LBPLocationData('The Frozen Tundra - Score Bubble 216', LEVEL, Kind.SCORE, uid=410672),
    LBPLocationData('The Frozen Tundra - Score Bubble 217', LEVEL, Kind.SCORE, uid=410673),
    LBPLocationData('The Frozen Tundra - Score Bubble 218', LEVEL, Kind.SCORE, uid=410674),
    LBPLocationData('The Frozen Tundra - Score Bubble 219', LEVEL, Kind.SCORE, uid=410675),
    LBPLocationData('The Frozen Tundra - Score Bubble 220', LEVEL, Kind.SCORE, uid=410676),
    LBPLocationData('The Frozen Tundra - Score Bubble 221', LEVEL, Kind.SCORE, uid=410677),
    LBPLocationData('The Frozen Tundra - Score Bubble 222', LEVEL, Kind.SCORE, uid=410678),
    LBPLocationData('The Frozen Tundra - Score Bubble 223', LEVEL, Kind.SCORE, uid=410679),
    LBPLocationData('The Frozen Tundra - Score Bubble 224', LEVEL, Kind.SCORE, uid=410680),
    LBPLocationData('The Frozen Tundra - Score Bubble 225', LEVEL, Kind.SCORE, uid=410681),
    LBPLocationData('The Frozen Tundra - Score Bubble 226', LEVEL, Kind.SCORE, uid=410687),
    LBPLocationData('The Frozen Tundra - Score Bubble 227', LEVEL, Kind.SCORE, uid=410688),
    LBPLocationData('The Frozen Tundra - Score Bubble 228', LEVEL, Kind.SCORE, uid=410689),
    LBPLocationData('The Frozen Tundra - Score Bubble 229', LEVEL, Kind.SCORE, uid=410690),
    LBPLocationData('The Frozen Tundra - Score Bubble 230', LEVEL, Kind.SCORE, uid=410691),
    LBPLocationData('The Frozen Tundra - Score Bubble 231', LEVEL, Kind.SCORE, uid=410692),
    LBPLocationData('The Frozen Tundra - Score Bubble 232', LEVEL, Kind.SCORE, uid=410693),
    LBPLocationData('The Frozen Tundra - Score Bubble 233', LEVEL, Kind.SCORE, uid=410694),
    LBPLocationData('The Frozen Tundra - Score Bubble 234', LEVEL, Kind.SCORE, uid=410695),
    LBPLocationData('The Frozen Tundra - Score Bubble 235', LEVEL, Kind.SCORE, uid=410696),
    LBPLocationData('The Frozen Tundra - Score Bubble 236', LEVEL, Kind.SCORE, uid=424604),
    LBPLocationData('The Frozen Tundra - Score Bubble 237', LEVEL, Kind.SCORE, uid=424605),
    LBPLocationData('The Frozen Tundra - Score Bubble 238', LEVEL, Kind.SCORE, uid=424606),
    LBPLocationData('The Frozen Tundra - Score Bubble 239', LEVEL, Kind.SCORE, uid=424607),
    LBPLocationData('The Frozen Tundra - Score Bubble 240', LEVEL, Kind.SCORE, uid=424608),
    LBPLocationData('The Frozen Tundra - Score Bubble 241', LEVEL, Kind.SCORE, uid=426241),
    LBPLocationData('The Frozen Tundra - Score Bubble 242', LEVEL, Kind.SCORE, uid=426242),
    LBPLocationData('The Frozen Tundra - Score Bubble 243', LEVEL, Kind.SCORE, uid=426243),
    LBPLocationData('The Frozen Tundra - Score Bubble 244', LEVEL, Kind.SCORE, uid=426244),
    LBPLocationData('The Frozen Tundra - Score Bubble 245', LEVEL, Kind.SCORE, uid=426245),
    LBPLocationData('The Frozen Tundra - Score Bubble 246', LEVEL, Kind.SCORE, uid=426246),
    LBPLocationData('The Frozen Tundra - Score Bubble 247', LEVEL, Kind.SCORE, uid=426247),
    LBPLocationData('The Frozen Tundra - Score Bubble 248', LEVEL, Kind.SCORE, uid=426248),
    LBPLocationData('The Frozen Tundra - Score Bubble 249', LEVEL, Kind.SCORE, uid=426249),
    LBPLocationData('The Frozen Tundra - Score Bubble 250', LEVEL, Kind.SCORE, uid=426250),
    LBPLocationData('The Frozen Tundra - Score Bubble 251', LEVEL, Kind.SCORE, uid=426251),
    LBPLocationData('The Frozen Tundra - Score Bubble 252', LEVEL, Kind.SCORE, uid=426252),
    LBPLocationData('The Frozen Tundra - Score Bubble 253', LEVEL, Kind.SCORE, uid=426253),
    LBPLocationData('The Frozen Tundra - Score Bubble 254', LEVEL, Kind.SCORE, uid=426254),
    LBPLocationData('The Frozen Tundra - Score Bubble 255', LEVEL, Kind.SCORE, uid=426255),
    LBPLocationData('The Frozen Tundra - Score Bubble 256', LEVEL, Kind.SCORE, uid=429262),
    LBPLocationData('The Frozen Tundra - Score Bubble 257', LEVEL, Kind.SCORE, uid=429263),
    LBPLocationData('The Frozen Tundra - Score Bubble 258', LEVEL, Kind.SCORE, uid=429264),
    LBPLocationData('The Frozen Tundra - Score Bubble 259', LEVEL, Kind.SCORE, uid=430711),
    LBPLocationData('The Frozen Tundra - Score Bubble 260', LEVEL, Kind.SCORE, uid=430712),
    LBPLocationData('The Frozen Tundra - Score Bubble 261', LEVEL, Kind.SCORE, uid=430713),
    LBPLocationData('The Frozen Tundra - Score Bubble 262', LEVEL, Kind.SCORE, uid=430714),
    LBPLocationData('The Frozen Tundra - Score Bubble 263', LEVEL, Kind.SCORE, uid=430715),
    LBPLocationData('The Frozen Tundra - Score Bubble 264', LEVEL, Kind.SCORE, uid=430716),
    LBPLocationData('The Frozen Tundra - Score Bubble 265', LEVEL, Kind.SCORE, uid=430717),
    LBPLocationData('The Frozen Tundra - Score Bubble 266', LEVEL, Kind.SCORE, uid=430718),
    LBPLocationData('The Frozen Tundra - Score Bubble 267', LEVEL, Kind.SCORE, uid=430719),
    LBPLocationData('The Frozen Tundra - Score Bubble 268', LEVEL, Kind.SCORE, uid=460491),
    LBPLocationData('The Frozen Tundra - Score Bubble 269', LEVEL, Kind.SCORE, uid=460492),
    LBPLocationData('The Frozen Tundra - Score Bubble 270', LEVEL, Kind.SCORE, uid=460493),
    LBPLocationData('The Frozen Tundra - Score Bubble 271', LEVEL, Kind.SCORE, uid=460494),
    LBPLocationData('The Frozen Tundra - Score Bubble 272', LEVEL, Kind.SCORE, uid=460495),
    LBPLocationData('The Frozen Tundra - Score Bubble 273', LEVEL, Kind.SCORE, uid=460496),
    LBPLocationData('The Frozen Tundra - Score Bubble 274', LEVEL, Kind.SCORE, uid=460497),
    LBPLocationData('The Frozen Tundra - Score Bubble 275', LEVEL, Kind.SCORE, uid=460498),
    LBPLocationData('The Frozen Tundra - Score Bubble 276', LEVEL, Kind.SCORE, uid=460499),
    LBPLocationData('The Frozen Tundra - Score Bubble 277', LEVEL, Kind.SCORE, uid=460500),
    LBPLocationData('The Frozen Tundra - Score Bubble 278', LEVEL, Kind.SCORE, uid=465037),
    LBPLocationData('The Frozen Tundra - Score Bubble 279', LEVEL, Kind.SCORE, uid=465038),
    LBPLocationData('The Frozen Tundra - Score Bubble 280', LEVEL, Kind.SCORE, uid=465039),
    LBPLocationData('The Frozen Tundra - Score Bubble 281', LEVEL, Kind.SCORE, uid=465040),
    LBPLocationData('The Frozen Tundra - Score Bubble 282', LEVEL, Kind.SCORE, uid=465041),
    LBPLocationData('The Frozen Tundra - Score Bubble 283', LEVEL, Kind.SCORE, uid=465042),
    LBPLocationData('The Frozen Tundra - Score Bubble 284', LEVEL, Kind.SCORE, uid=465043),
    LBPLocationData('The Frozen Tundra - Prize Bubble 1 - Relaxed Toy Soldier', LEVEL, Kind.PRIZE, uid=234246, plan='g33510'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 2 - Shooting Toy Soldier', LEVEL, Kind.PRIZE, uid=234248, plan='g33511'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 3 - Grenade Toy Soldier', LEVEL, Kind.PRIZE, uid=234249, plan='g33512'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 4 - Falling Icicle', LEVEL, Kind.PRIZE, uid=236290, plan='g47345'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 5 - Iron Bridge', LEVEL, Kind.PRIZE, uid=236297, plan='g48914'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 6 - Breakable Ice Platform', LEVEL, Kind.PRIZE, uid=236309, plan='g47294'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 7 - Bunker Stone', LEVEL, Kind.PRIZE, uid=236441, plan='g39297'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 8 - Cream Concrete', LEVEL, Kind.PRIZE, uid=271309, plan='g51124'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 9 - Light Bulb Graphic', LEVEL, Kind.PRIZE, uid=335954, plan='g51366'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 10 - Lone Wiper Enemy', LEVEL, Kind.PRIZE, uid=335955, plan='g56186'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 11 - Iron Oil Rig', LEVEL, Kind.PRIZE, uid=359683, plan='g47292'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 12 - Rocket Dog with Sled', LEVEL, Kind.PRIZE, uid=359685, plan='g56384'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 13 - Winter Tree', LEVEL, Kind.PRIZE, uid=359687, plan='g47293'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 14 - Long Grey Coat', LEVEL, Kind.PRIZE, uid=361644, plan='g33505'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 15 - Fur Hat', LEVEL, Kind.PRIZE, uid=361645, plan='g33506'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 16 - Ponytail Hair Wig', LEVEL, Kind.PRIZE, uid=361646, plan='g33507'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 17 - PVC Raincoat', LEVEL, Kind.PRIZE, uid=361647, plan='g33508'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 18 - PVC Trousers', LEVEL, Kind.PRIZE, uid=361648, plan='g33509'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 19 - Snow Paper', LEVEL, Kind.PRIZE, uid=361679, plan='g33513'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 20 - Newspaper', LEVEL, Kind.PRIZE, uid=362476, plan='g33525'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 21 - Narrow Hammer', LEVEL, Kind.PRIZE, uid=362477, plan='g33514'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 22 - Hazard', LEVEL, Kind.PRIZE, uid=362478, plan='g51365'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 23 - Long Ice Slide', LEVEL, Kind.PRIZE, uid=362484, plan='g47165'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 24 - Short Ice Slide', LEVEL, Kind.PRIZE, uid=362485, plan='g47169'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 25 - Level Ice Slide', LEVEL, Kind.PRIZE, uid=362486, plan='g47167'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 26 - The Last Stand', LEVEL, Kind.PRIZE, uid=362487, plan='g47360'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 27 - Missile', LEVEL, Kind.PRIZE, uid=362488, plan='g48917'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 28 - Lone Double-Wiper Enemy', LEVEL, Kind.PRIZE, uid=362489, plan='g56188'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 29 - Triple-Decker Enemy', LEVEL, Kind.PRIZE, uid=362490, plan='g60518'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 30 - Gear Graphic', LEVEL, Kind.PRIZE, uid=364371, plan='g51367'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 31 - Half Scissors', LEVEL, Kind.PRIZE, uid=364372, plan='g51364'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 32 - Dice - 6', LEVEL, Kind.PRIZE, uid=364373, plan='g51372'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 33 - Merman Fork', LEVEL, Kind.PRIZE, uid=364374, plan='g51385'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 34 - Pencil', LEVEL, Kind.PRIZE, uid=364375, plan='g51384'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 35 - Brown Stripe Patch', LEVEL, Kind.PRIZE, uid=364376, plan='g51373'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 36 - Jigsaw Piece', LEVEL, Kind.PRIZE, uid=364377, plan='g51383'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 37 - Retro TV', LEVEL, Kind.PRIZE, uid=364378, plan='g51369'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 38 - Pink Splat', LEVEL, Kind.PRIZE, uid=369480, plan='g32534', rule=Has('Gear Graphic')),
    LBPLocationData('The Frozen Tundra - Prize Bubble 39 - Tree', LEVEL, Kind.PRIZE, uid=369481, plan='g32531', rule=Has('Gear Graphic')),
    LBPLocationData('The Frozen Tundra - Prize Bubble 40 - Red Devil', LEVEL, Kind.PRIZE, uid=369483, plan='g32543', players=4),
    LBPLocationData('The Frozen Tundra - Prize Bubble 41 - Red Horns', LEVEL, Kind.PRIZE, uid=369484, plan='g32472', players=4),
    LBPLocationData('The Frozen Tundra - Prize Bubble 42 - Devil Tail', LEVEL, Kind.PRIZE, uid=369485, plan='g32386', players=4),
    LBPLocationData('The Frozen Tundra - Prize Bubble 43 - Gun Turret', LEVEL, Kind.PRIZE, uid=369751, plan='g47173'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 44 - The Soldier', LEVEL, Kind.PRIZE, uid=369752, plan='g51075'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 45 - Wirey Tree', LEVEL, Kind.PRIZE, uid=370019, plan='g33520'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 46 - Red Dress', LEVEL, Kind.PRIZE, uid=370287, plan='g39756', players=4),
    LBPLocationData('The Frozen Tundra - Prize Bubble 47 - Devil Trousers', LEVEL, Kind.PRIZE, uid=370553, plan='g32385', players=4),
    LBPLocationData('The Frozen Tundra - Prize Bubble 48 - Red Circles Pattern', LEVEL, Kind.PRIZE, uid=371084, plan='g51093'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 49 - Stylised Red Smoke', LEVEL, Kind.PRIZE, uid=371085, plan='g51123'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 50 - Spiral Graphic', LEVEL, Kind.PRIZE, uid=371088, plan='g51121'),
    LBPLocationData('The Frozen Tundra - Prize Bubble 51 - Wilderness IntMusic', LEVEL, Kind.PRIZE, uid=480782, plan='g38990'),
    LBPLocationData('The Frozen Tundra - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('The Frozen Tundra - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('The Frozen Tundra - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('The Frozen Tundra - Completion Reward 1 - Robot Box Helmet', LEVEL, Kind.REWARD, plan='g39750', condition=Kind.COMPLETE),
    LBPLocationData('The Frozen Tundra - Completion Reward 2 - Green Camo', LEVEL, Kind.REWARD, plan='g32541', condition=Kind.COMPLETE),
    LBPLocationData('The Frozen Tundra - All Prizes Reward 1 - Circus Concept with Frame', LEVEL, Kind.REWARD, plan='g52818', condition=Kind.ALL_PRIZES),
    LBPLocationData('The Frozen Tundra - All Prizes Reward 2 - Circus Concept', LEVEL, Kind.REWARD, plan='g52744', condition=Kind.ALL_PRIZES),
    LBPLocationData('The Frozen Tundra - Ace Reward 1 - White Neon Eyes', LEVEL, Kind.REWARD, plan='g39747', condition=Kind.ACE),
    LBPLocationData('The Frozen Tundra - Sticker Switch 1 - Gear Graphic', LEVEL, Kind.STICKER_SWITCH, uid=334354, plan='g51367'),
    LBPLocationData('The Frozen Tundra - Key 1', LEVEL, Kind.KEY, uid=229900, target_slot='SlotID{DEVELOPER, 27609}'),
)
