from rule_builder.rules import Has

from ..model import Kind, LBPLocationData

LEVEL = 'g20368'

LOCATIONS = (
    LBPLocationData("The Collector's Lair - Score Bubble 1", LEVEL, Kind.SCORE, uid=18801),
    LBPLocationData("The Collector's Lair - Score Bubble 2", LEVEL, Kind.SCORE, uid=18803),
    LBPLocationData("The Collector's Lair - Score Bubble 3", LEVEL, Kind.SCORE, uid=18805),
    LBPLocationData("The Collector's Lair - Score Bubble 4", LEVEL, Kind.SCORE, uid=18807),
    LBPLocationData("The Collector's Lair - Score Bubble 5", LEVEL, Kind.SCORE, uid=18809),
    LBPLocationData("The Collector's Lair - Score Bubble 6", LEVEL, Kind.SCORE, uid=18811),
    LBPLocationData("The Collector's Lair - Score Bubble 7", LEVEL, Kind.SCORE, uid=18813),
    LBPLocationData("The Collector's Lair - Score Bubble 8", LEVEL, Kind.SCORE, uid=18815),
    LBPLocationData("The Collector's Lair - Score Bubble 9", LEVEL, Kind.SCORE, uid=18817),
    LBPLocationData("The Collector's Lair - Score Bubble 10", LEVEL, Kind.SCORE, uid=18819),
    LBPLocationData("The Collector's Lair - Score Bubble 11", LEVEL, Kind.SCORE, uid=18821),
    LBPLocationData("The Collector's Lair - Score Bubble 12", LEVEL, Kind.SCORE, uid=18823),
    LBPLocationData("The Collector's Lair - Score Bubble 13", LEVEL, Kind.SCORE, uid=18825),
    LBPLocationData("The Collector's Lair - Score Bubble 14", LEVEL, Kind.SCORE, uid=18827),
    LBPLocationData("The Collector's Lair - Score Bubble 15", LEVEL, Kind.SCORE, uid=18829),
    LBPLocationData("The Collector's Lair - Score Bubble 16", LEVEL, Kind.SCORE, uid=18831),
    LBPLocationData("The Collector's Lair - Score Bubble 17", LEVEL, Kind.SCORE, uid=18833),
    LBPLocationData("The Collector's Lair - Score Bubble 18", LEVEL, Kind.SCORE, uid=18835),
    LBPLocationData("The Collector's Lair - Score Bubble 19", LEVEL, Kind.SCORE, uid=18837),
    LBPLocationData("The Collector's Lair - Score Bubble 20", LEVEL, Kind.SCORE, uid=18839),
    LBPLocationData("The Collector's Lair - Score Bubble 21", LEVEL, Kind.SCORE, uid=18841),
    LBPLocationData("The Collector's Lair - Score Bubble 22", LEVEL, Kind.SCORE, uid=18847),
    LBPLocationData("The Collector's Lair - Score Bubble 23", LEVEL, Kind.SCORE, uid=18849),
    LBPLocationData("The Collector's Lair - Score Bubble 24", LEVEL, Kind.SCORE, uid=18851),
    LBPLocationData("The Collector's Lair - Score Bubble 25", LEVEL, Kind.SCORE, uid=18853),
    LBPLocationData("The Collector's Lair - Score Bubble 26", LEVEL, Kind.SCORE, uid=18855),
    LBPLocationData("The Collector's Lair - Score Bubble 27", LEVEL, Kind.SCORE, uid=18857),
    LBPLocationData("The Collector's Lair - Score Bubble 28", LEVEL, Kind.SCORE, uid=18858),
    LBPLocationData("The Collector's Lair - Score Bubble 29", LEVEL, Kind.SCORE, uid=18859),
    LBPLocationData("The Collector's Lair - Score Bubble 30", LEVEL, Kind.SCORE, uid=18860),
    LBPLocationData("The Collector's Lair - Score Bubble 31", LEVEL, Kind.SCORE, uid=18861),
    LBPLocationData("The Collector's Lair - Score Bubble 32", LEVEL, Kind.SCORE, uid=18862),
    LBPLocationData("The Collector's Lair - Score Bubble 33", LEVEL, Kind.SCORE, uid=18863),
    LBPLocationData("The Collector's Lair - Score Bubble 34", LEVEL, Kind.SCORE, uid=18864),
    LBPLocationData("The Collector's Lair - Score Bubble 35", LEVEL, Kind.SCORE, uid=18865),
    LBPLocationData("The Collector's Lair - Score Bubble 36", LEVEL, Kind.SCORE, uid=18866),
    LBPLocationData("The Collector's Lair - Score Bubble 37", LEVEL, Kind.SCORE, uid=18867),
    LBPLocationData("The Collector's Lair - Score Bubble 38", LEVEL, Kind.SCORE, uid=18868),
    LBPLocationData("The Collector's Lair - Score Bubble 39", LEVEL, Kind.SCORE, uid=18869),
    LBPLocationData("The Collector's Lair - Score Bubble 40", LEVEL, Kind.SCORE, uid=18870),
    LBPLocationData("The Collector's Lair - Score Bubble 41", LEVEL, Kind.SCORE, uid=18871),
    LBPLocationData("The Collector's Lair - Score Bubble 42", LEVEL, Kind.SCORE, uid=18876),
    LBPLocationData("The Collector's Lair - Score Bubble 43", LEVEL, Kind.SCORE, uid=18877),
    LBPLocationData("The Collector's Lair - Score Bubble 44", LEVEL, Kind.SCORE, uid=18878),
    LBPLocationData("The Collector's Lair - Score Bubble 45", LEVEL, Kind.SCORE, uid=18879),
    LBPLocationData("The Collector's Lair - Score Bubble 46", LEVEL, Kind.SCORE, uid=18880),
    LBPLocationData("The Collector's Lair - Score Bubble 47", LEVEL, Kind.SCORE, uid=18881),
    LBPLocationData("The Collector's Lair - Score Bubble 48", LEVEL, Kind.SCORE, uid=18882),
    LBPLocationData("The Collector's Lair - Score Bubble 49", LEVEL, Kind.SCORE, uid=18883),
    LBPLocationData("The Collector's Lair - Score Bubble 50", LEVEL, Kind.SCORE, uid=18894),
    LBPLocationData("The Collector's Lair - Score Bubble 51", LEVEL, Kind.SCORE, uid=18895),
    LBPLocationData("The Collector's Lair - Score Bubble 52", LEVEL, Kind.SCORE, uid=18896),
    LBPLocationData("The Collector's Lair - Score Bubble 53", LEVEL, Kind.SCORE, uid=18897),
    LBPLocationData("The Collector's Lair - Score Bubble 54", LEVEL, Kind.SCORE, uid=18900),
    LBPLocationData("The Collector's Lair - Score Bubble 55", LEVEL, Kind.SCORE, uid=18901),
    LBPLocationData("The Collector's Lair - Score Bubble 56", LEVEL, Kind.SCORE, uid=18902),
    LBPLocationData("The Collector's Lair - Score Bubble 57", LEVEL, Kind.SCORE, uid=18903),
    LBPLocationData("The Collector's Lair - Score Bubble 58", LEVEL, Kind.SCORE, uid=18904),
    LBPLocationData("The Collector's Lair - Score Bubble 59", LEVEL, Kind.SCORE, uid=18905),
    LBPLocationData("The Collector's Lair - Score Bubble 60", LEVEL, Kind.SCORE, uid=18906),
    LBPLocationData("The Collector's Lair - Score Bubble 61", LEVEL, Kind.SCORE, uid=18907),
    LBPLocationData("The Collector's Lair - Score Bubble 62", LEVEL, Kind.SCORE, uid=18908),
    LBPLocationData("The Collector's Lair - Score Bubble 63", LEVEL, Kind.SCORE, uid=18909),
    LBPLocationData("The Collector's Lair - Score Bubble 64", LEVEL, Kind.SCORE, uid=18910),
    LBPLocationData("The Collector's Lair - Score Bubble 65", LEVEL, Kind.SCORE, uid=18911),
    LBPLocationData("The Collector's Lair - Score Bubble 66", LEVEL, Kind.SCORE, uid=18912),
    LBPLocationData("The Collector's Lair - Score Bubble 67", LEVEL, Kind.SCORE, uid=18913),
    LBPLocationData("The Collector's Lair - Score Bubble 68", LEVEL, Kind.SCORE, uid=18914),
    LBPLocationData("The Collector's Lair - Score Bubble 69", LEVEL, Kind.SCORE, uid=18915),
    LBPLocationData("The Collector's Lair - Score Bubble 70", LEVEL, Kind.SCORE, uid=18916),
    LBPLocationData("The Collector's Lair - Score Bubble 71", LEVEL, Kind.SCORE, uid=18917),
    LBPLocationData("The Collector's Lair - Score Bubble 72", LEVEL, Kind.SCORE, uid=18918),
    LBPLocationData("The Collector's Lair - Score Bubble 73", LEVEL, Kind.SCORE, uid=18919),
    LBPLocationData("The Collector's Lair - Score Bubble 74", LEVEL, Kind.SCORE, uid=18920),
    LBPLocationData("The Collector's Lair - Score Bubble 75", LEVEL, Kind.SCORE, uid=18924),
    LBPLocationData("The Collector's Lair - Score Bubble 76", LEVEL, Kind.SCORE, uid=18990),
    LBPLocationData("The Collector's Lair - Score Bubble 77", LEVEL, Kind.SCORE, uid=18991),
    LBPLocationData("The Collector's Lair - Score Bubble 78", LEVEL, Kind.SCORE, uid=18992),
    LBPLocationData("The Collector's Lair - Score Bubble 79", LEVEL, Kind.SCORE, uid=18993),
    LBPLocationData("The Collector's Lair - Score Bubble 80", LEVEL, Kind.SCORE, uid=18994),
    LBPLocationData("The Collector's Lair - Score Bubble 81", LEVEL, Kind.SCORE, uid=18995),
    LBPLocationData("The Collector's Lair - Score Bubble 82", LEVEL, Kind.SCORE, uid=18996),
    LBPLocationData("The Collector's Lair - Score Bubble 83", LEVEL, Kind.SCORE, uid=18997),
    LBPLocationData("The Collector's Lair - Score Bubble 84", LEVEL, Kind.SCORE, uid=18998),
    LBPLocationData("The Collector's Lair - Score Bubble 85", LEVEL, Kind.SCORE, uid=18999),
    LBPLocationData("The Collector's Lair - Score Bubble 86", LEVEL, Kind.SCORE, uid=19000),
    LBPLocationData("The Collector's Lair - Score Bubble 87", LEVEL, Kind.SCORE, uid=19001),
    LBPLocationData("The Collector's Lair - Score Bubble 88", LEVEL, Kind.SCORE, uid=19002),
    LBPLocationData("The Collector's Lair - Score Bubble 89", LEVEL, Kind.SCORE, uid=19003),
    LBPLocationData("The Collector's Lair - Score Bubble 90", LEVEL, Kind.SCORE, uid=19004),
    LBPLocationData("The Collector's Lair - Score Bubble 91", LEVEL, Kind.SCORE, uid=19005),
    LBPLocationData("The Collector's Lair - Score Bubble 92", LEVEL, Kind.SCORE, uid=19006),
    LBPLocationData("The Collector's Lair - Score Bubble 93", LEVEL, Kind.SCORE, uid=19007),
    LBPLocationData("The Collector's Lair - Score Bubble 94", LEVEL, Kind.SCORE, uid=19008),
    LBPLocationData("The Collector's Lair - Score Bubble 95", LEVEL, Kind.SCORE, uid=19009),
    LBPLocationData("The Collector's Lair - Score Bubble 96", LEVEL, Kind.SCORE, uid=19010),
    LBPLocationData("The Collector's Lair - Score Bubble 97", LEVEL, Kind.SCORE, uid=19011),
    LBPLocationData("The Collector's Lair - Score Bubble 98", LEVEL, Kind.SCORE, uid=19012),
    LBPLocationData("The Collector's Lair - Score Bubble 99", LEVEL, Kind.SCORE, uid=19013),
    LBPLocationData("The Collector's Lair - Score Bubble 100", LEVEL, Kind.SCORE, uid=19014),
    LBPLocationData("The Collector's Lair - Score Bubble 101", LEVEL, Kind.SCORE, uid=19390),
    LBPLocationData("The Collector's Lair - Score Bubble 102", LEVEL, Kind.SCORE, uid=19391),
    LBPLocationData("The Collector's Lair - Score Bubble 103", LEVEL, Kind.SCORE, uid=19392),
    LBPLocationData("The Collector's Lair - Score Bubble 104", LEVEL, Kind.SCORE, uid=19393),
    LBPLocationData("The Collector's Lair - Score Bubble 105", LEVEL, Kind.SCORE, uid=19394),
    LBPLocationData("The Collector's Lair - Score Bubble 106", LEVEL, Kind.SCORE, uid=19395),
    LBPLocationData("The Collector's Lair - Score Bubble 107", LEVEL, Kind.SCORE, uid=19396),
    LBPLocationData("The Collector's Lair - Score Bubble 108", LEVEL, Kind.SCORE, uid=19397),
    LBPLocationData("The Collector's Lair - Score Bubble 109", LEVEL, Kind.SCORE, uid=19398),
    LBPLocationData("The Collector's Lair - Score Bubble 110", LEVEL, Kind.SCORE, uid=19399),
    LBPLocationData("The Collector's Lair - Score Bubble 111", LEVEL, Kind.SCORE, uid=19400),
    LBPLocationData("The Collector's Lair - Score Bubble 112", LEVEL, Kind.SCORE, uid=19401),
    LBPLocationData("The Collector's Lair - Score Bubble 113", LEVEL, Kind.SCORE, uid=19627),
    LBPLocationData("The Collector's Lair - Score Bubble 114", LEVEL, Kind.SCORE, uid=19628),
    LBPLocationData("The Collector's Lair - Score Bubble 115", LEVEL, Kind.SCORE, uid=19629),
    LBPLocationData("The Collector's Lair - Score Bubble 116", LEVEL, Kind.SCORE, uid=19630),
    LBPLocationData("The Collector's Lair - Score Bubble 117", LEVEL, Kind.SCORE, uid=19631),
    LBPLocationData("The Collector's Lair - Score Bubble 118", LEVEL, Kind.SCORE, uid=19632),
    LBPLocationData("The Collector's Lair - Score Bubble 119", LEVEL, Kind.SCORE, uid=19633),
    LBPLocationData("The Collector's Lair - Score Bubble 120", LEVEL, Kind.SCORE, uid=19634),
    LBPLocationData("The Collector's Lair - Score Bubble 121", LEVEL, Kind.SCORE, uid=19635),
    LBPLocationData("The Collector's Lair - Score Bubble 122", LEVEL, Kind.SCORE, uid=19636),
    LBPLocationData("The Collector's Lair - Score Bubble 123", LEVEL, Kind.SCORE, uid=19637),
    LBPLocationData("The Collector's Lair - Score Bubble 124", LEVEL, Kind.SCORE, uid=19638),
    LBPLocationData("The Collector's Lair - Score Bubble 125", LEVEL, Kind.SCORE, uid=19639),
    LBPLocationData("The Collector's Lair - Score Bubble 126", LEVEL, Kind.SCORE, uid=19640),
    LBPLocationData("The Collector's Lair - Score Bubble 127", LEVEL, Kind.SCORE, uid=19641),
    LBPLocationData("The Collector's Lair - Score Bubble 128", LEVEL, Kind.SCORE, uid=19642),
    LBPLocationData("The Collector's Lair - Score Bubble 129", LEVEL, Kind.SCORE, uid=19643),
    LBPLocationData("The Collector's Lair - Score Bubble 130", LEVEL, Kind.SCORE, uid=19644),
    LBPLocationData("The Collector's Lair - Score Bubble 131", LEVEL, Kind.SCORE, uid=19645),
    LBPLocationData("The Collector's Lair - Score Bubble 132", LEVEL, Kind.SCORE, uid=19646),
    LBPLocationData("The Collector's Lair - Score Bubble 133", LEVEL, Kind.SCORE, uid=19647),
    LBPLocationData("The Collector's Lair - Score Bubble 134", LEVEL, Kind.SCORE, uid=19648),
    LBPLocationData("The Collector's Lair - Score Bubble 135", LEVEL, Kind.SCORE, uid=19651),
    LBPLocationData("The Collector's Lair - Score Bubble 136", LEVEL, Kind.SCORE, uid=19655),
    LBPLocationData("The Collector's Lair - Score Bubble 137", LEVEL, Kind.SCORE, uid=19658),
    LBPLocationData("The Collector's Lair - Score Bubble 138", LEVEL, Kind.SCORE, uid=19659),
    LBPLocationData("The Collector's Lair - Score Bubble 139", LEVEL, Kind.SCORE, uid=19660),
    LBPLocationData("The Collector's Lair - Score Bubble 140", LEVEL, Kind.SCORE, uid=19661),
    LBPLocationData("The Collector's Lair - Score Bubble 141", LEVEL, Kind.SCORE, uid=19662),
    LBPLocationData("The Collector's Lair - Score Bubble 142", LEVEL, Kind.SCORE, uid=19663),
    LBPLocationData("The Collector's Lair - Score Bubble 143", LEVEL, Kind.SCORE, uid=19664),
    LBPLocationData("The Collector's Lair - Score Bubble 144", LEVEL, Kind.SCORE, uid=19665),
    LBPLocationData("The Collector's Lair - Score Bubble 145", LEVEL, Kind.SCORE, uid=19666),
    LBPLocationData("The Collector's Lair - Score Bubble 146", LEVEL, Kind.SCORE, uid=19667),
    LBPLocationData("The Collector's Lair - Score Bubble 147", LEVEL, Kind.SCORE, uid=19668),
    LBPLocationData("The Collector's Lair - Score Bubble 148", LEVEL, Kind.SCORE, uid=19669),
    LBPLocationData("The Collector's Lair - Score Bubble 149", LEVEL, Kind.SCORE, uid=19674),
    LBPLocationData("The Collector's Lair - Score Bubble 150", LEVEL, Kind.SCORE, uid=19675),
    LBPLocationData("The Collector's Lair - Score Bubble 151", LEVEL, Kind.SCORE, uid=19676),
    LBPLocationData("The Collector's Lair - Score Bubble 152", LEVEL, Kind.SCORE, uid=19677),
    LBPLocationData("The Collector's Lair - Score Bubble 153", LEVEL, Kind.SCORE, uid=19678),
    LBPLocationData("The Collector's Lair - Score Bubble 154", LEVEL, Kind.SCORE, uid=19679),
    LBPLocationData("The Collector's Lair - Score Bubble 155", LEVEL, Kind.SCORE, uid=19680),
    LBPLocationData("The Collector's Lair - Score Bubble 156", LEVEL, Kind.SCORE, uid=19681),
    LBPLocationData("The Collector's Lair - Score Bubble 157", LEVEL, Kind.SCORE, uid=19682),
    LBPLocationData("The Collector's Lair - Score Bubble 158", LEVEL, Kind.SCORE, uid=19683),
    LBPLocationData("The Collector's Lair - Score Bubble 159", LEVEL, Kind.SCORE, uid=19686),
    LBPLocationData("The Collector's Lair - Score Bubble 160", LEVEL, Kind.SCORE, uid=19687),
    LBPLocationData("The Collector's Lair - Score Bubble 161", LEVEL, Kind.SCORE, uid=19694),
    LBPLocationData("The Collector's Lair - Score Bubble 162", LEVEL, Kind.SCORE, uid=19695),
    LBPLocationData("The Collector's Lair - Score Bubble 163", LEVEL, Kind.SCORE, uid=19696),
    LBPLocationData("The Collector's Lair - Score Bubble 164", LEVEL, Kind.SCORE, uid=19697),
    LBPLocationData("The Collector's Lair - Score Bubble 165", LEVEL, Kind.SCORE, uid=19698),
    LBPLocationData("The Collector's Lair - Score Bubble 166", LEVEL, Kind.SCORE, uid=19699),
    LBPLocationData("The Collector's Lair - Score Bubble 167", LEVEL, Kind.SCORE, uid=19700),
    LBPLocationData("The Collector's Lair - Score Bubble 168", LEVEL, Kind.SCORE, uid=19701),
    LBPLocationData("The Collector's Lair - Score Bubble 169", LEVEL, Kind.SCORE, uid=19702),
    LBPLocationData("The Collector's Lair - Score Bubble 170", LEVEL, Kind.SCORE, uid=19703),
    LBPLocationData("The Collector's Lair - Score Bubble 171", LEVEL, Kind.SCORE, uid=19704),
    LBPLocationData("The Collector's Lair - Score Bubble 172", LEVEL, Kind.SCORE, uid=19705),
    LBPLocationData("The Collector's Lair - Score Bubble 173", LEVEL, Kind.SCORE, uid=19706),
    LBPLocationData("The Collector's Lair - Score Bubble 174", LEVEL, Kind.SCORE, uid=19707),
    LBPLocationData("The Collector's Lair - Score Bubble 175", LEVEL, Kind.SCORE, uid=19708),
    LBPLocationData("The Collector's Lair - Score Bubble 176", LEVEL, Kind.SCORE, uid=19709),
    LBPLocationData("The Collector's Lair - Score Bubble 177", LEVEL, Kind.SCORE, uid=19710),
    LBPLocationData("The Collector's Lair - Score Bubble 178", LEVEL, Kind.SCORE, uid=19711),
    LBPLocationData("The Collector's Lair - Score Bubble 179", LEVEL, Kind.SCORE, uid=19712),
    LBPLocationData("The Collector's Lair - Score Bubble 180", LEVEL, Kind.SCORE, uid=19713),
    LBPLocationData("The Collector's Lair - Score Bubble 181", LEVEL, Kind.SCORE, uid=19714),
    LBPLocationData("The Collector's Lair - Score Bubble 182", LEVEL, Kind.SCORE, uid=19715),
    LBPLocationData("The Collector's Lair - Score Bubble 183", LEVEL, Kind.SCORE, uid=19716),
    LBPLocationData("The Collector's Lair - Score Bubble 184", LEVEL, Kind.SCORE, uid=19717),
    LBPLocationData("The Collector's Lair - Score Bubble 185", LEVEL, Kind.SCORE, uid=19719),
    LBPLocationData("The Collector's Lair - Score Bubble 186", LEVEL, Kind.SCORE, uid=19720),
    LBPLocationData("The Collector's Lair - Score Bubble 187", LEVEL, Kind.SCORE, uid=19721),
    LBPLocationData("The Collector's Lair - Score Bubble 188", LEVEL, Kind.SCORE, uid=19722),
    LBPLocationData("The Collector's Lair - Score Bubble 189", LEVEL, Kind.SCORE, uid=19723),
    LBPLocationData("The Collector's Lair - Score Bubble 190", LEVEL, Kind.SCORE, uid=19724),
    LBPLocationData("The Collector's Lair - Score Bubble 191", LEVEL, Kind.SCORE, uid=19725),
    LBPLocationData("The Collector's Lair - Score Bubble 192", LEVEL, Kind.SCORE, uid=19729),
    LBPLocationData("The Collector's Lair - Score Bubble 193", LEVEL, Kind.SCORE, uid=19730),
    LBPLocationData("The Collector's Lair - Score Bubble 194", LEVEL, Kind.SCORE, uid=19731),
    LBPLocationData("The Collector's Lair - Score Bubble 195", LEVEL, Kind.SCORE, uid=19732),
    LBPLocationData("The Collector's Lair - Score Bubble 196", LEVEL, Kind.SCORE, uid=19733),
    LBPLocationData("The Collector's Lair - Score Bubble 197", LEVEL, Kind.SCORE, uid=19734),
    LBPLocationData("The Collector's Lair - Score Bubble 198", LEVEL, Kind.SCORE, uid=19735),
    LBPLocationData("The Collector's Lair - Score Bubble 199", LEVEL, Kind.SCORE, uid=19736),
    LBPLocationData("The Collector's Lair - Score Bubble 200", LEVEL, Kind.SCORE, uid=19738),
    LBPLocationData("The Collector's Lair - Score Bubble 201", LEVEL, Kind.SCORE, uid=19739),
    LBPLocationData("The Collector's Lair - Score Bubble 202", LEVEL, Kind.SCORE, uid=19740),
    LBPLocationData("The Collector's Lair - Score Bubble 203", LEVEL, Kind.SCORE, uid=19742),
    LBPLocationData("The Collector's Lair - Score Bubble 204", LEVEL, Kind.SCORE, uid=19743),
    LBPLocationData("The Collector's Lair - Score Bubble 205", LEVEL, Kind.SCORE, uid=19744),
    LBPLocationData("The Collector's Lair - Score Bubble 206", LEVEL, Kind.SCORE, uid=19745),
    LBPLocationData("The Collector's Lair - Score Bubble 207", LEVEL, Kind.SCORE, uid=19747),
    LBPLocationData("The Collector's Lair - Score Bubble 208", LEVEL, Kind.SCORE, uid=19748),
    LBPLocationData("The Collector's Lair - Score Bubble 209", LEVEL, Kind.SCORE, uid=19749),
    LBPLocationData("The Collector's Lair - Score Bubble 210", LEVEL, Kind.SCORE, uid=19750),
    LBPLocationData("The Collector's Lair - Score Bubble 211", LEVEL, Kind.SCORE, uid=19751),
    LBPLocationData("The Collector's Lair - Score Bubble 212", LEVEL, Kind.SCORE, uid=19752),
    LBPLocationData("The Collector's Lair - Score Bubble 213", LEVEL, Kind.SCORE, uid=19753),
    LBPLocationData("The Collector's Lair - Score Bubble 214", LEVEL, Kind.SCORE, uid=19754),
    LBPLocationData("The Collector's Lair - Score Bubble 215", LEVEL, Kind.SCORE, uid=19755),
    LBPLocationData("The Collector's Lair - Score Bubble 216", LEVEL, Kind.SCORE, uid=19756),
    LBPLocationData("The Collector's Lair - Score Bubble 217", LEVEL, Kind.SCORE, uid=19757),
    LBPLocationData("The Collector's Lair - Score Bubble 218", LEVEL, Kind.SCORE, uid=19758),
    LBPLocationData("The Collector's Lair - Score Bubble 219", LEVEL, Kind.SCORE, uid=19759),
    LBPLocationData("The Collector's Lair - Score Bubble 220", LEVEL, Kind.SCORE, uid=19760),
    LBPLocationData("The Collector's Lair - Score Bubble 221", LEVEL, Kind.SCORE, uid=19761),
    LBPLocationData("The Collector's Lair - Score Bubble 222", LEVEL, Kind.SCORE, uid=19762),
    LBPLocationData("The Collector's Lair - Score Bubble 223", LEVEL, Kind.SCORE, uid=19763),
    LBPLocationData("The Collector's Lair - Score Bubble 224", LEVEL, Kind.SCORE, uid=131339),
    LBPLocationData("The Collector's Lair - Score Bubble 225", LEVEL, Kind.SCORE, uid=131340),
    LBPLocationData("The Collector's Lair - Score Bubble 226", LEVEL, Kind.SCORE, uid=131341),
    LBPLocationData("The Collector's Lair - Score Bubble 227", LEVEL, Kind.SCORE, uid=131345),
    LBPLocationData("The Collector's Lair - Score Bubble 228", LEVEL, Kind.SCORE, uid=131346),
    LBPLocationData("The Collector's Lair - Score Bubble 229", LEVEL, Kind.SCORE, uid=131347),
    LBPLocationData("The Collector's Lair - Score Bubble 230", LEVEL, Kind.SCORE, uid=131348),
    LBPLocationData("The Collector's Lair - Score Bubble 231", LEVEL, Kind.SCORE, uid=134285),
    LBPLocationData("The Collector's Lair - Score Bubble 232", LEVEL, Kind.SCORE, uid=134286),
    LBPLocationData("The Collector's Lair - Score Bubble 233", LEVEL, Kind.SCORE, uid=134287),
    LBPLocationData("The Collector's Lair - Score Bubble 234", LEVEL, Kind.SCORE, uid=134288),
    LBPLocationData("The Collector's Lair - Score Bubble 235", LEVEL, Kind.SCORE, uid=134291),
    LBPLocationData("The Collector's Lair - Score Bubble 236", LEVEL, Kind.SCORE, uid=134292),
    LBPLocationData("The Collector's Lair - Score Bubble 237", LEVEL, Kind.SCORE, uid=134293),
    LBPLocationData("The Collector's Lair - Score Bubble 238", LEVEL, Kind.SCORE, uid=134294),
    LBPLocationData("The Collector's Lair - Score Bubble 239", LEVEL, Kind.SCORE, uid=136570),
    LBPLocationData("The Collector's Lair - Score Bubble 240", LEVEL, Kind.SCORE, uid=136571),
    LBPLocationData("The Collector's Lair - Score Bubble 241", LEVEL, Kind.SCORE, uid=136572),
    LBPLocationData("The Collector's Lair - Score Bubble 242", LEVEL, Kind.SCORE, uid=136573),
    LBPLocationData("The Collector's Lair - Score Bubble 243", LEVEL, Kind.SCORE, uid=136576),
    LBPLocationData("The Collector's Lair - Score Bubble 244", LEVEL, Kind.SCORE, uid=136577),
    LBPLocationData("The Collector's Lair - Score Bubble 245", LEVEL, Kind.SCORE, uid=136578),
    LBPLocationData("The Collector's Lair - Score Bubble 246", LEVEL, Kind.SCORE, uid=136579),
    LBPLocationData("The Collector's Lair - Score Bubble 247", LEVEL, Kind.SCORE, uid=136582),
    LBPLocationData("The Collector's Lair - Score Bubble 248", LEVEL, Kind.SCORE, uid=136583),
    LBPLocationData("The Collector's Lair - Score Bubble 249", LEVEL, Kind.SCORE, uid=136584),
    LBPLocationData("The Collector's Lair - Score Bubble 250", LEVEL, Kind.SCORE, uid=136585),
    LBPLocationData("The Collector's Lair - Score Bubble 251", LEVEL, Kind.SCORE, uid=136588),
    LBPLocationData("The Collector's Lair - Score Bubble 252", LEVEL, Kind.SCORE, uid=136589),
    LBPLocationData("The Collector's Lair - Score Bubble 253", LEVEL, Kind.SCORE, uid=136590),
    LBPLocationData("The Collector's Lair - Score Bubble 254", LEVEL, Kind.SCORE, uid=136591),
    LBPLocationData("The Collector's Lair - Score Bubble 255", LEVEL, Kind.SCORE, uid=136594),
    LBPLocationData("The Collector's Lair - Score Bubble 256", LEVEL, Kind.SCORE, uid=136595),
    LBPLocationData("The Collector's Lair - Score Bubble 257", LEVEL, Kind.SCORE, uid=136596),
    LBPLocationData("The Collector's Lair - Score Bubble 258", LEVEL, Kind.SCORE, uid=136597),
    LBPLocationData("The Collector's Lair - Score Bubble 259", LEVEL, Kind.SCORE, uid=148233),
    LBPLocationData("The Collector's Lair - Score Bubble 260", LEVEL, Kind.SCORE, uid=148234),
    LBPLocationData("The Collector's Lair - Score Bubble 261", LEVEL, Kind.SCORE, uid=148235),
    LBPLocationData("The Collector's Lair - Score Bubble 262", LEVEL, Kind.SCORE, uid=148236),
    LBPLocationData("The Collector's Lair - Score Bubble 263", LEVEL, Kind.SCORE, uid=148237),
    LBPLocationData("The Collector's Lair - Score Bubble 264", LEVEL, Kind.SCORE, uid=148238),
    LBPLocationData("The Collector's Lair - Score Bubble 265", LEVEL, Kind.SCORE, uid=148239),
    LBPLocationData("The Collector's Lair - Score Bubble 266", LEVEL, Kind.SCORE, uid=148240),
    LBPLocationData("The Collector's Lair - Score Bubble 267", LEVEL, Kind.SCORE, uid=148241),
    LBPLocationData("The Collector's Lair - Score Bubble 268", LEVEL, Kind.SCORE, uid=148242),
    LBPLocationData("The Collector's Lair - Score Bubble 269", LEVEL, Kind.SCORE, uid=148243),
    LBPLocationData("The Collector's Lair - Score Bubble 270", LEVEL, Kind.SCORE, uid=148244),
    LBPLocationData("The Collector's Lair - Score Bubble 271", LEVEL, Kind.SCORE, uid=148245),
    LBPLocationData("The Collector's Lair - Score Bubble 272", LEVEL, Kind.SCORE, uid=148246),
    LBPLocationData("The Collector's Lair - Score Bubble 273", LEVEL, Kind.SCORE, uid=148247),
    LBPLocationData("The Collector's Lair - Score Bubble 274", LEVEL, Kind.SCORE, uid=148248),
    LBPLocationData("The Collector's Lair - Score Bubble 275", LEVEL, Kind.SCORE, uid=148249),
    LBPLocationData("The Collector's Lair - Score Bubble 276", LEVEL, Kind.SCORE, uid=148516),
    LBPLocationData("The Collector's Lair - Score Bubble 277", LEVEL, Kind.SCORE, uid=148517),
    LBPLocationData("The Collector's Lair - Score Bubble 278", LEVEL, Kind.SCORE, uid=148518),
    LBPLocationData("The Collector's Lair - Score Bubble 279", LEVEL, Kind.SCORE, uid=148519),
    LBPLocationData("The Collector's Lair - Score Bubble 280", LEVEL, Kind.SCORE, uid=148520),
    LBPLocationData("The Collector's Lair - Score Bubble 281", LEVEL, Kind.SCORE, uid=148521),
    LBPLocationData("The Collector's Lair - Score Bubble 282", LEVEL, Kind.SCORE, uid=148522),
    LBPLocationData("The Collector's Lair - Score Bubble 283", LEVEL, Kind.SCORE, uid=148523),
    LBPLocationData("The Collector's Lair - Score Bubble 284", LEVEL, Kind.SCORE, uid=148524),
    LBPLocationData("The Collector's Lair - Score Bubble 285", LEVEL, Kind.SCORE, uid=148794),
    LBPLocationData("The Collector's Lair - Score Bubble 286", LEVEL, Kind.SCORE, uid=148795),
    LBPLocationData("The Collector's Lair - Score Bubble 287", LEVEL, Kind.SCORE, uid=148796),
    LBPLocationData("The Collector's Lair - Score Bubble 288", LEVEL, Kind.SCORE, uid=149065),
    LBPLocationData("The Collector's Lair - Score Bubble 289", LEVEL, Kind.SCORE, uid=149066),
    LBPLocationData("The Collector's Lair - Score Bubble 290", LEVEL, Kind.SCORE, uid=149067),
    LBPLocationData("The Collector's Lair - Score Bubble 291", LEVEL, Kind.SCORE, uid=149068),
    LBPLocationData("The Collector's Lair - Score Bubble 292", LEVEL, Kind.SCORE, uid=149069),
    LBPLocationData("The Collector's Lair - Score Bubble 293", LEVEL, Kind.SCORE, uid=149070),
    LBPLocationData("The Collector's Lair - Score Bubble 294", LEVEL, Kind.SCORE, uid=149608),
    LBPLocationData("The Collector's Lair - Score Bubble 295", LEVEL, Kind.SCORE, uid=149609),
    LBPLocationData("The Collector's Lair - Score Bubble 296", LEVEL, Kind.SCORE, uid=149610),
    LBPLocationData("The Collector's Lair - Score Bubble 297", LEVEL, Kind.SCORE, uid=149611),
    LBPLocationData("The Collector's Lair - Score Bubble 298", LEVEL, Kind.SCORE, uid=149612),
    LBPLocationData("The Collector's Lair - Score Bubble 299", LEVEL, Kind.SCORE, uid=149613),
    LBPLocationData("The Collector's Lair - Score Bubble 300", LEVEL, Kind.SCORE, uid=149614),
    LBPLocationData("The Collector's Lair - Score Bubble 301", LEVEL, Kind.SCORE, uid=149615),
    LBPLocationData("The Collector's Lair - Score Bubble 302", LEVEL, Kind.SCORE, uid=149616),
    LBPLocationData("The Collector's Lair - Score Bubble 303", LEVEL, Kind.SCORE, uid=149617),
    LBPLocationData("The Collector's Lair - Score Bubble 304", LEVEL, Kind.SCORE, uid=149620),
    LBPLocationData("The Collector's Lair - Score Bubble 305", LEVEL, Kind.SCORE, uid=150162),
    LBPLocationData("The Collector's Lair - Score Bubble 306", LEVEL, Kind.SCORE, uid=150163),
    LBPLocationData("The Collector's Lair - Score Bubble 307", LEVEL, Kind.SCORE, uid=150164),
    LBPLocationData("The Collector's Lair - Score Bubble 308", LEVEL, Kind.SCORE, uid=150166),
    LBPLocationData("The Collector's Lair - Score Bubble 309", LEVEL, Kind.SCORE, uid=150167),
    LBPLocationData("The Collector's Lair - Score Bubble 310", LEVEL, Kind.SCORE, uid=150437),
    LBPLocationData("The Collector's Lair - Score Bubble 311", LEVEL, Kind.SCORE, uid=150438),
    LBPLocationData("The Collector's Lair - Score Bubble 312", LEVEL, Kind.SCORE, uid=150444),
    LBPLocationData("The Collector's Lair - Score Bubble 313", LEVEL, Kind.SCORE, uid=150445),
    LBPLocationData("The Collector's Lair - Score Bubble 314", LEVEL, Kind.SCORE, uid=150446),
    LBPLocationData("The Collector's Lair - Score Bubble 315", LEVEL, Kind.SCORE, uid=150447),
    LBPLocationData("The Collector's Lair - Score Bubble 316", LEVEL, Kind.SCORE, uid=150448),
    LBPLocationData("The Collector's Lair - Score Bubble 317", LEVEL, Kind.SCORE, uid=150449),
    LBPLocationData("The Collector's Lair - Score Bubble 318", LEVEL, Kind.SCORE, uid=150722),
    LBPLocationData("The Collector's Lair - Score Bubble 319", LEVEL, Kind.SCORE, uid=150723),
    LBPLocationData("The Collector's Lair - Score Bubble 320", LEVEL, Kind.SCORE, uid=150724),
    LBPLocationData("The Collector's Lair - Score Bubble 321", LEVEL, Kind.SCORE, uid=150725),
    LBPLocationData("The Collector's Lair - Score Bubble 322", LEVEL, Kind.SCORE, uid=150726),
    LBPLocationData("The Collector's Lair - Score Bubble 323", LEVEL, Kind.SCORE, uid=150727),
    LBPLocationData("The Collector's Lair - Score Bubble 324", LEVEL, Kind.SCORE, uid=150728),
    LBPLocationData("The Collector's Lair - Score Bubble 325", LEVEL, Kind.SCORE, uid=150729),
    LBPLocationData("The Collector's Lair - Score Bubble 326", LEVEL, Kind.SCORE, uid=150730),
    LBPLocationData("The Collector's Lair - Score Bubble 327", LEVEL, Kind.SCORE, uid=150997),
    LBPLocationData("The Collector's Lair - Score Bubble 328", LEVEL, Kind.SCORE, uid=150998),
    LBPLocationData("The Collector's Lair - Score Bubble 329", LEVEL, Kind.SCORE, uid=150999),
    LBPLocationData("The Collector's Lair - Score Bubble 330", LEVEL, Kind.SCORE, uid=151268),
    LBPLocationData("The Collector's Lair - Score Bubble 331", LEVEL, Kind.SCORE, uid=151269),
    LBPLocationData("The Collector's Lair - Score Bubble 332", LEVEL, Kind.SCORE, uid=151270),
    LBPLocationData("The Collector's Lair - Score Bubble 333", LEVEL, Kind.SCORE, uid=151271),
    LBPLocationData("The Collector's Lair - Score Bubble 334", LEVEL, Kind.SCORE, uid=151272),
    LBPLocationData("The Collector's Lair - Score Bubble 335", LEVEL, Kind.SCORE, uid=151273),
    LBPLocationData("The Collector's Lair - Score Bubble 336", LEVEL, Kind.SCORE, uid=151274),
    LBPLocationData("The Collector's Lair - Score Bubble 337", LEVEL, Kind.SCORE, uid=151275),
    LBPLocationData("The Collector's Lair - Score Bubble 338", LEVEL, Kind.SCORE, uid=151276),
    LBPLocationData("The Collector's Lair - Score Bubble 339", LEVEL, Kind.SCORE, uid=151277),
    LBPLocationData("The Collector's Lair - Score Bubble 340", LEVEL, Kind.SCORE, uid=151278),
    LBPLocationData("The Collector's Lair - Score Bubble 341", LEVEL, Kind.SCORE, uid=151282),
    LBPLocationData("The Collector's Lair - Score Bubble 342", LEVEL, Kind.SCORE, uid=151283),
    LBPLocationData("The Collector's Lair - Score Bubble 343", LEVEL, Kind.SCORE, uid=151284),
    LBPLocationData("The Collector's Lair - Score Bubble 344", LEVEL, Kind.SCORE, uid=151285),
    LBPLocationData("The Collector's Lair - Score Bubble 345", LEVEL, Kind.SCORE, uid=151286),
    LBPLocationData("The Collector's Lair - Score Bubble 346", LEVEL, Kind.SCORE, uid=151287),
    LBPLocationData("The Collector's Lair - Score Bubble 347", LEVEL, Kind.SCORE, uid=151288),
    LBPLocationData("The Collector's Lair - Score Bubble 348", LEVEL, Kind.SCORE, uid=151289),
    LBPLocationData("The Collector's Lair - Score Bubble 349", LEVEL, Kind.SCORE, uid=151557),
    LBPLocationData("The Collector's Lair - Score Bubble 350", LEVEL, Kind.SCORE, uid=151558),
    LBPLocationData("The Collector's Lair - Score Bubble 351", LEVEL, Kind.SCORE, uid=229295),
    LBPLocationData("The Collector's Lair - Score Bubble 352", LEVEL, Kind.SCORE, uid=229297),
    LBPLocationData("The Collector's Lair - Score Bubble 353", LEVEL, Kind.SCORE, uid=229299),
    LBPLocationData("The Collector's Lair - Score Bubble 354", LEVEL, Kind.SCORE, uid=232752),
    LBPLocationData("The Collector's Lair - Score Bubble 355", LEVEL, Kind.SCORE, uid=232754),
    LBPLocationData("The Collector's Lair - Score Bubble 356", LEVEL, Kind.SCORE, uid=232755),
    LBPLocationData("The Collector's Lair - Score Bubble 357", LEVEL, Kind.SCORE, uid=232756),
    LBPLocationData("The Collector's Lair - Score Bubble 358", LEVEL, Kind.SCORE, uid=232757),
    LBPLocationData("The Collector's Lair - Score Bubble 359", LEVEL, Kind.SCORE, uid=232758),
    LBPLocationData("The Collector's Lair - Score Bubble 360", LEVEL, Kind.SCORE, uid=232759),
    LBPLocationData("The Collector's Lair - Score Bubble 361", LEVEL, Kind.SCORE, uid=232760),
    LBPLocationData("The Collector's Lair - Score Bubble 362", LEVEL, Kind.SCORE, uid=232761),
    LBPLocationData("The Collector's Lair - Score Bubble 363", LEVEL, Kind.SCORE, uid=232762),
    LBPLocationData("The Collector's Lair - Score Bubble 364", LEVEL, Kind.SCORE, uid=232763),
    LBPLocationData("The Collector's Lair - Score Bubble 365", LEVEL, Kind.SCORE, uid=232764),
    LBPLocationData("The Collector's Lair - Score Bubble 366", LEVEL, Kind.SCORE, uid=232765),
    LBPLocationData("The Collector's Lair - Score Bubble 367", LEVEL, Kind.SCORE, uid=232766),
    LBPLocationData("The Collector's Lair - Score Bubble 368", LEVEL, Kind.SCORE, uid=232767),
    LBPLocationData("The Collector's Lair - Score Bubble 369", LEVEL, Kind.SCORE, uid=232768),
    LBPLocationData("The Collector's Lair - Score Bubble 370", LEVEL, Kind.SCORE, uid=232769),
    LBPLocationData("The Collector's Lair - Score Bubble 371", LEVEL, Kind.SCORE, uid=232770),
    LBPLocationData("The Collector's Lair - Score Bubble 372", LEVEL, Kind.SCORE, uid=232771),
    LBPLocationData("The Collector's Lair - Score Bubble 373", LEVEL, Kind.SCORE, uid=232772),
    LBPLocationData("The Collector's Lair - Score Bubble 374", LEVEL, Kind.SCORE, uid=232773),
    LBPLocationData("The Collector's Lair - Score Bubble 375", LEVEL, Kind.SCORE, uid=232774),
    LBPLocationData("The Collector's Lair - Score Bubble 376", LEVEL, Kind.SCORE, uid=232775),
    LBPLocationData("The Collector's Lair - Score Bubble 377", LEVEL, Kind.SCORE, uid=232776),
    LBPLocationData("The Collector's Lair - Score Bubble 378", LEVEL, Kind.SCORE, uid=232777),
    LBPLocationData("The Collector's Lair - Score Bubble 379", LEVEL, Kind.SCORE, uid=232778),
    LBPLocationData("The Collector's Lair - Score Bubble 380", LEVEL, Kind.SCORE, uid=232779),
    LBPLocationData("The Collector's Lair - Score Bubble 381", LEVEL, Kind.SCORE, uid=232780),
    LBPLocationData("The Collector's Lair - Score Bubble 382", LEVEL, Kind.SCORE, uid=232781),
    LBPLocationData("The Collector's Lair - Score Bubble 383", LEVEL, Kind.SCORE, uid=232782),
    LBPLocationData("The Collector's Lair - Score Bubble 384", LEVEL, Kind.SCORE, uid=232783),
    LBPLocationData("The Collector's Lair - Score Bubble 385", LEVEL, Kind.SCORE, uid=232784),
    LBPLocationData("The Collector's Lair - Score Bubble 386", LEVEL, Kind.SCORE, uid=232786),
    LBPLocationData("The Collector's Lair - Score Bubble 387", LEVEL, Kind.SCORE, uid=232787),
    LBPLocationData("The Collector's Lair - Score Bubble 388", LEVEL, Kind.SCORE, uid=232788),
    LBPLocationData("The Collector's Lair - Score Bubble 389", LEVEL, Kind.SCORE, uid=232789),
    LBPLocationData("The Collector's Lair - Score Bubble 390", LEVEL, Kind.SCORE, uid=232792),
    LBPLocationData("The Collector's Lair - Score Bubble 391", LEVEL, Kind.SCORE, uid=232796),
    LBPLocationData("The Collector's Lair - Score Bubble 392", LEVEL, Kind.SCORE, uid=232798),
    LBPLocationData("The Collector's Lair - Score Bubble 393", LEVEL, Kind.SCORE, uid=232799),
    LBPLocationData("The Collector's Lair - Score Bubble 394", LEVEL, Kind.SCORE, uid=232800),
    LBPLocationData("The Collector's Lair - Score Bubble 395", LEVEL, Kind.SCORE, uid=232801),
    LBPLocationData("The Collector's Lair - Score Bubble 396", LEVEL, Kind.SCORE, uid=232802),
    LBPLocationData("The Collector's Lair - Score Bubble 397", LEVEL, Kind.SCORE, uid=232803),
    LBPLocationData("The Collector's Lair - Score Bubble 398", LEVEL, Kind.SCORE, uid=232805),
    LBPLocationData("The Collector's Lair - Score Bubble 399", LEVEL, Kind.SCORE, uid=232806),
    LBPLocationData("The Collector's Lair - Score Bubble 400", LEVEL, Kind.SCORE, uid=232807),
    LBPLocationData("The Collector's Lair - Score Bubble 401", LEVEL, Kind.SCORE, uid=232808),
    LBPLocationData("The Collector's Lair - Score Bubble 402", LEVEL, Kind.SCORE, uid=232810),
    LBPLocationData("The Collector's Lair - Score Bubble 403", LEVEL, Kind.SCORE, uid=232811),
    LBPLocationData("The Collector's Lair - Score Bubble 404", LEVEL, Kind.SCORE, uid=232812),
    LBPLocationData("The Collector's Lair - Score Bubble 405", LEVEL, Kind.SCORE, uid=232813),
    LBPLocationData("The Collector's Lair - Score Bubble 406", LEVEL, Kind.SCORE, uid=233086),
    LBPLocationData("The Collector's Lair - Score Bubble 407", LEVEL, Kind.SCORE, uid=233087),
    LBPLocationData("The Collector's Lair - Score Bubble 408", LEVEL, Kind.SCORE, uid=233088),
    LBPLocationData("The Collector's Lair - Score Bubble 409", LEVEL, Kind.SCORE, uid=233089),
    LBPLocationData("The Collector's Lair - Score Bubble 410", LEVEL, Kind.SCORE, uid=233090),
    LBPLocationData("The Collector's Lair - Score Bubble 411", LEVEL, Kind.SCORE, uid=233091),
    LBPLocationData("The Collector's Lair - Score Bubble 412", LEVEL, Kind.SCORE, uid=233092),
    LBPLocationData("The Collector's Lair - Score Bubble 413", LEVEL, Kind.SCORE, uid=233093),
    LBPLocationData("The Collector's Lair - Score Bubble 414", LEVEL, Kind.SCORE, uid=233094),
    LBPLocationData("The Collector's Lair - Score Bubble 415", LEVEL, Kind.SCORE, uid=234685),
    LBPLocationData("The Collector's Lair - Score Bubble 416", LEVEL, Kind.SCORE, uid=234686),
    LBPLocationData("The Collector's Lair - Score Bubble 417", LEVEL, Kind.SCORE, uid=234687),
    LBPLocationData("The Collector's Lair - Score Bubble 418", LEVEL, Kind.SCORE, uid=234688),
    LBPLocationData("The Collector's Lair - Score Bubble 419", LEVEL, Kind.SCORE, uid=234689),
    LBPLocationData("The Collector's Lair - Score Bubble 420", LEVEL, Kind.SCORE, uid=234690),
    LBPLocationData("The Collector's Lair - Score Bubble 421", LEVEL, Kind.SCORE, uid=234691),
    LBPLocationData("The Collector's Lair - Score Bubble 422", LEVEL, Kind.SCORE, uid=234692),
    LBPLocationData("The Collector's Lair - Score Bubble 423", LEVEL, Kind.SCORE, uid=234693),
    LBPLocationData("The Collector's Lair - Score Bubble 424", LEVEL, Kind.SCORE, uid=234694),
    LBPLocationData("The Collector's Lair - Score Bubble 425", LEVEL, Kind.SCORE, uid=234695),
    LBPLocationData("The Collector's Lair - Score Bubble 426", LEVEL, Kind.SCORE, uid=234964),
    LBPLocationData("The Collector's Lair - Score Bubble 427", LEVEL, Kind.SCORE, uid=234965),
    LBPLocationData("The Collector's Lair - Score Bubble 428", LEVEL, Kind.SCORE, uid=234966),
    LBPLocationData("The Collector's Lair - Score Bubble 429", LEVEL, Kind.SCORE, uid=234967),
    LBPLocationData("The Collector's Lair - Score Bubble 430", LEVEL, Kind.SCORE, uid=234968),
    LBPLocationData("The Collector's Lair - Score Bubble 431", LEVEL, Kind.SCORE, uid=234969),
    LBPLocationData("The Collector's Lair - Score Bubble 432", LEVEL, Kind.SCORE, uid=234973),
    LBPLocationData("The Collector's Lair - Score Bubble 433", LEVEL, Kind.SCORE, uid=234974),
    LBPLocationData("The Collector's Lair - Score Bubble 434", LEVEL, Kind.SCORE, uid=234975),
    LBPLocationData("The Collector's Lair - Score Bubble 435", LEVEL, Kind.SCORE, uid=234976),
    LBPLocationData("The Collector's Lair - Score Bubble 436", LEVEL, Kind.SCORE, uid=234977),
    LBPLocationData("The Collector's Lair - Score Bubble 437", LEVEL, Kind.SCORE, uid=234978),
    LBPLocationData("The Collector's Lair - Score Bubble 438", LEVEL, Kind.SCORE, uid=234979),
    LBPLocationData("The Collector's Lair - Score Bubble 439", LEVEL, Kind.SCORE, uid=234980),
    LBPLocationData("The Collector's Lair - Score Bubble 440", LEVEL, Kind.SCORE, uid=235246),
    LBPLocationData("The Collector's Lair - Score Bubble 441", LEVEL, Kind.SCORE, uid=235247),
    LBPLocationData("The Collector's Lair - Score Bubble 442", LEVEL, Kind.SCORE, uid=235248),
    LBPLocationData("The Collector's Lair - Score Bubble 443", LEVEL, Kind.SCORE, uid=235249),
    LBPLocationData("The Collector's Lair - Prize Bubble 1 - Bungee Bridge", LEVEL, Kind.PRIZE, uid=18922, plan='g48132'),
    LBPLocationData("The Collector's Lair - Prize Bubble 2 - Tin Foil", LEVEL, Kind.PRIZE, uid=88321, plan='g33499'),
    LBPLocationData("The Collector's Lair - Prize Bubble 3 - Iron Circular Safe", LEVEL, Kind.PRIZE, uid=90456, plan='g48053'),
    LBPLocationData("The Collector's Lair - Prize Bubble 4 - Tube Race Washer", LEVEL, Kind.PRIZE, uid=104073, plan='g56385'),
    LBPLocationData("The Collector's Lair - Prize Bubble 5 - Tube Race Crusher 2", LEVEL, Kind.PRIZE, uid=104075, plan='g48134'),
    LBPLocationData("The Collector's Lair - Prize Bubble 6 - Little Xim", LEVEL, Kind.PRIZE, uid=136196, plan='g55911'),
    LBPLocationData("The Collector's Lair - Prize Bubble 7 - Don Lu's Dog", LEVEL, Kind.PRIZE, uid=136278, plan='g48721'),
    LBPLocationData("The Collector's Lair - Prize Bubble 8 - Meerkat Mum", LEVEL, Kind.PRIZE, uid=136284, plan='g52336'),
    LBPLocationData("The Collector's Lair - Prize Bubble 9 - Big Xam", LEVEL, Kind.PRIZE, uid=136290, plan='g55910'),
    LBPLocationData("The Collector's Lair - Prize Bubble 10 - King Croc", LEVEL, Kind.PRIZE, uid=136296, plan='g52334'),
    LBPLocationData("The Collector's Lair - Prize Bubble 11 - Mags the Mechanic", LEVEL, Kind.PRIZE, uid=136308, plan='g48961'),
    LBPLocationData("The Collector's Lair - Prize Bubble 12 - The Great Magician", LEVEL, Kind.PRIZE, uid=136314, plan='g52345'),
    LBPLocationData("The Collector's Lair - Prize Bubble 13 - Grandmaster Sensei", LEVEL, Kind.PRIZE, uid=136326, plan='g53168'),
    LBPLocationData("The Collector's Lair - Prize Bubble 14 - Devante", LEVEL, Kind.PRIZE, uid=136332, plan='g48547'),
    LBPLocationData("The Collector's Lair - Prize Bubble 15 - Frida the Bride", LEVEL, Kind.PRIZE, uid=136338, plan='g48718'),
    LBPLocationData("The Collector's Lair - Prize Bubble 16 - The Goddess", LEVEL, Kind.PRIZE, uid=136344, plan='g48490'),
    LBPLocationData("The Collector's Lair - Prize Bubble 17 - Right-Angled Platform 1", LEVEL, Kind.PRIZE, uid=147963, plan='g48064'),
    LBPLocationData("The Collector's Lair - Prize Bubble 18 - Jumper Platform", LEVEL, Kind.PRIZE, uid=148525, plan='g48127'),
    LBPLocationData("The Collector's Lair - Prize Bubble 19 - Complex Platform", LEVEL, Kind.PRIZE, uid=149063, plan='g48130'),
    LBPLocationData("The Collector's Lair - Prize Bubble 20 - Mechanical Door", LEVEL, Kind.PRIZE, uid=163370, plan='g48024'),
    LBPLocationData("The Collector's Lair - Prize Bubble 21 - Expandable Square 1", LEVEL, Kind.PRIZE, uid=163636, plan='g48041'),
    LBPLocationData("The Collector's Lair - Prize Bubble 22 - Tube Race Crusher 1", LEVEL, Kind.PRIZE, uid=165758, plan='g48133'),
    LBPLocationData("The Collector's Lair - Prize Bubble 23 - Tube Race Rotators", LEVEL, Kind.PRIZE, uid=166024, plan='g48136'),
    LBPLocationData("The Collector's Lair - Prize Bubble 24 - Platform Expander", LEVEL, Kind.PRIZE, uid=166555, plan='g48958'),
    LBPLocationData("The Collector's Lair - Prize Bubble 25 - Angled Platform Expander", LEVEL, Kind.PRIZE, uid=167616, plan='g48945'),
    LBPLocationData("The Collector's Lair - Prize Bubble 26 - Right-Angled Platform 2", LEVEL, Kind.PRIZE, uid=168412, plan='g48069'),
    LBPLocationData("The Collector's Lair - Prize Bubble 27 - Mechanical Prison", LEVEL, Kind.PRIZE, uid=169739, plan='g48026'),
    LBPLocationData("The Collector's Lair - Prize Bubble 28 - Metal Beam", LEVEL, Kind.PRIZE, uid=170270, plan='g33497'),
    LBPLocationData("The Collector's Lair - Prize Bubble 29 - Cuddly Bear Head", LEVEL, Kind.PRIZE, uid=171862, plan='g51287'),
    LBPLocationData("The Collector's Lair - Prize Bubble 30 - Cuddly Bear Arm", LEVEL, Kind.PRIZE, uid=171863, plan='g51286'),
    LBPLocationData("The Collector's Lair - Prize Bubble 31 - Cuddly Bear Leg", LEVEL, Kind.PRIZE, uid=171864, plan='g51288'),
    LBPLocationData("The Collector's Lair - Prize Bubble 32 - Cuddly Bear Torso", LEVEL, Kind.PRIZE, uid=171865, plan='g51289'),
    LBPLocationData("The Collector's Lair - Prize Bubble 33 - Male Doll Arm", LEVEL, Kind.PRIZE, uid=171866, plan='g51290'),
    LBPLocationData("The Collector's Lair - Prize Bubble 34 - Male Doll Torso", LEVEL, Kind.PRIZE, uid=171867, plan='g51291'),
    LBPLocationData("The Collector's Lair - Prize Bubble 35 - Male Doll Leg", LEVEL, Kind.PRIZE, uid=171868, plan='g50980'),
    LBPLocationData("The Collector's Lair - Prize Bubble 36 - Male Doll Head", LEVEL, Kind.PRIZE, uid=171869, plan='g50979'),
    LBPLocationData("The Collector's Lair - Prize Bubble 37 - Baby Doll Head", LEVEL, Kind.PRIZE, uid=171870, plan='g51294'),
    LBPLocationData("The Collector's Lair - Prize Bubble 38 - Baby Doll Torso", LEVEL, Kind.PRIZE, uid=171871, plan='g51296'),
    LBPLocationData("The Collector's Lair - Prize Bubble 39 - Baby Doll Arm", LEVEL, Kind.PRIZE, uid=171872, plan='g51293'),
    LBPLocationData("The Collector's Lair - Prize Bubble 40 - Baby Doll Leg", LEVEL, Kind.PRIZE, uid=171873, plan='g51295'),
    LBPLocationData("The Collector's Lair - Prize Bubble 41 - Rusty Metal", LEVEL, Kind.PRIZE, uid=172934, plan='g33496'),
    LBPLocationData("The Collector's Lair - Prize Bubble 42 - Wooden Crate", LEVEL, Kind.PRIZE, uid=173467, plan='g33500'),
    LBPLocationData("The Collector's Lair - Prize Bubble 43 - Metal Plate", LEVEL, Kind.PRIZE, uid=173468, plan='g33501'),
    LBPLocationData("The Collector's Lair - Prize Bubble 44 - Factory Silhouette", LEVEL, Kind.PRIZE, uid=173470, plan='g33523'),
    LBPLocationData("The Collector's Lair - Prize Bubble 45 - Pixel Green Block", LEVEL, Kind.PRIZE, uid=173471, plan='g33524'),
    LBPLocationData("The Collector's Lair - Prize Bubble 46 - Power Fist", LEVEL, Kind.PRIZE, uid=173472, plan='g33516'),
    LBPLocationData("The Collector's Lair - Prize Bubble 47 - Uncle Jalapeño", LEVEL, Kind.PRIZE, uid=175627, plan='g48735'),
    LBPLocationData("The Collector's Lair - Prize Bubble 48 - Frida, Don Lu & The Butler", LEVEL, Kind.PRIZE, uid=175628, plan='g52337'),
    LBPLocationData("The Collector's Lair - Prize Bubble 49 - Bear", LEVEL, Kind.PRIZE, uid=176424, plan='g48013'),
    LBPLocationData("The Collector's Lair - Prize Bubble 50 - Head Dress", LEVEL, Kind.PRIZE, uid=176691, plan='g39748', players=3),
    LBPLocationData("The Collector's Lair - Prize Bubble 51 - Chinese Dragon Mask", LEVEL, Kind.PRIZE, uid=176692, plan='g32464', players=3),
    LBPLocationData("The Collector's Lair - Prize Bubble 52 - Danger Platform", LEVEL, Kind.PRIZE, uid=176693, plan='g48128', players=3),
    LBPLocationData("The Collector's Lair - Prize Bubble 53 - Metal Vent", LEVEL, Kind.PRIZE, uid=176694, plan='g33503', players=3),
    LBPLocationData("The Collector's Lair - Prize Bubble 54 - Scale Swimsuit", LEVEL, Kind.PRIZE, uid=176695, plan='g32367', rule=Has('Wirey Tree')),
    LBPLocationData("The Collector's Lair - Prize Bubble 55 - Mermaid Tail", LEVEL, Kind.PRIZE, uid=176696, plan='g32366', rule=Has('Wirey Tree')),
    LBPLocationData("The Collector's Lair - Prize Bubble 56 - 'Rainbow Warrior'", LEVEL, Kind.PRIZE, uid=179665, plan='g52638', players=3),
    LBPLocationData("The Collector's Lair - Prize Bubble 57 - 'Leaders Of Men'", LEVEL, Kind.PRIZE, uid=179666, plan='g52637'),
    LBPLocationData("The Collector's Lair - Prize Bubble 58 - The Bouncer", LEVEL, Kind.PRIZE, uid=195743, plan='g48539'),
    LBPLocationData("The Collector's Lair - Prize Bubble 59 - Ze Dude", LEVEL, Kind.PRIZE, uid=195744, plan='g48962'),
    LBPLocationData("The Collector's Lair - Prize Bubble 60 - King Zola", LEVEL, Kind.PRIZE, uid=195745, plan='g53510'),
    LBPLocationData("The Collector's Lair - Prize Bubble 61 - Butler", LEVEL, Kind.PRIZE, uid=195746, plan='g48665'),
    LBPLocationData("The Collector's Lair - Prize Bubble 62 - Don Lu", LEVEL, Kind.PRIZE, uid=195747, plan='g48720'),
    LBPLocationData("The Collector's Lair - Prize Bubble 63 - Blue Camo", LEVEL, Kind.PRIZE, uid=206736, plan='g32539', players=3),
    LBPLocationData("The Collector's Lair - Prize Bubble 64 - The King", LEVEL, Kind.PRIZE, uid=219388, plan='g48550'),
    LBPLocationData("The Collector's Lair - Prize Bubble 65 - The Queen", LEVEL, Kind.PRIZE, uid=219655, plan='g51444'),
    LBPLocationData("The Collector's Lair - Level Complete", LEVEL, Kind.COMPLETE),
    LBPLocationData("The Collector's Lair - All Prize Bubbles", LEVEL, Kind.ALL_PRIZES),
    LBPLocationData("The Collector's Lair - Ace (No Deaths)", LEVEL, Kind.ACE),
    LBPLocationData("The Collector's Lair - Completion Reward 1 - Robot Trousers", LEVEL, Kind.REWARD, plan='g32390', condition=Kind.COMPLETE),
    LBPLocationData("The Collector's Lair - Completion Reward 2 - The Wilderness", LEVEL, Kind.REWARD, plan='g34408', condition=Kind.COMPLETE),
    LBPLocationData("The Collector's Lair - All Prizes Reward 1 - Jumping Tank", LEVEL, Kind.REWARD, plan='g50917', condition=Kind.ALL_PRIZES),
    LBPLocationData("The Collector's Lair - All Prizes Reward 2 - Very First LittleBigPlanet™ Concept with Frame", LEVEL, Kind.REWARD, plan='g52820', condition=Kind.ALL_PRIZES),
    LBPLocationData("The Collector's Lair - All Prizes Reward 3 - Very First LittleBigPlanet™ Concept", LEVEL, Kind.REWARD, plan='g52749', condition=Kind.ALL_PRIZES),
    LBPLocationData("The Collector's Lair - Ace Reward 1 - Neon Dress", LEVEL, Kind.REWARD, plan='g32391', condition=Kind.ACE),
    LBPLocationData("The Collector's Lair - Sticker Switch 1 - Wirey Tree", LEVEL, Kind.STICKER_SWITCH, uid=157487, plan='g33520'),
    LBPLocationData("The Collector's Lair - Key 1", LEVEL, Kind.KEY, uid=21791, target_slot='SlotID{DEVELOPER, 31090}'),
)
