from ..model import Kind, LBPLocationData

LEVEL = 'g31205'

LOCATIONS = (
    LBPLocationData('The Construction Site - Score Bubble 1', LEVEL, Kind.SCORE, uid=49098),
    LBPLocationData('The Construction Site - Score Bubble 2', LEVEL, Kind.SCORE, uid=49099),
    LBPLocationData('The Construction Site - Score Bubble 3', LEVEL, Kind.SCORE, uid=49100),
    LBPLocationData('The Construction Site - Score Bubble 4', LEVEL, Kind.SCORE, uid=49103),
    LBPLocationData('The Construction Site - Score Bubble 5', LEVEL, Kind.SCORE, uid=49104),
    LBPLocationData('The Construction Site - Score Bubble 6', LEVEL, Kind.SCORE, uid=49105),
    LBPLocationData('The Construction Site - Score Bubble 7', LEVEL, Kind.SCORE, uid=49111),
    LBPLocationData('The Construction Site - Score Bubble 8', LEVEL, Kind.SCORE, uid=49112),
    LBPLocationData('The Construction Site - Score Bubble 9', LEVEL, Kind.SCORE, uid=49113),
    LBPLocationData('The Construction Site - Score Bubble 10', LEVEL, Kind.SCORE, uid=49116),
    LBPLocationData('The Construction Site - Score Bubble 11', LEVEL, Kind.SCORE, uid=49117),
    LBPLocationData('The Construction Site - Score Bubble 12', LEVEL, Kind.SCORE, uid=49118),
    LBPLocationData('The Construction Site - Score Bubble 13', LEVEL, Kind.SCORE, uid=49121),
    LBPLocationData('The Construction Site - Score Bubble 14', LEVEL, Kind.SCORE, uid=49122),
    LBPLocationData('The Construction Site - Score Bubble 15', LEVEL, Kind.SCORE, uid=49123),
    LBPLocationData('The Construction Site - Score Bubble 16', LEVEL, Kind.SCORE, uid=49126),
    LBPLocationData('The Construction Site - Score Bubble 17', LEVEL, Kind.SCORE, uid=49127),
    LBPLocationData('The Construction Site - Score Bubble 18', LEVEL, Kind.SCORE, uid=49128),
    LBPLocationData('The Construction Site - Score Bubble 19', LEVEL, Kind.SCORE, uid=49131),
    LBPLocationData('The Construction Site - Score Bubble 20', LEVEL, Kind.SCORE, uid=49132),
    LBPLocationData('The Construction Site - Score Bubble 21', LEVEL, Kind.SCORE, uid=49133),
    LBPLocationData('The Construction Site - Score Bubble 22', LEVEL, Kind.SCORE, uid=49164),
    LBPLocationData('The Construction Site - Score Bubble 23', LEVEL, Kind.SCORE, uid=49165),
    LBPLocationData('The Construction Site - Score Bubble 24', LEVEL, Kind.SCORE, uid=49166),
    LBPLocationData('The Construction Site - Score Bubble 25', LEVEL, Kind.SCORE, uid=49169),
    LBPLocationData('The Construction Site - Score Bubble 26', LEVEL, Kind.SCORE, uid=49170),
    LBPLocationData('The Construction Site - Score Bubble 27', LEVEL, Kind.SCORE, uid=49171),
    LBPLocationData('The Construction Site - Score Bubble 28', LEVEL, Kind.SCORE, uid=49174),
    LBPLocationData('The Construction Site - Score Bubble 29', LEVEL, Kind.SCORE, uid=49175),
    LBPLocationData('The Construction Site - Score Bubble 30', LEVEL, Kind.SCORE, uid=49176),
    LBPLocationData('The Construction Site - Score Bubble 31', LEVEL, Kind.SCORE, uid=49179),
    LBPLocationData('The Construction Site - Score Bubble 32', LEVEL, Kind.SCORE, uid=49180),
    LBPLocationData('The Construction Site - Score Bubble 33', LEVEL, Kind.SCORE, uid=49181),
    LBPLocationData('The Construction Site - Score Bubble 34', LEVEL, Kind.SCORE, uid=49184),
    LBPLocationData('The Construction Site - Score Bubble 35', LEVEL, Kind.SCORE, uid=49185),
    LBPLocationData('The Construction Site - Score Bubble 36', LEVEL, Kind.SCORE, uid=49186),
    LBPLocationData('The Construction Site - Score Bubble 37', LEVEL, Kind.SCORE, uid=49235),
    LBPLocationData('The Construction Site - Score Bubble 38', LEVEL, Kind.SCORE, uid=49236),
    LBPLocationData('The Construction Site - Score Bubble 39', LEVEL, Kind.SCORE, uid=49237),
    LBPLocationData('The Construction Site - Score Bubble 40', LEVEL, Kind.SCORE, uid=49240),
    LBPLocationData('The Construction Site - Score Bubble 41', LEVEL, Kind.SCORE, uid=49241),
    LBPLocationData('The Construction Site - Score Bubble 42', LEVEL, Kind.SCORE, uid=49242),
    LBPLocationData('The Construction Site - Score Bubble 43', LEVEL, Kind.SCORE, uid=49245),
    LBPLocationData('The Construction Site - Score Bubble 44', LEVEL, Kind.SCORE, uid=49246),
    LBPLocationData('The Construction Site - Score Bubble 45', LEVEL, Kind.SCORE, uid=49247),
    LBPLocationData('The Construction Site - Score Bubble 46', LEVEL, Kind.SCORE, uid=49323),
    LBPLocationData('The Construction Site - Score Bubble 47', LEVEL, Kind.SCORE, uid=49324),
    LBPLocationData('The Construction Site - Score Bubble 48', LEVEL, Kind.SCORE, uid=49325),
    LBPLocationData('The Construction Site - Score Bubble 49', LEVEL, Kind.SCORE, uid=49326),
    LBPLocationData('The Construction Site - Score Bubble 50', LEVEL, Kind.SCORE, uid=49327),
    LBPLocationData('The Construction Site - Score Bubble 51', LEVEL, Kind.SCORE, uid=49328),
    LBPLocationData('The Construction Site - Score Bubble 52', LEVEL, Kind.SCORE, uid=49335),
    LBPLocationData('The Construction Site - Score Bubble 53', LEVEL, Kind.SCORE, uid=49336),
    LBPLocationData('The Construction Site - Score Bubble 54', LEVEL, Kind.SCORE, uid=49337),
    LBPLocationData('The Construction Site - Score Bubble 55', LEVEL, Kind.SCORE, uid=53705),
    LBPLocationData('The Construction Site - Score Bubble 56', LEVEL, Kind.SCORE, uid=53706),
    LBPLocationData('The Construction Site - Score Bubble 57', LEVEL, Kind.SCORE, uid=53707),
    LBPLocationData('The Construction Site - Score Bubble 58', LEVEL, Kind.SCORE, uid=53711),
    LBPLocationData('The Construction Site - Score Bubble 59', LEVEL, Kind.SCORE, uid=53712),
    LBPLocationData('The Construction Site - Score Bubble 60', LEVEL, Kind.SCORE, uid=53713),
    LBPLocationData('The Construction Site - Score Bubble 61', LEVEL, Kind.SCORE, uid=53721),
    LBPLocationData('The Construction Site - Score Bubble 62', LEVEL, Kind.SCORE, uid=53722),
    LBPLocationData('The Construction Site - Score Bubble 63', LEVEL, Kind.SCORE, uid=53723),
    LBPLocationData('The Construction Site - Score Bubble 64', LEVEL, Kind.SCORE, uid=53772),
    LBPLocationData('The Construction Site - Score Bubble 65', LEVEL, Kind.SCORE, uid=53773),
    LBPLocationData('The Construction Site - Score Bubble 66', LEVEL, Kind.SCORE, uid=53774),
    LBPLocationData('The Construction Site - Score Bubble 67', LEVEL, Kind.SCORE, uid=53778),
    LBPLocationData('The Construction Site - Score Bubble 68', LEVEL, Kind.SCORE, uid=53779),
    LBPLocationData('The Construction Site - Score Bubble 69', LEVEL, Kind.SCORE, uid=53780),
    LBPLocationData('The Construction Site - Score Bubble 70', LEVEL, Kind.SCORE, uid=54055),
    LBPLocationData('The Construction Site - Score Bubble 71', LEVEL, Kind.SCORE, uid=54056),
    LBPLocationData('The Construction Site - Score Bubble 72', LEVEL, Kind.SCORE, uid=54057),
    LBPLocationData('The Construction Site - Score Bubble 73', LEVEL, Kind.SCORE, uid=54653),
    LBPLocationData('The Construction Site - Score Bubble 74', LEVEL, Kind.SCORE, uid=54654),
    LBPLocationData('The Construction Site - Score Bubble 75', LEVEL, Kind.SCORE, uid=54655),
    LBPLocationData('The Construction Site - Score Bubble 76', LEVEL, Kind.SCORE, uid=54666),
    LBPLocationData('The Construction Site - Score Bubble 77', LEVEL, Kind.SCORE, uid=54667),
    LBPLocationData('The Construction Site - Score Bubble 78', LEVEL, Kind.SCORE, uid=54668),
    LBPLocationData('The Construction Site - Score Bubble 79', LEVEL, Kind.SCORE, uid=54673),
    LBPLocationData('The Construction Site - Score Bubble 80', LEVEL, Kind.SCORE, uid=54674),
    LBPLocationData('The Construction Site - Score Bubble 81', LEVEL, Kind.SCORE, uid=54675),
    LBPLocationData('The Construction Site - Score Bubble 82', LEVEL, Kind.SCORE, uid=54678),
    LBPLocationData('The Construction Site - Score Bubble 83', LEVEL, Kind.SCORE, uid=54679),
    LBPLocationData('The Construction Site - Score Bubble 84', LEVEL, Kind.SCORE, uid=54680),
    LBPLocationData('The Construction Site - Score Bubble 85', LEVEL, Kind.SCORE, uid=54723),
    LBPLocationData('The Construction Site - Score Bubble 86', LEVEL, Kind.SCORE, uid=54724),
    LBPLocationData('The Construction Site - Score Bubble 87', LEVEL, Kind.SCORE, uid=54725),
    LBPLocationData('The Construction Site - Score Bubble 88', LEVEL, Kind.SCORE, uid=54785),
    LBPLocationData('The Construction Site - Score Bubble 89', LEVEL, Kind.SCORE, uid=54787),
    LBPLocationData('The Construction Site - Score Bubble 90', LEVEL, Kind.SCORE, uid=54788),
    LBPLocationData('The Construction Site - Score Bubble 91', LEVEL, Kind.SCORE, uid=54789),
    LBPLocationData('The Construction Site - Score Bubble 92', LEVEL, Kind.SCORE, uid=54790),
    LBPLocationData('The Construction Site - Score Bubble 93', LEVEL, Kind.SCORE, uid=54791),
    LBPLocationData('The Construction Site - Score Bubble 94', LEVEL, Kind.SCORE, uid=54792),
    LBPLocationData('The Construction Site - Score Bubble 95', LEVEL, Kind.SCORE, uid=54793),
    LBPLocationData('The Construction Site - Score Bubble 96', LEVEL, Kind.SCORE, uid=54794),
    LBPLocationData('The Construction Site - Score Bubble 97', LEVEL, Kind.SCORE, uid=54795),
    LBPLocationData('The Construction Site - Score Bubble 98', LEVEL, Kind.SCORE, uid=54871),
    LBPLocationData('The Construction Site - Score Bubble 99', LEVEL, Kind.SCORE, uid=54872),
    LBPLocationData('The Construction Site - Score Bubble 100', LEVEL, Kind.SCORE, uid=54873),
    LBPLocationData('The Construction Site - Score Bubble 101', LEVEL, Kind.SCORE, uid=54874),
    LBPLocationData('The Construction Site - Score Bubble 102', LEVEL, Kind.SCORE, uid=54875),
    LBPLocationData('The Construction Site - Score Bubble 103', LEVEL, Kind.SCORE, uid=201355),
    LBPLocationData('The Construction Site - Score Bubble 104', LEVEL, Kind.SCORE, uid=201356),
    LBPLocationData('The Construction Site - Score Bubble 105', LEVEL, Kind.SCORE, uid=201357),
    LBPLocationData('The Construction Site - Score Bubble 106', LEVEL, Kind.SCORE, uid=205552),
    LBPLocationData('The Construction Site - Score Bubble 107', LEVEL, Kind.SCORE, uid=205553),
    LBPLocationData('The Construction Site - Score Bubble 108', LEVEL, Kind.SCORE, uid=205554),
    LBPLocationData('The Construction Site - Score Bubble 109', LEVEL, Kind.SCORE, uid=206393),
    LBPLocationData('The Construction Site - Score Bubble 110', LEVEL, Kind.SCORE, uid=206394),
    LBPLocationData('The Construction Site - Score Bubble 111', LEVEL, Kind.SCORE, uid=232171),
    LBPLocationData('The Construction Site - Score Bubble 112', LEVEL, Kind.SCORE, uid=232172),
    LBPLocationData('The Construction Site - Score Bubble 113', LEVEL, Kind.SCORE, uid=232173),
    LBPLocationData('The Construction Site - Prize Bubble 1 - Wheelbarrow Man', LEVEL, Kind.PRIZE, uid=16068, plan='g48979'),
    LBPLocationData('The Construction Site - Prize Bubble 2 - Basketball', LEVEL, Kind.PRIZE, uid=16225, plan='g51267'),
    LBPLocationData('The Construction Site - Prize Bubble 3 - Big Crane', LEVEL, Kind.PRIZE, uid=54731, plan='g47571', players=2),
    LBPLocationData('The Construction Site - Prize Bubble 4 - Skyline 1', LEVEL, Kind.PRIZE, uid=127375, plan='g33227'),
    LBPLocationData('The Construction Site - Prize Bubble 5 - Red Football Hat', LEVEL, Kind.PRIZE, uid=127379, plan='g33225'),
    LBPLocationData('The Construction Site - Prize Bubble 6 - Front Red Football Hat', LEVEL, Kind.PRIZE, uid=127380, plan='g33224'),
    LBPLocationData('The Construction Site - Prize Bubble 7 - Electric Guitar', LEVEL, Kind.PRIZE, uid=127381, plan='g51231'),
    LBPLocationData('The Construction Site - Prize Bubble 8 - Lightning Outline', LEVEL, Kind.PRIZE, uid=127382, plan='g51232'),
    LBPLocationData('The Construction Site - Prize Bubble 9 - Chicken Drumstick', LEVEL, Kind.PRIZE, uid=192106, plan='g33253'),
    LBPLocationData('The Construction Site - Prize Bubble 10 - Spike Hammer Block', LEVEL, Kind.PRIZE, uid=204293, plan='g56180'),
    LBPLocationData('The Construction Site - Prize Bubble 11 - Crane Hook', LEVEL, Kind.PRIZE, uid=214951, plan='g47565'),
    LBPLocationData('The Construction Site - Prize Bubble 12 - Power Digger Man', LEVEL, Kind.PRIZE, uid=215380, plan='g48983'),
    LBPLocationData('The Construction Site - Prize Bubble 13 - Long Conveyer', LEVEL, Kind.PRIZE, uid=216237, plan='g47589'),
    LBPLocationData('The Construction Site - Prize Bubble 14 - Grey Concrete', LEVEL, Kind.PRIZE, uid=216239, plan='g51097'),
    LBPLocationData('The Construction Site - Prize Bubble 15 - Boxing Glove Front', LEVEL, Kind.PRIZE, uid=217098, plan='g33248', players=2),
    LBPLocationData('The Construction Site - Prize Bubble 16 - Boxing Glove Back', LEVEL, Kind.PRIZE, uid=217099, plan='g33247', players=2),
    LBPLocationData('The Construction Site - Prize Bubble 17 - Red Stiletto', LEVEL, Kind.PRIZE, uid=217100, plan='g34607', players=2),
    LBPLocationData('The Construction Site - Prize Bubble 18 - Blue Cardboard Skyscraper', LEVEL, Kind.PRIZE, uid=217529, plan='g44741'),
    LBPLocationData('The Construction Site - Prize Bubble 19 - Red Cardboard Skyscraper', LEVEL, Kind.PRIZE, uid=217530, plan='g44739'),
    LBPLocationData('The Construction Site - Prize Bubble 20 - Brown Cardboard Skyscraper', LEVEL, Kind.PRIZE, uid=217531, plan='g44737'),
    LBPLocationData('The Construction Site - Prize Bubble 21 - Polystyrene Packing', LEVEL, Kind.PRIZE, uid=217532, plan='g33257'),
    LBPLocationData('The Construction Site - Prize Bubble 22 - Fiery Coal Emitter', LEVEL, Kind.PRIZE, uid=217534, plan='g47646'),
    LBPLocationData('The Construction Site - Prize Bubble 23 - Rough Concrete', LEVEL, Kind.PRIZE, uid=217965, plan='g51098'),
    LBPLocationData('The Construction Site - Prize Bubble 24 - Dark Grey Concrete', LEVEL, Kind.PRIZE, uid=217968, plan='g51099'),
    LBPLocationData('The Construction Site - Prize Bubble 25 - Bumpy Concrete', LEVEL, Kind.PRIZE, uid=217971, plan='g51100'),
    LBPLocationData('The Construction Site - Prize Bubble 26 - Knitted Fabric', LEVEL, Kind.PRIZE, uid=218401, plan='g33256'),
    LBPLocationData('The Construction Site - Prize Bubble 27 - Flame Motif Metal', LEVEL, Kind.PRIZE, uid=218402, plan='g33241'),
    LBPLocationData('The Construction Site - Prize Bubble 28 - Checked Concrete', LEVEL, Kind.PRIZE, uid=218403, plan='g33259'),
    LBPLocationData('The Construction Site - Prize Bubble 29 - Disco Metal', LEVEL, Kind.PRIZE, uid=218404, plan='g33238'),
    LBPLocationData('The Construction Site - Prize Bubble 30 - Brown & Cream Concrete', LEVEL, Kind.PRIZE, uid=218405, plan='g33258'),
    LBPLocationData('The Construction Site - Prize Bubble 31 - Basketball Head', LEVEL, Kind.PRIZE, uid=219690, plan='g48978'),
    LBPLocationData('The Construction Site - Prize Bubble 32 - Two Arrows Warning', LEVEL, Kind.PRIZE, uid=220547, plan='g51235'),
    LBPLocationData('The Construction Site - Prize Bubble 33 - Umbrella Warning', LEVEL, Kind.PRIZE, uid=220548, plan='g51236'),
    LBPLocationData('The Construction Site - Prize Bubble 34 - Fragile Warning', LEVEL, Kind.PRIZE, uid=220549, plan='g51234'),
    LBPLocationData('The Construction Site - Prize Bubble 35 - Plane Silhouette', LEVEL, Kind.PRIZE, uid=220550, plan='g51240'),
    LBPLocationData('The Construction Site - Prize Bubble 36 - Half Glasses', LEVEL, Kind.PRIZE, uid=220551, plan='g51233'),
    LBPLocationData('The Construction Site - Prize Bubble 37 - Intense Blue Graffiti', LEVEL, Kind.PRIZE, uid=221409, plan='g51239'),
    LBPLocationData('The Construction Site - Prize Bubble 38 - Yellow Builder Cap', LEVEL, Kind.PRIZE, uid=222709, plan='g32488', players=2),
    LBPLocationData('The Construction Site - Prize Bubble 39 - Dungarees Top', LEVEL, Kind.PRIZE, uid=222710, plan='g40434', players=2),
    LBPLocationData('The Construction Site - Prize Bubble 40 - Red Flash', LEVEL, Kind.PRIZE, uid=223139, plan='g32537'),
    LBPLocationData('The Construction Site - Prize Bubble 41 - White Burlap', LEVEL, Kind.PRIZE, uid=223140, plan='g32527'),
    LBPLocationData('The Construction Site - Prize Bubble 42 - Skyline 2', LEVEL, Kind.PRIZE, uid=237207, plan='g33226'),
    LBPLocationData("The Construction Site - Prize Bubble 43 - Ze Dude's Private Jet", LEVEL, Kind.PRIZE, uid=255267, plan='g55836'),
    LBPLocationData("The Construction Site - Prize Bubble 44 - 'Atlas'", LEVEL, Kind.PRIZE, uid=293589, plan='g33147', players=2),
    LBPLocationData('The Construction Site - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('The Construction Site - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('The Construction Site - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('The Construction Site - Completion Reward 1 - Blonde Hair Wig', LEVEL, Kind.REWARD, plan='g32484', condition=Kind.COMPLETE),
    LBPLocationData('The Construction Site - Completion Reward 2 - The Metropolis', LEVEL, Kind.REWARD, plan='g34409', condition=Kind.COMPLETE),
    LBPLocationData('The Construction Site - Completion Reward 3 - Custom Motorbike', LEVEL, Kind.REWARD, plan='g48985', condition=Kind.COMPLETE),
    LBPLocationData('The Construction Site - All Prizes Reward 1 - Monster Truck', LEVEL, Kind.REWARD, plan='g56179', condition=Kind.ALL_PRIZES),
    LBPLocationData('The Construction Site - All Prizes Reward 2 - Giant Concept with Frame', LEVEL, Kind.REWARD, plan='g52809', condition=Kind.ALL_PRIZES),
    LBPLocationData('The Construction Site - All Prizes Reward 3 - Boss Concept', LEVEL, Kind.REWARD, plan='g52753', condition=Kind.ALL_PRIZES),
    LBPLocationData('The Construction Site - Ace Reward 1 - Dinosaur Mask', LEVEL, Kind.REWARD, plan='g32476', condition=Kind.ACE),
    LBPLocationData('The Construction Site - Sticker Switch 1 - Skyline 4', LEVEL, Kind.STICKER_SWITCH, uid=127383, plan='g33210'),
    LBPLocationData('The Construction Site - Sticker Switch 2 - Skyline 3', LEVEL, Kind.STICKER_SWITCH, uid=127384, plan='g33211'),
    LBPLocationData('The Construction Site - Sticker Switch 3 - Skyline 2', LEVEL, Kind.STICKER_SWITCH, uid=127385, plan='g33226'),
    LBPLocationData('The Construction Site - Sticker Switch 4 - Skyline 4', LEVEL, Kind.STICKER_SWITCH, uid=127386, plan='g33210'),
    LBPLocationData('The Construction Site - Sticker Switch 5 - Skyline 2', LEVEL, Kind.STICKER_SWITCH, uid=127387, plan='g33226'),
    LBPLocationData('The Construction Site - Sticker Switch 6 - Skyline 4', LEVEL, Kind.STICKER_SWITCH, uid=127388, plan='g33210'),
    LBPLocationData('The Construction Site - Key 1', LEVEL, Kind.KEY, uid=16430, target_slot='SlotID{DEVELOPER, 31091}'),
)
