from ..model import Kind, LBPLocationData

LEVEL = 'g20354'

LOCATIONS = (
    LBPLocationData("The Dancers' Court - Score Bubble 1", LEVEL, Kind.SCORE, uid=15975),
    LBPLocationData("The Dancers' Court - Score Bubble 2", LEVEL, Kind.SCORE, uid=15976),
    LBPLocationData("The Dancers' Court - Score Bubble 3", LEVEL, Kind.SCORE, uid=15977),
    LBPLocationData("The Dancers' Court - Score Bubble 4", LEVEL, Kind.SCORE, uid=15978),
    LBPLocationData("The Dancers' Court - Score Bubble 5", LEVEL, Kind.SCORE, uid=15979),
    LBPLocationData("The Dancers' Court - Score Bubble 6", LEVEL, Kind.SCORE, uid=15980),
    LBPLocationData("The Dancers' Court - Score Bubble 7", LEVEL, Kind.SCORE, uid=15981),
    LBPLocationData("The Dancers' Court - Score Bubble 8", LEVEL, Kind.SCORE, uid=15982),
    LBPLocationData("The Dancers' Court - Score Bubble 9", LEVEL, Kind.SCORE, uid=15983),
    LBPLocationData("The Dancers' Court - Score Bubble 10", LEVEL, Kind.SCORE, uid=16459),
    LBPLocationData("The Dancers' Court - Score Bubble 11", LEVEL, Kind.SCORE, uid=16460),
    LBPLocationData("The Dancers' Court - Score Bubble 12", LEVEL, Kind.SCORE, uid=16461),
    LBPLocationData("The Dancers' Court - Score Bubble 13", LEVEL, Kind.SCORE, uid=16462),
    LBPLocationData("The Dancers' Court - Score Bubble 14", LEVEL, Kind.SCORE, uid=16463),
    LBPLocationData("The Dancers' Court - Score Bubble 15", LEVEL, Kind.SCORE, uid=16464),
    LBPLocationData("The Dancers' Court - Score Bubble 16", LEVEL, Kind.SCORE, uid=16465),
    LBPLocationData("The Dancers' Court - Score Bubble 17", LEVEL, Kind.SCORE, uid=16466),
    LBPLocationData("The Dancers' Court - Score Bubble 18", LEVEL, Kind.SCORE, uid=16467),
    LBPLocationData("The Dancers' Court - Score Bubble 19", LEVEL, Kind.SCORE, uid=16468),
    LBPLocationData("The Dancers' Court - Score Bubble 20", LEVEL, Kind.SCORE, uid=16469),
    LBPLocationData("The Dancers' Court - Score Bubble 21", LEVEL, Kind.SCORE, uid=16470),
    LBPLocationData("The Dancers' Court - Score Bubble 22", LEVEL, Kind.SCORE, uid=16471),
    LBPLocationData("The Dancers' Court - Score Bubble 23", LEVEL, Kind.SCORE, uid=16472),
    LBPLocationData("The Dancers' Court - Score Bubble 24", LEVEL, Kind.SCORE, uid=16473),
    LBPLocationData("The Dancers' Court - Score Bubble 25", LEVEL, Kind.SCORE, uid=16474),
    LBPLocationData("The Dancers' Court - Score Bubble 26", LEVEL, Kind.SCORE, uid=16475),
    LBPLocationData("The Dancers' Court - Score Bubble 27", LEVEL, Kind.SCORE, uid=16641),
    LBPLocationData("The Dancers' Court - Score Bubble 28", LEVEL, Kind.SCORE, uid=16642),
    LBPLocationData("The Dancers' Court - Score Bubble 29", LEVEL, Kind.SCORE, uid=16643),
    LBPLocationData("The Dancers' Court - Score Bubble 30", LEVEL, Kind.SCORE, uid=16644),
    LBPLocationData("The Dancers' Court - Score Bubble 31", LEVEL, Kind.SCORE, uid=16645),
    LBPLocationData("The Dancers' Court - Score Bubble 32", LEVEL, Kind.SCORE, uid=16646),
    LBPLocationData("The Dancers' Court - Score Bubble 33", LEVEL, Kind.SCORE, uid=16647),
    LBPLocationData("The Dancers' Court - Score Bubble 34", LEVEL, Kind.SCORE, uid=16648),
    LBPLocationData("The Dancers' Court - Score Bubble 35", LEVEL, Kind.SCORE, uid=16649),
    LBPLocationData("The Dancers' Court - Score Bubble 36", LEVEL, Kind.SCORE, uid=16650),
    LBPLocationData("The Dancers' Court - Score Bubble 37", LEVEL, Kind.SCORE, uid=16651),
    LBPLocationData("The Dancers' Court - Score Bubble 38", LEVEL, Kind.SCORE, uid=16652),
    LBPLocationData("The Dancers' Court - Score Bubble 39", LEVEL, Kind.SCORE, uid=16653),
    LBPLocationData("The Dancers' Court - Score Bubble 40", LEVEL, Kind.SCORE, uid=16654),
    LBPLocationData("The Dancers' Court - Score Bubble 41", LEVEL, Kind.SCORE, uid=16655),
    LBPLocationData("The Dancers' Court - Score Bubble 42", LEVEL, Kind.SCORE, uid=63377),
    LBPLocationData("The Dancers' Court - Score Bubble 43", LEVEL, Kind.SCORE, uid=63379),
    LBPLocationData("The Dancers' Court - Score Bubble 44", LEVEL, Kind.SCORE, uid=63381),
    LBPLocationData("The Dancers' Court - Score Bubble 45", LEVEL, Kind.SCORE, uid=63383),
    LBPLocationData("The Dancers' Court - Score Bubble 46", LEVEL, Kind.SCORE, uid=63384),
    LBPLocationData("The Dancers' Court - Score Bubble 47", LEVEL, Kind.SCORE, uid=63385),
    LBPLocationData("The Dancers' Court - Score Bubble 48", LEVEL, Kind.SCORE, uid=63386),
    LBPLocationData("The Dancers' Court - Score Bubble 49", LEVEL, Kind.SCORE, uid=63387),
    LBPLocationData("The Dancers' Court - Score Bubble 50", LEVEL, Kind.SCORE, uid=63388),
    LBPLocationData("The Dancers' Court - Score Bubble 51", LEVEL, Kind.SCORE, uid=63389),
    LBPLocationData("The Dancers' Court - Score Bubble 52", LEVEL, Kind.SCORE, uid=63390),
    LBPLocationData("The Dancers' Court - Score Bubble 53", LEVEL, Kind.SCORE, uid=63391),
    LBPLocationData("The Dancers' Court - Score Bubble 54", LEVEL, Kind.SCORE, uid=64037),
    LBPLocationData("The Dancers' Court - Score Bubble 55", LEVEL, Kind.SCORE, uid=64038),
    LBPLocationData("The Dancers' Court - Score Bubble 56", LEVEL, Kind.SCORE, uid=64039),
    LBPLocationData("The Dancers' Court - Score Bubble 57", LEVEL, Kind.SCORE, uid=64040),
    LBPLocationData("The Dancers' Court - Score Bubble 58", LEVEL, Kind.SCORE, uid=64048),
    LBPLocationData("The Dancers' Court - Score Bubble 59", LEVEL, Kind.SCORE, uid=64049),
    LBPLocationData("The Dancers' Court - Score Bubble 60", LEVEL, Kind.SCORE, uid=64050),
    LBPLocationData("The Dancers' Court - Score Bubble 61", LEVEL, Kind.SCORE, uid=64051),
    LBPLocationData("The Dancers' Court - Score Bubble 62", LEVEL, Kind.SCORE, uid=64059),
    LBPLocationData("The Dancers' Court - Score Bubble 63", LEVEL, Kind.SCORE, uid=64060),
    LBPLocationData("The Dancers' Court - Score Bubble 64", LEVEL, Kind.SCORE, uid=64061),
    LBPLocationData("The Dancers' Court - Score Bubble 65", LEVEL, Kind.SCORE, uid=64062),
    LBPLocationData("The Dancers' Court - Score Bubble 66", LEVEL, Kind.SCORE, uid=64070),
    LBPLocationData("The Dancers' Court - Score Bubble 67", LEVEL, Kind.SCORE, uid=64071),
    LBPLocationData("The Dancers' Court - Score Bubble 68", LEVEL, Kind.SCORE, uid=64072),
    LBPLocationData("The Dancers' Court - Score Bubble 69", LEVEL, Kind.SCORE, uid=64073),
    LBPLocationData("The Dancers' Court - Score Bubble 70", LEVEL, Kind.SCORE, uid=64074),
    LBPLocationData("The Dancers' Court - Score Bubble 71", LEVEL, Kind.SCORE, uid=64081),
    LBPLocationData("The Dancers' Court - Score Bubble 72", LEVEL, Kind.SCORE, uid=64082),
    LBPLocationData("The Dancers' Court - Score Bubble 73", LEVEL, Kind.SCORE, uid=64083),
    LBPLocationData("The Dancers' Court - Score Bubble 74", LEVEL, Kind.SCORE, uid=64092),
    LBPLocationData("The Dancers' Court - Score Bubble 75", LEVEL, Kind.SCORE, uid=64093),
    LBPLocationData("The Dancers' Court - Score Bubble 76", LEVEL, Kind.SCORE, uid=64094),
    LBPLocationData("The Dancers' Court - Score Bubble 77", LEVEL, Kind.SCORE, uid=64095),
    LBPLocationData("The Dancers' Court - Score Bubble 78", LEVEL, Kind.SCORE, uid=64096),
    LBPLocationData("The Dancers' Court - Score Bubble 79", LEVEL, Kind.SCORE, uid=64097),
    LBPLocationData("The Dancers' Court - Score Bubble 80", LEVEL, Kind.SCORE, uid=64101),
    LBPLocationData("The Dancers' Court - Score Bubble 81", LEVEL, Kind.SCORE, uid=64102),
    LBPLocationData("The Dancers' Court - Score Bubble 82", LEVEL, Kind.SCORE, uid=64103),
    LBPLocationData("The Dancers' Court - Score Bubble 83", LEVEL, Kind.SCORE, uid=64768),
    LBPLocationData("The Dancers' Court - Score Bubble 84", LEVEL, Kind.SCORE, uid=64769),
    LBPLocationData("The Dancers' Court - Score Bubble 85", LEVEL, Kind.SCORE, uid=64770),
    LBPLocationData("The Dancers' Court - Score Bubble 86", LEVEL, Kind.SCORE, uid=64771),
    LBPLocationData("The Dancers' Court - Score Bubble 87", LEVEL, Kind.SCORE, uid=64772),
    LBPLocationData("The Dancers' Court - Score Bubble 88", LEVEL, Kind.SCORE, uid=64773),
    LBPLocationData("The Dancers' Court - Score Bubble 89", LEVEL, Kind.SCORE, uid=64774),
    LBPLocationData("The Dancers' Court - Score Bubble 90", LEVEL, Kind.SCORE, uid=64775),
    LBPLocationData("The Dancers' Court - Score Bubble 91", LEVEL, Kind.SCORE, uid=64776),
    LBPLocationData("The Dancers' Court - Score Bubble 92", LEVEL, Kind.SCORE, uid=65422),
    LBPLocationData("The Dancers' Court - Score Bubble 93", LEVEL, Kind.SCORE, uid=65423),
    LBPLocationData("The Dancers' Court - Score Bubble 94", LEVEL, Kind.SCORE, uid=65424),
    LBPLocationData("The Dancers' Court - Score Bubble 95", LEVEL, Kind.SCORE, uid=65429),
    LBPLocationData("The Dancers' Court - Score Bubble 96", LEVEL, Kind.SCORE, uid=65430),
    LBPLocationData("The Dancers' Court - Score Bubble 97", LEVEL, Kind.SCORE, uid=65431),
    LBPLocationData("The Dancers' Court - Score Bubble 98", LEVEL, Kind.SCORE, uid=66081),
    LBPLocationData("The Dancers' Court - Score Bubble 99", LEVEL, Kind.SCORE, uid=66082),
    LBPLocationData("The Dancers' Court - Score Bubble 100", LEVEL, Kind.SCORE, uid=66083),
    LBPLocationData("The Dancers' Court - Score Bubble 101", LEVEL, Kind.SCORE, uid=66084),
    LBPLocationData("The Dancers' Court - Score Bubble 102", LEVEL, Kind.SCORE, uid=66085),
    LBPLocationData("The Dancers' Court - Score Bubble 103", LEVEL, Kind.SCORE, uid=66086),
    LBPLocationData("The Dancers' Court - Score Bubble 104", LEVEL, Kind.SCORE, uid=66087),
    LBPLocationData("The Dancers' Court - Score Bubble 105", LEVEL, Kind.SCORE, uid=66088),
    LBPLocationData("The Dancers' Court - Score Bubble 106", LEVEL, Kind.SCORE, uid=66089),
    LBPLocationData("The Dancers' Court - Score Bubble 107", LEVEL, Kind.SCORE, uid=66090),
    LBPLocationData("The Dancers' Court - Score Bubble 108", LEVEL, Kind.SCORE, uid=66091),
    LBPLocationData("The Dancers' Court - Score Bubble 109", LEVEL, Kind.SCORE, uid=66092),
    LBPLocationData("The Dancers' Court - Score Bubble 110", LEVEL, Kind.SCORE, uid=66093),
    LBPLocationData("The Dancers' Court - Score Bubble 111", LEVEL, Kind.SCORE, uid=66094),
    LBPLocationData("The Dancers' Court - Score Bubble 112", LEVEL, Kind.SCORE, uid=66095),
    LBPLocationData("The Dancers' Court - Score Bubble 113", LEVEL, Kind.SCORE, uid=66096),
    LBPLocationData("The Dancers' Court - Score Bubble 114", LEVEL, Kind.SCORE, uid=66097),
    LBPLocationData("The Dancers' Court - Score Bubble 115", LEVEL, Kind.SCORE, uid=66102),
    LBPLocationData("The Dancers' Court - Score Bubble 116", LEVEL, Kind.SCORE, uid=66103),
    LBPLocationData("The Dancers' Court - Score Bubble 117", LEVEL, Kind.SCORE, uid=66104),
    LBPLocationData("The Dancers' Court - Score Bubble 118", LEVEL, Kind.SCORE, uid=66116),
    LBPLocationData("The Dancers' Court - Score Bubble 119", LEVEL, Kind.SCORE, uid=66117),
    LBPLocationData("The Dancers' Court - Score Bubble 120", LEVEL, Kind.SCORE, uid=66118),
    LBPLocationData("The Dancers' Court - Score Bubble 121", LEVEL, Kind.SCORE, uid=66123),
    LBPLocationData("The Dancers' Court - Score Bubble 122", LEVEL, Kind.SCORE, uid=66124),
    LBPLocationData("The Dancers' Court - Score Bubble 123", LEVEL, Kind.SCORE, uid=66125),
    LBPLocationData("The Dancers' Court - Score Bubble 124", LEVEL, Kind.SCORE, uid=66130),
    LBPLocationData("The Dancers' Court - Score Bubble 125", LEVEL, Kind.SCORE, uid=66131),
    LBPLocationData("The Dancers' Court - Score Bubble 126", LEVEL, Kind.SCORE, uid=66132),
    LBPLocationData("The Dancers' Court - Score Bubble 127", LEVEL, Kind.SCORE, uid=66137),
    LBPLocationData("The Dancers' Court - Score Bubble 128", LEVEL, Kind.SCORE, uid=66138),
    LBPLocationData("The Dancers' Court - Score Bubble 129", LEVEL, Kind.SCORE, uid=66139),
    LBPLocationData("The Dancers' Court - Score Bubble 130", LEVEL, Kind.SCORE, uid=66144),
    LBPLocationData("The Dancers' Court - Score Bubble 131", LEVEL, Kind.SCORE, uid=66145),
    LBPLocationData("The Dancers' Court - Score Bubble 132", LEVEL, Kind.SCORE, uid=66146),
    LBPLocationData("The Dancers' Court - Score Bubble 133", LEVEL, Kind.SCORE, uid=67441),
    LBPLocationData("The Dancers' Court - Score Bubble 134", LEVEL, Kind.SCORE, uid=67442),
    LBPLocationData("The Dancers' Court - Score Bubble 135", LEVEL, Kind.SCORE, uid=67443),
    LBPLocationData("The Dancers' Court - Score Bubble 136", LEVEL, Kind.SCORE, uid=68093),
    LBPLocationData("The Dancers' Court - Score Bubble 137", LEVEL, Kind.SCORE, uid=68094),
    LBPLocationData("The Dancers' Court - Score Bubble 138", LEVEL, Kind.SCORE, uid=68095),
    LBPLocationData("The Dancers' Court - Score Bubble 139", LEVEL, Kind.SCORE, uid=68099),
    LBPLocationData("The Dancers' Court - Score Bubble 140", LEVEL, Kind.SCORE, uid=68100),
    LBPLocationData("The Dancers' Court - Score Bubble 141", LEVEL, Kind.SCORE, uid=68101),
    LBPLocationData("The Dancers' Court - Score Bubble 142", LEVEL, Kind.SCORE, uid=68102),
    LBPLocationData("The Dancers' Court - Score Bubble 143", LEVEL, Kind.SCORE, uid=68104),
    LBPLocationData("The Dancers' Court - Score Bubble 144", LEVEL, Kind.SCORE, uid=68105),
    LBPLocationData("The Dancers' Court - Score Bubble 145", LEVEL, Kind.SCORE, uid=68107),
    LBPLocationData("The Dancers' Court - Score Bubble 146", LEVEL, Kind.SCORE, uid=68108),
    LBPLocationData("The Dancers' Court - Score Bubble 147", LEVEL, Kind.SCORE, uid=68110),
    LBPLocationData("The Dancers' Court - Score Bubble 148", LEVEL, Kind.SCORE, uid=68111),
    LBPLocationData("The Dancers' Court - Score Bubble 149", LEVEL, Kind.SCORE, uid=68112),
    LBPLocationData("The Dancers' Court - Score Bubble 150", LEVEL, Kind.SCORE, uid=68113),
    LBPLocationData("The Dancers' Court - Score Bubble 151", LEVEL, Kind.SCORE, uid=68114),
    LBPLocationData("The Dancers' Court - Score Bubble 152", LEVEL, Kind.SCORE, uid=68116),
    LBPLocationData("The Dancers' Court - Score Bubble 153", LEVEL, Kind.SCORE, uid=68117),
    LBPLocationData("The Dancers' Court - Score Bubble 154", LEVEL, Kind.SCORE, uid=68118),
    LBPLocationData("The Dancers' Court - Score Bubble 155", LEVEL, Kind.SCORE, uid=68119),
    LBPLocationData("The Dancers' Court - Score Bubble 156", LEVEL, Kind.SCORE, uid=68120),
    LBPLocationData("The Dancers' Court - Score Bubble 157", LEVEL, Kind.SCORE, uid=68121),
    LBPLocationData("The Dancers' Court - Score Bubble 158", LEVEL, Kind.SCORE, uid=68122),
    LBPLocationData("The Dancers' Court - Score Bubble 159", LEVEL, Kind.SCORE, uid=68123),
    LBPLocationData("The Dancers' Court - Score Bubble 160", LEVEL, Kind.SCORE, uid=68124),
    LBPLocationData("The Dancers' Court - Score Bubble 161", LEVEL, Kind.SCORE, uid=68773),
    LBPLocationData("The Dancers' Court - Score Bubble 162", LEVEL, Kind.SCORE, uid=68774),
    LBPLocationData("The Dancers' Court - Score Bubble 163", LEVEL, Kind.SCORE, uid=68775),
    LBPLocationData("The Dancers' Court - Score Bubble 164", LEVEL, Kind.SCORE, uid=68779),
    LBPLocationData("The Dancers' Court - Score Bubble 165", LEVEL, Kind.SCORE, uid=68780),
    LBPLocationData("The Dancers' Court - Score Bubble 166", LEVEL, Kind.SCORE, uid=68781),
    LBPLocationData("The Dancers' Court - Score Bubble 167", LEVEL, Kind.SCORE, uid=68782),
    LBPLocationData("The Dancers' Court - Score Bubble 168", LEVEL, Kind.SCORE, uid=68783),
    LBPLocationData("The Dancers' Court - Score Bubble 169", LEVEL, Kind.SCORE, uid=68784),
    LBPLocationData("The Dancers' Court - Score Bubble 170", LEVEL, Kind.SCORE, uid=68785),
    LBPLocationData("The Dancers' Court - Score Bubble 171", LEVEL, Kind.SCORE, uid=68786),
    LBPLocationData("The Dancers' Court - Score Bubble 172", LEVEL, Kind.SCORE, uid=68787),
    LBPLocationData("The Dancers' Court - Score Bubble 173", LEVEL, Kind.SCORE, uid=68788),
    LBPLocationData("The Dancers' Court - Score Bubble 174", LEVEL, Kind.SCORE, uid=68789),
    LBPLocationData("The Dancers' Court - Score Bubble 175", LEVEL, Kind.SCORE, uid=68790),
    LBPLocationData("The Dancers' Court - Score Bubble 176", LEVEL, Kind.SCORE, uid=68791),
    LBPLocationData("The Dancers' Court - Score Bubble 177", LEVEL, Kind.SCORE, uid=68792),
    LBPLocationData("The Dancers' Court - Score Bubble 178", LEVEL, Kind.SCORE, uid=68793),
    LBPLocationData("The Dancers' Court - Score Bubble 179", LEVEL, Kind.SCORE, uid=68794),
    LBPLocationData("The Dancers' Court - Score Bubble 180", LEVEL, Kind.SCORE, uid=68795),
    LBPLocationData("The Dancers' Court - Score Bubble 181", LEVEL, Kind.SCORE, uid=68796),
    LBPLocationData("The Dancers' Court - Score Bubble 182", LEVEL, Kind.SCORE, uid=68797),
    LBPLocationData("The Dancers' Court - Score Bubble 183", LEVEL, Kind.SCORE, uid=68798),
    LBPLocationData("The Dancers' Court - Score Bubble 184", LEVEL, Kind.SCORE, uid=68799),
    LBPLocationData("The Dancers' Court - Score Bubble 185", LEVEL, Kind.SCORE, uid=68800),
    LBPLocationData("The Dancers' Court - Score Bubble 186", LEVEL, Kind.SCORE, uid=68801),
    LBPLocationData("The Dancers' Court - Score Bubble 187", LEVEL, Kind.SCORE, uid=68802),
    LBPLocationData("The Dancers' Court - Score Bubble 188", LEVEL, Kind.SCORE, uid=68803),
    LBPLocationData("The Dancers' Court - Score Bubble 189", LEVEL, Kind.SCORE, uid=68804),
    LBPLocationData("The Dancers' Court - Score Bubble 190", LEVEL, Kind.SCORE, uid=68805),
    LBPLocationData("The Dancers' Court - Score Bubble 191", LEVEL, Kind.SCORE, uid=71386),
    LBPLocationData("The Dancers' Court - Score Bubble 192", LEVEL, Kind.SCORE, uid=71388),
    LBPLocationData("The Dancers' Court - Score Bubble 193", LEVEL, Kind.SCORE, uid=71393),
    LBPLocationData("The Dancers' Court - Score Bubble 194", LEVEL, Kind.SCORE, uid=71394),
    LBPLocationData("The Dancers' Court - Score Bubble 195", LEVEL, Kind.SCORE, uid=71395),
    LBPLocationData("The Dancers' Court - Score Bubble 196", LEVEL, Kind.SCORE, uid=71400),
    LBPLocationData("The Dancers' Court - Score Bubble 197", LEVEL, Kind.SCORE, uid=71401),
    LBPLocationData("The Dancers' Court - Score Bubble 198", LEVEL, Kind.SCORE, uid=71402),
    LBPLocationData("The Dancers' Court - Score Bubble 199", LEVEL, Kind.SCORE, uid=72697),
    LBPLocationData("The Dancers' Court - Score Bubble 200", LEVEL, Kind.SCORE, uid=72698),
    LBPLocationData("The Dancers' Court - Score Bubble 201", LEVEL, Kind.SCORE, uid=72699),
    LBPLocationData("The Dancers' Court - Score Bubble 202", LEVEL, Kind.SCORE, uid=84997),
    LBPLocationData("The Dancers' Court - Score Bubble 203", LEVEL, Kind.SCORE, uid=84998),
    LBPLocationData("The Dancers' Court - Score Bubble 204", LEVEL, Kind.SCORE, uid=84999),
    LBPLocationData("The Dancers' Court - Score Bubble 205", LEVEL, Kind.SCORE, uid=158233),
    LBPLocationData("The Dancers' Court - Score Bubble 206", LEVEL, Kind.SCORE, uid=158234),
    LBPLocationData("The Dancers' Court - Score Bubble 207", LEVEL, Kind.SCORE, uid=158235),
    LBPLocationData("The Dancers' Court - Score Bubble 208", LEVEL, Kind.SCORE, uid=158240),
    LBPLocationData("The Dancers' Court - Score Bubble 209", LEVEL, Kind.SCORE, uid=158241),
    LBPLocationData("The Dancers' Court - Score Bubble 210", LEVEL, Kind.SCORE, uid=158242),
    LBPLocationData("The Dancers' Court - Score Bubble 211", LEVEL, Kind.SCORE, uid=160193),
    LBPLocationData("The Dancers' Court - Score Bubble 212", LEVEL, Kind.SCORE, uid=160194),
    LBPLocationData("The Dancers' Court - Score Bubble 213", LEVEL, Kind.SCORE, uid=160195),
    LBPLocationData("The Dancers' Court - Score Bubble 214", LEVEL, Kind.SCORE, uid=167305),
    LBPLocationData("The Dancers' Court - Score Bubble 215", LEVEL, Kind.SCORE, uid=167307),
    LBPLocationData("The Dancers' Court - Score Bubble 216", LEVEL, Kind.SCORE, uid=167309),
    LBPLocationData("The Dancers' Court - Score Bubble 217", LEVEL, Kind.SCORE, uid=167311),
    LBPLocationData("The Dancers' Court - Score Bubble 218", LEVEL, Kind.SCORE, uid=167313),
    LBPLocationData("The Dancers' Court - Score Bubble 219", LEVEL, Kind.SCORE, uid=167315),
    LBPLocationData("The Dancers' Court - Score Bubble 220", LEVEL, Kind.SCORE, uid=167317),
    LBPLocationData("The Dancers' Court - Score Bubble 221", LEVEL, Kind.SCORE, uid=167319),
    LBPLocationData("The Dancers' Court - Score Bubble 222", LEVEL, Kind.SCORE, uid=167966),
    LBPLocationData("The Dancers' Court - Score Bubble 223", LEVEL, Kind.SCORE, uid=167967),
    LBPLocationData("The Dancers' Court - Score Bubble 224", LEVEL, Kind.SCORE, uid=167968),
    LBPLocationData("The Dancers' Court - Score Bubble 225", LEVEL, Kind.SCORE, uid=167969),
    LBPLocationData("The Dancers' Court - Score Bubble 226", LEVEL, Kind.SCORE, uid=167970),
    LBPLocationData("The Dancers' Court - Score Bubble 227", LEVEL, Kind.SCORE, uid=167971),
    LBPLocationData("The Dancers' Court - Score Bubble 228", LEVEL, Kind.SCORE, uid=243640),
    LBPLocationData("The Dancers' Court - Score Bubble 229", LEVEL, Kind.SCORE, uid=507920),
    LBPLocationData("The Dancers' Court - Score Bubble 230", LEVEL, Kind.SCORE, uid=507921),
    LBPLocationData("The Dancers' Court - Score Bubble 231", LEVEL, Kind.SCORE, uid=507922),
    LBPLocationData("The Dancers' Court - Score Bubble 232", LEVEL, Kind.SCORE, uid=507925),
    LBPLocationData("The Dancers' Court - Score Bubble 233", LEVEL, Kind.SCORE, uid=507926),
    LBPLocationData("The Dancers' Court - Score Bubble 234", LEVEL, Kind.SCORE, uid=507927),
    LBPLocationData("The Dancers' Court - Score Bubble 235", LEVEL, Kind.SCORE, uid=507928),
    LBPLocationData("The Dancers' Court - Score Bubble 236", LEVEL, Kind.SCORE, uid=507929),
    LBPLocationData("The Dancers' Court - Score Bubble 237", LEVEL, Kind.SCORE, uid=507930),
    LBPLocationData("The Dancers' Court - Score Bubble 238", LEVEL, Kind.SCORE, uid=507935),
    LBPLocationData("The Dancers' Court - Score Bubble 239", LEVEL, Kind.SCORE, uid=507936),
    LBPLocationData("The Dancers' Court - Score Bubble 240", LEVEL, Kind.SCORE, uid=507937),
    LBPLocationData("The Dancers' Court - Score Bubble 241", LEVEL, Kind.SCORE, uid=507943),
    LBPLocationData("The Dancers' Court - Score Bubble 242", LEVEL, Kind.SCORE, uid=507944),
    LBPLocationData("The Dancers' Court - Score Bubble 243", LEVEL, Kind.SCORE, uid=507945),
    LBPLocationData("The Dancers' Court - Score Bubble 244", LEVEL, Kind.SCORE, uid=528763),
    LBPLocationData("The Dancers' Court - Score Bubble 245", LEVEL, Kind.SCORE, uid=528764),
    LBPLocationData("The Dancers' Court - Score Bubble 246", LEVEL, Kind.SCORE, uid=528765),
    LBPLocationData("The Dancers' Court - Score Bubble 247", LEVEL, Kind.SCORE, uid=528766),
    LBPLocationData("The Dancers' Court - Score Bubble 248", LEVEL, Kind.SCORE, uid=528767),
    LBPLocationData("The Dancers' Court - Score Bubble 249", LEVEL, Kind.SCORE, uid=528768),
    LBPLocationData("The Dancers' Court - Score Bubble 250", LEVEL, Kind.SCORE, uid=528769),
    LBPLocationData("The Dancers' Court - Score Bubble 251", LEVEL, Kind.SCORE, uid=528770),
    LBPLocationData("The Dancers' Court - Score Bubble 252", LEVEL, Kind.SCORE, uid=539787),
    LBPLocationData("The Dancers' Court - Score Bubble 253", LEVEL, Kind.SCORE, uid=539788),
    LBPLocationData("The Dancers' Court - Score Bubble 254", LEVEL, Kind.SCORE, uid=539789),
    LBPLocationData("The Dancers' Court - Score Bubble 255", LEVEL, Kind.SCORE, uid=539790),
    LBPLocationData("The Dancers' Court - Score Bubble 256", LEVEL, Kind.SCORE, uid=539794),
    LBPLocationData("The Dancers' Court - Score Bubble 257", LEVEL, Kind.SCORE, uid=539795),
    LBPLocationData("The Dancers' Court - Score Bubble 258", LEVEL, Kind.SCORE, uid=539796),
    LBPLocationData("The Dancers' Court - Score Bubble 259", LEVEL, Kind.SCORE, uid=539797),
    LBPLocationData("The Dancers' Court - Score Bubble 260", LEVEL, Kind.SCORE, uid=539800),
    LBPLocationData("The Dancers' Court - Score Bubble 261", LEVEL, Kind.SCORE, uid=539801),
    LBPLocationData("The Dancers' Court - Score Bubble 262", LEVEL, Kind.SCORE, uid=539802),
    LBPLocationData("The Dancers' Court - Score Bubble 263", LEVEL, Kind.SCORE, uid=539804),
    LBPLocationData("The Dancers' Court - Score Bubble 264", LEVEL, Kind.SCORE, uid=539805),
    LBPLocationData("The Dancers' Court - Score Bubble 265", LEVEL, Kind.SCORE, uid=539806),
    LBPLocationData("The Dancers' Court - Score Bubble 266", LEVEL, Kind.SCORE, uid=539807),
    LBPLocationData("The Dancers' Court - Score Bubble 267", LEVEL, Kind.SCORE, uid=539808),
    LBPLocationData("The Dancers' Court - Score Bubble 268", LEVEL, Kind.SCORE, uid=539809),
    LBPLocationData("The Dancers' Court - Score Bubble 269", LEVEL, Kind.SCORE, uid=540473),
    LBPLocationData("The Dancers' Court - Score Bubble 270", LEVEL, Kind.SCORE, uid=540474),
    LBPLocationData("The Dancers' Court - Score Bubble 271", LEVEL, Kind.SCORE, uid=540475),
    LBPLocationData("The Dancers' Court - Score Bubble 272", LEVEL, Kind.SCORE, uid=540476),
    LBPLocationData("The Dancers' Court - Score Bubble 273", LEVEL, Kind.SCORE, uid=540477),
    LBPLocationData("The Dancers' Court - Score Bubble 274", LEVEL, Kind.SCORE, uid=540478),
    LBPLocationData("The Dancers' Court - Score Bubble 275", LEVEL, Kind.SCORE, uid=540479),
    LBPLocationData("The Dancers' Court - Score Bubble 276", LEVEL, Kind.SCORE, uid=540480),
    LBPLocationData("The Dancers' Court - Prize Bubble 1 - Tiger", LEVEL, Kind.PRIZE, uid=86936, plan='g31932'),
    LBPLocationData("The Dancers' Court - Prize Bubble 2 - Green Pattern Wood", LEVEL, Kind.PRIZE, uid=86937, plan='g31952'),
    LBPLocationData("The Dancers' Court - Prize Bubble 3 - Girl Body", LEVEL, Kind.PRIZE, uid=86940, plan='g31936'),
    LBPLocationData("The Dancers' Court - Prize Bubble 4 - Fabric Hair Wig", LEVEL, Kind.PRIZE, uid=86941, plan='g39723'),
    LBPLocationData("The Dancers' Court - Prize Bubble 5 - Bouncy Rubber Snake", LEVEL, Kind.PRIZE, uid=86942, plan='g42359'),
    LBPLocationData("The Dancers' Court - Prize Bubble 6 - Prince Arm", LEVEL, Kind.PRIZE, uid=86943, plan='g31939'),
    LBPLocationData("The Dancers' Court - Prize Bubble 7 - Girl Arm", LEVEL, Kind.PRIZE, uid=86944, plan='g31935'),
    LBPLocationData("The Dancers' Court - Prize Bubble 8 - Girl Face", LEVEL, Kind.PRIZE, uid=86946, plan='g31934'),
    LBPLocationData("The Dancers' Court - Prize Bubble 9 - Blue Boy Dancer", LEVEL, Kind.PRIZE, uid=86947, plan='g56382'),
    LBPLocationData("The Dancers' Court - Prize Bubble 10 - The Goddess' Parlour", LEVEL, Kind.PRIZE, uid=86948, plan='g59999'),
    LBPLocationData("The Dancers' Court - Prize Bubble 11 - Prince Face", LEVEL, Kind.PRIZE, uid=86952, plan='g31938'),
    LBPLocationData("The Dancers' Court - Prize Bubble 12 - Ornate Windows", LEVEL, Kind.PRIZE, uid=86953, plan='g48759'),
    LBPLocationData("The Dancers' Court - Prize Bubble 13 - Palace Curtain", LEVEL, Kind.PRIZE, uid=86954, plan='g31959'),
    LBPLocationData("The Dancers' Court - Prize Bubble 14 - Big Wave Snake", LEVEL, Kind.PRIZE, uid=86955, plan='g48764'),
    LBPLocationData("The Dancers' Court - Prize Bubble 15 - Cat", LEVEL, Kind.PRIZE, uid=86962, plan='g48758'),
    LBPLocationData("The Dancers' Court - Prize Bubble 16 - The Shopkeeper", LEVEL, Kind.PRIZE, uid=86963, plan='g48499'),
    LBPLocationData("The Dancers' Court - Prize Bubble 17 - Cardboard Arch", LEVEL, Kind.PRIZE, uid=86964, plan='g31961'),
    LBPLocationData("The Dancers' Court - Prize Bubble 18 - Brown Pattern Wood", LEVEL, Kind.PRIZE, uid=86965, plan='g31951'),
    LBPLocationData("The Dancers' Court - Prize Bubble 19 - Blue Dancer", LEVEL, Kind.PRIZE, uid=86966, plan='g48761'),
    LBPLocationData("The Dancers' Court - Prize Bubble 20 - Blue Yoga Dancer", LEVEL, Kind.PRIZE, uid=86968, plan='g48760'),
    LBPLocationData("The Dancers' Court - Prize Bubble 21 - Cobra Head", LEVEL, Kind.PRIZE, uid=86970, plan='g31924'),
    LBPLocationData("The Dancers' Court - Prize Bubble 22 - Rubber Snake", LEVEL, Kind.PRIZE, uid=86971, plan='g51463'),
    LBPLocationData("The Dancers' Court - Prize Bubble 23 - Blue Dancer Leg", LEVEL, Kind.PRIZE, uid=86972, plan='g40048'),
    LBPLocationData("The Dancers' Court - Prize Bubble 24 - Blue Dancer Arm", LEVEL, Kind.PRIZE, uid=86973, plan='g39726'),
    LBPLocationData("The Dancers' Court - Prize Bubble 25 - Blue Dancer Head", LEVEL, Kind.PRIZE, uid=86974, plan='g39724'),
    LBPLocationData("The Dancers' Court - Prize Bubble 26 - 12 Teeth Cog", LEVEL, Kind.PRIZE, uid=86975, plan='g32768'),
    LBPLocationData("The Dancers' Court - Prize Bubble 27 - 18 Teeth Cog", LEVEL, Kind.PRIZE, uid=86976, plan='g32769'),
    LBPLocationData("The Dancers' Court - Prize Bubble 28 - 24 Teeth Cog", LEVEL, Kind.PRIZE, uid=86977, plan='g32770'),
    LBPLocationData("The Dancers' Court - Prize Bubble 29 - 36 Teeth Cog", LEVEL, Kind.PRIZE, uid=86978, plan='g32771'),
    LBPLocationData("The Dancers' Court - Prize Bubble 30 - Sherwani", LEVEL, Kind.PRIZE, uid=86979, plan='g31950'),
    LBPLocationData("The Dancers' Court - Prize Bubble 31 - Turban", LEVEL, Kind.PRIZE, uid=86980, plan='g31947'),
    LBPLocationData("The Dancers' Court - Prize Bubble 32 - Beard", LEVEL, Kind.PRIZE, uid=86981, plan='g31946'),
    LBPLocationData("The Dancers' Court - Prize Bubble 33 - Baggy Silk Trousers", LEVEL, Kind.PRIZE, uid=86982, plan='g31948'),
    LBPLocationData("The Dancers' Court - Prize Bubble 34 - Blue Headscarf", LEVEL, Kind.PRIZE, uid=86983, plan='g31945'),
    LBPLocationData("The Dancers' Court - Prize Bubble 35 - Blue Sari", LEVEL, Kind.PRIZE, uid=86984, plan='g31949'),
    LBPLocationData("The Dancers' Court - Prize Bubble 36 - Four Rotating Platforms", LEVEL, Kind.PRIZE, uid=166658, plan='g56353'),
    LBPLocationData("The Dancers' Court - Prize Bubble 37 - Tower", LEVEL, Kind.PRIZE, uid=457467, plan='g31942'),
    LBPLocationData("The Dancers' Court - Prize Bubble 38 - Temple", LEVEL, Kind.PRIZE, uid=457468, plan='g31941'),
    LBPLocationData("The Dancers' Court - Prize Bubble 39 - Flame-Throwing Cat", LEVEL, Kind.PRIZE, uid=507220, plan='g56477'),
    LBPLocationData("The Dancers' Court - Prize Bubble 40 - 'Dancing Drums'", LEVEL, Kind.PRIZE, uid=592413, plan='g33150'),
    LBPLocationData("The Dancers' Court - Level Complete", LEVEL, Kind.COMPLETE),
    LBPLocationData("The Dancers' Court - All Prize Bubbles", LEVEL, Kind.ALL_PRIZES),
    LBPLocationData("The Dancers' Court - Ace (No Deaths)", LEVEL, Kind.ACE),
    LBPLocationData("The Dancers' Court - Completion Reward 1 - Green Goggles", LEVEL, Kind.REWARD, plan='g51062', condition=Kind.COMPLETE),
    LBPLocationData("The Dancers' Court - Completion Reward 2 - Dotted Line", LEVEL, Kind.REWARD, plan='g32535', condition=Kind.COMPLETE),
    LBPLocationData("The Dancers' Court - All Prizes Reward 1 - LittleBigPlanet™ Concept with Frame", LEVEL, Kind.REWARD, plan='g52815', condition=Kind.ALL_PRIZES),
    LBPLocationData("The Dancers' Court - All Prizes Reward 2 - Background Environment Concept", LEVEL, Kind.REWARD, plan='g52780', condition=Kind.ALL_PRIZES),
    LBPLocationData("The Dancers' Court - Ace Reward 1 - Chicken Beak", LEVEL, Kind.REWARD, plan='g32489', condition=Kind.ACE),
    LBPLocationData("The Dancers' Court - Sticker Switch 1 - Prince Face", LEVEL, Kind.STICKER_SWITCH, uid=15428, plan='g31938'),
    LBPLocationData("The Dancers' Court - Sticker Switch 2 - Tower", LEVEL, Kind.STICKER_SWITCH, uid=81744, plan='g31942'),
    LBPLocationData("The Dancers' Court - Sticker Switch 3 - Temple", LEVEL, Kind.STICKER_SWITCH, uid=81745, plan='g31941'),
    LBPLocationData("The Dancers' Court - Sticker Switch 4 - Tower", LEVEL, Kind.STICKER_SWITCH, uid=81746, plan='g31942'),
    LBPLocationData("The Dancers' Court - Sticker Switch 5 - Tower", LEVEL, Kind.STICKER_SWITCH, uid=81747, plan='g31942'),
    LBPLocationData("The Dancers' Court - Sticker Switch 6 - Tower", LEVEL, Kind.STICKER_SWITCH, uid=81748, plan='g31942'),
)
