from rule_builder.rules import Has

from ..model import Kind, LBPLocationData

LEVEL = 'g26421'

LOCATIONS = (
    LBPLocationData('The Darkness - Score Bubble 1', LEVEL, Kind.SCORE, uid=16103),
    LBPLocationData('The Darkness - Score Bubble 2', LEVEL, Kind.SCORE, uid=16114),
    LBPLocationData('The Darkness - Score Bubble 3', LEVEL, Kind.SCORE, uid=16115),
    LBPLocationData('The Darkness - Score Bubble 4', LEVEL, Kind.SCORE, uid=16119),
    LBPLocationData('The Darkness - Score Bubble 5', LEVEL, Kind.SCORE, uid=16120),
    LBPLocationData('The Darkness - Score Bubble 6', LEVEL, Kind.SCORE, uid=16121),
    LBPLocationData('The Darkness - Score Bubble 7', LEVEL, Kind.SCORE, uid=16175),
    LBPLocationData('The Darkness - Score Bubble 8', LEVEL, Kind.SCORE, uid=16176),
    LBPLocationData('The Darkness - Score Bubble 9', LEVEL, Kind.SCORE, uid=16177),
    LBPLocationData('The Darkness - Score Bubble 10', LEVEL, Kind.SCORE, uid=16188),
    LBPLocationData('The Darkness - Score Bubble 11', LEVEL, Kind.SCORE, uid=16189),
    LBPLocationData('The Darkness - Score Bubble 12', LEVEL, Kind.SCORE, uid=16190),
    LBPLocationData('The Darkness - Score Bubble 13', LEVEL, Kind.SCORE, uid=16323),
    LBPLocationData('The Darkness - Score Bubble 14', LEVEL, Kind.SCORE, uid=16324),
    LBPLocationData('The Darkness - Score Bubble 15', LEVEL, Kind.SCORE, uid=16325),
    LBPLocationData('The Darkness - Score Bubble 16', LEVEL, Kind.SCORE, uid=16330),
    LBPLocationData('The Darkness - Score Bubble 17', LEVEL, Kind.SCORE, uid=16331),
    LBPLocationData('The Darkness - Score Bubble 18', LEVEL, Kind.SCORE, uid=16332),
    LBPLocationData('The Darkness - Score Bubble 19', LEVEL, Kind.SCORE, uid=16333),
    LBPLocationData('The Darkness - Score Bubble 20', LEVEL, Kind.SCORE, uid=16334),
    LBPLocationData('The Darkness - Score Bubble 21', LEVEL, Kind.SCORE, uid=16335),
    LBPLocationData('The Darkness - Score Bubble 22', LEVEL, Kind.SCORE, uid=16605),
    LBPLocationData('The Darkness - Score Bubble 23', LEVEL, Kind.SCORE, uid=16606),
    LBPLocationData('The Darkness - Score Bubble 24', LEVEL, Kind.SCORE, uid=16607),
    LBPLocationData('The Darkness - Score Bubble 25', LEVEL, Kind.SCORE, uid=16701),
    LBPLocationData('The Darkness - Score Bubble 26', LEVEL, Kind.SCORE, uid=16702),
    LBPLocationData('The Darkness - Score Bubble 27', LEVEL, Kind.SCORE, uid=16703),
    LBPLocationData('The Darkness - Score Bubble 28', LEVEL, Kind.SCORE, uid=17451),
    LBPLocationData('The Darkness - Score Bubble 29', LEVEL, Kind.SCORE, uid=17452),
    LBPLocationData('The Darkness - Score Bubble 30', LEVEL, Kind.SCORE, uid=17453),
    LBPLocationData('The Darkness - Score Bubble 31', LEVEL, Kind.SCORE, uid=17457),
    LBPLocationData('The Darkness - Score Bubble 32', LEVEL, Kind.SCORE, uid=17458),
    LBPLocationData('The Darkness - Score Bubble 33', LEVEL, Kind.SCORE, uid=17459),
    LBPLocationData('The Darkness - Score Bubble 34', LEVEL, Kind.SCORE, uid=17460),
    LBPLocationData('The Darkness - Score Bubble 35', LEVEL, Kind.SCORE, uid=17461),
    LBPLocationData('The Darkness - Score Bubble 36', LEVEL, Kind.SCORE, uid=17462),
    LBPLocationData('The Darkness - Score Bubble 37', LEVEL, Kind.SCORE, uid=17665),
    LBPLocationData('The Darkness - Score Bubble 38', LEVEL, Kind.SCORE, uid=17666),
    LBPLocationData('The Darkness - Score Bubble 39', LEVEL, Kind.SCORE, uid=17667),
    LBPLocationData('The Darkness - Score Bubble 40', LEVEL, Kind.SCORE, uid=17668),
    LBPLocationData('The Darkness - Score Bubble 41', LEVEL, Kind.SCORE, uid=17671),
    LBPLocationData('The Darkness - Score Bubble 42', LEVEL, Kind.SCORE, uid=17672),
    LBPLocationData('The Darkness - Score Bubble 43', LEVEL, Kind.SCORE, uid=17673),
    LBPLocationData('The Darkness - Score Bubble 44', LEVEL, Kind.SCORE, uid=17674),
    LBPLocationData('The Darkness - Score Bubble 45', LEVEL, Kind.SCORE, uid=17836),
    LBPLocationData('The Darkness - Score Bubble 46', LEVEL, Kind.SCORE, uid=17837),
    LBPLocationData('The Darkness - Score Bubble 47', LEVEL, Kind.SCORE, uid=17838),
    LBPLocationData('The Darkness - Score Bubble 48', LEVEL, Kind.SCORE, uid=17839),
    LBPLocationData('The Darkness - Score Bubble 49', LEVEL, Kind.SCORE, uid=17840),
    LBPLocationData('The Darkness - Score Bubble 50', LEVEL, Kind.SCORE, uid=17841),
    LBPLocationData('The Darkness - Score Bubble 51', LEVEL, Kind.SCORE, uid=17972),
    LBPLocationData('The Darkness - Score Bubble 52', LEVEL, Kind.SCORE, uid=17973),
    LBPLocationData('The Darkness - Score Bubble 53', LEVEL, Kind.SCORE, uid=17974),
    LBPLocationData('The Darkness - Score Bubble 54', LEVEL, Kind.SCORE, uid=18889),
    LBPLocationData('The Darkness - Score Bubble 55', LEVEL, Kind.SCORE, uid=18890),
    LBPLocationData('The Darkness - Score Bubble 56', LEVEL, Kind.SCORE, uid=18891),
    LBPLocationData('The Darkness - Score Bubble 57', LEVEL, Kind.SCORE, uid=18892),
    LBPLocationData('The Darkness - Score Bubble 58', LEVEL, Kind.SCORE, uid=18893),
    LBPLocationData('The Darkness - Score Bubble 59', LEVEL, Kind.SCORE, uid=18894),
    LBPLocationData('The Darkness - Score Bubble 60', LEVEL, Kind.SCORE, uid=18901),
    LBPLocationData('The Darkness - Score Bubble 61', LEVEL, Kind.SCORE, uid=18902),
    LBPLocationData('The Darkness - Score Bubble 62', LEVEL, Kind.SCORE, uid=18903),
    LBPLocationData('The Darkness - Score Bubble 63', LEVEL, Kind.SCORE, uid=18946),
    LBPLocationData('The Darkness - Score Bubble 64', LEVEL, Kind.SCORE, uid=18947),
    LBPLocationData('The Darkness - Score Bubble 65', LEVEL, Kind.SCORE, uid=18948),
    LBPLocationData('The Darkness - Score Bubble 66', LEVEL, Kind.SCORE, uid=18949),
    LBPLocationData('The Darkness - Score Bubble 67', LEVEL, Kind.SCORE, uid=18950),
    LBPLocationData('The Darkness - Score Bubble 68', LEVEL, Kind.SCORE, uid=18951),
    LBPLocationData('The Darkness - Score Bubble 69', LEVEL, Kind.SCORE, uid=18952),
    LBPLocationData('The Darkness - Score Bubble 70', LEVEL, Kind.SCORE, uid=18953),
    LBPLocationData('The Darkness - Score Bubble 71', LEVEL, Kind.SCORE, uid=18954),
    LBPLocationData('The Darkness - Score Bubble 72', LEVEL, Kind.SCORE, uid=18981),
    LBPLocationData('The Darkness - Score Bubble 73', LEVEL, Kind.SCORE, uid=18982),
    LBPLocationData('The Darkness - Score Bubble 74', LEVEL, Kind.SCORE, uid=18983),
    LBPLocationData('The Darkness - Score Bubble 75', LEVEL, Kind.SCORE, uid=19142),
    LBPLocationData('The Darkness - Score Bubble 76', LEVEL, Kind.SCORE, uid=19143),
    LBPLocationData('The Darkness - Score Bubble 77', LEVEL, Kind.SCORE, uid=19144),
    LBPLocationData('The Darkness - Score Bubble 78', LEVEL, Kind.SCORE, uid=19180),
    LBPLocationData('The Darkness - Score Bubble 79', LEVEL, Kind.SCORE, uid=19181),
    LBPLocationData('The Darkness - Score Bubble 80', LEVEL, Kind.SCORE, uid=19182),
    LBPLocationData('The Darkness - Score Bubble 81', LEVEL, Kind.SCORE, uid=19183),
    LBPLocationData('The Darkness - Score Bubble 82', LEVEL, Kind.SCORE, uid=22238),
    LBPLocationData('The Darkness - Score Bubble 83', LEVEL, Kind.SCORE, uid=22239),
    LBPLocationData('The Darkness - Score Bubble 84', LEVEL, Kind.SCORE, uid=22240),
    LBPLocationData('The Darkness - Score Bubble 85', LEVEL, Kind.SCORE, uid=22336),
    LBPLocationData('The Darkness - Score Bubble 86', LEVEL, Kind.SCORE, uid=22337),
    LBPLocationData('The Darkness - Score Bubble 87', LEVEL, Kind.SCORE, uid=22338),
    LBPLocationData('The Darkness - Score Bubble 88', LEVEL, Kind.SCORE, uid=22339),
    LBPLocationData('The Darkness - Score Bubble 89', LEVEL, Kind.SCORE, uid=22340),
    LBPLocationData('The Darkness - Score Bubble 90', LEVEL, Kind.SCORE, uid=22341),
    LBPLocationData('The Darkness - Score Bubble 91', LEVEL, Kind.SCORE, uid=22589),
    LBPLocationData('The Darkness - Score Bubble 92', LEVEL, Kind.SCORE, uid=22590),
    LBPLocationData('The Darkness - Score Bubble 93', LEVEL, Kind.SCORE, uid=22591),
    LBPLocationData('The Darkness - Score Bubble 94', LEVEL, Kind.SCORE, uid=22592),
    LBPLocationData('The Darkness - Score Bubble 95', LEVEL, Kind.SCORE, uid=22593),
    LBPLocationData('The Darkness - Score Bubble 96', LEVEL, Kind.SCORE, uid=22594),
    LBPLocationData('The Darkness - Score Bubble 97', LEVEL, Kind.SCORE, uid=23502),
    LBPLocationData('The Darkness - Score Bubble 98', LEVEL, Kind.SCORE, uid=23503),
    LBPLocationData('The Darkness - Score Bubble 99', LEVEL, Kind.SCORE, uid=23504),
    LBPLocationData('The Darkness - Score Bubble 100', LEVEL, Kind.SCORE, uid=23505),
    LBPLocationData('The Darkness - Score Bubble 101', LEVEL, Kind.SCORE, uid=23506),
    LBPLocationData('The Darkness - Score Bubble 102', LEVEL, Kind.SCORE, uid=23507),
    LBPLocationData('The Darkness - Score Bubble 103', LEVEL, Kind.SCORE, uid=23508),
    LBPLocationData('The Darkness - Score Bubble 104', LEVEL, Kind.SCORE, uid=23509),
    LBPLocationData('The Darkness - Score Bubble 105', LEVEL, Kind.SCORE, uid=23510),
    LBPLocationData('The Darkness - Score Bubble 106', LEVEL, Kind.SCORE, uid=23511),
    LBPLocationData('The Darkness - Score Bubble 107', LEVEL, Kind.SCORE, uid=23512),
    LBPLocationData('The Darkness - Score Bubble 108', LEVEL, Kind.SCORE, uid=23513),
    LBPLocationData('The Darkness - Score Bubble 109', LEVEL, Kind.SCORE, uid=23514),
    LBPLocationData('The Darkness - Score Bubble 110', LEVEL, Kind.SCORE, uid=23515),
    LBPLocationData('The Darkness - Score Bubble 111', LEVEL, Kind.SCORE, uid=23516),
    LBPLocationData('The Darkness - Score Bubble 112', LEVEL, Kind.SCORE, uid=23517),
    LBPLocationData('The Darkness - Score Bubble 113', LEVEL, Kind.SCORE, uid=23518),
    LBPLocationData('The Darkness - Score Bubble 114', LEVEL, Kind.SCORE, uid=23519),
    LBPLocationData('The Darkness - Score Bubble 115', LEVEL, Kind.SCORE, uid=23520),
    LBPLocationData('The Darkness - Score Bubble 116', LEVEL, Kind.SCORE, uid=23521),
    LBPLocationData('The Darkness - Score Bubble 117', LEVEL, Kind.SCORE, uid=23522),
    LBPLocationData('The Darkness - Score Bubble 118', LEVEL, Kind.SCORE, uid=23523),
    LBPLocationData('The Darkness - Score Bubble 119', LEVEL, Kind.SCORE, uid=23524),
    LBPLocationData('The Darkness - Score Bubble 120', LEVEL, Kind.SCORE, uid=23525),
    LBPLocationData('The Darkness - Score Bubble 121', LEVEL, Kind.SCORE, uid=23526),
    LBPLocationData('The Darkness - Score Bubble 122', LEVEL, Kind.SCORE, uid=23527),
    LBPLocationData('The Darkness - Score Bubble 123', LEVEL, Kind.SCORE, uid=23528),
    LBPLocationData('The Darkness - Score Bubble 124', LEVEL, Kind.SCORE, uid=23534),
    LBPLocationData('The Darkness - Score Bubble 125', LEVEL, Kind.SCORE, uid=23535),
    LBPLocationData('The Darkness - Score Bubble 126', LEVEL, Kind.SCORE, uid=23536),
    LBPLocationData('The Darkness - Score Bubble 127', LEVEL, Kind.SCORE, uid=23540),
    LBPLocationData('The Darkness - Score Bubble 128', LEVEL, Kind.SCORE, uid=23541),
    LBPLocationData('The Darkness - Score Bubble 129', LEVEL, Kind.SCORE, uid=23542),
    LBPLocationData('The Darkness - Score Bubble 130', LEVEL, Kind.SCORE, uid=23543),
    LBPLocationData('The Darkness - Score Bubble 131', LEVEL, Kind.SCORE, uid=23544),
    LBPLocationData('The Darkness - Score Bubble 132', LEVEL, Kind.SCORE, uid=23545),
    LBPLocationData('The Darkness - Score Bubble 133', LEVEL, Kind.SCORE, uid=23546),
    LBPLocationData('The Darkness - Score Bubble 134', LEVEL, Kind.SCORE, uid=23547),
    LBPLocationData('The Darkness - Score Bubble 135', LEVEL, Kind.SCORE, uid=23548),
    LBPLocationData('The Darkness - Score Bubble 136', LEVEL, Kind.SCORE, uid=23549),
    LBPLocationData('The Darkness - Score Bubble 137', LEVEL, Kind.SCORE, uid=23550),
    LBPLocationData('The Darkness - Score Bubble 138', LEVEL, Kind.SCORE, uid=23551),
    LBPLocationData('The Darkness - Score Bubble 139', LEVEL, Kind.SCORE, uid=23555),
    LBPLocationData('The Darkness - Score Bubble 140', LEVEL, Kind.SCORE, uid=23556),
    LBPLocationData('The Darkness - Score Bubble 141', LEVEL, Kind.SCORE, uid=23557),
    LBPLocationData('The Darkness - Score Bubble 142', LEVEL, Kind.SCORE, uid=23558),
    LBPLocationData('The Darkness - Score Bubble 143', LEVEL, Kind.SCORE, uid=23559),
    LBPLocationData('The Darkness - Score Bubble 144', LEVEL, Kind.SCORE, uid=23560),
    LBPLocationData('The Darkness - Score Bubble 145', LEVEL, Kind.SCORE, uid=23561),
    LBPLocationData('The Darkness - Score Bubble 146', LEVEL, Kind.SCORE, uid=23562),
    LBPLocationData('The Darkness - Score Bubble 147', LEVEL, Kind.SCORE, uid=23563),
    LBPLocationData('The Darkness - Prize Bubble 1 - Christmas Light', LEVEL, Kind.PRIZE, uid=22622, plan='g51305'),
    LBPLocationData('The Darkness - Prize Bubble 2 - Skull', LEVEL, Kind.PRIZE, uid=22642, plan='g31975'),
    LBPLocationData('The Darkness - Prize Bubble 3 - Purple Skull Arm', LEVEL, Kind.PRIZE, uid=23125, plan='g31996'),
    LBPLocationData('The Darkness - Prize Bubble 4 - Ceramic Mosaic', LEVEL, Kind.PRIZE, uid=23830, plan='g32004'),
    LBPLocationData('The Darkness - Prize Bubble 5 - Picture Frame', LEVEL, Kind.PRIZE, uid=23832, plan='g36210'),
    LBPLocationData('The Darkness - Prize Bubble 6 - Grey Ghost', LEVEL, Kind.PRIZE, uid=23843, plan='g51263'),
    LBPLocationData('The Darkness - Prize Bubble 7 - Metal Skull Plate', LEVEL, Kind.PRIZE, uid=23848, plan='g39392'),
    LBPLocationData('The Darkness - Prize Bubble 8 - Red Candle', LEVEL, Kind.PRIZE, uid=23851, plan='g51306'),
    LBPLocationData('The Darkness - Prize Bubble 9 - Spotty Skull Leg', LEVEL, Kind.PRIZE, uid=23852, plan='g31997'),
    LBPLocationData('The Darkness - Prize Bubble 10 - Purple Skull Skirt', LEVEL, Kind.PRIZE, uid=23853, plan='g31998'),
    LBPLocationData('The Darkness - Prize Bubble 11 - Piñata Dog', LEVEL, Kind.PRIZE, uid=23854, plan='g32017'),
    LBPLocationData('The Darkness - Prize Bubble 12 - Blue Piñata Motif', LEVEL, Kind.PRIZE, uid=23855, plan='g32018', players=2),
    LBPLocationData('The Darkness - Prize Bubble 13 - Purple & Orange Piñata Motif', LEVEL, Kind.PRIZE, uid=23856, plan='g32019'),
    LBPLocationData('The Darkness - Prize Bubble 14 - Pink Piñata Motif', LEVEL, Kind.PRIZE, uid=23857, plan='g32020'),
    LBPLocationData('The Darkness - Prize Bubble 15 - Flower Frame', LEVEL, Kind.PRIZE, uid=23858, plan='g48601', players=2),
    LBPLocationData('The Darkness - Prize Bubble 16 - Purple Piñata Motif', LEVEL, Kind.PRIZE, uid=23859, plan='g48600', players=2),
    LBPLocationData('The Darkness - Prize Bubble 17 - Green Piñata Motif', LEVEL, Kind.PRIZE, uid=23860, plan='g48602', players=2),
    LBPLocationData('The Darkness - Prize Bubble 18 - Red Piñata Motif', LEVEL, Kind.PRIZE, uid=23861, plan='g48608', players=2),
    LBPLocationData('The Darkness - Prize Bubble 19 - Skeleton Hand', LEVEL, Kind.PRIZE, uid=23866, plan='g48595'),
    LBPLocationData('The Darkness - Prize Bubble 20 - Cartoon Bone', LEVEL, Kind.PRIZE, uid=23868, plan='g51253'),
    LBPLocationData('The Darkness - Prize Bubble 21 - Skeleton Leg', LEVEL, Kind.PRIZE, uid=23871, plan='g31980'),
    LBPLocationData('The Darkness - Prize Bubble 22 - Skeleton Torso', LEVEL, Kind.PRIZE, uid=23872, plan='g31976'),
    LBPLocationData('The Darkness - Prize Bubble 23 - Skeleton Arm', LEVEL, Kind.PRIZE, uid=23873, plan='g31979'),
    LBPLocationData('The Darkness - Prize Bubble 24 - Sugar Skull', LEVEL, Kind.PRIZE, uid=23879, plan='g32022'),
    LBPLocationData('The Darkness - Prize Bubble 25 - Pink Star Sunglasses', LEVEL, Kind.PRIZE, uid=23888, plan='g32426', players=2),
    LBPLocationData('The Darkness - Prize Bubble 26 - Cyclops Eye', LEVEL, Kind.PRIZE, uid=23889, plan='g32428', players=2),
    LBPLocationData('The Darkness - Prize Bubble 27 - Bunny', LEVEL, Kind.PRIZE, uid=23890, plan='g37935', rule=Has('Pixel Skull')),
    LBPLocationData('The Darkness - Prize Bubble 28 - Brown Leather', LEVEL, Kind.PRIZE, uid=23891, plan='g32521', rule=Has('Pixel Skull')),
    LBPLocationData('The Darkness - Prize Bubble 29 - Bull Skull', LEVEL, Kind.PRIZE, uid=23894, plan='g51292'),
    LBPLocationData('The Darkness - Prize Bubble 30 - Seated Skeleton', LEVEL, Kind.PRIZE, uid=23899, plan='g32024'),
    LBPLocationData('The Darkness - Prize Bubble 31 - Skeleton Hip Bone', LEVEL, Kind.PRIZE, uid=23904, plan='g48597'),
    LBPLocationData('The Darkness - Prize Bubble 32 - Pixel Skull', LEVEL, Kind.PRIZE, uid=24109, plan='g31988'),
    LBPLocationData('The Darkness - Prize Bubble 33 - Sugar Bone', LEVEL, Kind.PRIZE, uid=24247, plan='g32021', players=2),
    LBPLocationData("The Darkness - Prize Bubble 34 - 'The Appliance Of Science'", LEVEL, Kind.PRIZE, uid=24248, plan='g52635'),
    LBPLocationData('The Darkness - Prize Bubble 35 - Small LED Light', LEVEL, Kind.PRIZE, uid=24647, plan='g54695'),
    LBPLocationData('The Darkness - Prize Bubble 36 - Deadly Bat', LEVEL, Kind.PRIZE, uid=24650, plan='g56313'),
    LBPLocationData('The Darkness - Prize Bubble 37 - Fairy Light', LEVEL, Kind.PRIZE, uid=24953, plan='g51308'),
    LBPLocationData('The Darkness - Prize Bubble 38 - Torn Cloth', LEVEL, Kind.PRIZE, uid=25026, plan='g33195', players=2),
    LBPLocationData('The Darkness - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('The Darkness - All Prize Bubbles', LEVEL, Kind.ALL_PRIZES),
    LBPLocationData('The Darkness - Ace (No Deaths)', LEVEL, Kind.ACE),
    LBPLocationData('The Darkness - Completion Reward 1 - Pink Fairy Wings', LEVEL, Kind.REWARD, plan='g32371', condition=Kind.COMPLETE),
    LBPLocationData('The Darkness - Completion Reward 2 - Pink Dot', LEVEL, Kind.REWARD, plan='g37934', condition=Kind.COMPLETE),
    LBPLocationData('The Darkness - All Prizes Reward 1 - Themed Characters Concept with Frame', LEVEL, Kind.REWARD, plan='g52805', condition=Kind.ALL_PRIZES),
    LBPLocationData('The Darkness - All Prizes Reward 2 - Themed Characters Concept', LEVEL, Kind.REWARD, plan='g52792', condition=Kind.ALL_PRIZES),
    LBPLocationData('The Darkness - Ace Reward 1 - Roman Armor', LEVEL, Kind.REWARD, plan='g32376', condition=Kind.ACE),
    LBPLocationData('The Darkness - Sticker Switch 1 - Pixel Skull', LEVEL, Kind.STICKER_SWITCH, uid=22326, plan='g31988'),
    LBPLocationData('The Darkness - Sticker Switch 2 - Pixel Skull', LEVEL, Kind.STICKER_SWITCH, uid=22327, plan='g31988'),
    LBPLocationData('The Darkness - Sticker Switch 3 - Pixel Skull', LEVEL, Kind.STICKER_SWITCH, uid=22328, plan='g31988'),
    LBPLocationData('The Darkness - Sticker Switch 4 - Pixel Skull', LEVEL, Kind.STICKER_SWITCH, uid=22329, plan='g31988'),
    LBPLocationData('The Darkness - Sticker Switch 5 - Pixel Skull', LEVEL, Kind.STICKER_SWITCH, uid=22330, plan='g31988'),
    LBPLocationData('The Darkness - Key 1', LEVEL, Kind.KEY, uid=21673, target_slot='SlotID{DEVELOPER, 26942}'),
)
