from ..model import Kind, LBPLocationData

LEVEL = 'g27481'

LOCATIONS = (
    LBPLocationData('Tunnel Plunge - Score Bubble 1', LEVEL, Kind.SCORE, uid=51879),
    LBPLocationData('Tunnel Plunge - Score Bubble 2', LEVEL, Kind.SCORE, uid=51882),
    LBPLocationData('Tunnel Plunge - Score Bubble 3', LEVEL, Kind.SCORE, uid=51883),
    LBPLocationData('Tunnel Plunge - Score Bubble 4', LEVEL, Kind.SCORE, uid=51886),
    LBPLocationData('Tunnel Plunge - Score Bubble 5', LEVEL, Kind.SCORE, uid=51889),
    LBPLocationData('Tunnel Plunge - Score Bubble 6', LEVEL, Kind.SCORE, uid=51890),
    LBPLocationData('Tunnel Plunge - Score Bubble 7', LEVEL, Kind.SCORE, uid=51891),
    LBPLocationData('Tunnel Plunge - Score Bubble 8', LEVEL, Kind.SCORE, uid=51892),
    LBPLocationData('Tunnel Plunge - Score Bubble 9', LEVEL, Kind.SCORE, uid=51893),
    LBPLocationData('Tunnel Plunge - Score Bubble 10', LEVEL, Kind.SCORE, uid=51894),
    LBPLocationData('Tunnel Plunge - Score Bubble 11', LEVEL, Kind.SCORE, uid=51895),
    LBPLocationData('Tunnel Plunge - Score Bubble 12', LEVEL, Kind.SCORE, uid=51896),
    LBPLocationData('Tunnel Plunge - Score Bubble 13', LEVEL, Kind.SCORE, uid=51898),
    LBPLocationData('Tunnel Plunge - Score Bubble 14', LEVEL, Kind.SCORE, uid=51900),
    LBPLocationData('Tunnel Plunge - Score Bubble 15', LEVEL, Kind.SCORE, uid=51902),
    LBPLocationData('Tunnel Plunge - Score Bubble 16', LEVEL, Kind.SCORE, uid=51904),
    LBPLocationData('Tunnel Plunge - Score Bubble 17', LEVEL, Kind.SCORE, uid=51906),
    LBPLocationData('Tunnel Plunge - Score Bubble 18', LEVEL, Kind.SCORE, uid=51916),
    LBPLocationData('Tunnel Plunge - Score Bubble 19', LEVEL, Kind.SCORE, uid=51917),
    LBPLocationData('Tunnel Plunge - Score Bubble 20', LEVEL, Kind.SCORE, uid=51918),
    LBPLocationData('Tunnel Plunge - Score Bubble 21', LEVEL, Kind.SCORE, uid=51923),
    LBPLocationData('Tunnel Plunge - Score Bubble 22', LEVEL, Kind.SCORE, uid=51924),
    LBPLocationData('Tunnel Plunge - Score Bubble 23', LEVEL, Kind.SCORE, uid=51925),
    LBPLocationData('Tunnel Plunge - Score Bubble 24', LEVEL, Kind.SCORE, uid=51926),
    LBPLocationData('Tunnel Plunge - Score Bubble 25', LEVEL, Kind.SCORE, uid=51927),
    LBPLocationData('Tunnel Plunge - Score Bubble 26', LEVEL, Kind.SCORE, uid=51928),
    LBPLocationData('Tunnel Plunge - Score Bubble 27', LEVEL, Kind.SCORE, uid=51984),
    LBPLocationData('Tunnel Plunge - Score Bubble 28', LEVEL, Kind.SCORE, uid=51985),
    LBPLocationData('Tunnel Plunge - Score Bubble 29', LEVEL, Kind.SCORE, uid=51986),
    LBPLocationData('Tunnel Plunge - Score Bubble 30', LEVEL, Kind.SCORE, uid=51987),
    LBPLocationData('Tunnel Plunge - Score Bubble 31', LEVEL, Kind.SCORE, uid=51988),
    LBPLocationData('Tunnel Plunge - Score Bubble 32', LEVEL, Kind.SCORE, uid=51994),
    LBPLocationData('Tunnel Plunge - Score Bubble 33', LEVEL, Kind.SCORE, uid=51995),
    LBPLocationData('Tunnel Plunge - Score Bubble 34', LEVEL, Kind.SCORE, uid=51996),
    LBPLocationData('Tunnel Plunge - Score Bubble 35', LEVEL, Kind.SCORE, uid=51997),
    LBPLocationData('Tunnel Plunge - Score Bubble 36', LEVEL, Kind.SCORE, uid=51998),
    LBPLocationData('Tunnel Plunge - Score Bubble 37', LEVEL, Kind.SCORE, uid=53432),
    LBPLocationData('Tunnel Plunge - Score Bubble 38', LEVEL, Kind.SCORE, uid=53433),
    LBPLocationData('Tunnel Plunge - Score Bubble 39', LEVEL, Kind.SCORE, uid=53434),
    LBPLocationData('Tunnel Plunge - Score Bubble 40', LEVEL, Kind.SCORE, uid=53435),
    LBPLocationData('Tunnel Plunge - Score Bubble 41', LEVEL, Kind.SCORE, uid=53436),
    LBPLocationData('Tunnel Plunge - Score Bubble 42', LEVEL, Kind.SCORE, uid=53953),
    LBPLocationData('Tunnel Plunge - Score Bubble 43', LEVEL, Kind.SCORE, uid=53954),
    LBPLocationData('Tunnel Plunge - Score Bubble 44', LEVEL, Kind.SCORE, uid=53956),
    LBPLocationData('Tunnel Plunge - Score Bubble 45', LEVEL, Kind.SCORE, uid=53957),
    LBPLocationData('Tunnel Plunge - Level Complete', LEVEL, Kind.COMPLETE),
    LBPLocationData('Tunnel Plunge - Ace (No Deaths)', LEVEL, Kind.ACE),
)
